### ISSUE TITLE
Replacing NAT Gateways fails because EIP is already associated

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi-aws#1483] opened 2021-05-09 19:02 UTC
## Expected behavior
Dependent object is dis-associated as part of the create replacement flow?

## Current behavior
When you change something about a NAT Gateway, eg changing its subnet, Pulumi will calculate it needs to be replaced.  When the replacement is attempted to be created before destroy, it fails because the EIP is already in use.

## Steps to reproduce

diff:
```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:sandbox::buildkite-20-infra::pulumi:pulumi:Stack::buildkite-20-infra-sandbox]
    + aws:ec2/subnet:Subnet: (create)
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/subnet:Subnet::subnet-public-a]
        assignIpv6AddressOnCreation: false
        availabilityZone           : "us-west-2a"
        cidrBlock                  : "10.128.0.0/18"
        mapPublicIpOnLaunch        : false
        vpcId                      : "vpc-027605a5e8008dba9"
    + aws:ec2/subnet:Subnet: (create)
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/subnet:Subnet::subnet-public-b]
        assignIpv6AddressOnCreation: false
        availabilityZone           : "us-west-2b"
        cidrBlock                  : "10.128.64.0/18"
        mapPublicIpOnLaunch        : false
        vpcId                      : "vpc-027605a5e8008dba9"
    ++aws:ec2/natGateway:NatGateway: (create-replacement)
        [id=nat-0558b1e5fffb4423f]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-a]
      ~ subnetId: "subnet-071a467aac6937ffd" => output<string>
    +-aws:ec2/natGateway:NatGateway: (replace)
        [id=nat-0558b1e5fffb4423f]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-a]
      ~ subnetId: "subnet-071a467aac6937ffd" => output<string>
    --outputs:--
  + c1:subnet_public_a      : output<string>
  + c1:subnet_public_b      : output<string>
    ++aws:ec2/natGateway:NatGateway: (create-replacement)
        [id=nat-00ba4f3a2df1182ed]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-b]
      ~ subnetId: "subnet-0dc2d48045da512e1" => output<string>
    + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/routeTableAssociation:RouteTableAssociation::route-table-association-public-b]
        routeTableId: "rtb-01b5bfd78a3d451b4"
        subnetId    : output<string>
    +-aws:ec2/natGateway:NatGateway: (replace)
        [id=nat-00ba4f3a2df1182ed]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-b]
      ~ subnetId: "subnet-0dc2d48045da512e1" => output<string>
    + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/routeTableAssociation:RouteTableAssociation::route-table-association-public-a]
        routeTableId: "rtb-01b5bfd78a3d451b4"
        subnetId    : output<string>
    ~ aws:ec2/routeTable:RouteTable: (update)
        [id=rtb-011fb40ad4ee794a7]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/routeTable:RouteTable::route-table-private-a]
      ~ routes: [
          ~ [0]: {
                  ~ cidrBlock   : "0.0.0.0/0" => "0.0.0.0/0"
                  ~ natGatewayId: "nat-0558b1e5fffb4423f" => output<string>
                }
        ]
    ~ aws:ec2/routeTable:RouteTable: (update)
        [id=rtb-0697b501e3ad58de7]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/routeTable:RouteTable::route-table-private-b]
      ~ routes: [
          ~ [0]: {
                  ~ cidrBlock   : "0.0.0.0/0" => "0.0.0.0/0"
                  ~ natGatewayId: "nat-00ba4f3a2df1182ed" => output<string>
                }
        ]
    --aws:ec2/natGateway:NatGateway: (delete-replaced)
        [id=nat-0558b1e5fffb4423f]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-a]
    --aws:ec2/natGateway:NatGateway: (delete-replaced)
        [id=nat-00ba4f3a2df1182ed]
        [urn=urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-b]
```

fails eventually with:
```
  aws:ec2:NatGateway (nat-gateway-a):
    error: 1 error occurred:
    	* creating urn:pulumi:sandbox::buildkite-20-infra::aws:ec2/natGateway:NatGateway::nat-gateway-a: 1 error occurred:
    	* Error waiting for NAT Gateway (nat-08440fbd3a577e59f) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)
```

AWS Console shows this:
```
Status: Failed
State message: Elastic IP address [eipalloc-043e7f6ab9dbfa231] is already associated
```

**Comment by lukehoban** [comment] 2021-05-10 00:22
Note that you can use the `deleteBeforeReplace` resource option to indicate that you want the NAT gateway to be deleted before the new one is allocated. 

https://www.pulumi.com/docs/intro/concepts/resources/#deletebeforereplace

It's possible this should be the default for NAT Gateways - though in the case that you are intentionally assigning a new EIP, create before destroy actually would be a way to ensure no downtime for the change.

**Comment by lukehoban** [comment] 2022-12-24 15:55
Going to close this out as by design.  `deleteBeforeReplace` can be used to get the needed behaviour in this case, and there are cases where it may be important to ensure the resource is creadted first to ensure no downtime, so I don't think we want to force override the deleteBEforeReplace option for the whole resource.

**Closed by lukehoban** 2022-12-24 15:55 UTC
Labels: kind/bug, resolution/by-design
