### ISSUE TITLE
aws.cognito.IdentityProvider always updates without having changed

### ISSUE THREAD

**Issue by BerndWessels** [pulumi/pulumi-aws#679] opened 2019-07-28 19:23 UTC
Hi

`pulumi version v0.17.26 Windows 10`

I have a UserPool with a Google Identity Provider. Now **everytime** I run `pulumi up` it believes it has updates even though there have been **no changes**.

This prevents automatic continues deployment via pulumi since infrastructure now deploys everytime even without changes :(

```
pulumi up
Previewing update (dev):

     Type                             Name                    Plan
     pulumi:pulumi:Stack              product_aws-dev           running...
 ~   └─ aws:cognito:IdentityProvider  identityProviderGoogle  update
     Type                             Name                    Plan
     pulumi:pulumi:Stack              product_aws-dev
 ~   └─ aws:cognito:IdentityProvider  identityProviderGoogle  update

Resources:
    ~ 1 to update
    28 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::product_aws::pulumi:pulumi:Stack::product_aws-dev]
    ~ aws:cognito/identityProvider:IdentityProvider: (update)
        [id=us-east-1_XXXXXXXXX:Google]
        [urn=urn:pulumi:dev::product_aws::aws:cognito/identityProvider:IdentityProvider::identityProviderGoogle]
        attributeMapping: {
            email     : "email"
            username  : "sub"
        }
        providerDetails : {
            authorize_scopes: "openid email profile"
            client_id       : "123456789012-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
            client_secret   : "XXXXXXXXXXXXXXXXXXXXXX-_"
        }
        providerName    : "Google"
        providerType    : "Google"
        userPoolId      : "us-east-1_XXXXXXXXX"
```

This is the relevant pulumi code

```js
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Cognito
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const userPool = new aws.cognito.UserPool("userPool", {
    autoVerifiedAttributes: ["email"],
    // Sometimes there is an error saying something like
    //   Error updating Cognito User pool: InvalidParameterException: Please use TemporaryPasswordValidityDays instead of UnusedAccountValidityDays
    // Use the following command to fix this, temporarily :(
    //   aws cognito-idp update-user-pool --user-pool-id "us-east-1_xxxxxxxxx" --admin-create-user-config "AllowAdminCreateUserOnly=false" --region "us-east-1" --profile product
    lambdaConfig: {
        postAuthentication: userPoolPostAuthenticationDispatcherLambda.arn
    }
});

const userPoolClient = new aws.cognito.UserPoolClient("userPoolClient", {
    allowedOauthFlows: ["code"],
    allowedOauthFlowsUserPoolClient: true,
    allowedOauthScopes: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
    callbackUrls: ["http://localhost:3000", "https://product.app"],
    defaultRedirectUri: "https://product.app",
    generateSecret: false,
    logoutUrls: ["http://localhost:3000", "https://product.app"],
    supportedIdentityProviders: ["COGNITO", "Google"], // , "Facebook"
    userPoolId: userPool.id,
});

const userPoolDomain = new aws.cognito.UserPoolDomain("userPoolDomain", {
    domain: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    userPoolId: userPool.id,
});
const identityProviderGoogle = new aws.cognito.IdentityProvider("identityProviderGoogle", {
    attributeMapping: {
        email: "email",
        username: "sub",
    },
    providerDetails: {
        authorize_scopes: "openid email profile",
        client_id: "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
        client_secret: "xxxxxxxxxxxxxxxxxxxxxx-_",
    },
    providerName: "Google",
    providerType: "Google",
    userPoolId: userPool.id,
});

const identityPool = new aws.cognito.IdentityPool("identityPool", {
    allowUnauthenticatedIdentities: true,
    cognitoIdentityProviders: userPool.endpoint.apply(endpoint => [{
            client_id: userPoolClient.id,
            providerName: endpoint,
            serverSideTokenCheck: true,
        }]
    ),
    identityPoolName: "identityPool",
});

/* first I tried this, but it is even worse :(
const identityPool = new aws.cognito.IdentityPool("identityPool", {
    allowUnauthenticatedIdentities: true,
    cognitoIdentityProviders: [{
            client_id: userPoolClient.id,
            providerName: userPool.endpoint,
            serverSideTokenCheck: true,
        }],
    identityPoolName: "identityPool",
});
*/
const identityPoolAuthenticatedRole = new aws.iam.Role("identityPoolAuthenticatedRole", {
    assumeRolePolicy: identityPool.id.apply(id => JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Federated": "cognito-identity.amazonaws.com"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                    "StringEquals": {
                        "cognito-identity.amazonaws.com:aud": id
                    },
                    "ForAnyValue:StringLike": {
                        "cognito-identity.amazonaws.com:amr": "authenticated"
                    }
                }
            }
        ]
    })),
});

const identityPoolAuthenticatedRolePolicy = new aws.iam.RolePolicy("identityPoolAuthenticatedRolePolicy", {
    policy: JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "mobileanalytics:PutEvents",
                    "cognito-sync:*",
                    "cognito-identity:*"
                ],
                "Resource": [
                    "*"
                ]
            }
        ]
    }),
    role: identityPoolAuthenticatedRole.id,
});

const identityPoolUnauthenticatedRole = new aws.iam.Role("identityPoolUnauthenticatedRole", {
    assumeRolePolicy: identityPool.id.apply(id => JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Federated": "cognito-identity.amazonaws.com"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                    "StringEquals": {
                        "cognito-identity.amazonaws.com:aud": id
                    },
                    "ForAnyValue:StringLike": {
                        "cognito-identity.amazonaws.com:amr": "unauthenticated"
                    }
                }
            }
        ]
    })),
});

const identityPoolUnauthenticatedRolePolicy = new aws.iam.RolePolicy("identityPoolUnauthenticatedRolePolicy", {
    policy: JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "mobileanalytics:PutEvents",
                    "cognito-sync:*",
                ],
                "Resource": [
                    "*"
                ]
            }
        ]
    }),
    role: identityPoolUnauthenticatedRole.id,
});

const identityPoolRoleAttachment = new aws.cognito.IdentityPoolRoleAttachment("identityPoolRoleAttachment", {
    identityPoolId: identityPool.id,
    roles: {
        authenticated: identityPoolAuthenticatedRole.arn,
        unauthenticated: identityPoolUnauthenticatedRole.arn,
    },
});
```

**Comment by leezen** [comment] 2020-02-22 05:15
This appears to be a bug in the upstream provider. Please see https://github.com/terraform-providers/terraform-provider-aws/issues/5704 -- that issue also provides a workaround: you can fully specify all the attributes for `providerDetails` (e.g. `attributes_url`, `attributes_url_add_attributes`, etc.)

Thanks for reporting this. Closing as a dupe of the upstream issue, which will be fixed in pulumi-aws once the upstream issue is fixed.

**Closed by leezen** 2020-02-22 05:15 UTC
