### ISSUE TITLE
AWS Cognito userPoolClient keeps updating with no visible diffs

### ISSUE THREAD

**Issue by lucabergamini** [pulumi/pulumi-aws#3112] opened 2023-12-08 15:55 UTC
### What happened?

We have a bunch of userPoolClient provisioned through pulumi that we use for m-2-m auth. Since we created them, every time we do a `pulumi up` we see an update for each one of them in the plan.

The details don't show anything really, except for a generic `update` next to the resource (like `~aws:cognito/userPoolClient:UserPoolClient: (update)`)

The good news is that this is not creating any issue in aws, as nothing really changes. The bad ones is that it takes ages (~2.4h) to push any update in our production env where we have ~100 of these clients.

### Example

Resources for the stack

```python
POOL_NAME = f"pool-{stack}"
POOL_SCOPE_NAME = f"access-{stack}"


user_pool = aws.cognito.UserPool(
    resource_name=POOL_NAME,
    name=POOL_NAME,
    mfa_configuration="OFF",
    username_attributes=["email"],
    auto_verified_attributes=["email"],
)

user_pool_resource_server = aws.cognito.ResourceServer(
    resource_name=f"{POOL_NAME}-resource-server",
    name=f"{POOL_NAME}-resource-server",
    identifier=f"{POOL_NAME}-resource-server",
    user_pool_id=user_pool.id,
    scopes=[
        aws.cognito.ResourceServerScopeArgs(
            scope_description="machine access", scope_name=POOL_SCOPE_NAME
        )
    ],
)

user_pool_domain = aws.cognito.UserPoolDomain(
    resource_name=f"{POOL_NAME}-user-pool-domain",
    domain=f"{POOL_NAME}",
    user_pool_id=user_pool.id,
)

```

Resource for the client (one for each client):
```python
    cognito_app_client = aws.cognito.UserPoolClient(
        resource_name=f"{POOL_NAME}-app-client",
        name="app",
        user_pool_id=user_pool.id,
        generate_secret=True,
        access_token_validity=24,
        id_token_validity=24,
        enable_token_revocation=True,
        explicit_auth_flows=["ALLOW_REFRESH_TOKEN_AUTH"],
        allowed_oauth_flows=["client_credentials"],
        allowed_oauth_scopes=user_pool_resource_server.scope_identifiers,
        allowed_oauth_flows_user_pool_client=True,
    )

```

### Output of `pulumi about`

```
CLI
Version      3.94.2
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
auth0       2.24.1
aws         6.2.0
aws-native  0.78.0
python      unknown
random      4.14.0
tailscale   0.13.2

Host
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in python: executable='/Users/luca/.pyenv/shims/python3' version='3.10.4'

Backend
Name           luca-Macbook-M2.local
URL            s3://orcamobility-pulumi-state
User           luca
Organizations
Token type     personal

Dependencies:
NAME               VERSION
pip                23.3.1
pulumi-auth0       2.24.1
pulumi-aws         6.2.0
pulumi-aws-native  0.78.0
pulumi-random      4.14.0
pulumi-tailscale   0.13.2
setuptools         69.0.2
wheel              0.41.3
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lucabergamini** [comment] 2023-12-09 10:13
I swear I searched for it before opening mine and could find anything lol. Thanks for the pointer @justinvp , it looks like the exact same issue we are hitting!

**Comment by VenelinMartinov** [comment] 2023-12-11 22:10
Sorry you had this issue @lucabergamini and thanks for the repro!

I had a quick go at debugging this but unfortunately don't have a workaround yet. It looks like the problematic properties are `analytics_configuration` and `token_validity_units`. I tried setting them in `ignore_changes` but it doesn't seem to help = (

Here are the GRPC logs from the diff:
```
{
    "method": "/pulumirpc.ResourceProvider/Diff",
    "request": {
        "id": "2talj499aj6o403njn2dr6lof1",
        "urn": "urn:pulumi:dev1::cognito::aws:cognito/userPoolClient:UserPoolClient::pool-dev1-app-client",
        "olds": {
            "accessTokenValidity": 24,
            "allowedOauthFlows": [
                "client_credentials"
            ],
            "allowedOauthFlowsUserPoolClient": true,
            "allowedOauthScopes": [
                "pool-dev1-resource-server/access-dev1"
            ],
            "authSessionValidity": 3,
            "callbackUrls": [],
            "clientSecret": "e4fhc9b8l52b8ogk4gbpvfkpq13apfshfat4ncfo5mvaov3ng37",
            "defaultRedirectUri": "",
            "enablePropagateAdditionalUserContextData": false,
            "enableTokenRevocation": true,
            "explicitAuthFlows": [
                "ALLOW_REFRESH_TOKEN_AUTH"
            ],
            "generateSecret": true,
            "id": "2talj499aj6o403njn2dr6lof1",
            "idTokenValidity": 24,
            "logoutUrls": [],
            "name": "app",
            "preventUserExistenceErrors": "",
            "readAttributes": [],
            "refreshTokenValidity": 30,
            "supportedIdentityProviders": [],
            "userPoolId": "us-west-2_bnqFDRKnh",
            "writeAttributes": []
        },
        "news": {
            "accessTokenValidity": 24,
            "allowedOauthFlows": [
                "client_credentials"
            ],
            "allowedOauthFlowsUserPoolClient": true,
            "allowedOauthScopes": [
                "pool-dev1-resource-server/access-dev1"
            ],
            "enableTokenRevocation": true,
            "explicitAuthFlows": [
                "ALLOW_REFRESH_TOKEN_AUTH"
            ],
            "generateSecret": true,
            "idTokenValidity": 24,
            "name": "app",
            "userPoolId": "us-west-2_bnqFDRKnh"
        },
        "ignoreChanges": [
            "analyticsConfiguration",
            "tokenValidityUnits",
            "tokenValidityUnits",
            "analyticsConfiguration"
        ],
        "oldInputs": {
            "accessTokenValidity": 24,
            "allowedOauthFlows": [
                "client_credentials"
            ],
            "allowedOauthFlowsUserPoolClient": true,
            "allowedOauthScopes": [
                "pool-dev1-resource-server/access-dev1"
            ],
            "enableTokenRevocation": true,
            "explicitAuthFlows": [
                "ALLOW_REFRESH_TOKEN_AUTH"
            ],
            "generateSecret": true,
            "idTokenValidity": 24,
            "name": "app",
            "userPoolId": "us-west-2_bnqFDRKnh"
        }
    },
    "response": {
        "changes": "DIFF_SOME",
        "diffs": [
            "analyticsConfiguration",
            "tokenValidityUnits"
        ]
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "aws"
    }
}
```

Both these properties are defined as `ListNestedBlocks` in the upstream schema with a `SizeAtMost(1)` validator: https://github.com/hashicorp/terraform-provider-aws/blob/66dcdb554936952190b046164cf09b82ae5f5d8b/internal/service/cognitoidp/user_pool_client.go#L297C1-L297C1

**Comment by iwahbe** [comment] 2023-12-12 08:28
I agree with @justinvp. I'm closing this issue as a duplicate of https://github.com/pulumi/pulumi-aws/issues/2868.

**Closed by iwahbe** 2023-12-12 08:28 UTC
Labels: kind/bug, resolution/duplicate, bug/diff
