### ISSUE TITLE
ManagedPolicies consts for dotnet

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi-aws#1147] opened 2020-10-05 20:17 UTC
Hi,

Node (JS/TS) has a useful collection of [managed policies](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/iam/managedPolicies.ts). However the equivalent does not exist for .NET (or possibly other langs).

Cheers.

**Comment by leezen** [comment] 2020-10-06 17:58
Dupe of https://github.com/pulumi/pulumi-aws/issues/1130 (I'll add a note in there to make sure we include managed policies)

**Closed by leezen** 2020-10-06 17:58 UTC
