### ISSUE TITLE
Add notification configuration to SQS Queue Python Example is Incorrect

### ISSUE THREAD

**Issue by estenrye** [pulumi/pulumi-aws#1888] opened 2022-03-31 03:23 UTC
File: [themes/default/content/registry/packages/aws/api-docs/s3/bucketnotification/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketnotification/)

Section: [Add notification configuration to SQS Queue](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketnotification/#add-notification-configuration-to-sqs-queue)

The python example for setting up an S3 notification to an SQS queue does not work.  The inline queue policy results in the policy authorizing sqs:SendMessage to a non-existent Queue.

The example should be replaced with:

```python
import pulumi
import pulumi_aws as aws

bucket = aws.s3.BucketV2("bucket")
queue = aws.sqs.Queue("queue")

policy = pulumi.Output.all(queue_arn=queue.arn, source_arn=bucket.arn).apply(lambda args: f"""{{
    "Version": "2012-10-17",
    "Statement": [{{
        "Effect": "Allow",
        "Principal": "*",
        "Action": "sqs:SendMessage",
        "Resource": "{ args['queue_arn'] }",
        "Condition": {{
            "ArnEquals": {{
                "aws:SourceArn": "{ args['source_arn'] }"
            }}
        }}
    }}]
}}
"""
queue_policy = aws.sqs.Queue_Policy("queue_policy", queue_url=queue.id, policy=policy)

bucket_notification = aws.s3.BucketNotification("bucketNotification",
    bucket=bucket.id,
    queues=[aws.s3.BucketNotificationQueueArgs(
        queue_arn=queue.arn,
        events=["s3:ObjectCreated:*"],
        filter_suffix=".log",
    )])
```

**Comment by lukehoban** [comment] 2022-04-01 12:18
Moving as this will likely need to be addressed in the provider (or upstream fork).

**Comment by lukehoban** [comment] 2022-12-28 06:20
Closing as duplicate of https://github.com/pulumi/pulumi-aws/issues/1774, which is itself now closed and tracked in https://github.com/pulumi/pulumi-terraform-bridge/issues/709.

**Closed by lukehoban** 2022-12-28 06:20 UTC
Labels: kind/bug, resolution/duplicate, docs/api
