### ISSUE TITLE
GetVpc error when assuming role in AWS

### ISSUE THREAD

**Issue by Sindvero** [pulumi/pulumi-aws#2214] opened 2022-11-13 23:36 UTC
### What happened?

When using the getVpc sdk in golang with pulumi operator in k8s, I get the following issue when assuming aws role:

```
Diagnostics:
  pulumi:pulumi:Stack (vpc-peering-go-sc-vpc-peering-ssh.aws.dev):
    <nil>

    error: an unhandled error occurred: program failed:
    1 error occurred:
      * rpc error: code = Unknown desc = invocation of aws:ec2/getVpc:getVpc returned an error: 1 error occurred:
      * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable
    error: an unhandled error occurred: program exited with non-zero exit code: 32

Resources:
    2 unchanged
```
While using the following go code:
```
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := aws.NewProvider(ctx, "vpc-peering", &aws.ProviderArgs{
			SkipMetadataApiCheck:      pulumi.Bool(false),
			SkipCredentialsValidation: pulumi.Bool(true),
			Region:                    pulumi.String("MYREGION"),
		})

		if err != nil {
			return err
		}

		targetVpcTags := make(map[string]string)
		targetVpcTags["Name"] = "test"
		targetVpc, err := ec2.LookupVpc(ctx, &ec2.LookupVpcArgs{
			Tags: targetVpcTags,
		})
		// targetVpc, err := ec2.NewVpc(ctx, "target", &ec2.VpcArgs{
		// 	CidrBlock: pulumi.String("10.0.0.0/16"),
		// })
		fmt.Println(targetVpc)
		if err != nil {
			return err
		}
	return nil
	})

}
```

The getProvider works, it's the LookupVpc that get the error.

### Steps to reproduce

Deploy the code above while using the latest pulumi operator release: v1.10.1

I also follow that issue: #1359 and it still doesn't work.

### Expected Behavior

It works

### Actual Behavior

it crash with the following error:

```
1 error occurred:
      * rpc error: code = Unknown desc = invocation of aws:ec2/getVpc:getVpc returned an error: 1 error occurred:
      * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.
```

**Comment by Sindvero** [comment] 2022-11-14 19:15
I think it's for several programming language, and I think this issue is coming from the terraform aws provider.

Did someone find a workaround?

Thanks

**Comment by thomas11** [comment] 2022-11-15 17:24
Hi @Sindvero! How are you configuring AWS authentication in your program? It seems that the issue is there and might not be specific to Pulumi. The above code sample doesn't actually authenticate via Pulumi since you specified `SkipCredentialsValidation`.

**Comment by Sindvero** [comment] 2022-11-15 19:40
I find out the issue with the help of slack. Apparently, Terraform broke the auth system in the new provider which also broke the auth in pulumi last release, so I just went back to the previous provider version and it worked.

**Comment by thomas11** [comment] 2022-11-15 20:57
Thanks for reporting back, @Sindvero! Are you referring to these changes in [Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication)? If so, local configuration changes should enable you to use the latest provider.

If you were referring to another regression, could you link to the Slack convo you saw?

I'll close this issue then since

**Comment by Sindvero** [comment] 2022-11-15 21:53
Yes, I'm referring to those Terraform changes. I honestly didn't figure out how to make it works. Also to note, I'm using the k8s pulumi operator to deploy my stack. I may be missing something in the configuration. If you can show me where to change the configuration, please let me know

Thanks!

**Comment by thomas11** [comment] 2022-11-15 22:08
Hey @Sindvero, the Pulumi docs should have all you need for [setting up authentication](https://www.pulumi.com/registry/packages/aws/installation-configuration/). The essential point of the Terraform change seems to be this, so maybe double-check for that case:

> Before v4.0, if profile was configured in the provider configuration but did not correspond to an AWS profile or valid credentials, the provider would attempt to use environment variables. This is no longer the case. _An explicitly set profile that does not have valid credentials will cause an authentication error_.

**Comment by kpitzen** [comment] 2023-03-31 14:53
As it seems this is working as intended with the new provider configuration (explicit providers now requiring credentials to be set rather than falling back to the underlying environment), I'm going to mark this as working as intended. If explicitly setting these credentials on the provider constructor still fails, please feel free to reach out, and I'll be happy to reopen for further investigation.

Thank you!

**Closed by kpitzen** 2023-03-31 14:53 UTC
Labels: kind/bug, area/providers, resolution/by-design
