### ISSUE TITLE
Description for EventTarget `arn` input is incorrect

### ISSUE THREAD

**Issue by robodair** [pulumi/pulumi-aws#1993] opened 2021-12-10 06:22 UTC
File: [themes/default/content/registry/packages/aws/api-docs/cloudwatch/eventtarget/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/eventtarget/)

The text currently present for the `arn` input is incorrect:

> ARN of the SQS queue specified as the target for the dead-letter queue.

The correct text would be:

> The Amazon Resource Name (ARN) of the target.

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html

**Comment by danielrbradley** [comment] 2022-07-14 13:57
Closing as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529

Once the core issue is solved this will be fixed on the next upgrade of the TF bridge.

**Closed by danielrbradley** 2022-07-14 13:57 UTC
Labels: kind/bug, resolution/duplicate
