### ISSUE TITLE
CallbackFunction should accept Input and not just prompt strings

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-aws#995] opened 2020-06-05 16:42 UTC
https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/lambdaMixins.ts#L180

https://pulumi-community.slack.com/archives/CRH5ENVDX/p1591352061275400

The way it is, there's no easy way to use an a policy's ARN `Output` within the same program

**Comment by lukehoban** [comment] 2020-06-05 16:54
The key reason we haven't done this is the requirements of the code below which (a) needs to be able to create a resource per policy - meaning the array part must be prompt and (b) needs to create a unique name for each attachment derived from the policy so needs prompt access to the policy contents.  Not clear how we would best loosen these requirements while maintaining correctness here.

```ts
            for (const policy of args.policies) {
                // RolePolicyAttachment objects don't have a physical identity, and create/deletes are processed
                // structurally based on the `role` and `policyArn`.  So we need to make sure our Pulumi name matches the
                // structural identity by using a name that includes the role name and policyArn.
                const attachment = new iam.RolePolicyAttachment(`${name}-${utils.sha1hash(policy)}`, {
                    role: role,
                    policyArn: policy,
                }, opts);
            }
```

**Comment by amichel** [comment] 2020-06-06 19:09
I use following in few places:
```ts
 policyArns.map(policy => {
            let p = pulumi.interpolate`${policy}`;
            p.apply(arn =>
                getResourceFromPolicyArn(arn).apply(resource =>
                    new aws.iam.RolePolicyAttachment(`RoleAttachment-${roleName}-${resource}}`, { role: role, policyArn: policy })
                ))
        });

function getResourceFromPolicyArn(arn: string) {
    return pulumi.output(getArn({ arn: arn })).resource.apply(r => { return r.split("/").pop() });
}
```

**Comment by lukehoban** [comment] 2022-12-23 19:40
> I use following in few places

This approach results in creating `RolePolicyAttachment` resources inside an `apply`, which means that the preview will not in general be accurate - when the number of ARNs or any of the individual ARNs are not yet known (because they are dependent on the output of other resource), Pulumi will not be able to report whether or how many `RolePolicyAttachment` resources will be created.  

For this built-in component, we've aimed to ensure that the preview can be completely reliable, which today means that the resource. creations must not be inside `apply`s.

**Comment by lukehoban** [comment] 2022-12-23 19:40
Going to close this out as a dupe of https://github.com/pulumi/pulumi/issues/4834#issuecomment-644827733.

Until that is supported in core Pulumi, I don't believe there is anything we can or should change here.

**Closed by lukehoban** 2022-12-23 19:40 UTC
Labels: kind/enhancement, resolution/duplicate
