### ISSUE TITLE
Unable to set MessageBody on SNS Topic Subscription

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#2576] opened 2023-06-27 16:20 UTC
### What happened?

I am provisioning an AWS SNS topic, queue and topic subscription with the property `filterPolicyScope`.

Despite setting the property to the desired `MessageBody` does not seem to take any effect.

This does seem sporadic, and sometimes it works, sometimes it doesn't.

### Expected Behavior

I expece the created subscription to set the message body correctly

### Steps to reproduce

Create the resources like so:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const topic = new aws.sns.Topic("example", {})

const queue = new aws.sqs.Queue("example", {})

const sub = new aws.sns.TopicSubscription("example", {
    endpoint: queue.arn,
    protocol: "sqs",
    topic: topic.arn,
    filterPolicy: "{\"type\":[\"foo\"]}",
    filterPolicyScope: "MessageBody"
})

export const subscriptionArn = sub.arn
```

```
aws sns get-subscription-attributes --subscription-arn $(pulumi stack output subscriptionArn) --no-paginate
```

```
{
    "Attributes": {
        "SubscriptionPrincipal": "arn:aws:iam::616138583583:role/aws-reserved/sso.amazonaws.com/us-west-2/AWSReservedSSO_AdministratorAccess_224e23fb315b65cb",
        "Owner": "616138583583",
        "RawMessageDelivery": "false",
        "FilterPolicy": "{\"type\":[\"foo\"]}",
        "TopicArn": "arn:aws:sns:us-west-2:616138583583:example-cc2b39c",
        "Endpoint": "arn:aws:sqs:us-west-2:616138583583:example-c14bb01",
        "FilterPolicyScope": "MessageAttributes",
        "Protocol": "sqs",
        "PendingConfirmation": "false",
        "ConfirmationWasAuthenticated": "true",
        "SubscriptionArn": "arn:aws:sns:us-west-2:616138583583:example-cc2b39c:9bb79462-bb5b-47c6-bfd3-e5f6fb13141b"
    }
}
```

### Output of `pulumi about`

```
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.41.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.3.1'

Current Stack: lbrlabs58/sns/dev

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:dev::sns::pulumi:pulumi:Stack::sns-dev
pulumi:providers:aws                         urn:pulumi:dev::sns::pulumi:providers:aws::default_5_41_0
aws:sns/topic:Topic                          urn:pulumi:dev::sns::aws:sns/topic:Topic::example
aws:sqs/queue:Queue                          urn:pulumi:dev::sns::aws:sqs/queue:Queue::example
aws:sns/topicSubscription:TopicSubscription  urn:pulumi:dev::sns::aws:sns/topicSubscription:TopicSubscription::example


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/jaxxstorm
User           jaxxstorm
Organizations  jaxxstorm, lbrlabs, pulumi, demo

Dependencies:
NAME            VERSION
@pulumi/aws     5.41.0
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.73.0
@types/node     16.18.37

Pulumi locates its logs in /var/folders/rk/2c715ngd14jc4c7d3659m7pm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment] 2023-06-27 16:41
Possibly the same issue tracked in https://github.com/hashicorp/terraform-provider-aws/issues/32072?

**Comment by keithwenzler** [comment] 2023-08-15 14:27
Can this issue be given priority please?

I'm really needing to use IaC to maintain the filterPolicyScope at MessageBody instead of manually updating it after every Pulumi refresh / up combination that is executed on each of the dev, stage & prod environments. Currently, the value always defaults to MessageAttributes even though it is set to MessageBody in IaC. 

Thanks

**Comment by lakindu2002** [comment] 2023-08-16 09:57
Hi, is there any update on this? This is something I'm really needing to work, but my architecture cannot be optimized because this is missing in Pulumi.

**Comment by chrisvensand** [comment] 2023-09-06 22:05
Hi commenting for visibility, is there any update on this?

**Comment by Chasic** [comment] 2023-10-03 10:18
Hey everyone, do you have any update on this, please? It may look like a small issue but in fact it can block quite important architecture not only around alerting subscription to CW alarms. For us this is really a big blocker, thanks!

**Comment by kpitzen** [comment] 2023-10-03 16:35
Hi all, I'm no longer assigned to the team responsible for prioritizing providers issues. @mikhailshilkov likely has a clearer idea for where this would fit in prioritization.

Thanks!

**Comment by hiwit** [comment] 2023-10-24 12:59
Is there any progress on this topic (pun intend ;) )? Hard to work around this one :/

**Comment by SelimAbidin** [comment] 2023-10-25 13:25
We also have the same problem. We checked the pulumi code if we cannot fix but lost in GO 😅 
Anyway, we temporarily publish message attributes till this is solve.

**Comment by lukehoban** [comment] 2024-01-20 22:21
This appears to be the same issue tracked in https://github.com/hashicorp/terraform-provider-aws/issues/32072 upstream.

**Comment by iwahbe** [comment] 2024-02-14 01:46
I believe that this was fixed upstream as part of the last major version bump, at least as originally described. I am unable to reproduce the bug with the provided repro on v6.22.0. Because the bug is sporadic, I tried to repro within a loop:

```sh
$ for i in $(seq 10); do 
    pu up --yes --skip-preview;
    pu env run dev-sandbox -- aws sns get-subscription-attributes --subscription-arn $(pulumi stack output subscriptionArn) --no-paginate | jq .Attributes.FilterPolicyScope >> 6.22.0.txt;
    pu destroy --yes --skip-preview; 
done

$ cat 6.22.0.txt
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
"MessageBody"
```


I was able to reproduce consistently on v5.41.0.

```sh
$ pu up --yes --skip-preview && pu env run dev-sandbox -- aws sns get-subscription-attributes --subscription-arn $(pulumi stack output subscriptionArn) --no-paginate | jq .Attributes.FilterPolicyScope >> 5.41.0.txt && pu destroy --yes --skip-preview

$ cat 5.41.0.text
"MessageAttributes"
```

**Comment by iwahbe** [comment] 2024-02-14 01:49
I'm going to close as fixed. If you are able to reproduce the bug on pulumi-aws v6, please open a new issue with a repro.

**Closed by iwahbe** 2024-02-14 01:49 UTC
Labels: impact/usability, kind/bug, area/providers, resolution/fixed, awaiting-upstream, impact/quality
