### ISSUE TITLE
Support RDS master password management

### ISSUE THREAD

**Issue by arjun810** [pulumi/pulumi-aws#2452] opened 2023-04-04 19:01 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recently, AWS added support for automatically managing RDS master passwords. Terraform added this support here:
https://github.com/hashicorp/terraform-provider-aws/issues/28538

It would be nice for Pulumi's AWS api to expose this.

**Comment by danielrbradley** [comment] 2023-04-05 12:29
Hi @arjun810 this feature will be resolved in the next release. 

Closing as a duplicate of #2445 it looks like this feature was a part of the v4.61.0 release.

**Closed as completed by danielrbradley** 2023-04-05 12:29 UTC
Labels: kind/enhancement, resolution/duplicate
