### ISSUE TITLE
Cannot authenticate on AWS using switchrole

### ISSUE THREAD

**Issue by jnancel** [pulumi/pulumi-aws#252] opened 2018-06-29 12:42 UTC
Hello,

I'm trying to bootstrap my first pulumi project but I'm encountering an issue with the supported authentication method on AWS. 

If I'm using a profile in which my credentials are defined ( with `aws_access_key_id` and `aws_secret_access_key` ), it works like a charm. But that's not how we work in my company, we have a source account and we're using switchrole to jump from that source account to all other accouts ( this is standard AWS procedure when you're dealing with multiple accounts ).

Here's the look of my profiles in `~/.aws/config` : 

```
[profile myprofile]
role_arn = arn:aws:iam::<AWS destination account id>:role/<the role I'm going to impersonate>
mfa_serial = arn:aws:iam::<source AWS account ID>:mfa/<IAM User name on the source account>
source_profile = <the profile name in which my keys are defined for my source account>
```

Now when I'm using one of those profile, it fails : 
```
$ AWS_PROFILE=myprofile pulumi update
Previewing update of stack 'prod'
Previewing changes:

     Type                    Name               Plan          Info
 *   global                  global             no change     1 error
 +   └─ pulumi:pulumi:Stack  first-pulumi-prod  create        
 
Diagnostics:
  global: global
    error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
 
error: an error occurred while advancing the preview
```

When using the same command line with my source profile ( the one with the keys ), I have the expected result :
```
      Type                 Name               Plan       Info
 +   pulumi:pulumi:Stack  first-pulumi-prod  create
 +   └─ aws:s3:Bucket     my-bucket          create

info: 2 changes previewed:
    + 2 resources to create

Do you want to perform this update?
  yes
> no
  details
```

Is there any configuration I'm missing or is it not possible for the moment to use an AWS profile with switchrole ?

Thanks

**Comment by jnancel** [comment] 2018-07-02 07:48
Hello Matt,

Thanks for the answer, I tried enabling that option but encountered a `panic` error : 
```
$ AWS_PROFILE=myprofile pulumi preview
Previewing update of stack 'prod'
Previewing changes:

     Type    Name    Plan          Info
 *   global  global  no change     1 error, 2 info messages
 
Diagnostics:
  global: global
    info: 2018/07/02 09:45:04 ERROR: failed to create session with AWS_SDK_LOAD_CONFIG enabled. Use session.NewSession to handle errors occurring during session creation. Error: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
 
  global: global
    info: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8f3b4e]
    goroutine 34 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.unmarshalHandler(0xc4206c0800)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go:119 +0x3e
    github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc4206c09e8, 0xc4206c0800)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:213 +0x9d
    github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc4206c0800, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:525 +0x4d9
    github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0xc42000e780, 0x2e2dfc4, 0xb, 0x0, 0x2e2dcc2, 0xb, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:28 +0x18b
    github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).Available(0xc42000e780, 0xc420495a00)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:129 +0x40
    github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws.GetCredentials(0xc4200a0280, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws/auth_helpers.go:164 +0x1ba5
    github.com/pulumi/pulumi-aws.preConfigureCallback(0xc420290870, 0xc420734000, 0xc420208db0, 0xc420208e40)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/resources.go:166 +0x411
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Configure(0xc420239770, 0x4acab20, 0xc4202907e0, 0xc42000e060, 0xc420239770, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:227 +0xdf7
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Configure_Handler.func1(0x4acab20, 0xc4202907e0, 0x2a72c20, 0xc42000e060, 0x4acab20, 0xc4202907e0, 0x4acfda0, 0x4b68c68)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:699 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4acab20, 0xc4202907e0, 0x2a72c20, 0xc42000e060, 0xc4205342a0, 0xc4205342c0, 0x0, 0x0, 0x4abbca0, 0xc4202532e0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Configure_Handler(0x2d73640, 0xc420239770, 0x4acab20, 0xc4205942a0, 0xc42030e410, 0xc4204ce560, 0x0, 0x0, 0x30, 0x2aeb560)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:701 +0x16d
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200b2000, 0x4ace9a0, 0xc4200b0000, 0xc420572200, 0xc42026dbc0, 0x4b3d460, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200b2000, 0x4ace9a0, 0xc4200b0000, 0xc420572200, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202ad320, 0xc4200b2000, 0x4ace9a0, 0xc4200b0000, 0xc420572200)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1
 
  global: global
    error: transport is closing
 
error: an error occurred while advancing the preview
```

Thanks

**Comment by joeduffy** [comment] 2018-09-24 17:59
@jen20 just offered to help track this down, so reassigning.

**Comment by jen20** [comment] 2018-11-26 12:40
Hi @jnancel! Sorry for the delay in replying here. I committed an example of using AssumeRole to the [`pulumi/examples`](https://github.com/pulumi/examples) repository a few weeks back - it's [here](https://github.com/pulumi/examples/tree/master/aws-ts-assume-role). Can you give that approach a try?

I'll close out this issue for now since there is a way to do this - please feel free to comment further if you think this doesn't address your requirements though and we'll take another look!

**Comment by lukehoban** [comment] 2018-11-26 13:52
@jen20 That example shows how to use an assumed role programmatically from within Pulumi.  

But do we know why the steps @jnancel tried don' work?  Is it expected that setting `AWS_PROFILE` will not work?  Is it expected that also settings `AWS_SDK_LOAD_CONFIG=1  ` causes a panic?  Can `pulumi config set aws:profile <profile>` be used instead correctly?  This approach of trying to set a profile from outside of the `pulumi` invocation feels like it will be common.

**Comment by lukehoban** [comment] 2019-01-05 17:48
Re-opening. I hit this again recently myself, and was able to work around via an approach like the example, but as expected to just be able to set the profile externally.

**Comment by lukehoban** [comment] 2019-02-28 01:34
This has come up from users several times - I'd love to nail down any remaining issues here and document the expected modes that work.

**Comment by eshamay** [comment] 2019-05-10 21:36
I've just run into a strikingly similar issue.

I have the following setup:
```$ echo $AWS_PROFILE
online-sandbox-admin```

```$ cat ~/.aws/config
[profile online-sandbox-admin]
source_profile = bastion
region = us-west-2
role_arn = arn:aws:iam::redact:role/online-sandbox-admin-role```

```$ cat ~/.aws/credentials
[bastion]
aws_access_key_id = redact
aws_secret_access_key = redact
region = us-west-2
aws_session_token = redact```

```$ aws sts get-caller-identity
{
    "Account": "redact",
    "UserId": "redact-session-1557521500",
    "Arn": "arn:aws:sts::redact:assumed-role/online-sandbox-admin-role/redact-session-1557521500"
}```


When using the `aws` CLI directly then things work exactly as expected (e.g. list roles, instances, etc). I can see all the resources in my account. However, running `pulumi refresh` lists everything as `delete` meaning that pulumi can't find the resources.

**Comment by brandonbloom** [comment] 2019-05-22 20:38
We use `AssumeRole` as well. I'd like to cast my vote for supporting the `aws:profile` configuration setting.

**Comment by keen99** [comment] 2019-05-23 20:02
+1 for native role assumption for the CLI tools based on AWS_PROFILE, aws:profile, and other profile setting methods.  it's a significant blocker to not support that for any kind of modern multi account setup.

**Comment by mi5guided** [comment] 2019-05-30 02:03
the above changes work for profiles that either assume role or have access keys defined.  I have not been able to do a thorough testing of the change, since I can't get the build to finish all the way through.  Any hints on how the environment should be set up is appreciated. For example, should `pulumi-aws` be in the `pulumi` directory?  And, if so, what is the command to make just `pulumi-aws`?

**Comment by joeduffy** [comment] 2019-11-01 13:48
It appears this is still a problem. The issue seems to be specifically with `source_profile`, which we apparently do not respect. We hit this in a workshop today. The error is as follows:

`error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration`

**Comment by butschi** [comment] 2019-11-08 16:01
@joeduffy I had the same problem and after reading your comment I just created a new aws profile for pulumi and copied the remaining lines from the source profile into it. Then it worked. Thanks!

Also keep in mind that the other issue #584 leaves the impression that it does not work at all with MFA tokens.

**Comment by casey-robertson** [comment] 2019-12-11 22:33
Running into this too.  @butschi @joeduffy - do you mean just create a specific named profile and not one that sources from a 'default' ?

Like the others have mentioned I think this is pretty standard for assuming roles in AWS.  The odd part is why it works for me in some stacks of the same program and not others.

**Comment by casey-robertson** [comment] 2019-12-11 23:06
Ok I found and solved my particular issue.  Had to do with versions of the `aws` plugin and/or providers.  Here's my plugin list:

```
NAME        KIND      VERSION  SIZE    INSTALLED    LAST USED
aws         resource  1.14.1   193 MB  1 hour ago   now
aws         resource  1.8.0    220 MB  1 hour ago   now
aws         resource  1.7.0    220 MB  1 week ago   now
aws         resource  1.3.0    217 MB  1 hour ago   now
aws         resource  0.18.27  209 MB  1 hour ago   now
```

Had multiple people vet that my pulumi stack config referring to AWS was correct and aws cli commands worked fine.  Turns out at some point I had changed my naming scheme of my AWS profiles.  After exporting the stack to json and searching for `profile` we discovered two provider entries:

```
"urn": "urn:pulumi:casey-robertson::aws-networking::pulumi:providers:aws::default_1_8_0"
```
and
```
"urn": "urn:pulumi:casey-robertson::aws-networking::pulumi:providers:aws::default"
```

The latter had a reference to my old profile name of `arcuscasey` rather than the newer, current `arcus_casey`.  I edited those entries, imported the stack file and all is good again.  So search around your stack to see if this is happening to you.  I'd like to true up my resources so I only have one provider as there is nothing that makes it immediately apparent that it's a stack 'cache' / support issue.

**Comment by mikhailshilkov** [comment] 2020-01-22 15:00
Can anyone summarize the remaining work here for me, or is the issue that nobody knows?

Unfortunately, I'm a noob in the fascinating world of AWS IAM, so I may need some hand-holding here.

**Comment by cleverguy25** [comment] 2020-02-11 02:32
I am seeing this issue as well, and I swore it worked once upon a time.

**Comment by lukehoban** [comment] 2020-02-11 02:40
@cleverguy25 which issue specifically are you hitting?  (This GitHub issue has unfortunately tracked 3 different things in its lifetime).

**Comment by cleverguy25** [comment] 2020-02-11 19:04
Context, I am using WSL on windows.  I am logged on to our bastian account, and doing the whole source profile thing to assume a role in another account.  AWS cli works, but pulumi gives me this error:

**Comment by lukehoban** [comment] 2020-02-11 23:08
With the setup below - things work.

In `~/.aws/credentials`:
```
[pulumi-token]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
aws_session_token = <redacted>
```

In `~/.aws/config`:
```
[profile staging-token]
role_arn=arn:aws:iam::<redacted>:role/OrganizationAccountAccessRole
source_profile=pulumi-token
region=us-west-2
```

In `Pulumi.<stack>.yaml`:
```yaml
config:
  aws:profile: staging-token
  aws:region: us-west-2
```

Results:

```
$ pulumi up
Previewing update (staging):

     Type                 Name                Plan       
 +   pulumi:pulumi:Stack  assumerole-staging  create     
 +   └─ aws:s3:Bucket     my-bucket           create     
 
Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (staging):

     Type                 Name                Status      
 +   pulumi:pulumi:Stack  assumerole-staging  created     
 +   └─ aws:s3:Bucket     my-bucket           created     
 
Outputs:
    bucketName: "my-bucket-77c7547"

Resources:
    + 2 created

Duration: 1m27s
```

However, if I remove the  `aws:profile` setting and instead set the `AWS_PROFILE` env var I can reproduce:

```
  aws:s3:Bucket (my-bucket):
    error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
```

I presume that provides a workaround for anyone hitting this (use `pulumi config set aws:profile <profile>`), though we should also fix the `AWS_PROFILE` env var support.

Are there any other configurations folks have that are also hitting this error?

**Closed** 2020-02-12 02:35 UTC
Labels: area/providers, customer/feedback, kind/bug, priority/P1

**Comment by Noam-greenberrg** [comment] 2020-09-05 11:32
HI , this issue will not work if you using user and no rule 

in my case the user have credential to do what he need and NOT assume rule so i cant set in the aws config file " role_arn=arn:aws:iam  " as the user dont have the " assume role " 

i think you missing the point the account Id need to be available to any option e.g. role or account access key 

this is my error 

    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16ecc2d]
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*Context).Invoke(0xc0002e2100, 0x4cc7ddd, 0x2d, 0x0, 0x0, 0x4272ee0, 0xc00007c4c0, 0xc00029fb18, 0x2, 0x2, ...)
    	/Users/noam/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/context.go:164 +0x17d
    github.com/pulumi/pulumi-aws/sdk/v2/go/aws.GetCallerIdentity(0xc0002e2100, 0xc00029fb18, 0x2, 0x2, 0xc000000180, 0x16ee98d, 0xc00029fb68)
    	/Users/noam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v2@v2.13.1/go/aws/getCallerIdentity.go:38 +0x9e
    main.main.func1(0xc0002e2100, 0x4cb15d6, 0x13)
    	/Users/noam/Mycode/sentinalone/dv-gateway/deploy/pulumi-dv/main.go:39 +0xab


my config is like this 
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
region=<redacted> 

and if i will use BOTO3 i will get the account id 
import boto3
boto3.client('sts').get_caller_identity().get('Account')


if some one know what is this issue ? 

Thansk

**Comment by geof2001** [comment] 2021-03-31 00:22
New to pulumi and have tried having both aws:profile set in Pulumi.<env>.yaml and env set with AWS_PROFILE individually and set together and have run into the same `error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration` each time.  This is pretty basic authentication using ootb AWS IAM methods.  Hard to even get interested in this as a project without basic auth methods being nailed down properly.  No issues with aws CLI with the env setup with AWS_PROFILE.

**Comment by lukehoban** [comment] 2021-03-31 00:29
@geof2001 would love anymore details you can share on your setup. The usage pattern you describe is definitely supported in general, and used by many/most Pulumi users on AWS - so I expect there is some other more subtle twist on the scenario in your environment. Without sharing any sensitive data - can you share details of how you have your profile configured?

**Comment by geof2001** [comment] 2021-03-31 03:24
~/.aws/credentials is populated with account profiles like this

`[profile-admin]
aws_access_key_id=redact
aws_secret_access_key=redact
aws_session_token=redact`

Have tried setting env var for `export AWS_PROFILE=profile-admin` to this as well as setting `pulami config set aws:profile profile-admin` individually and separately and get the error posted in prior message.  

The only way i've been able to get anything to work is to set all three env variables:
`AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN`

**Comment by rubiagatra** [comment] 2021-07-23 04:26
is there any update for this?

**Comment by mati0090** [comment] 2021-08-04 10:06
I had same issue with AWS CLI configured. The reason was `aws.Provider` set for resources with non-default `profile` defined:
```
export const provider = new aws.Provider("infra", {
  profile: 'test-account',
  region: aws.config.requireRegion(),
});
```
Removing `profile` setting fixed issue.
