### ISSUE TITLE
Infinite loop in aws.acm.Certificate.domain_validation_options

### ISSUE THREAD

**Issue by toidi** [pulumi/pulumi-aws#1201] opened 2020-11-04 18:38 UTC
Hi there,

I've got an infinite loop with the following python snippet:

```python
import pulumi
from pulumi_aws import (
    acm,
    Provider as AWSProvider,
)

config = pulumi.Config()

useast1 = AWSProvider('useast1', region='us-east-1')

cloudfront_cert = acm.Certificate('cloudfront_certificate',
    domain_name=domain_name,
    validation_method='DNS',
    __opts__=pulumi.ResourceOptions(provider=useast1),
)

for i, dvo in enumerate(cloudfront_cert.domain_validation_options):
    print(i, dvo)
```

It runs forever, and if I stop `pulumi up`, it shows the following.

Log tail:
```
$ pulumi up
...
    93897 <pulumi.output.Output object at 0x1269155e0>
    93898 <pulumi.output.Output object at 0x126915820>
    93899 <pulumi.output.Output object at 0x126915a60>
    93900 <pulumi.output.Output object at 0x126915ca0>
    93901 <pulumi.output.Output object at 0x126915ee0>
    93902 <pulumi.output.Output object at 0x12691a160>
    93903 <pulumi.output.Output object at 0x12691a3a0>
    93904 <pulumi.output.Output object at 0x12691a5e0>
    93905 <pulumi.output.Output object at 0x12691a820>
    93906 <pulumi.output.Output object at 0x12691aa60>
    93907 <pulumi.output.Output object at 0x12691aca0>
 
    error: preview canceled
```

**Comment by leezen** [comment] 2020-11-04 20:19
Closing as a dupe of https://github.com/pulumi/pulumi/issues/5028

**Closed by leezen** 2020-11-04 20:19 UTC
