### ISSUE TITLE
Plugin outputs nothing to stdout, access denied exception and call stack to stderr, on two different Windows 10 systems

### ISSUE THREAD

**Issue by dnadle** [pulumi/pulumi-aws#1139] opened 2020-09-25 12:26 UTC
I installed pulumi on two different Windows machines, one running build 1909 and the other 2004. Both systems encounter an exception calling pulumi-resource-aws.exe. The plugin exits immediately with the following output to stderr:

```
    Exception 0xc0000005 0x0 0x7ffa34e70fff 0xf0e0000
    PC=0xf0e0000
    syscall.loadsystemlibrary(0xc0000470e0, 0xc00004a8c0, 0xc00004a8c0, 0x20)
        /opt/hostedtoolcache/go/1.14.9/x64/src/runtime/syscall_windows.go:136 +0xe7
    syscall.LoadDLL(0x6233ef5, 0xb, 0x4404d3, 0xc00006e000, 0x300000002)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/dll_windows.go:80 +0x15e
    syscall.(*LazyDLL).Load(0xc0000041c0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/dll_windows.go:236 +0xc7
    syscall.(*LazyProc).Find(0xc00007fbf0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/dll_windows.go:291 +0xbe
    syscall.(*LazyProc).mustFind(0xc00007fbf0)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/dll_windows.go:309 +0x32
    syscall.(*LazyProc).Addr(0xc00007fbf0, 0x1)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/dll_windows.go:318 +0x32
    syscall.GetUserProfileDirectory(0x14c, 0xc000142270, 0xc00019fc30, 0xc000142270, 0xee56070)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/zsyscall_windows.go:1910 +0x38
    syscall.Token.GetUserProfileDirectory(0x14c, 0xc000048600, 0x2c, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.9/x64/src/syscall/security_windows.go:368 +0x8a
    os/user.current(0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.9/x64/src/os/user/lookup_windows.go:217 +0x1ba
    os/user.Current.func1()
        /opt/hostedtoolcache/go/1.14.9/x64/src/os/user/lookup.go:15 +0x29
    sync.(*Once).doSlow(0xaf32a00, 0x636bc10)
        /opt/hostedtoolcache/go/1.14.9/x64/src/sync/once.go:66 +0xf3
    sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.14.9/x64/src/sync/once.go:57
    os/user.Current(0xc00004d0e8, 0x5, 0x621f595)
        /opt/hostedtoolcache/go/1.14.9/x64/src/os/user/lookup.go:15 +0xf9
    github.com/golang/glog.init.1()
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog_file.go:63 +0x48
    goroutine 6 [chan receive]:
    github.com/golang/glog.(*loggingT).flushDaemon(0xaf33560)
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x92
    created by github.com/golang/glog.init.0
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x276
    rax     0x7ffa322c5784
    rbx     0x7ffa322c5782
    rcx     0x41
    rdi     0xffffffffffbadd11
    rsi     0x0
    rbp     0x0
    rsp     0xedaf4f0
    r8      0x0
    r9      0x0
    r10     0x0
    r11     0x97c
    r12     0xc000007a
    r13     0x0
    r14     0x7ffa322c5784
    r15     0x7ffa34c70000
    rip     0xf0e0000
    rflags  0x10206
    cs      0x33
    fs      0x53
    gs      0x2b
```

This exception occurs both within a 'pulumi up' context or even executing the .exe manually with no arguments. I tried disabling all AV / malware protection. It just seems that the call to GetUserProfileDirectory() is not allowed.

**Comment by Pavel910** [comment] 2021-02-05 12:01
@dnadle any new information on this? One of our users is reporting this exact same problem, would love to know if you found the solution/reason for it. Cheers!

**Comment by Pavel910** [comment] 2021-02-05 13:52
UPDATE: for anyone coming to this issue, the solution is to remove (disable?) your `Webroot` antivirus. Maybe this also applies to other antiviruses as well, but I don't have problems using ESET Internet Security. The Webroot issue is confirmed to be resolved by uninstalling it on 3 machines.

**Comment by leezen** [comment] 2021-02-06 02:14
Thanks for the update. Closing as a dupe of https://github.com/pulumi/pulumi/issues/6093

**Closed by leezen** 2021-02-06 02:14 UTC
Labels: impact/performance, impact/usability
