### ISSUE TITLE
Error when setting VPC configuration in AWS OpenSearch

### ISSUE THREAD

**Issue by mausch** [pulumi/pulumi-aws#2280] opened 2022-12-21 16:21 UTC
### What happened?

Same as https://github.com/pulumi/pulumi-aws/issues/1904 but for OpenSearch.

### Steps to reproduce

Try to create an AWS OpenSearch domain defining a VPC.

### Expected Behavior

Not throw an error.

### Actual Behavior

```
error: aws:opensearch/domain:Domain resource 'my-opensearch' has a problem: Value for unconfigurable attribute: Can't configure a value for "vpc_options.0.vpc_id": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'Domain.VpcOptions.VpcId'.
```

### Additional context

It works when setting a subnet and omitting the VPC (The VPC gets inferred from the subnet).
So I guess it's a matter of fixing the error message or the `DomainVpcOptions` type.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2022-12-22 17:24
Hi @mausch thanks for logging this issue. 

Just to confirm I've understood the issue correctly
- The [OpenSearch Domain resource](https://www.pulumi.com/registry/packages/aws/api-docs/opensearch/domain/) has a property of `vpcOptions.vpcId`.
- When this property is set it causes an error because it's supurflous.
- When the property is not set it work correctly using just the subnet details.
- Therefore we should not expose the vpcId as an input because it can't be used.

Is this correct?

**Comment by mausch** [comment] 2022-12-22 22:11
Yep, that's what I understand.

**Comment by lukehoban** [comment] 2022-12-28 06:29
Closing as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/493 which is tracking the underlying cause of this property being made available as an input when it cannot be used.

**Closed by lukehoban** 2022-12-28 06:29 UTC
Labels: impact/usability, kind/bug, resolution/duplicate
