### ISSUE TITLE
Refresh adds properties to inputs with invalid `""` values

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#1046] opened 2020-07-20 22:36 UTC
[opening in pulumi/aws, though it is likely an issue in pulumi/pulumi or pulumi/pulumi-terraform-bridge]

When deploying a bucket that includes this:

```ts
                replicationConfiguration: {
                    role: replicationRole.arn,
                    rules: [
                        {
                            destination: {
                                bucket: this.destinationBucket.arn,
                            },
                            status: "Enabled",
                            priority: 1,
                        },
                    ],
                },
```

The inputs to the resource initially contain this:

```
                                "destination": {
                                    "__defaults": [],
                                    "bucket": "arn:aws:s3:::redacted"
                                },
```

But after `pulumi refresh` contain this:

```
                                "destination": {
                                    "accessControlTranslation": null,
                                    "accountId": "",
                                    "bucket": "arn:aws:s3:::redacted,
                                    "replicaKmsKeyId": "",
                                    "storageClass": ""
                                },

```

This then leads to a `pulumi preview` failure, as `""` is not a valid input value for `accountId` or `storageClass`:

```
  aws:s3:Bucket (checkpoint-bucket):
    error: aws:s3/bucket:Bucket resource 'checkpoint-bucket' has a problem: "replication_configuration.0.rules.0.destination.0.account_id" doesn't look like AWS Account ID (exactly 12 digits): ""
    error: aws:s3/bucket:Bucket resource 'checkpoint-bucket' has a problem: expected replication_configuration.0.rules.0.destination.0.storage_class to be one of [STANDARD REDUCED_REDUNDANCY STANDARD_IA ONEZONE_IA INTELLIGENT_TIERING GLACIER DEEP_ARCHIVE], got 
```

It seems that either empty string values should be left out for optional properties, or empty string values should be treated as missing in later check/diff calls?

**Comment by pgavlin** [comment] 2020-07-20 22:54
> It seems that either empty string values should be left out for optional properties, or empty string values should be treated as missing in later check/diff calls?

I _think_ that an empty string value for an optional property behaves identically to an absent property, but I'm not 100% certain. We should dig into this and see if we can take the former approach.

**Comment by pgavlin** [comment] 2022-02-11 18:14
The original repro here no longer occurs. There's a bit of other weirdness, though.

Here's the diff between the state files before and after `refresh`:

```diff
--- initial.json	2022-02-11 09:33:25.000000000 -0800
+++ refresh.json	2022-02-11 09:34:23.000000000 -0800
@@ -4,3 +4,3 @@
         "manifest": {
-            "time": "2022-02-11T09:33:12.25472-08:00",
+            "time": "2022-02-11T09:33:51.956462-08:00",
             "magic": "99bb60c3c1c0f0fabcb19da0b5b5ab5b24a3798bc50b58f9f8bb46c604eac765",
@@ -54,3 +54,3 @@
                     ],
-                    "assumeRolePolicy": "{\"Statement\":[{\"Action\":\"sts:AssumeRole\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"s3.amazonaws.com\"}}],\"Version\":\"2012-10-17\"}",
+                    "assumeRolePolicy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"s3.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}",
                     "forceDetachPolicies": false,
@@ -73,3 +73,5 @@
                     ],
-                    "managedPolicyArns": [],
+                    "managedPolicyArns": [
+                        "arn:aws:iam::616138583583:policy/access-9db5826"
+                    ],
                     "maxSessionDuration": 3600,
@@ -160,3 +162,2 @@
                     "replicationConfiguration": {
-                        "__defaults": [],
                         "role": "arn:aws:iam::616138583583:role/repl-659d262",
@@ -164,8 +165,6 @@
                             {
-                                "__defaults": [],
                                 "destination": {
-                                    "__defaults": [],
                                     "bucket": "arn:aws:s3:::dest-eefa236"
                                 },
-                                "priority": 1,
+                                "priority": 0,
                                 "status": "Enabled"
@@ -291,3 +290,2 @@
                 "inputs": {
-                    "__defaults": [],
                     "policyArn": "arn:aws:iam::616138583583:policy/access-9db5826",
```

Defaults annotations are being stripped (they probably shouldn't be) and the `priority` is changing (which I _think_ is legit). The next `up` shows the following diffs:

```
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::gh1046::pulumi:pulumi:Stack::gh1046-dev]
    ~ aws:s3/bucket:Bucket: (update)
        [id=src-4b1d349]
        [urn=urn:pulumi:dev::gh1046::aws:s3/bucket:Bucket::src]
        [provider=urn:pulumi:dev::gh1046::pulumi:providers:aws::default_4_37_3::82612637-4397-43d5-9122-372cdbabfbef]
      ~ replicationConfiguration: {
          ~ rules: [
              ~ [0]: {
                      ~ destination: {
                          ~ bucket: "arn:aws:s3:::dest-eefa236" => "arn:aws:s3:::dest-eefa236"
                        }
                      - id         : "NmU5MWIzNGYtY2Q3Yy00Yjg4LTk0YTItYWY1NWVhMDBlMzgw"
                      + priority   : 1
                      ~ status     : "Enabled" => "Enabled"
                    }
            ]
        }
```

The diff returned from the provider is:
```
{
    "replicationConfiguration.rules[0].destination.bucket": "UPDATE",
    "replicationConfiguration.rules[0].id": "DELETE",
    "replicationConfiguration.rules[0].priority": "",
    "replicationConfiguration.rules[0].status": "UPDATE",
}
```

Annoyingly, the same diff is returned if I re-import the initial state file prior to refresh, so this doesn't seem refresh-related. Indeed, the equivalent TF config reproduces these diffs:

```
  # aws_s3_bucket.src will be updated in-place
  ~ resource "aws_s3_bucket" "src" {
        id                          = "src20220211181250620600000001"
        tags                        = {}
        # (11 unchanged attributes hidden)

      ~ replication_configuration {
            # (1 unchanged attribute hidden)

          + rules {
              + priority = 1
              + status   = "Enabled"

              + destination {
                  + bucket = "arn:aws:s3:::dest20220211181200392000000002"
                }
            }
          - rules {
              - id       = "MjRhZDJmYjctMWQzNC00NGVmLWFjZjQtOTk0MDAyMDhiMmI2" -> null
              - priority = 0 -> null
              - status   = "Enabled" -> null

              - destination {
                  - bucket = "arn:aws:s3:::dest20220211181200392000000002" -> null
                }
            }
        }

        # (1 unchanged block hidden)
    }
```

The original issue at hand, though, seems to be fixed, so I'm going to go ahead and close this.

**Closed** 2022-02-11 18:14 UTC
Labels: kind/bug, resolution/no-repro
