### ISSUE TITLE
aws:ecr:RepositoryPolicy displays diff for `repository` on every run

### ISSUE THREAD

**Issue by agibralter** [pulumi/pulumi-aws#2491] opened 2023-04-26 18:41 UTC
### What happened?

Given the following code, every run of `pulumi up` or `pulumi preview` displays a `diff` for the RepositoryPolicy's repository:

```python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

ALLOWED_ACCOUNT_IDS = [
    "xxx",  # dev
    "yyy",  # staging
    "zzz",  # prod
]

# Set up app container image repository
repository = awsx.ecr.Repository(
    "backend",
    name="backend",
    lifecycle_policy={
        "rules": [
            {
                "description": "Delete build images after 90 days",
                "maximum_age_limit": 90,
                "tag_status": "any",
            },
        ],
    },
)

# Allow app subaccounts to pull from image repository
repository_policy = aws.ecr.RepositoryPolicy(
    "repository-policy",
    repository=repository.name,
    policy={
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowCrossAccountPull",
                "Effect": "Allow",
                "Principal": {
                    "AWS": [
                        f"arn:aws:iam::{account_id}:root"
                        for account_id in ALLOWED_ACCOUNT_IDS
                    ]
                },
                "Action": [
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:BatchGetImage",
                    "ecr:GetDownloadUrlForLayer",
                ],
            }
        ],
    },
)

pulumi.export("ecr-url", repository.url)
```

### Expected Behavior

If nothing changes in the code, there should be no resource updates.

### Steps to reproduce

Use the code above and run `pulumi up` then run `pulumi up` again.

### Output of `pulumi about`

```
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.36.0
aws-tags       0.4.1
awsx           1.0.2
datadog        4.16.0
docker         3.6.1
pulumiservice  0.6.1
python         unknown

Host     
OS       darwin
Version  13.2.1
Arch     x86_64

This project is written in python: executable='/Users/me/Library/Caches/pypoetry/virtualenvs/MYORG-infra-Csm7IBmd-py3.10/bin/python3' version='3.10.9
'

Current Stack: MYORG/app-builds/ci

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:ci::app-builds::pulumi:pulumi:Stack::app-builds-ci
pulumi:providers:awsx                      urn:pulumi:ci::app-builds::pulumi:providers:awsx::default_1_0_2
awsx:ecr:Repository                        urn:pulumi:ci::app-builds::awsx:ecr:Repository::MYORG-app-backend-common
pulumi:providers:aws                       urn:pulumi:ci::app-builds::pulumi:providers:aws::default_5_16_2
aws:ecr/repository:Repository              urn:pulumi:ci::app-builds::awsx:ecr:Repository$aws:ecr/repository:Repository::MYORG-app-backend-common
aws:ecr/lifecyclePolicy:LifecyclePolicy    urn:pulumi:ci::app-builds::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::MYORG-app-backend-common
pulumi:providers:pulumi                    urn:pulumi:ci::app-builds::pulumi:providers:pulumi::default
pulumi:providers:aws                       urn:pulumi:ci::app-builds::pulumi:providers:aws::default_5_36_0
aws:ecr/repositoryPolicy:RepositoryPolicy  urn:pulumi:ci::app-builds::aws:ecr/repositoryPolicy:RepositoryPolicy::MYORG-app-repository-policy


Found no pending operations associated with MYORG/ci

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ME
User           ME
Organizations  ME, MYORG

Pulumi locates its logs in /var/folders/_4/rl08tps91zzdbj17jj5s879m0000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: types-PyYAML@6.0.12.9: Invalid character(s) found in patch number "12.9"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-04-26 20:10
@agibralter Thanks for reporting this issue and we apologize for any inconvenience caused by this. We're currently aware of several diffing related bugs and are actively working to improve our user experience with these.

For additional information for when we look further into resolving this specific case, I was able to reproduce this issue. The following are detailed logs indicating which fields require being "updated":

```
    Type                         Name                   Plan        Info
     pulumi:pulumi:Stack          aws-native-python-dev              
 +-  └─ aws:ecr:RepositoryPolicy  repository-policy      replace     [diff: ~repository]


Resources:
    +-1 to replace
    4 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws-native-python::pulumi:pulumi:Stack::aws-native-python-dev]
    ++aws:ecr/repositoryPolicy:RepositoryPolicy: (create-replacement)
        [id=backend]
        [urn=urn:pulumi:dev::aws-native-python::aws:ecr/repositoryPolicy:RepositoryPolicy::repository-policy]
        [provider=urn:pulumi:dev::aws-native-python::pulumi:providers:aws::default_5_37_0::7ac762e1-dfe4-4c8c-a7f1-93fa743f0cf3]
      ~ repository: "backend" => output<string>
    +-aws:ecr/repositoryPolicy:RepositoryPolicy: (replace)
        [id=backend]
        [urn=urn:pulumi:dev::aws-native-python::aws:ecr/repositoryPolicy:RepositoryPolicy::repository-policy]
        [provider=urn:pulumi:dev::aws-native-python::pulumi:providers:aws::default_5_37_0::7ac762e1-dfe4-4c8c-a7f1-93fa743f0cf3]
      ~ repository: "backend" => output<string>
    --aws:ecr/repositoryPolicy:RepositoryPolicy: (delete-replaced)
        [id=backend]
        [urn=urn:pulumi:dev::aws-native-python::aws:ecr/repositoryPolicy:RepositoryPolicy::repository-policy]
        [provider=urn:pulumi:dev::aws-native-python::pulumi:providers:aws::default_5_37_0::7ac762e1-dfe4-4c8c-a7f1-93fa743f0cf3]
```

It appears that we're attempting to recalculate the repository name on each `pulumi up` invocation, resulting in the spurious diff we observe. One potential workaround for now, though sadly not ideal, is to manually specify the name of the repository the policy should target, eg:
```
repository_policy = aws.ecr.RepositoryPolicy(
    "repository-policy",
    repository="backend", # manually specifying the name, instead of dynamically getting from repository object
    ...
)
```

**Comment by t0yv0** [comment] 2024-05-06 18:28
I've looked a this briefly and unfortunately it still reproduces. This is an interesting issue around how Component Resources are handled in Python since awsx.ecr.Repository is one of those. Currently I'm seeing this in the gRPC log:

```
{
  "method": "/pulumirpc.ResourceMonitor/RegisterResource",
  "request": {
    "type": "awsx:ecr:Repository",
    "name": "backend",
    "parent": "urn:pulumi:dev2::aws-2491::pulumi:pulumi:Stack::aws-2491-dev2",
    "object": {
      "lifecyclePolicy": {
        "rules": [
          {
            "description": "Delete build images after 90 days",
            "maximumAgeLimit": 90,
            "tagStatus": "any"
          }
        ]
      },
      "name": "backend"
    },
    "propertyDependencies": {
      "lifecyclePolicy": {},
      "name": {}
    },
    "version": "2.9.0",
    "acceptSecrets": true,
    "supportsPartialValues": true,
    "remote": true,
    "acceptResources": true,
    "sourcePosition": {
      "uri": "file:///Users/anton/Library/Mobile%20Documents/com~apple~CloudDocs/pulumi-bugs/aws-2491/venv/lib/python3.10/site-packages/pulumi_awsx/ecr/repository.py",
      "line": 189
    }
  },
  "response": {
    "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository::backend",
    "object": {
      "lifecyclePolicy": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "id": "backend",
        "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::backend"
      },
      "repository": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "id": "backend",
        "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/repository:Repository::backend"
      },
      "url": "616138583583.dkr.ecr.us-west-2.amazonaws.com/backend"
    },
    "propertyDependencies": {
      "lifecyclePolicy": {
        "urns": [
          "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::backend"
        ]
      },
      "repository": {
        "urns": [
          "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/repository:Repository::backend"
        ]
      },
      "url": {
        "urns": [
          "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/repository:Repository::backend"
        ]
      }
    }
  },
  "metadata": {
    "mode": "server"
  }
}
``` 

It's not populating name as resource outputs in RegisterResource, it also has this:


```
{
  "method": "/pulumirpc.ResourceMonitor/RegisterResourceOutputs",
  "request": {
    "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository::backend",
    "outputs": {
      "lifecyclePolicy": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "id": "backend",
        "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::backend"
      },
      "repository": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "id": "backend",
        "urn": "urn:pulumi:dev2::aws-2491::awsx:ecr:Repository$aws:ecr/repository:Repository::backend"
      }
    }
  },
  "response": {},
  "metadata": {
    "mode": "server"
  }
}
```

Most interestingly in the schema of AWSx, name is not considered an output property.

**Comment by t0yv0** [comment] 2024-05-06 18:41
As a workaround I recommend computing the name out of the exported `url` property:

```python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

ALLOWED_ACCOUNT_IDS = [
    "xxx",  # dev
    "yyy",  # staging
    "zzz",  # prod
]

# Set up app container image repository
repository = awsx.ecr.Repository(
    "backend",
    name="backend",
    lifecycle_policy={
        "rules": [
            {
                "description": "Delete build images after 90 days",
                "maximum_age_limit": 90,
                "tag_status": "any",
            },
        ],
    },
)

computed_name = repository.url.apply(lambda x: x.split('/')[-1])


repository_policy = aws.iam.get_policy_document(statements=[aws.iam.GetPolicyDocumentStatementArgs(
    sid="new policy",
    effect="Allow",
    principals=[aws.iam.GetPolicyDocumentStatementPrincipalArgs(
        type="AWS",
        identifiers=["616138583583"],
    )],
    actions=[
        "ecr:GetDownloadUrlForLayer",
        "ecr:BatchGetImage",
        "ecr:BatchCheckLayerAvailability",
        "ecr:PutImage",
        "ecr:InitiateLayerUpload",
        "ecr:UploadLayerPart",
        "ecr:CompleteLayerUpload",
        "ecr:DescribeRepositories",
        "ecr:GetRepositoryPolicy",
        "ecr:ListImages",
        "ecr:DeleteRepository",
        "ecr:BatchDeleteImage",
        "ecr:SetRepositoryPolicy",
        "ecr:DeleteRepositoryPolicy",
    ],
)])


# Allow app subaccounts to pull from image repository
repository_policy = aws.ecr.RepositoryPolicy(
    "repository-policy-40",
    repository=computed_name,
    policy=repository_policy.json
)


pulumi.export("ecr-name", repository.name)
pulumi.export("ecr-url", repository.url)
pulumi.export("computed-name", computed_name)

```

This works as expected with `pulumi up`.

I'll add an issue in pulumi-awsx to export the name property.

**Closed** 2024-05-06 18:41 UTC
Labels: kind/bug, resolution/by-design, bug/diff
