### ISSUE TITLE
Continuous diff on AWS API v2 Integration

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#2490] opened 2023-04-26 18:01 UTC
### What happened?

When creating an AWS API v2 Integration and using with a lambda function invoke, a continuous diff is shown on passthrough behaviour, even if the passthrough behaviour isn't set. If it is set, it constantly tries to update

```
Please choose a stack, or create a new one: dev
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/jaxxstorm/apigateway_integration/dev/previews/98baa2f9-6037-4f3b-a05b-1dcc06f4e65d

     Type                             Name                        Plan     Info
     pulumi:pulumi:Stack              apigateway_integration-dev
     ├─ aws:apigatewayv2:Api          example
     ├─ aws:lambda:Function           example                              [diff: ~code]
     ├─ aws:iam:Role                  example-dotnet-lambda
     └─ aws:apigatewayv2:Integration  example                              [diff: ~__defaults,passthroughBehavior]


Resources:
    5 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::apigateway_integration::pulumi:pulumi:Stack::apigateway_integration-dev]
~ pulumi:pulumi:Stack: (refresh)
    [urn=urn:pulumi:dev::apigateway_integration::pulumi:pulumi:Stack::apigateway_integration-dev]
    ~ aws:apigatewayv2/integration:Integration: (refresh)
        [id=umqutr3]
        [urn=urn:pulumi:dev::apigateway_integration::aws:apigatewayv2/integration:Integration::example]
        [provider=urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0::1cc8a585-caa2-4f6b-a6d5-0382a4b5be5b]
    ~ aws:apigatewayv2/api:Api: (refresh)
        [id=5nn4fallli]
        [urn=urn:pulumi:dev::apigateway_integration::aws:apigatewayv2/api:Api::example]
        [provider=urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0::1cc8a585-caa2-4f6b-a6d5-0382a4b5be5b]
    ~ aws:lambda/function:Function: (refresh)
        [id=example-4a6de35]
        [urn=urn:pulumi:dev::apigateway_integration::aws:lambda/function:Function::example]
        [provider=urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0::1cc8a585-caa2-4f6b-a6d5-0382a4b5be5b]
    ~ aws:iam/role:Role: (refresh)
        [id=example-dotnet-lambda-b7796b8]
        [urn=urn:pulumi:dev::apigateway_integration::aws:iam/role:Role::example-dotnet-lambda]
        [provider=urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0::1cc8a585-caa2-4f6b-a6d5-0382a4b5be5b]

Do you want to perform this update?  [Use arrows to move, type to filter]
  yes
> no
  details
```

### Expected Behavior

Passthrough behaviour shouldn't be touched/modified

### Steps to reproduce

Create a program that creates an IAM role, lambda function, Api Gateway API and v2 integration. Here's an example in csharp:

```csharp
using Pulumi;
using Aws = Pulumi.Aws;
using System.Text.Json;
using System.Collections.Generic;

return await Deployment.RunAsync(() =>
{

    var role = new Aws.Iam.Role("example-dotnet-lambda", new Aws.Iam.RoleArgs
    {
        AssumeRolePolicy = JsonSerializer.Serialize(new
        {
            Version = "2008-10-17",
            Statement = new[]
             {
                new
                {
                    Sid = "",
                    Effect = "Allow",
                    Principal = new
                    {
                        Service = "lambda.amazonaws.com"
                    },
                    Action = "sts:AssumeRole"
                }
            }
        }),
        ManagedPolicyArns = new[]
        {
            "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        }
    });

    var lambda = new Aws.Lambda.Function("example", new Aws.Lambda.FunctionArgs
    {
        Runtime = "dotnetcore3.1",
        Code = new FileArchive("../DotnetLambda/src/DotnetLambda/bin/Debug/netcoreapp3.1/publish"),
        Handler = "DotnetLambda::DotnetLambda.Function::FunctionHandler",
        Role = role.Arn
    });

    var api = new Aws.ApiGatewayV2.Api("example", new Aws.ApiGatewayV2.ApiArgs
    {
        ProtocolType = "HTTP",
    });

    var httpIntegration = new Aws.ApiGatewayV2.Integration("example", new Aws.ApiGatewayV2.IntegrationArgs
    {
        ApiId = api.Id,
        IntegrationMethod = "POST",
        IntegrationType = "AWS_PROXY",
        PayloadFormatVersion = "2.0",
        IntegrationUri = lambda.InvokeArn

    });


    // Export the name of the bucket
    return new Dictionary<string, object?>
    {
        ["httpIntegration"] = httpIntegration.Id
    };
});
```

Run `pulumi up` to create the program, then run `pulumi up -r` to refesh

### Output of `pulumi about`

```
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  apigateway_integration -> /Users/lbriggs/src/github/jaxxstorm/pulumi-examples/dotnet/aws/apigateway_integration/infra/bin/Debug/net6.0/apigateway_integration.dll


Build succeeded.

    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.46

'dotnet build -nologo .' completed successfully
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.37.0
dotnet  unknown

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in dotnet: executable='/opt/homebrew/bin/dotnet' version='7.0.202'

Current Stack: jaxxstorm/apigateway_integration/dev

TYPE                                      URN
pulumi:pulumi:Stack                       urn:pulumi:dev::apigateway_integration::pulumi:pulumi:Stack::apigateway_integration-dev
pulumi:providers:aws                      urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0
aws:apigatewayv2/api:Api                  urn:pulumi:dev::apigateway_integration::aws:apigatewayv2/api:Api::example
aws:iam/role:Role                         urn:pulumi:dev::apigateway_integration::aws:iam/role:Role::example-dotnet-lambda
aws:lambda/function:Function              urn:pulumi:dev::apigateway_integration::aws:lambda/function:Function::example
aws:apigatewayv2/integration:Integration  urn:pulumi:dev::apigateway_integration::aws:apigatewayv2/integration:Integration::example


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jaxxstorm
User           jaxxstorm
Organizations  jaxxstorm

Dependencies:
NAME        VERSION
Pulumi      3.54.1
Pulumi.Aws  5.37.0

Pulumi locates its logs in /var/folders/rk/2c715ngd14jc4c7d3659m7pm0000gn/T/ by default

```

### Additional context

If you set the passthrough behaviour:

```
  var httpIntegration = new Aws.ApiGatewayV2.Integration("example", new Aws.ApiGatewayV2.IntegrationArgs
    {
        ApiId = api.Id,
        IntegrationMethod = "POST",
        IntegrationType = "AWS_PROXY",
        PayloadFormatVersion = "2.0",
        IntegrationUri = lambda.InvokeArn,
        PassthroughBehavior = "NEVER",

    });
```

It constantly modifies:

```
Please choose a stack, or create a new one: dev
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/jaxxstorm/apigateway_integration/dev/previews/02f4d58f-e6f6-420b-b699-41c0919528af

     Type                             Name                        Plan       Info
     pulumi:pulumi:Stack              apigateway_integration-dev
 ~   └─ aws:apigatewayv2:Integration  example                     update     [diff: ~passthroughBehavior]


Resources:
    ~ 1 to update
    4 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::apigateway_integration::pulumi:pulumi:Stack::apigateway_integration-dev]
    ~ aws:apigatewayv2/integration:Integration: (update)
        [id=6mj0zgu]
        [urn=urn:pulumi:dev::apigateway_integration::aws:apigatewayv2/integration:Integration::example]
        [provider=urn:pulumi:dev::apigateway_integration::pulumi:providers:aws::default_5_37_0::49c322e5-b133-47fa-b946-7b1d77738e60]
      + passthroughBehavior: "NEVER"
```

I believe this is due to a bug in the `READ` method in the provider

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2024-01-30 22:12
Revisiting this in some depth..

Looks like if I remove this line it's OK:

```
        // PassthroughBehavior = "NEVER"
```

Per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration#argument-reference specifying passthroughBehavior is only supported for WebSocket APIs but the example is an HTTP API.

```
[passthrough_behavior](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration#passthrough_behavior) - (Optional) Pass-through behavior for incoming requests based on the Content-Type header in the request, and the available mapping templates specified as the request_templates attribute. Valid values: WHEN_NO_MATCH, WHEN_NO_TEMPLATES, NEVER. Default is WHEN_NO_MATCH. Supported only for WebSocket APIs.
```

**Comment by t0yv0** [comment] 2024-01-30 22:13
While I still can reproduce this I suspect this might hold upstream as well. Per the earlier test 

```
// The real upstream code makes an API call and then calls resourceIntegrationRead. The API call does
// not return passthrough_behavior and effectively this sets "passthrough_behavior" to nil.
```

I'll leave it open for now. CC @iwahbe

**Comment by iwahbe** [comment] 2024-01-31 10:01
Since we currently believe that this is an upstream bug, I'll mark as `awaiting-upstream`.

**Comment by t0yv0** [comment] 2024-04-26 17:27
On latest this issue is fixed but replaced by another one:

```
Previewing refresh (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/anton-pulumi-corp/aws-2490/dev/previews/c2e0fd57-f57e-47f3-8009-af825e7e8493

     Type                             Name                   Plan       Info
     pulumi:pulumi:Stack              aws-2490-dev                      
     ├─ aws:apigatewayv2:Api          example                           
     ├─ aws:iam:Role                  example-dotnet-lambda             
     ├─ aws:apigatewayv2:Integration  example                           
 ~   └─ aws:lambda:Function           example                update     [diff: +replacementSecurityGroupIds]

Resources:
    ~ 1 to update
    4 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
 details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws-2490::pulumi:pulumi:Stack::aws-2490-dev]
    ~ aws:lambda/function:Function: (update)
        [id=example-a38227f]
        [urn=urn:pulumi:dev::aws-2490::aws:lambda/function:Function::example]
        [provider=urn:pulumi:dev::aws-2490::pulumi:providers:aws::default_6_32_0::17a03856-baf4-41b0-acf0-ee60b9237762]
        --outputs:--
      + replacementSecurityGroupIds : []

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
  [Use arrows to move, type to filter]
  yes
  no
> details

```

I think it's in the series of issues that repro in TF where there is benign drift from nil to [] that TF does not warn on but Pulumi does. I'll close this as fixed and reopen the new repro. We do have to solve for this as it is annoying.

**Closed** 2024-04-26 17:28 UTC
Labels: kind/bug, resolution/no-repro, awaiting-upstream, area/refresh
