### ISSUE TITLE
[appsync] support for serverless aurora rds data source missing

### ISSUE THREAD

**Issue by BerndWessels** [pulumi/pulumi-aws#461] opened 2019-02-07 01:05 UTC
It seems that the support for [aurora serverless rds data source](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html) is missing.

If so please take this as a feature request.

If not please point me to the documentation.

Thank you

**Comment by BerndWessels** [comment] 2019-05-14 20:15
Any updates on this?

It looks like Terraform has already support for it [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/vendor/github.com/aws/aws-sdk-go/service/appsync/api.go#L3768)

Urgently needed

**Comment by lukehoban** [comment] 2019-05-14 20:41
> It looks like Terraform has already support for it here

That link is to the AWS Go SDK (vendored into terraform-provider-aws).  Are you sure this feature is exposed through the Terraform provider currently? I so not see it in https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_appsync_datasource.go#L15.

**Comment by BerndWessels** [comment] 2019-05-14 22:01
@lukehoban I thought pulumi is using the terraform go sdk providers, doesn't it?

I am fighting an uphill battle in our enterprise against the proponents of the cloud formation based solutions, but its hard to argue when features are taking month and month to arrive, if at all.

I hope there will be some progress. Is there anyway to contribute to speed this up?

**Comment by lukehoban** [comment] 2019-05-15 00:06
> @lukehoban I thought pulumi is using the terraform go sdk providers, doesn't it?

The `@pulumi/aws` package builds on the `terraform-provider-aws` Terraform provider, which in turn builds on top of the AWS Go SDK.

The code you linked is code within the AWS Go SDK, which does have support for Aurora appsync databases.  That code is not yet called from anything in the Terraform AWS provider - which does not yet support these.  Once support is added to the Terraform AWS provider, it will be available in `@pulumi/aws` within a couple days.

To contribute here - I'd suggest opening an issue and/or PR in https://github.com/terraform-providers/terraform-provider-aws.  This PR (which added initial support for AppSync Datasources) gives a sense of what is needed: https://github.com/terraform-providers/terraform-provider-aws/pull/2758.

**Comment by stack72** [comment] 2019-06-05 14:49
Hi @BerndWessels,

As this is not available in the upstream terraform provider, I just opened an issue in that repository that we will use to track the progression of this work.

Once that has been implemented upstream, then Pulumi will be able to take advantage of this. I am going to close this issue out as a duplicate of the upstream issue. Please feel free to +1 that issue :)

https://github.com/terraform-providers/terraform-provider-aws/issues/8870

Thanks again

Paul

**Closed by stack72** 2019-06-05 14:49 UTC
