### ISSUE TITLE
AWS S3 Bucket/Replication Policy Deleted After 2nd/3rd Deploy Because of Tag Edits

### ISSUE THREAD

**Issue by matan-orland-lmnd** [pulumi/pulumi-aws#2577] opened 2023-06-27 16:33 UTC
### What happened?

Recently I've implemented `AWS S3` bucket replication for **existing** buckets to new buckets in a different `AWS` account. **TL;DR: 2nd/3rd deploy with no change to code or environment removed resources, even ones that were added before this change.**

Upon first deploy all correct resources were created:
1. `aws:iam:Role` as a source replication role
2. `aws:iam:Policy` as a source replication policy (see below for details)
3. `pulumi:providers:aws` - destination account provider
4. `aws:s3:Bucket` - destination bucket
5. `aws:s3:BucketPolicy` - destination bucket policy
6. `aws:s3:BucketReplicationConfig` - source bucket replication configuration

Upon 2nd deploy with the exact same code the following diff is observed:
```
        ~ aws:s3/bucket:Bucket: (update) 🔒
            [id=****]
            [urn=****aws:s3/bucket:Bucket::****]
            [provider=****]
          - lifecycleRules: [
     			... /*whatever lifecycle rule was defined on the bucket*/
            ]
 ```
 
 Upon 3rd deploy (again, exact same code) the following diff was observed:
 ```
         ~ aws:s3/bucket:Bucket: (update) 🔒
            [id=****]
            [urn=****$aws:s3/bucket:Bucket::****]
            [provider=****]
          - replicationConfiguration: {
              .../* replication configuration as defined */
            }
 ```

deleting the previously created replication configuration (again, no code/environment changes)

The code follows this structure: (I've removed redundant details)
```ts
    const sourceBucket = new aws.s3.Bucket(
      name,
      {
        bucket: bucketName,
        versioning: { enabled: true },
        ...
      },
      { parent: this, protect: true }
    )

    new aws.s3.BucketLifecycleConfigurationV2(
      name,
      {
        bucket: sourceBucket.id,
        rules: [
          ...
        ],
      },
      { parent: sourceBucket }
    )

    // setup aws provider for destination account
    const destinationAccountProvider = new aws.Provider(
      `destination-account-provider`,
      {
        assumeRole: {
          roleArn: ...,
        },
        skipCredentialsValidation: true,
      },
      { parent: sourceBucket }
    )

    const destinationBucketName = 'some-name'

    // destination bucket
    const destinationBucket = new aws.s3.Bucket(
      'destination-bucket',
      { bucket: destinationBucketName, versioning: { enabled: true }, ... },
      { parent: sourceBucket, provider: destinationAccountProvider, retainOnDelete: true }
    )

    // create source replication role
    const replicationRole = new aws.iam.Role(
      's3-source-replication-role',
      {
        assumeRolePolicy: JSON.stringify({
          Version: '2012-10-17',
          Statement: [
            {
              Action: 'sts:AssumeRole',
              Principal: {
                Service: 's3.amazonaws.com',
              },
              Effect: 'Allow',
              Sid: '',
            }
          ],
        }),
      },
      { parent: sourceBucket }
    )

    // create source replication policy for replication role
    p.all([sourceBucket.arn, destinationBucket.arn]).apply(async ([sourceBucketArn, destinationBucketArn]) => {
      new aws.iam.RolePolicy(
        's3-source-replication-policy',
        {
          role: replicationRole.id,
          policy: JSON.stringify({
            Version: '2012-10-17',
            Statement: [
              /* statements allowing for replication (and batch replication) */
            ],
          }),
        },
        { parent: replicationRole }
      )
    })

    // destination bucket policy document
    const destinationBucketPolicyDocument = p
      .all([destinationBucket.arn, replicationRole.arn])
      .apply(async ([destinationBucketArn, replicationRoleArn]) => {
        return aws.iam
          .getPolicyDocument(
            {
              statements: [
                /* bucket policy to allow replication */
              ],
            },
            { parent: destinationBucket, async: true, provider: destinationAccountProvider }
          )
          .then((x) => x.json)
      })

    // destination bucket policy
    new aws.s3.BucketPolicy(
      `destination-bucket-policy`,
      {
        bucket: destinationBucket.id,
        policy: destinationBucketPolicyDocument,
      },
      {
        parent: destinationBucket,
        provider: destinationAccountProvider,
        retainOnDelete: true,
      }
    )

    // setup replication
    new aws.s3.BucketReplicationConfig(
      `s3-source-bucket-replication-config`,
      {
        bucket: sourceBucket.id,
        role: replicationRole.arn,
        rules: [
          {
            id: 'destination-replication-rule',
            status: 'Enabled',
            destination: {
              bucket: destinationBucket.arn,
            },
          },
        ],
      },
      { parent: sourceBucket }
    )
```

### Expected Behavior

Consequent deploys with no change to code should have empty diffs and not delete any resource.

### Steps to reproduce

1. create source bucket with policy
2. `pulumi up`
3. create replication
4. `pulumi up`
5. `pulumi up` (one resource is removed)
6. `pulumi up` (another resource is removed)

### Output of `pulumi about`

```
CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.41.0
cloudflare  3.6.0
datadog     4.16.0
datadog     3.3.0
docker      3.6.1
kafka       3.4.0
kubernetes  3.29.1
kubernetes  3.20.3
mysql       3.1.0
nodejs      unknown
okta        3.23.0
pagerduty   2.2.0
postgresql  3.8.0
rabbitmq    3.3.0
random      4.13.2
spotinst    3.8.0
tls         4.10.0

Host
OS       debian
Version  11.7
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment] 2023-06-29 16:59
Hi @matan-orland-lmnd - thank you for the thorough reproduction here! It appears this is a bug in the upstream Terraform provider, as well. I found [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/27324) which also mentions a workaround. I'm going to mark this as an upstream bug for now, and please let us know if this workaround does not solve your immediate issue. Until the upstream issue is resolved, unfortunately, it will persist on our end as well.

Thanks again!

**Comment by matan-orland-lmnd** [comment] 2023-06-29 20:36
Thanks @kpitzen! I'll look at the workaround next week and report back on the status.

**Comment by matan-orland-lmnd** [comment] 2023-07-02 14:42
@kpitzen note that I also have another problem, which is that enabling this `s3 replication` deletes the bucket `lifecycle policy`. The suggested solution [here](https://github.com/hashicorp/terraform-provider-aws/issues/27324), when extended to `lifecycle policies` (i.e define them inline) results in no lifecycle policy being created, and the existing one still being removed. Very odd.

I've tried looking at your documentation, and couldn't find anything that would make `replication configuration` and `lifecycle policies` mutually exclusive.

I did, however, find a minor mistake in your [documentation](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketlifecycleconfigurationv2/#properties) of `BucketLifecycleConfigurationV2` where the description of the rules field states

> List of configuration blocks describing the rules managing **the replication**. See below.

**Comment by matan-orland-lmnd** [comment] 2023-08-28 10:24
@kpitzen I've finally figured out where this bug is coming from, and it is not the original bug from Terraform, although it could still come from Terraform.

The one thing I failed to mention in my reproduction example, was that we were also opting out of using `AWS Backup` when we were opting in to `S3 Replication` - we do this by editing tags on the bucket, which `AWS Backup` then uses to decide which bucket to back up. This edit of the tags on the first `pulumi up` is what causes the deletion of lifecycle, and then replication policies. Meaning it is completely separate from the Terraform bug you posted.

I've reproduced this by creating a bucket, then updating the tags, then running `pulumi up` again, and it removed the bucket lifecycle policies. Couldn't find a similar issue in your issues. I've tried adding, removing and editing tags - all with the same outcome.

I've also tried (back when I thought this was the same Terraform bug):
1. Creating lifecycle policy in a dynamic provider.
2. Creating all resources on destination account in a dynamic provider.
3. Creating all replication-related resources in a dynamic provider.
4. Creating destination account resources manually. (with or without the other resources in a dynamic provider)
5. Creating everything manually.

Tag changes cause this.

**Comment by VenelinMartinov** [comment] 2024-01-22 15:41
I've constructed a repro from the description:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const name = "bucket-example"

const apply_tags = new pulumi.Config().getBoolean("apply_tags")

const sourceBucket = new aws.s3.Bucket(
    name,
    {
        versioning: { enabled: true },
        tags: apply_tags ? { "Name": "Staging" } : undefined,
    },
)

new aws.s3.BucketLifecycleConfigurationV2(
    name,
    {
        bucket: sourceBucket.id,
        rules: [{
            id: "rule-1",
            filter: {
                tag: {
                    key: "Name",
                    value: "Staging",
                },
            },
            expiration: {
                days: 90,
            },
            status: "Enabled",
        }],
    },
    { parent: sourceBucket }
)
```

1. `pulumi config set apply_tags true`
2. `pulumi up --yes`
3. `pulumi config set apply_tags false`
4. `pulumi up --yes`
5. Notice the tags change.
6. `pulumi up --yes` - this one should be a noop.
7. Notice that the `lifecycleRules` appears in the diff.


Here is the GRPC log for the lifecycle diff:

```
{
    "method": "/pulumirpc.ResourceProvider/Diff",
    "request": {
        "id": "bucket-example-29c0219",
        "urn": "urn:pulumi:dev::aws_bucket_2577::aws:s3/bucket:Bucket::bucket-example",
        "olds": {
            "accelerationStatus": "",
            "acl": "private",
            "arn": "arn:aws:s3:::bucket-example-29c0219",
            "bucket": "bucket-example-29c0219",
            "bucketDomainName": "bucket-example-29c0219.s3.amazonaws.com",
            "bucketRegionalDomainName": "bucket-example-29c0219.s3.amazonaws.com",
            "corsRules": [],
            "forceDestroy": false,
            "grants": [],
            "hostedZoneId": "Z3AQBSTGFYJSTF",
            "id": "bucket-example-29c0219",
            "lifecycleRules": [
                {
                    "abortIncompleteMultipartUploadDays": 0,
                    "enabled": true,
                    "expiration": {
                        "date": "",
                        "days": 90,
                        "expiredObjectDeleteMarker": false
                    },
                    "id": "rule-1",
                    "noncurrentVersionExpiration": null,
                    "noncurrentVersionTransitions": [],
                    "prefix": "",
                    "tags": {
                        "Name": "Staging"
                    },
                    "transitions": []
                }
            ],
            "loggings": [],
            "objectLockConfiguration": null,
            "region": "us-east-1",
            "replicationConfiguration": null,
            "requestPayer": "BucketOwner",
            "serverSideEncryptionConfiguration": {
                "rule": {
                    "applyServerSideEncryptionByDefault": {
                        "kmsMasterKeyId": "",
                        "sseAlgorithm": "AES256"
                    },
                    "bucketKeyEnabled": false
                }
            },
            "tags": {},
            "tagsAll": {},
            "versioning": {
                "enabled": true,
                "mfaDelete": false
            },
            "website": null
        },
        "news": {
            "__defaults": [
                "acl",
                "bucket",
                "forceDestroy"
            ],
            "acl": "private",
            "bucket": "bucket-example-29c0219",
            "forceDestroy": false,
            "versioning": {
                "__defaults": [
                    "mfaDelete"
                ],
                "enabled": true,
                "mfaDelete": false
            }
        },
        "oldInputs": {
            "__defaults": [
                "acl",
                "bucket",
                "forceDestroy"
            ],
            "acl": "private",
            "bucket": "bucket-example-29c0219",
            "forceDestroy": false,
            "versioning": {
                "__defaults": [
                    "mfaDelete"
                ],
                "enabled": true,
                "mfaDelete": false
            }
        }
    },
    "response": {
        "stables": [
            "bucket",
            "bucketPrefix"
        ],
        "changes": "DIFF_SOME",
        "diffs": [
            "lifecycleRules",
            "lifecycleRules",
            "lifecycleRules"
        ],
        "detailedDiff": {
            "lifecycleRules[0].enabled": {
                "kind": "DELETE"
            },
            "lifecycleRules[0].expiration.days": {
                "kind": "DELETE"
            },
            "lifecycleRules[0].tags.Name": {
                "kind": "DELETE"
            }
        },
        "hasDetailedDiff": true
    },
    "metadata": {
        "kind": "resource",
        "mode": "client",
        "name": "aws"
    }
}
```

**Comment by VenelinMartinov** [comment] 2024-01-26 15:00
@matan-orland-lmnd sorry you are having this issue - it certainly looks very counterintuitive.
In the original example you posted it looks like you are mixing `s3.Bucket` with `s3.BucketLifecycleConfigurationV2` - these two might be competing for the same cloud configuration as they don't really work together.

Are you able to replace the `s3.BucketLifecycleConfigurationV2` resource with the `lifecycleRules` on the `s3.Bucket` resource https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucket/#lifecyclerules_nodejs for your use case?

If not, could you tell us a bit more about your use case if you can achieve it with the V2 resources instead?

**Comment by matan-orland-lmnd** [comment] 2024-02-19 13:27
@VenelinMartinov Thank you for your response! 

Since we are using this code as part of our infrastructure platform (as a building block for our dev teams) I think it will be difficult to upgrade to newer versions currently. When you write about V2 resources are you talking about `aws.s3.BucketV2`? ([link](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketv2/)). I can check with the team what would be the repercussions of this change.

My usecase is the following - we offer an object storage building block which uses `S3` behind the scenes. We are in the process of moving away from `AWS Backup` to `S3 Replication` for backup (because of money). `AWS Backup` works by selecting resources with certain tags. When I enable `S3 Replication` I would like to remove those tags, but I can't because the lifecycle rules are being deleted.

In the meantime I solved this by simply not changing tags, and adding a global lambda that daily checks the buckets to see if they have replication rules and the backup tags, and if so removes the tags. It's ugly but it works for now. I will check if the `BucketV2` is a viable option for us. I will say that one of the steps I tried was using `s3.Bucket`'s built-in `lifecycleRules` and that didn't solve the issue (I think it was one of the suggestions made by @kpitzen.)

**Comment by VenelinMartinov** [comment] 2024-02-20 09:54
Thanks for the explanation @matan-orland-lmnd! I'm glad you've found a workaround to the issue!

>s3.Bucket's built-in lifecycleRules and that didn't solve the issue

Does that mean that it doesn't cover your use case or that you are still seeing the diff after the initial update? Note that when testing this you need to remove the `s3.BucketLifecycleConfigurationV2` resource as it will compete for the same configuration.

>When you write about V2 resources are you talking about aws.s3.BucketV2

Exactly that, yeah. Note that this represents the same S3 Buckets in AWS but is exposed via a different interface in the provider API.


I'm going to close the issue as the behaviour is not something we can address due to the mixing of V1 and V2 configuration. Please let us know if you still need help with this.

**Comment by VenelinMartinov** [comment] 2024-02-20 09:55
I'm going to close the issue as the behaviour is not something we can address due to the mixing of V1 and V2 configuration. Please let us know if you still need help with this.

**Closed by VenelinMartinov** 2024-02-20 09:55 UTC
Labels: kind/bug, area/providers, resolution/wont-fix

**Comment by matan-orland-lmnd** [comment] 2024-06-13 21:42
Update: After upgrading to `BucketV2` I can confirm this issue was resolved. Thanks everyone for the assistance!
