### ISSUE TITLE
Updating the tags of an RDS instance is causing a replace to happen (which then fails).

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-aws#574] opened 2019-05-23 21:22 UTC
Reported by @jasonhedges.  They have an RDS db instance.  During a minor change to their program (to just add tags to the instance) they encountered the following behavior.

> Pulumi stated (even during preview) that there would just be a change to `tags`.  However, at the same time, it specified that a `replace` would happen (which shouldnt' happen just with a change to `tags`).  

Investigating this, it was determined that pulumi wants to do a replace here because the `storageEncrypted` value changed on the instance.

When manual refreshes were performed, pulumi completed successfully, with no change to the `storageEncrypted` value.

There are several issues here:

1. that the UI doesn't properly state the reason we think a replace is necessary.  that's not great, but is more misleading, than being critically broken.
2. that update/refresh are somehow not consistent here in terms of how they're reading in this value.  'refresh' thinks all the values are fine, and doesn't want to change anything.  But update thinks this value is changing.
3. that update thinks this value is changing at all (even though only tags changed).

Overall, this brokenness has led to Jason being unable to change his resource in a simple way that should be totally supported.  From quickly skimming logs, i couldn't see anything standing out that obviously showed what the issue is.  Ihave a feeling someone will have to spelunk into the provider side of things to see why these values are coming back in this manner and causing the problems.

**Comment by CyrusNajmabadi** [comment] 2019-05-23 21:22
Tagging @ellismg @pgavlin .  The UI issue aside, this seems aws provider related.

**Comment by lukehoban** [comment] 2019-05-23 23:42
I'm guessing that (1) is https://github.com/pulumi/pulumi/issues/2453.

**Comment by pgavlin** [comment] 2019-05-24 00:01
> I'm guessing that (1) is pulumi/pulumi#2453.

That was my guess as well.

**Comment by lukehoban** [comment] 2019-05-24 00:29
And (3) appears to be the same issue we've seen many times with Terraform providers where they set a property inside `Read` but without it being marked `Computed`.  This leads to these unexpected replacements in both Pulumi and Terraform.

In this case:

https://github.com/terraform-providers/terraform-provider-aws/blob/ba65a491cf896fb962e8e82b71cbd1a9e5e0ec4c/aws/resource_aws_db_instance.go#L90-L95
```go
			"storage_encrypted": {
				Type:     schema.TypeBool,
				Optional: true,
				ForceNew: true,
			},

```

https://github.com/terraform-providers/terraform-provider-aws/blob/ba65a491cf896fb962e8e82b71cbd1a9e5e0ec4c/aws/resource_aws_db_instance.go#L1253
```go
d.Set("storage_encrypted", v.StorageEncrypted)
```

**Comment by stack72** [comment] 2019-05-24 14:42
@lukehoban do we want to update our own fork here and then send it back upstread?

**Comment by lukehoban** [comment] 2019-05-24 17:29
> They have an RDS db instance. During a minor change to their program (to just add tags to the instance) they encountered the following behavior.

I would love to have a repro for this.

I tried starting with this:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const defaultInstance = new aws.rds.Instance("default", {
    allocatedStorage: 20,
    engine: "mysql",
    engineVersion: "5.7",
    instanceClass: "db.t2.micro",
    name: "mydb",
    parameterGroupName: "default.mysql5.7",
    password: "foobarbaz",
    storageType: "gp2",
    username: "foo",
    // tags: {
    //     Name: "something",
    // }
});
```

And then doing `pulumi up`, `pulumi refresh`, uncomment the tags, `pulumi up`.  At no stage did I see a replacement.

**Comment by lukehoban** [comment] 2019-05-24 17:50
> @lukehoban do we want to update our own fork here and then send it back upstream?

Possibly - though I'd love to be able to reproduce to make sure what I noted above is correct.  (And to add tests to the upstream Terraform provider as part of fixing this).

**Comment by stack72** [comment] 2019-05-27 12:17
Hi @lukehoban 

Ok, IMO there is no error here. I started with the same config as above:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const defaultInstance = new aws.rds.Instance("default", {
    allocatedStorage: 20,
    engine: "mysql",
    engineVersion: "5.7",
    instanceClass: "db.t2.micro",
    name: "mydb",
    parameterGroupName: "default.mysql5.7",
    password: "foobarbaz",
    storageType: "gp2",
    username: "foo",
    // tags: {
    //     Name: "something",
    // }
});
```

Then I was able to run `pulumi up`

```
▶ envchain pulumi-aws pulumi up
Previewing update (dev):

     Type                 Name            Plan
 +   pulumi:pulumi:Stack  aws-gh-574-dev  create
 +   └─ aws:rds:Instance  default         create

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev):

     Type                 Name            Status
 +   pulumi:pulumi:Stack  aws-gh-574-dev  created
 +   └─ aws:rds:Instance  default         created

Resources:
    + 2 created

Duration: 9m14s

Permalink: https://app.pulumi.com/stack72/aws-gh-574/dev/updates/1
```

I then changed some tags in the AWS console and ran `pulumi refresh`:

```
▶ envchain pulumi-aws pulumi refresh
Previewing refresh (dev):

     Type                 Name            Plan       Info
     pulumi:pulumi:Stack  aws-gh-574-dev
 ~   └─ aws:rds:Instance  default         update     [diff: ~tags]

Resources:
    ~ 1 to update
    1 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. yes
Refreshing (dev):

     Type                 Name            Status      Info
     pulumi:pulumi:Stack  aws-gh-574-dev
 ~   └─ aws:rds:Instance  default         updated     [diff: ~tags]

Resources:
    ~ 1 updated
    1 unchanged

Duration: 4s

Permalink: https://app.pulumi.com/stack72/aws-gh-574/dev/updates/2
```

I then changed the config for the database to be completely new tags - from those in the console AND in the current code and ran `pulumi up`:

```
▶ envchain pulumi-aws pulumi up
Previewing update (dev):

     Type                 Name            Plan       Info
     pulumi:pulumi:Stack  aws-gh-574-dev
 ~   └─ aws:rds:Instance  default         update     [diff: ~tags]

Resources:
    ~ 1 to update
    1 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                 Name            Status      Info
     pulumi:pulumi:Stack  aws-gh-574-dev
 ~   └─ aws:rds:Instance  default         updated     [diff: ~tags]

Resources:
    ~ 1 updated
    1 unchanged

Duration: 7s

Permalink: https://app.pulumi.com/stack72/aws-gh-574/dev/updates/3
```

There is absolutely no operation regarding tags that causes a database instance to be recreated. IMO, the issue that was posted was not related to tags.

**Comment by stack72** [comment] 2019-06-11 14:18
ok @lukehoban, I am going to close this out - we can't actually reproduce this with respect to tags changing - this means that a different part of their application stack changed and pulumi was reacting to this

If you have any objections to this being closed - then let me know and we can definitely discuss this further

**Comment by jasonhedges** [comment] 2019-06-11 14:54
The problem I experienced was not on tagging a master RDS instance but on tagging a read replica.

**Comment by stack72** [comment] 2019-06-11 15:29
Hi @jasonhedges

Thank  you for that information - this is new to me I'm afraid so I apologise for not testing that earlier. I will reopen it now

Paul

**Comment by jasonhedges** [comment] 2019-06-11 18:56
This issue was originally raised in a Slack discussion and tags on master instances vs read replicas was really the main point of that discussion. Unfortunately, it looks like that did not make it into this ticket.

We may need another bug ticket for this but there seem to be other buggy things with read replicas as well. For example, after creating a simple instance with a read replica instance, pulumi won't delete the replica without a final snapshot ("DB Instance FinalSnapshotIdentifier is required when a final snapshot is required"). Note, AWS says in the console that "Final Snapshots are not available for Read Replica DB Instances".  Pulumi won't let me add the snapshot to my replica instance with the error "cannot elect new source database for replication".

I manually deleted my replica and ran a pulumi refresh and tried re-creating the replica with a final snapshot identifier. That succeeded but now when I try to remove the replica I get a "FinalDBSnapshotIdentifier can not be specified when deleting a replica instance" error. So you can see, you end up going in circles with these snapshot errors on read replicas.

**Comment by stack72** [comment] 2019-06-11 20:22
ok, I'm really happy with how this has turned out today - I just spoke to @jasonhedges and we have code that we can use to reproduce this! We will get to the bottom of this :) Thanks again for your @jasonhedges

**Comment by jasonhedges** [comment] 2019-06-11 22:05
Sure thing - thank you for taking time for a phone call and thank you all for working so hard to resolve this. It is very much appreciated!

**Comment by stack72** [comment] 2019-06-14 15:02
So I was able to recreate this and find out that the documentation around read_replicas is just terrible, both here, and in terraform. The following config works:

```
const defaultInstance = new aws.rds.Instance("default", {
    allocatedStorage: 20,
    engine: "mysql",
    engineVersion: "5.7",
    instanceClass: "db.t2.micro",
    name: "mydb",
    parameterGroupName: "default.mysql5.7",
    password: "foobarbaz",
    storageType: "gp2",
    username: "foo",
    backupRetentionPeriod: 30,
    backupWindow: "03:00-04:00", // UTC
    skipFinalSnapshot: true,

    tags: {
        Name: "test",
        Foo: "bar",
    }
});

const replicaInstance = new aws.rds.Instance("replica", {
    instanceClass: "db.t2.micro",
    skipFinalSnapshot: true,

    replicateSourceDb: defaultInstance.identifier,

    tags: {
        Name: "test",
        Foo: "bar",
    }
});

export const replicaID= replicaInstance.identifier;
export const mainDB = defaultInstance.identifier;

export const mainEndpoint = defaultInstance.endpoint
```

That creates the correct read replica. It also stops us being able to get spurious diffs. We can improve the documentation in the area greatly to help our users.

**Comment by stack72** [comment] 2019-06-20 10:05
@jasonhedges I believe what we spoke about allows us to mark this as resolved now - I'm confident that you won't face any more issues with this specific resource

Please comment and we can open it back up if so

Paul

**Closed by stack72** 2019-06-20 10:05 UTC
Labels: area/providers, kind/bug
