### ISSUE TITLE
cloudfront.Distribution Error 412

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-aws#308] opened 2018-08-25 02:21 UTC
After successfully creating and updating an `aws.cloudfront.Distribution` resource, I start getting the following errors: 

```
Updating stack 'default'
Performing changes:

     Type                            Name                    Status                  Info
 *   pulumi:pulumi:Stack             pulumi-scratch-default  done
 ~   └─ aws:cloudfront:Distribution  test-dist               **updating failed**     changes: ~ aliases, 1 error

Diagnostics:
  aws:cloudfront:Distribution: test-dist
    error: Plan apply failed: updating urn:pulumi:default::pulumi-scratch::aws:cloudfront/distribution:Distribution::test-dist: error updating CloudFront Distribution (EYJF95DXKETKL): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.
    	status code: 412, request id: 57185929-a80b-11e8-a357-ad021cd7bac9
```

Consequently the distribution resource can then no longer be updated or destroyed. The first few updates go through fine but then it eventually starts erroring. I don't know if it's related to the specific updates I'm doing (changing the `aliases` and `acmCertificateArn` fields repeatedly) or a certain amount of time passing.

**Comment by joeduffy** [comment] 2018-08-25 03:05
I believe this is due to https://github.com/pulumi/pulumi/issues/1449.

In a nutshell, many operations in AWS will silently mutate the CloudFront distribution's ETAG, and then subsequent attempts to update it will fail (due to this "precondition").

`pulumi refresh` will fix this, by re-synchronizing the ETAG in your state file, however @pgavlin just fixed a bug that was blocking its usage for this very scenario. I know we plan to release a new CLI imminently, which is likely required for this -- @pgavlin is this ready to go?

In the meantime, #1449 has some potential manual workarounds that we know will work.

**Comment by protometa** [comment] 2018-08-25 03:47
Is this the error on refresh?

```
Diagnostics:
  global: global
    error: diffing urn:pulumi:default::pulumi-scratch::aws:cloudfront/distribution:Distribution::test-dist: active_trusted_signers: 1 error(s) decoding:

    * '[items]' expected type 'string', got unconvertible type '[]interface {}'
```

**Comment by joeduffy** [comment] 2018-11-26 18:33
@pgavlin has offered to help load balance, as part of M19 shutdown. Thanks Pat!

**Comment by pgavlin** [comment] 2018-11-27 18:36
I have confirmed that `pulumi refresh` is working as expected for CloudFront distributions. I am closing this as a duplicate of https://github.com/pulumi/pulumi/issues/1449.

**Closed by pgavlin** 2018-11-27 18:36 UTC
Labels: customer/feedback
