### ISSUE TITLE
aws.ec2.SpotInstanceRequest ignores launch_template

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aws#1648] opened 2021-10-05 22:27 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have an `aws.ec2.LaunchTemplate` from which I can launch EC2 instances:

```
aws.ec2.Instance("on-demand-instance",
                 launch_template={"id": launch_template})
```

I've been trying and failing to use the same to launch EC2 spot instances. According to the documentation it should be as simple as:

```
aws.ec2.SpotInstanceRequest("on-demand-instance",
                            launch_template={"id": launch_template})
```

Unfortunately this does not work and I get various error messages like:

```
        * Error requesting spot instances: MissingParameter: The request must contain the parameter imageId
        status code: 400, request id: 878ebf1d-3edf-4447-b6fb-3b155116ec37
```
And
```
        * Error requesting spot instances: MissingParameter: The request must contain the parameter instanceType
        status code: 400, request id: 08998f08-0524-4a49-84cf-e45b6baf12e0
```

So it seems like `aws.ec2.SpotInstanceRequest` is completely ignoring `launch_template`, unlike `aws.ec2.Instance`.

**Comment by Sodki** [comment] 2022-01-29 17:58
@stack72 Did you ever manage to replicate this issue with my code examples?

**Comment by mikhailshilkov** [comment] 2023-11-02 09:01
I can reproduce the issue. Something looks odd about this resource setup. The upstream docs have no mention of launch_template at all: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_instance_request

I suspect something is wrong with our use of `IncludeArgumentsFrom: "aws_instance"`: https://github.com/pulumi/pulumi-aws/blob/master/provider/resources.go#L1760C6-L1760C26

Given the note below (from the docs), we may want to deprecate this resource...

> [AWS strongly discourages](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html#which-spot-request-method-to-use) the use of the legacy APIs called by this resource. We recommend using the EC2 Instance resource

**Comment by corymhall** [comment] 2024-09-25 13:00
Since this issue is pretty old and aws has recommended not using this legacy API for several years I am going to close this issue as `won't-fix`. We recommend using the recommended `EC2 Instance` resource instead.

**Closed by corymhall** 2024-09-25 13:00 UTC
Labels: kind/bug, resolution/wont-fix

**Comment by KeitelDOG** [comment] 2025-11-23 16:58
I have the same issue with aws cli not using the launch template data when creating ec2 instances, but not with `pulumi-aws`.

It happens to me with `localstack pro`. When I create the ec2 with `awslocal ec2 run-instances --image-id ami-024f768332f0 (...)`, it works great, launch the instance, excute user data code, etc.

When I create launch template first `awslocal ec2 create-launch-template (...) --launch-template-data '{"ImageId":"ami-024f768332f0", (...)}'` , the launch template is created, I check the version data, it's all there.

But when I create ec2 with the template `awslocal ec2 run-instances --launch-template LaunchTemplateId=lt-e0d36baf5d958914d,Version=1` it throw error: `An error occurred (MissingParameter) when calling the RunInstances operation: The request must contain the parameter ImageId`.

I find this issue here the closest one to what I'm experiencing, like `run-instances` does not use the launch template data at all. Maybe we could link the 2 behaviors to see if the problem is more on AWS side.
