### ISSUE TITLE
Reading certificate output cause python error

### ISSUE THREAD

**Issue by edalongeville** [pulumi/pulumi-aws#1188] opened 2020-10-27 12:07 UTC
Hello,

Attempting to read a acm.Certificate() resource (`certificate.domain_validation_options[0]["resourceRecordName"]`) output using the following versions:
```
pulumi == 2.12.1
pulumi-aws == 3.10.0
```

Will cause the following error at `pulumi up`:
```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-sample-certificate-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/eric/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 327, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 71, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 178, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 164, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/home/eric/git/pulumi_sample_certificate/venv/lib/python3.8/site-packages/pulumi/output.py", line 233, in <lambda>
        return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
    KeyError: 'resourceRecordName'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Steps to reproduce:**

1. Clone https://github.com/edalongeville/pulumi_sample_certificate
2. Create a python venv and pip install `requirements_broken.txt`
3. Run `pulumi up`

**Comment by tusharshahrs** [comment] 2020-10-27 12:54
pulumi 2.12.0 gives the same issue as above.

pulumi up works with `2.11.2` see below
$cat requirements.txt:
```
pulumi == 2.11.2
pulumi-aws == 3.10.0
```

/Users/..shah/Downloads/pulumi_2_11_2/pulumi/pulumi version
`v2.11.2`

```
/Users/tusharshah/Downloads/pulumi_2_11_2/pulumi/pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/shaht/pulumi-sample-certificate/dev/previews/7caa6a69-045b-4196-a113-6c13dbf458a6

     Type                     Name                           Plan
 +   pulumi:pulumi:Stack      pulumi-sample-certificate-dev  create
 +   ├─ pulumi:providers:aws  aws-provider-us-east-1         create
 +   ├─ aws:acm:Certificate   certificate                    create
 +   ├─ aws:route53:Zone      my-zone                        create
 +   └─ aws:route53:Record    record-certificate-validation  create

Resources:
    + 5 to create

Do you want to perform this update? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::pulumi-sample-certificate::pulumi:pulumi:Stack::pulumi-sample-certificate-dev]
    + pulumi:providers:aws: (create)
        [urn=urn:pulumi:dev::pulumi-sample-certificate::pulumi:providers:aws::aws-provider-us-east-1]
        region: "us-east-1"
    + aws:acm/certificate:Certificate: (create)
        [urn=urn:pulumi:dev::pulumi-sample-certificate::aws:acm/certificate:Certificate::certificate]
        [provider=urn:pulumi:dev::pulumi-sample-certificate::pulumi:providers:aws::aws-provider-us-east-1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        domainName             : "mydomain.com"
        subjectAlternativeNames: [
            [0]: "*.mydomain.com"
        ]
        validationMethod       : "DNS"
    + aws:route53/zone:Zone: (create)
        [urn=urn:pulumi:dev::pulumi-sample-certificate::aws:route53/zone:Zone::my-zone]
        [provider=urn:pulumi:dev::pulumi-sample-certificate::pulumi:providers:aws::default_3_10_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        comment     : "Managed by Pulumi"
        forceDestroy: false
        name        : "mydomain.com"
    + aws:route53/record:Record: (create)
        [urn=urn:pulumi:dev::pulumi-sample-certificate::aws:route53/record:Record::record-certificate-validation]
        [provider=urn:pulumi:dev::pulumi-sample-certificate::pulumi:providers:aws::aws-provider-us-east-1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        name      : output<string>
        records   : [
            [0]: output<string>
        ]
        ttl       : 300
        type      : output<string>
        zoneId    : output<string>
```

**Comment by joehillen** [comment] 2020-10-28 22:33
I'm having a similar issue in Typescript.

With this code:

```
    const certificate = new aws.acm.Certificate(
      `${name}-certificate`,
      {
        domainName: args.domainName,
        validationMethod: 'DNS',
      },
      { provider, parent: this },
    );
    certificate.domainValidationOptions.apply(console.log);
    const certificateValidationDomain = new aws.route53.Record(
      `${name}-validation-record`,
      {
        name: certificate.domainValidationOptions[0].resourceRecordName,
        zoneId: args.zone.zoneId,
        type: certificate.domainValidationOptions[0].resourceRecordType,
        records: [certificate.domainValidationOptions[0].resourceRecordValue],
        ttl: 600,
      },
      { parent: this },
    );
```

The result is:
```
Diagnostics:
  pulumi:pulumi:Stack (example-dev):
    [ { domainName: 'example.com' } ]
 
  aws:route53:Record (example-validation-record):
    error: aws:route53/record:Record resource 'example-validation-record' has a problem: Required attribute is not set
    error: aws:route53/record:Record resource 'example-validation-record' has a problem: Required attribute is not set
```

According to the types `resourceRecordName`, `resourceRecordType`, and `resourceRecordValue` should be present but isn't.

**Comment by joehillen** [comment] 2020-10-28 22:42
And as other have stated downgrading pulumi to 2.11.2 solves the issues:

```
curl -sSL https://get.pulumi.com | bash -s -- --version 2.11.2
```

**Comment by leezen** [comment] 2020-10-29 02:12
Thanks for the repro. I was able to reproduce with the steps you outlined above. It seems this is somehow related to the recently released preview functionality. We'll continue to investigate. In the meantime, as mentioned above, downgrading is one path forward. Alternatively, you can also set the environment variable `PULUMI_DISABLE_PROVIDER_PREVIEW=1` (or true) with pulumi CLI `2.12.x` and should be able to proceed.

**Comment by leezen** [comment] 2020-10-29 18:03
Since there seems to be a broader issue with the way provider preview interacts, we'll track progress in the issue in the pulumi/pulumi repo: https://github.com/pulumi/pulumi/issues/5633

**Comment by leezen** [comment] 2020-11-10 03:38
Closing as the tracking issue is now closed as well.

**Closed by leezen** 2020-11-10 03:38 UTC
Labels: priority/P1

**Comment by Sodki** [comment] 2020-11-24 00:27
@leezen The upstream tracking issue is closed, but I'm still getting the error with pPulumi 2.14.0 and pulumi-aws 3.14.0. I've noticed that the tracking issue was related to the Typescript provider, do you know if this has arrived to the Python provider yet?

Thank you for the workaround of setting the environment variable.

**Comment by leezen** [comment] 2020-11-24 00:37
@Sodki Yes, this should be fixed across all languages. Do you mind providing what your `pip list` looks like and what error you're getting? Is it the same error as in the OP?

**Comment by Sodki** [comment] 2020-12-02 17:01
Sorry about the delay in my response. It's the exact same error as the OP. Here's my `pip list`:

```Package           Version
----------------- ---------
Arpeggio          1.9.2
attrs             20.1.0
certifi           2020.6.20
chardet           3.0.4
dill              0.3.2
flake8            3.8.4
grpcio            1.31.0
idna              2.8
mccabe            0.6.1
parver            0.3.0
pip               20.3
pkg-resources     0.0.0
protobuf          3.13.0
pulumi            2.14.0
pulumi-aws        3.17.0
pulumi-kubernetes 2.7.2
pulumi-okta       2.6.2
pulumi-random     2.4.2
pulumi-tls        2.4.2
pycodestyle       2.6.0
pyflakes          2.2.0
PyYAML            5.3.1
requests          2.21.0
semver            2.10.2
setuptools        50.3.2
six               1.15.0
urllib3           1.24.3
wheel             0.36.0```

This only manifests for new resources.

**Comment by leezen** [comment] 2020-12-04 03:54
@Sodki thanks for the update and the details. Based on what you're describing, this sounds like https://github.com/pulumi/pulumi/issues/5864 which also includes a workaround for now.
