### ISSUE TITLE
tagsAll being marked as secret stops use of requireOutputValue in other stacks to access infrastructure objects

### ISSUE THREAD

**Issue by mwalker-g2u** [pulumi/pulumi-aws#3417] opened 2024-02-12 05:11 UTC
### What happened?

A common pattern in my use of pulumi is to put the object referencing a piece of infrastructure into the output, then pick that up using requireOutputValue in another stack in order to be able to use the various attributes.

In #2791 to fix #2778 a change was implemented to make the output of tagsAll as secret, as it was possible a tag was marked as secret but this would not be carried through to the tagsAll output.

I would argue that this change gives a false sense of security and it would be better, if a change is needed to stop this behaviour, to disallow the setting of tags to a value marked as secret. As remarked in #2778:

> The behavior is a bit pedantic since in real world use cases tags are fairly exposed in the cloud, can't think of an easy use case where they should be secret, but it is certainly an odd corner case.

which I would agree with, and for instance in https://docs.aws.amazon.com/secretsmanager/latest/userguide/managing-secrets_tagging.html AWS explicitly say:

> Never store sensitive information for a secret in a tag.

In AWS at least tags are exposed all over the place as read only, including to all sorts of roles like billing that should not have access to secrets.

Is there any appetite for having this change marking tagsAll as secret reverted?
And having values passed into tags that are marked as secret instead causing an error and the tag being unable to be set?

If this change can not be reverted I would appreciate some feedback on best practices for passing information about infrastructure between stacks, as I see it there are a few possible ways:

1. Switch to using requireOutput and wrap everything in an apply
2. Keep each parameter needed to be passed to another stack in its own output
3. Pass an id or ARN that can be used with the normal lookup methods to look up the infrastructure object in the other stack

Is there a recommended best practise from these or something else I haven't thought of?

### Example

A simple contrived example of how I pass an object to another stack using an output.

Certificates Stack:
```
  const websiteAlbCertificate = new aws.acm.Certificate(
    "website-alb",
    {
      domainName: "alb.example.com",
      tags: {project: "website",},
      validationMethod: "DNS",
    },
  );
```

```
return {
  websiteAlbCertificate: websiteAlbCertificate,
};
```

Certificate Validations Stack:
```
const certificatesStack = new pulumi.StackReference("certificates");
const websiteAlbCertificate = await certificatesStack.requireOutputValue("websiteAlbCertificate");
```

### Output of `pulumi about`

on7000nn902:certificates mwalke25$ pulumi about
CLI          
Version      3.105.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.6
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/opt/node@18/bin/node' version='v18.17.1'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-02-13 02:43
Hi @mwalker-g2u. I'm going to close this as a duplicate of https://github.com/pulumi/pulumi-aws/issues/3265. As a workaround for your specific use case, you can un-secret your return value. I'm not an inspired TypeScript developer, but I have tested this and it works:

```ts
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

const b = new aws.s3.BucketV2("bucket");

function sanatize_exports(exports: {[index: string]: pulumi.Resource}): {[index: string]: pulumi.Output<pulumi.Resource>} {
    const result: {[index: string]: pulumi.Output<pulumi.Resource>} = {};
    for (const k in exports) {
        result[k] = pulumi.unsecret(pulumi.output(exports[k]).apply((value) => {
            if ("tagsAll" in value) {
                const tagsAll: any = (value as any)["tagsAll"];
                (value as any)["tagsAll"] = pulumi.unsecret(pulumi.output(tagsAll));
            }
            return value;
        }));
    }
    return result;
}

export const outputs = sanatize_exports({
    bucket: b,
});
```

**Closed by iwahbe** 2024-02-13 02:43 UTC
Labels: kind/bug, resolution/duplicate

**Comment by mwalker-g2u** [comment] 2024-02-13 05:52
Thanks @iwahbe I will try that out and I appreciate you taking the time to provide a workaround, I'm also not an inspired TypeScript developer.

Sorry I missed #3265 and I will add to the discussion there.
