### ISSUE TITLE
undefined: GetCFTypeLoggingConfig

### ISSUE THREAD

**Issue by universam1** [pulumi/pulumi-aws#1489] opened 2021-05-14 09:05 UTC
```
 # github.com/pulumi/pulumi-aws/sdk/v4/go/aws/cloudformation
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/cftype.go:39:16: undefined: CFTypeLoggingConfigPtrOutput
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/cftype.go:110:17: undefined: CFTypeLoggingConfig
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/cftype.go:147:16: undefined: CFTypeLoggingConfigPtrInput
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/cftype.go:176:17: undefined: CFTypeLoggingConfig
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/cftype.go:190:16: undefined: CFTypeLoggingConfigPtrInput
    /home/sam/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.0/go/aws/cloudformation/getCFType.go:76:19: undefined: GetCFTypeLoggingConfig
```
 
**error: an unhandled error occurred: program exited with non-zero exit code: 2**

## Expected behavior
pulumi to compile

## Current behavior
erroring out during `pulumi up`

## Steps to reproduce
`eks.NewCluster(ctx, "eks", &eks.ClusterArgs{
			EnabledClusterLogTypes: pulumi.StringArray{
				pulumi.String("api"),
				pulumi.String("audit"),
				pulumi.String("authenticator"),
			},
}`

## Context (Environment)
Trying to deploy EKS

## Affected feature

From 4.1.0 any release affected including 4.3.1, unable to use Pulumi with AWS

**Comment by justinvp** [comment] 2021-05-17 20:26
Dupe of https://github.com/pulumi/pulumi-aws/issues/1492

**Closed by justinvp** 2021-05-17 20:26 UTC
Labels: resolution/duplicate

**Comment by universam1** [comment] 2021-05-19 08:42
thank you very much @stack72  @justinvp
