### ISSUE TITLE
CLI hangs at sts:GetCallerIdentity when temporary AWS credentials exist but are expired

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi-aws#814] opened 2019-12-03 22:14 UTC
Where there are no AWS access keys in my shell environment, running `pulumi up`  pretty much immediately errors out with `error: unable to discover AWS AccessKeyID and/or SecretAccessKey`. But when AWS access keys exist but had expired, it just hangs (for at least several minutes) at trying `sts:GetCallerIdentity` from what I can tell from the debug output (which I have now lost 😨 ), however without debug on it just looks like it's doing normal planning forever. Ideally it quickly determines the credentials are invalid and informs the user.

Pulumi: v1.6.1
Pulumi AWS: v1.13.0

**Comment by austinbutler** [comment] 2019-12-04 17:44
Let the token expire overnight to get the output:

```
> $ pulumi preview -d
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Previewing update (staging):

     Type                 Name                Plan       Info
 +   pulumi:pulumi:Stack  pulumi-staging  create     17 debugs
     └─ aws:s3:Bucket     newbucket              1 error

System Messages
  ^C received; cancelling. If you would like to terminate immediately, press ^C again.
  ^C received; terminating

Diagnostics:
  aws:s3:Bucket (newbucket):
    error: transport is closing

  pulumi:pulumi:Stack (pulumi-staging):
    debug: Registering resource: t=pulumi:pulumi:Stack, name=pulumi-staging, custom=false
    debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=pulumi-staging
    debug: RegisterResource RPC finished: resource:pulumi-staging[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:staging::pulumi::pulumi:pulumi:Stack::pulumi-staging,,,,
    debug: Running program '/Users/abutler/Documents/pulumi' in pwd '/Users/abutler/Documents/pulumi' w/ args:
    debug: Registering resource: t=aws:s3/bucket:Bucket, name=newbucket, custom=true
    debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:staging::pulumi::pulumi:pulumi:Stack::pulumi-staging
    debug: RegisterResource RPC prepared: t=aws:s3/bucket:Bucket, name=newbucket
    debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:staging::pulumi::pulumi:pulumi:Stack::pulumi-staging; err: null, resp:
    debug: Setting AWS metadata API timeout to 100ms
    debug: Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
    debug: AWS Auth provider used: "EnvProvider"
    debug: No assume_role block read from configuration
    debug: Building AWS auth structure
    debug: Setting AWS metadata API timeout to 100ms
    debug: Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
    debug: AWS Auth provider used: "EnvProvider"
    debug: Trying to get account information via sts:GetCallerIdentity

error: an error occurred while advancing the preview
```

**Comment by pgavlin** [comment] 2019-12-04 23:44
Yikes! Thanks for the report. @stack72 can you take a look?

**Comment by lukehoban** [comment] 2020-01-22 05:29
I just hit something very similar myself.  A stack that I have deployed many time before, I came back to after awhile and I can no longer update it - `pulumi up` hangs at this:

```
I0121 21:15:04.384759   56334 eventsink.go:60] AWS Auth provider used: "SharedCredentialsProvider"
I0121 21:15:04.385134   56334 eventsink.go:60] Attempting to AssumeRole arn:aws:iam::058607598222:role/OrganizationAccountAccessRole (SessionName: "", ExternalId: "", Policy: "")
I0121 21:15:04.972779   56334 eventsink.go:60] Trying to get account information via sts:GetCallerIdentity
```

I am using:

```
const awsProvider = new aws.Provider("testing", {
    region: region,
    assumeRole: {
        roleArn: "arn:aws:iam::058607598222:role/OrganizationAccountAccessRole",
    },
});
```

From outside `pulumi` - the following runs and immediately returns succesfully:

```
aws sts assume-role --role-arn arn:aws:iam::058607598222:role/OrganizationAccountAccessRole --role-session-name something
```

**Comment by borisbsu** [comment] 2020-02-27 12:15
Is there any workaround for this issue?

**Comment by lukehoban** [comment] 2020-03-01 22:00
@borisbsu Do you have details on your repro case for this?  I believe some issues which have symptoms similar to this may actually be unrelated to `sts:GetCallerIdentity` itself.  What is the case where you are seeing an issue?

**Comment by julienvincent** [comment] 2020-03-10 15:19
@borisbsu After playing around a bit the workaround I found was to:

+ downgrade `@pulumi/aws` to `1.21.0`
+ export current stack to file
+ remove all secrets (access key, secret key, token) from aws provider states
+ import updated stack file

This allowed me to continue

**Comment by lukehoban** [comment] 2020-03-11 00:25
Across the notes here, in https://github.com/pulumi/pulumi/issues/3604, and in https://github.com/pulumi/pulumi-aws/issues/873, it appears there are a few related but independent things going on:
- [ ] The upstream Terraform AWS provider fundamentally will hang (or at least retry with exponential backoff for a very long time) when credentials are expired (https://github.com/terraform-providers/terraform-provider-aws/issues/1351)
- [ ] The changes in https://github.com/pulumi/pulumi/pull/4004 led to a regression where old provider configuration for 1st class provider would be used during preview instead of new configuration.  This can make the case above worse, as old expired credentials get used when they shouldn't.
- [ ] The changes in https://github.com/pulumi/pulumi-aws/pull/874 led to some additional environment variables being written into the statefile that shouldn't have been - accentuating the above.

Together, these three compound.  We can fix the latter two, but the core initial issue is an upstream bug that appears to be considered "by design".  We will need to look into whether we can/should change the default behaviour for that in the Pulumi provider.

**Comment by lukehoban** [comment] 2020-03-12 03:44
The second two issues above have been fixed, which will reduce the likelihood of hitting this for unexpected reasons.

The core behaviour of hanging on expired credentials is due to upstream provider behavior - as tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/1351, https://github.com/terraform-providers/terraform-provider-aws/issues/4502, https://github.com/terraform-providers/terraform-provider-aws/issues/9601 and https://github.com/terraform-providers/terraform-provider-aws/issues/12023.

We are considering on diverging on some defaults which may ultimately impact this in https://github.com/pulumi/pulumi-aws/issues/873.  I'll close this issue out for now, and further improvements will be tracked in upstream provider issues and https://github.com/pulumi/pulumi-aws/issues/873.

**Comment by lukehoban** [comment] 2021-04-15 20:58
Re-opening as this is still an issue that Pulumi users hit somewhat regularly, and we will likely want to find a way to workaround the upstream issues here.

**Comment by farvour** [comment] 2021-05-26 19:17
FWIW, we are using the [aws-okta-processor](https://github.com/godaddy/aws-okta-processor) tool and when cached credentials aren't available this issue occurs. The underlying issue, so it seems if another process, such as through credential_process is "awaiting input", Pulumi will simply hang instead of pass the STDIN/prompt to the user. In our case, it was sitting and waiting for the user's Okta credentials to have the aws credentials move forward with the profile.

It might be worth having Pulumi also check during run to make sure there isn't any input expectation on the terminal when calling out 

It's probably worth calling this special use-case out in its own issue but I'll let guys decide. Ultimately pulumi should just not hang forever on this provider. I'd even rather have the tool spit back an error right if terminal input is blocking the finalization of credential retrieval. Ideally, it would just pass the input through to the interactive terminal and I could enter my password for Okta and move on. For now, I have to "prime" the profile being used by the provider, using say, `aws --profile pulumi-test sts get-caller-identity`

**Comment by lukehoban** [comment] 2023-06-24 15:11
This is fixed now, via https://github.com/hashicorp/aws-sdk-go-base/pull/362.

**Closed by lukehoban** 2023-06-24 15:11 UTC
Labels: kind/bug, resolution/fixed
