### ISSUE TITLE
Cannot run pulumi up with resource AWS

### ISSUE THREAD

**Issue by vanbasten17** [pulumi/pulumi-aws#1501] opened 2021-05-19 15:14 UTC
## Expected behavior
* Should run `pulumi up` as expected.

## Current behavior
After doing a clean install of pulumi with brew (MacOS 10.15.7) and logged in (as `pulumi login --local`) cannot deploy my stack of the project anymore.
Also tried after a clean install of: https://github.com/pulumi/examples/tree/master/aws-ts-static-website with same results.

## Steps to reproduce

1. Clone https://github.com/pulumi/examples/tree/master/aws-ts-static-website
2. `npm install`
3. `pulumi login --local`
4. Config the stack with `config set` command:
```
encryptionsalt: XXX
config:
  aws:profile: myprofile-super-admin
  static-website:pathToWebsiteContents: www
  static-website:targetDomain: test.mydomain.com
```
5. `pulumi up`: which produces the following output:

```
Previewing update (dev):
     Type                 Name                       Plan       Info
 +   pulumi:pulumi:Stack  aws-ts-static-website-dev  create...          /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0. +   pulumi:pulumi:Stack  aws-ts-static-website-dev  create...          /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:4173 +0x52e1     Type                     Name                       Plan       Info +   pulumi:pulumi:Stack      aws-ts-static-website-dev  create...      /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/m +   pulumi:pulumi:Stack      aws-ts-static-website-dev  create     9 messages
     └─ pulumi:providers:aws  default_4_5_0                         1 error
 
Diagnostics:
  pulumi:providers:aws (default_4_5_0):
    error: could not read plugin [/Users/me/.pulumi/plugins/resource-aws-v4.5.0/pulumi-resource-aws] stdout: EOF
 
  pulumi:pulumi:Stack (aws-ts-static-website-dev):
    panic: strconv.ParseUint: parsing "": invalid syntax
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0xc0013bf5b0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0.0/pkg/tfbridge/info.go:730 +0x1dc
    github.com/pulumi/pulumi-aws/provider/v4.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:4173 +0x52e1b
    main.main()
        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:26 +0x37
 
    Syncing contents from local disk at /Users/me/Desktop/examples/aws-ts-static-website/www
```

I have the project up and running just yesterday, and I have tried to uninstall and reinstall pulumi binary with no results. Any clue on this?

**Comment by vanbasten17** [comment] 2021-05-19 15:27
Hi @pierskarsenbarg, thanks for the quick response!
I will give a try whenever I can, let me know if I can help trying the new version :)

**Comment by dferretti** [comment] 2021-05-19 15:31
I'm hitting the same issue - I've bumped my stack back down to 4.4.1 for now, but I'm still having trouble with `pulumi up`. It looks like 4.5.0 got baked somehow into the stack state, so when I try `up` with 4.4.1 in use it still tries to install the 4.5.0 and 4.4.1 plugins, and the 4.5.0 fails. Is there a good way to get around this?

**Comment by pierskarsenbarg** [comment] 2021-05-19 16:28
Hi @dferretti and @vanbasten17 the v4.5.1 package is out now so that should work. I'll leave this issue open so if you can let me know by 👍  this comment that you're good now and I'll close it

**Comment by dferretti** [comment] 2021-05-19 16:44
Well I am not sure if this is a great idea, but it got me through heh - since I wasn't using any of the new features in 4.5.0 yet I just copied the 4.4.1 binaries into the 4.5.0 location. I'm doing this in a clean docker container each time and manually installing plugins (I think I have to because I am using dotnet prebuilt binary option). So this worked enough for me to get by:
```
pulumi plugin install resource aws v4.4.1 --exact
cp -r ~/.pulumi/plugins/resource-aws-v4.4.1 ~/.pulumi/plugins/resource-aws-v4.5.0
cp ~/.pulumi/plugins/resource-aws-v4.4.1.lock ~/.pulumi/plugins/resource-aws-v4.5.0.lock
```

I got some warnings about expected version mismatch but it at least let me continue working. I left that in there until v4.5.1 just got released and now I'm back to normal

**Comment by pierskarsenbarg** [comment] 2021-05-19 16:46
I think we refer to it as a "dirty" version if you have mis-matches. And yes, whilst I wouldn't advise doing this in your production pipeline, if it gets you moving then that's fine.

**Comment by dferretti** [comment] 2021-05-19 16:49
Ah whoops didn't see you other message til just now. Yeah all good here - thanks!

**Comment by pierskarsenbarg** [comment] 2021-05-19 20:56
I've also managed to reproduce this so I'm going to close this ticket

**Closed by pierskarsenbarg** 2021-05-19 20:56 UTC
Labels: area/providers, resolution/fixed

**Comment by vanbasten17** [comment] 2021-05-20 08:15
hi @pierskarsenbarg , I did manage to make it work with @dferretti suggestion of copy-paste the plugin from v.4.5.1 to v.4.50. I tried to install pulumi again and it keeps downloading the v.4.5.0 version. 
Is there any cache or similar which I can delete to avoid pointing to this version? Or is there a way to specify it directly in the config like..?
```
cloud:provider:
      description: Cloud Provider
      default: aws-v4.5.1
```

**Comment by pierskarsenbarg** [comment] 2021-05-20 08:27
@vanbasten17 what language are you using?

**Comment by vanbasten17** [comment] 2021-05-20 10:31
typescript

**Comment by pierskarsenbarg** [comment] 2021-05-20 14:31
Ok, so this is controlled through the dependencies in the `package.json` file:

```json
"dependencies": {
        "@pulumi/aws": "^4.5.1",
        "@pulumi/awsx": "^0.30.0",
        "@pulumi/pulumi": "^3.0.0"
    }```

In the JSON above, I'm targeting v4.5.1 of the AWS provider.
