### ISSUE TITLE
Fix performance baseline breach

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-aws#2799] opened 2023-08-25 14:44 UTC
<img width="805" alt="Screen Shot 2023-08-25 at 7 40 07 AM" src="https://github.com/pulumi/pulumi/assets/710598/6fbbe403-5122-44d1-a9b0-cfc64ad6d612">

With https://github.com/pulumi/pulumi/issues/13654, I bumped the `aws-ts-s3-folder` threshold from 4500 to 4800 after local investigation.

Now we're getting alerted that `aws-js-s3-folder`, `aws-py-s3-folder`, and `aws-ts-s3-folder` are over their thresholds for this test run. Needs investigation. Was it just a blip or consistent issue?

**Comment by mjeffryes** [comment] 2023-09-14 23:57
I've collected some trace data over several runs with a few different variations: [pulumi-aws/issues/2799 latency investigation](https://docs.google.com/spreadsheets/d/1po5TTyMO7XsGvJvC7OcXitWp-_MNYww6VpVzbSaIwh8/edit#gid=454194680) 

A few observations:
1) The latency increase is present in an empty update.
2) There is a smaller latency increase for both preview-only and update-no-preview commands
3) The latency increase is tied to the plugin version used and is not affected by the sdk version
4) The latency delta between versions does not seem to be influenced by how many resources you are creating
4) Most confounding to me so far is that the traces *don't* show a significant increase in latency for Check or Diff (or any other provider method), but the parent span(s) for RegisterResource do show the latency.

**Comment by mjeffryes** [comment] 2023-09-15 17:20
I think I have a lead on where the slowness may be coming from: 
There's a significant change in the spacing in /pulumirpc.ResourceMonitor/RegisterResource(2.32s) on either side of the /pulumirpc.ResourceProvider/CheckConfig trace for v6:

![v6](https://github.com/pulumi/pulumi-aws/assets/1189194/60c37d61-42c0-4dc8-b5eb-2fc4bad4b147)
![v5](https://github.com/pulumi/pulumi-aws/assets/1189194/b5085801-6df2-434f-881c-c4b755139131)

There's no subspan covering this time, but I suspect that it is where we are waiting on the provider plugin to start. Playing around with starting each plugin in my terminal, it does feel like there's a larger delay before printing the port number for v6. The difference is subtle (the traces indicate a difference of ~750ms), but since we restart the plugin multiple times during an update, it's probably enough to account for the ~3s increase in the overall update time.

 (We should probably add a tracing span to cover provider start times; if my hunch is correct, that trace could have saved me several hours of experimenting with different profiling runs.)

**Comment by mjeffryes** [comment] 2023-09-15 23:37
Further testing found that the v6 aws plugin does take ~500ms longer just to get printing the version string. The flame graphs shows a significant amount of time spent in `tfbridge.NewProviderMetadata` and `tfbridge.MustApplyAutoAliases`:

![Flamegraph](https://github.com/pulumi/pulumi-aws/assets/1189194/69cd1c52-4246-424d-a506-7509e5d1333d)

@t0yv0 confirmed that these are new to v6 as v6 is the first version of the aws provider that uses the tfbridge tools for bridging Provider Framework based tf providers. (v5 contained a number of patches to downgrade resources that the upstream had moved to PF back to tf SDKv2)

I think that gives us the answer to our initial question of what is causing the slow-down, but there are a number of different items to follow up on to try to improve the situation:

A large portion of the extra time is spend unmarshalling the large (45MB) `bridge-metadata.json` file:
- [ ] The `renames` key of the metadata is not required at runtime; stripping this from the embedded meta data should reduce the amount of data we unmarshall by 1/3
- [ ] Using a more efficient storage format for bridge-metadata.json could cut most of the overhead of loading this file

We could also:
- [ ] Take a lazy approach to loading bridge metadata so that we don't eat the whole cost of loading the file on init. To avoid simply shifting the cost around, we might need a storage format that facilitates random access.

Regardless of the approach we take to reducing init time; we should also:
- [ ] Fix tracing so that we get spans from the provider plugin and spans for when the engine is waiting on plugin init.
- [ ] Understand why the engine appears to be restarting the plugin between `CheckConfig` and `Configure`

**Comment by mikhailshilkov** [comment] 2023-09-18 12:01
It sounds like the source of impact is in our TFPF implementation, which is "expected" in some sense.

@mjeffryes How does a 500ms delay in plugin loading become a 3-second jump on all the charts in the issue description? Are we loading the plugin multiple times.

45 MB sounds like a lot! I think that's comparable to metadata in Azure Native, which is an entirely different thing, but that provider has so much more resources and resource properties... Do we see ways to reduce that? For instance, I see things like `RuleGroupRuleStatementAndStatementStatementNotStatementStatementRegexPatternSetReferenceStatementFieldToMatchHeader` in it. Does it mean our WafV2 rewrites aren't working for metadata?

What is your recommendation to proceed? Is there a low-hanging fruit, or do we need to park it until the next iteration? Is it still a P1?

Could you pleas open issue for the next steps?

**Comment by t0yv0** [comment] 2023-09-18 13:06
Glad you could take a look here, Wafv2 rewrites not applied is a good catch! I think Matthew's list above is our low hanging fruit (the first two items). Rid of renames and try a faster format or else even just a faster deserializer like drop in https://github.com/json-iterator/go that we use in p/p

**Comment by mikhailshilkov** [comment] 2023-09-18 13:45
Referencing https://github.com/pulumi/pulumi-azure-native/pull/1689 here as some related prior art. @mjeffryes @t0yv0 maybe we can reuse some of those ideas.

**Comment by t0yv0** [comment] 2023-09-18 13:54
@iwahbe 

At a low level, this is likely some ordering issue between the schema editing hook and the aliasing machinery. If Wafv2 stuff is showing up in renames that's going to be gone quite easily but if it's also showing up in aliasing data we need to figure out the aliasing interaction with the schema rewriting.

**Comment by mjeffryes** [comment] 2023-09-18 22:11
> @mjeffryes How does a 500ms delay in plugin loading become a 3-second jump on all the charts in the issue description? Are we loading the plugin multiple times.

Yes, apparently we are. It appears at a minimum, we are loading 4 times in a vanilla `pulumi up` before `CheckConfig` and `Configure` during preview, and then in both those places again for actual update.

**Comment by mjeffryes** [comment] 2023-09-18 23:16
>What is your recommendation to proceed? Is there a low-hanging fruit, or do we need to park it until the next iteration? Is it still a P1?

I think we can get some savings just by replacing the JSON library and trying to trim the size of the metadata a bit (Tickets filed) so we should probably does that right away. I'm pretty sure that won't get us entirely back to below the target latency, but maybe close enough to decide it's no longer P1? 

If we can avoid paying the startup cost 4 times, that would also save a ton, but I don't know if that's an easy win or not.

**Comment by EvanBoyle** [comment] 2023-09-18 23:23
Is this isolated to AWS or do all providers on the new PF take a similar hit proportional to provider size?

We need to take performance regressions seriously. The goal should not be removing the P1 label but making sure that our users have a great experience.

**Comment by mjeffryes** [comment] 2023-09-18 23:27
All providers using PF will take a hit proportional to provider size. AWS is just 1) big enough that the impact is noticeable and 2) used in the benchmark alerts.

**Comment by mjeffryes** [comment] 2023-09-18 23:41
WRT giving our customers a good experience: I don't know how the existing targets were decided on, but the existing 4.8s threshold for an empty update is already high enough that it's well past the threshold for breaking flow (https://www.nngroup.com/articles/response-times-3-important-limits/).

If we can easily get back down from 7.5s to 5s we absolutely should, but I think we can be pragmatic about how much effort we're willing to spend for each gain. 

It would probably make a nice impact on user perception if we could get an empty update down under 1s; but a real performance push would benefit from wider scope than the context of this one regression.

**Comment by EvanBoyle** [comment] 2023-09-19 00:42
I agree we have a ways to go before things are truly great here.

Rule number one when you're in a hole is stop digging. Either we can care about and respond to the tests and the thresholds we have set, or we should turn them off.

**Comment by t0yv0** [comment] 2023-09-19 02:33
If this helps, the process of setting thresholds involved taking a time-smoothed averages and adding 2 stddev to them.

**Comment by t0yv0** [comment] 2023-09-19 14:24
Yes https://github.com/pulumi/pulumi/issues/13987 Matthew did just that. I can confirm it's a regression from 2x to 4x somewhere per comment on 13987. Presumably loading the plugin 2x is done to have it once for preview and once for up.

**Comment by blampe** [comment] 2023-09-19 23:15
Adding another alternative to https://github.com/pulumi/pulumi-aws/issues/2799#issuecomment-1722028503 -- can we move this parsing to compile-time instead of runtime? This would be most helpful if most of our time is spent in the initial load.

Very roughly:
* Expose an entry point into `tfbridge` that takes an already-parsed `MetadataInfo` instead of `[]byte`.
* Add a `//go:generate` step that reads `bridge-metadata.json` and outputs a `.go` file containing a `MetadataInfo` (AFAICT this is just a `map[string]json.RawMessage`, so this should be simple).
* Provide the generated metadata to the new entry point.

**Comment by t0yv0** [comment] 2023-09-20 01:54
https://github.com/pulumi/pulumi-aws/pull/2819 some more numbers

**Comment by mjeffryes** [comment] 2023-09-22 00:17
@t0yv0 Shipped a change to use jsoniter for the metadata which is a meaningful improvement (https://github.com/pulumi/pulumi-terraform-bridge/pull/1385). I did some more digging today and the largest source of the remaining latency in AWS provider init is now `MustApplyAutoAliases`; a lot of the time spent there comes from the fact that it builds and serializes new alias metadata at the same time as it applies the old ones, but this new metadata construction is only needed when doing tfgen, it's all wasted effort when running an update with a published provider. There doesn't look to be a trivial way to separate the two pieces, but I can work with @iwahbe to try to come up with a way to disentangle.

**Comment by mikhailshilkov** [comment] 2023-09-22 06:41
Thank you for the investigation and shipping the initial fix. I removed P1 as we discussed, but let's make sure we have follow-up issues assigned to M95 to continue tackling this.

**Comment by mjeffryes** [comment] 2023-09-29 16:53
Closing this as our investigation is complete; planning to schedule work on more of the follow up tickets in M95

**Comment by EvanBoyle** [comment] 2023-09-29 20:07
We are not done here until the perf benchmarks are passing again. I've renamed the issue to reflect that and am adding back the P1 label.

**Comment by mikhailshilkov** [comment] 2023-10-02 14:35
Next steps:

- https://github.com/pulumi/pulumi/issues/13987
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1410
- https://github.com/pulumi/pulumi/issues/13986
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1376

**Comment by justinvp** [comment] 2023-10-17 21:05
We temporarily adjusted the alerting baselines until this issue has been resolved.

```
'pulumi-update-empty', 'aws-py-s3-folder', 4800 => 5300
'pulumi-update-empty', 'aws-js-s3-folder', 4500 => 5000
'pulumi-update-empty', 'aws-ts-s3-folder', 4800 => 5300
```

Part of addressing this issue is reverting these back to the previous values.

**Comment by blampe** [comment] 2023-11-08 19:43
@mjeffryes @t0yv0 I spent some time hacking on a prototype for https://github.com/pulumi/pulumi-aws/issues/2799#issuecomment-1726668077 and wanted to share some findings. 

First, to recap, I was curious to see if there's any benefit to moving some of our runtime deserialization down to the build/compile step. The schema and metadata we're embedding into the binary don't change, so (in theory) we should be able to build the result of our computation directly into the binary instead of re-computing it at runtime.

To set the baseline, benchmarking `Provider()` (with `isTfGen` `true`/`false`) on master gave me:
```
BenchmarkProviderGen-10    	       5	 228882600 ns/op	423606320 B/op	 2848954 allocs/op
BenchmarkProviderNoGen-10    	       5	 203570350 ns/op	347397752 B/op	 2308434 allocs/op
```

My first experiment was to slightly simplify but not eliminate the serialization altogether. In particular I noticed we only have 3 top-level keys. Instead of embedding the entire `bridge-metadata.json` struct we can generate a `hack.go` file which pulls out those fields, while still keeping the raw JSON around.
```go
var Data := tfbridge.Data{
    M: map[string]json.RawMessage{
        "auto-aliasing": json.RawMessage([]byte("{...}")), // taken from bridge-metadata.json
        "mux": json.RawMessage([]byte("{...}")),
        "renamed": json.RawMessage([]byte("{...}")),
    },
}
```
Initializing the provider with this eliminates the initial deserialization of the ~40MB blob, while subsequent operations still need to deserialize their smaller respective blobs. This is a relatively small/non-invasive change and cuts new provider time in ~half:
```
BenchmarkProviderGen-10    	       9	 113264319 ns/op	303111697 B/op	 1918905 allocs/op
BenchmarkProviderNoGen-10    	      10	 102601083 ns/op	277265940 B/op	 1615543 allocs/op
```

The next question was whether we could eliminate the deserialization altogether. The structs involved are large enough that we bump into https://github.com/golang/go/issues/33437 but after some wrestling with the compiler it is possible to embed everything natively. (That is, deserialize all of the metadata, run `MustApplyAutoAliases`, and persist the result in code.)

The result is >200k lines of Go (~50MB) which takes several minutes to compile. Fortunately we can use build tags in a way that lets us continue to toggle between the embed approach and this one (otherwise it would be a nightmare to develop against!). This came in at about ~1/4 of the baseline:

```
BenchmarkProviderGen-10    	      20	  51311821 ns/op	156296561 B/op	  883827 allocs/op
BenchmarkProviderNoGen-10    	      20	  52889356 ns/op	156296712 B/op	  883832 allocs/op
```

From here the bottleneck then becomes `NewUpstreamProvider`, which seems good? I'm not sure if we could do a similar trick with that one.

I have literally zero context on providers beyond the hacking I've done here, but I can push these branches if they would be useful!

**Comment by mjeffryes** [comment] 2023-11-08 22:16
@blampe Those are some pretty nice results! It's a bit strange that you get the roughly the same for Gen vs NoGen in all runs. I suspect it might lying and always running in one mode or the other. But I think we'd definitely be interested in seeing your branch and trying to lock in those wins.

**Comment by blampe** [comment] 2023-11-13 19:18
> It's a bit strange that you get the roughly the same for Gen vs NoGen in all runs. I suspect it might lying and always running in one mode or the other.

For sure, I could have also (very likely) borked something while I was hacking!

I've pushed branches [here](https://github.com/pulumi/pulumi-aws/tree/bryce/perf) and [here](https://github.com/pulumi/pulumi-terraform-bridge/tree/bryce/perf).

The "baseline codegen" commit is the first improvement (skipping the initial deserialization), and HEAD is the second (much crazier) codegen everything approach.

Run `go run cmd/codegen/main.go` to generate the `hack.go` file. To build the full codegen approach you'll need to add a build tag `go build -tags hack ./...` -- that one took upwards of 10 minutes for me locally.

**Comment by mjeffryes** [comment] 2023-11-30 18:02
With https://github.com/pulumi/pulumi-terraform-bridge/pull/1524 we are now roughly back in line with the v5 performance [Metabase](https://metabase.corp.pulumi.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3RcblxuYmVuY2htYXJrX3JlcG8sXG5jYXN0KGJlbmNobWFya19zdGFydCBhcyBkYXRlKSBhcyBiZW5jaG1hcmtfZGF0ZSxcbmJlbmNobWFya19uYW1lLFxuYmVuY2htYXJrX3BoYXNlLFxubWF4KHB1bHVtaV92ZXJzaW9uKSxcbmF2Zyh0aW1lX3RvdGFsX21zKSBhcyB0aW1lX3RvdGFsX21zXG5cbmZyb21cblxucHVsdW1pX2NsaV9wZXJmb3JtYW5jZV9tZXRyaWNzLnBlcmZfbWV0cmljc1xuXG53aGVyZVxuXG5iZW5jaG1hcmtfc3RhcnQgaXMgbm90IG51bGxcbmFuZCBwdWx1bWlfcHJvY2VzcyA9ICdwdWx1bWknXG5hbmQgYmVuY2htYXJrX3JlcG8gPSAncHVsdW1pL2V4YW1wbGVzJ1xuYW5kIGJlbmNobWFya19waGFzZSA9ICdwdWx1bWktdXBkYXRlLWVtcHR5J1xuYW5kIGJlbmNobWFya19uYW1lID0gJ2F3cy10cy1zMy1mb2xkZXInXG5hbmQgYmVuY2htYXJrX2RhdGUgPj0gIGN1cnJlbnRfZGF0ZSAtIGludGVydmFsICcxMjAgZGF5J1xuXG5ncm91cCBieSAxLCAyLCAzLCA0XG5vcmRlciBieSAxLCAyLCAzLCA0O1xuXG4iLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6ImxpbmUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiYmVuY2htYXJrX2RhdGUiXSwic2VyaWVzX3NldHRpbmdzIjp7InRpbWVfdG90YWxfbXMiOnsiY29sb3IiOiIjODhCRjREIn19LCJncmFwaC5zaG93X2dvYWwiOnRydWUsImdyYXBoLmdvYWxfbGFiZWwiOiJkbyBub3QgYnJlYWNoIiwiZ3JhcGguZ29hbF92YWx1ZSI6NTgwMCwidGFibGUucGl2b3RfY29sdW1uIjoiYmVuY2htYXJrX3JlcG8iLCJ0YWJsZS5jZWxsX2NvbHVtbiI6InRpbWVfdG90YWxfbXMiLCJncmFwaC5tZXRyaWNzIjpbInRpbWVfdG90YWxfbXMiXX0sIm9yaWdpbmFsX2NhcmRfaWQiOjExMzh9)

**Comment by t0yv0** [comment] 2023-11-30 19:52
By all means, let's do that so we can close.

I wasn't aware we've improved here so I was doing some work on this in the iteration.

- https://github.com/pulumi/pulumi-aws/pull/3070
- https://github.com/pulumi/pulumi-terraform-bridge/pull/1544
- https://github.com/pulumi/pulumi-aws/issues/3071

The changes in 1544 are a little invasive and I'm still verifying if they're safe. 

BenchmarkRuntimeProvider is down to 50-60ms.

The runtime metadata is much smaller.

```
du -sh provider/cmd/pulumi-resource-aws/runtime-bridge-metadata.json                                                                                       ~/code/pulumi-aws
 88K    provider/cmd/pulumi-resource-aws/runtime-bridge-metadata.json
```

AutoAliasing is not a major contributor in the profile anymore.

**Comment by mjeffryes** [comment] 2023-11-30 23:44
Lowered the thresholds that we raised while investigating this issue:
```
'pulumi-update-empty', 'aws-py-s3-folder', 5800 -> 4800
'pulumi-update-empty', 'aws-js-s3-folder', 5800 -> 4800
'pulumi-update-empty', 'aws-ts-s3-folder', 5800 -> 4800
```

**Closed** 2023-12-01 09:21 UTC
Labels: kind/bug, impact/performance, resolution/fixed, p1
