### ISSUE TITLE
Invalid resource type

### ISSUE THREAD

**Issue by lcswillems** [pulumi/pulumi-aws#2365] opened 2023-02-13 12:15 UTC
### What happened?

The following code currently contains a type error:

```
import * as aws from "@pulumi/aws";

const cachingOptimizedPolicy = aws.cloudfront.getCachePolicyOutput({
  name: "Managed-CachingOptimized",
});

const distribution = new aws.cloudfront.Distribution("distribution", {
  orderedCacheBehaviors: [
    {
      cachePolicyId: cachingOptimizedPolicy.id,
      ...
    }
  ],
  ...
});
```

`cachePolicyId` expects a string. However, `cachingOptimizedPolicy.id` is of type `string | undefined`.

### Expected Behavior

I expect no type error.

### Steps to reproduce

See code above.

### Output of `pulumi about`

CLI          
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.29.1
awsx        1.0.1
cloudflare  4.15.0
docker      3.6.1
nodejs      unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2023-02-13 12:22
Hi there @lcswillems thanks for filing the issue! This must be an issue with our schema definition for type of `GetCachePolicyResult` where `id` should be required. As a workaround for your code, you can tell Typescript to assume that the property is just `string` rather than `string | undefined` as follows:

```ts
const cachingOptimizedPolicy = aws.cloudfront.getCachePolicyOutput({
    name: "Managed-CachingOptimized",
});

const distribution = new aws.cloudfront.Distribution("distribution", {
  orderedCacheBehaviors: [
    {
      cachePolicyId: cachingOptimizedPolicy.apply((policy) => policy.id!),
    }
  ]
});
```
It is indeed a bit more verbose but we will look into the underlying type issue as soon as possible

**Comment by lcswillems** [comment] 2023-02-13 12:39
Thanks @Zaid-Ajaj for the fast answer!

**Comment by lukehoban** [comment] 2023-02-15 23:02
I believe this is a duplicate of https://github.com/pulumi/pulumi/issues/6175, which is suggesting changing TypeScript code generation to ensure that inputs are typed as `input?: Input<string | undefined>` instead of the current `input?: Input<string>`.  

As @Zaid-Ajaj mentions - in the meantime - the workaround he suggests is possible to tell TypeScript this is okay.

**Closed by lukehoban** 2023-02-15 23:02 UTC
Labels: kind/bug, resolution/duplicate

**Comment by lcswillems** [comment] 2023-02-17 12:40
@lukehoban I don't understand the link with the issue you are pointing to?
