### ISSUE TITLE
Elastic Beanstalk always show diff.

### ISSUE THREAD

**Issue by skopa** [pulumi/pulumi-aws#878] opened 2020-02-16 11:57 UTC
When setups the settings of elastic beanstalk environment Pulumi always show updates.

STR:
configure some environment with settings.
run `pulumi up`
run `pulumi up` one more time without changes

second runs will show diff

**Comment by leezen** [comment] 2020-02-22 05:19
Could you please provide more details on what your program looks like and where the diff occurs?

**Comment by clstokes** [comment] 2020-04-23 15:53
Same issue as https://github.com/pulumi/pulumi-aws/issues/920, which has repro code.

**Comment by lukehoban** [comment] 2022-11-19 03:04
Closing as dupe of #920.

**Closed by lukehoban** 2022-11-19 03:04 UTC
Labels: kind/bug, resolution/duplicate
