### ISSUE TITLE
Python: AWS Batch Fargate Compatibility Not Working

### ISSUE THREAD

**Issue by bryceAebi** [pulumi/pulumi-aws#1523] opened 2021-06-08 22:27 UTC
I am trying to set up an `aws.batch.ComputeEnvironment` and there seem to be several issues with the batch api.

## Steps to reproduce

This basic example (more or less copied from the documentation for this API) is throwing an error:

```
batch_compute_environment = aws.batch.ComputeEnvironment(
    'batch-compute-environment',
    compute_environment_name='batch-compute-environment',
    compute_resources=aws.batch.ComputeEnvironmentComputeResourcesArgs(
        max_vcpus=256,
        security_group_ids=batch_security_group.id,
        subnets=vpc_subnet_ids,
        type="FARGATE",
    ),
    service_role=batch_service_role.arn,
    type="FARGATE",
)
```

It's worth calling out that the example in the documentation sets `type="Managed"`, which the documentation does not list as a valid value. Either way throws the same error.

Expected:  
I would like Pulumi to stand up the resource.

Actual: 
`TypeError: __init__() missing 3 required keyword-only arguments: 'instance_role', 'instance_types', and 'min_vcpus'`. Appears that the `type` is reverting to the default of `EC2`

**Comment by bryceAebi** [comment] 2021-06-22 03:31
More details: I created the compute environment via the AWS console, imported the resource into Pulumi, copied the resource code from the import command, and then ran `pulumi up`. I get:

```
Diagnostics:
  aws:batch:ComputeEnvironment (staging-batch-compute-environment):
    error: aws:batch/computeEnvironment:ComputeEnvironment resource 'staging-batch-compute-environment' has a problem: expected compute_resources.0.type to be one of [EC2 SPOT], got FARGATE. Examine values at 'ComputeEnvironment.ComputeResources.Type'.
 ```

**Comment by lukehoban** [comment] 2021-06-22 06:14
> It's worth calling out that the example in the documentation sets type="Managed", which the documentation does not list as a valid value. Either way throws the same error.

The documentation appears to be incorrect, the allowed values for the outer `type` are `MANAGED` and `UNMANAGED`.

If I take the example as provided in the docs (and fix up for some unreferenced variables) and append to the EC2 example above - it deploys for me as expected (using `MANAGED`):

```py
sample = aws.batch.ComputeEnvironment("sample",
    compute_environment_name="sample2",
    compute_resources=aws.batch.ComputeEnvironmentComputeResourcesArgs(
        max_vcpus=16,
        security_group_ids=[sample_security_group.id],
        subnets=[sample_subnet.id],
        type="FARGATE",
    ),
    service_role=aws_batch_service_role_role.arn,
    type="MANAGED",
    opts=pulumi.ResourceOptions(depends_on=[aws_batch_service_role_role_policy_attachment]))
```

The errors you mention above don't look like they should be possible with the code you shared.  Do you have a complete repro of that, and also possibly the full output from the update?

**Comment by lukehoban** [comment] 2021-06-22 06:18
Ahh - actually - what version of `pulumi_aws` are you using?  Support for Fargate w/ Batch was added in version [4.2.0](https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md#420-2021-05-04).  The issues above look like they could all be caused by using an older version of the provider from before that feature was supported.

**Comment by lukehoban** [comment] 2021-06-22 06:21
Confirmed that if I use an older version of `pulumi_aws` I see the same errors as above, so will close this out.  If you upgrade to >=4.2.0 this should work as expected.

**Closed** 2021-06-22 06:21 UTC
Labels: kind/bug, resolution/by-design
