### ISSUE TITLE
[import] AWS autoscaling group import and subsequent `up` tries to fix defaults to actual default values

### ISSUE THREAD

**Issue by rulatir** [pulumi/pulumi-aws#4457] opened 2024-09-12 20:32 UTC
### What happened?

I imported an autoscaling group with pulumi import, added the generated code to the pulumi program, and issued `pulumi preview`.

Expected: no changes.

Actual: pulumi insists on fixing some properties that are set to "Default" in the cloud reality to their respective actual default values. This is undesirable.

```
      + forceDelete                  : false
      + forceDeleteWarmPool          : false
      + ignoreFailedScalingActivities: false
      + waitForCapacityTimeout       : "10m"
```

I inspected the state using `pulumi stack export`, and all these properties are `null` in the state after import, and they are not specified in code either. If the state says `null` and the cloud reality says "Default" (as an option selected in a select widget in the AWS Console), and the program says nothing, then where does `false` or `"10m"` even come from?

### Example

Import command:
```
pulumi import --generate-code 'aws:autoscaling/group:Group' platform Infra-ECS-Cluster-zaffre-37cd4e5b-ECSAutoScalingGroup-982zexeihkOe
```

Generated code:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const platform = new aws.autoscaling.Group("platform", {
    availabilityZones: ["eu-central-1a"],
    defaultCooldown: 300,
    healthCheckGracePeriod: 0,
    healthCheckType: "EC2",
    launchTemplate: {
        id: "lt-0789d9b35b0a9d959",
        version: "$Latest",
    },
    maxSize: 2,
    minSize: 0,
    name: "Infra-ECS-Cluster-zaffre-37cd4e5b-ECSAutoScalingGroup-982zexeihkOe",
    serviceLinkedRoleArn: "arn:aws:iam::164629628951:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling",
    tags: [
        {
            key: "AmazonECSManaged",
            propagateAtLaunch: true,
            value: "",
        },
        {
            key: "Name",
            propagateAtLaunch: true,
            value: "ECS Instance - zaffre",
        },
    ],
}, {
    protect: true,
});
```

### Output of `pulumi about`

```
CLI          
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.51.0
resource  aws     6.51.0
resource  awsx    2.14.0
resource  awsx    2.14.0
resource  docker  4.5.5
resource  docker  4.5.5
resource  docker  3.6.1
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/home/rulatir/projects/zaffre/internment/nave/store/installed/node-modern/bin/node' version='v22.2.0'

Current Stack: organization/zuu-iac/permanent

TYPE                                   URN
[REDACTED]

Found no pending operations associated with permanent

Backend        
Name           berbelek
URL            s3://zuu-iac/attempts/PPM
User           rulatir
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /home/rulatir/projects/zaffre/cloud/attempts/PPM/yarn.lock or /home/rulatir/projects/zaffre/cloud/attempts/PPM/package-lock.json
```

Note about the last warning: I chose `pnpm` during `pulumi new`; it seems `pulumi about` can't handle that yet.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rulatir** [comment] 2024-09-13 07:51
Can this be worked around somehow? I must emphasize that by "work around" I don't mean "give up", i.e. "just let pulumi fix those defaults".

**Comment by flostadler** [comment] 2024-09-13 09:37
Hey @rulatir sorry you're running into this! This seems to be a regression caused by a recent change that was rolled out in [v6.51.0](https://github.com/pulumi/pulumi-aws/releases/tag/v6.51.0).
It is tracked here: https://github.com/pulumi/pulumi-terraform-bridge/issues/2372.
As a workaround you could roll back to `v6.50.1` of the provider.

Alternatively, running `pulumi up` should align the state without modifying the cloud resource. None of those parameters are part of the cloud state of that resource: 
- `forceDelete` and `forceDeleteWarmPool` are inputs for the [`DeleteAutoScalingGroup`](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DeleteAutoScalingGroup.html) and [`DeleteWarmPool`](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DeleteWarmPool.html) API calls. 
- `ignoreFailedScalingActivities` and `waitForCapacityTimeout ` are provider level settings for how to handle updates to the Auto Scaling Groups

**Comment by rulatir** [comment] 2024-09-28 10:20
I upgraded to 6.54.0 and tried to run `pulumi preview` on the code/state/cloud reality combo that hasn't been touched since I ran into this issue and got stuck. I expected to get unstuck. I did not: I got the exact same update plan as previously, with pulumi declaring that it WOULD, as opposed to ABSOLUTELY WOULDN'T, attempt to immediately modify ASGs that were just imported and the generated code was added to the program. Therefore the issue is not fixed. Please reopen.

(Perhaps the problem is that an already imported resource is tied to the provider version in the state, and you can't upgrade the provider first and only then use the new provider to do the actual work - these steps cann't be decoupled. That would be a **huge** architectural issue with Pulumi if true, because it would effectively mean that it is simply impossible to "fix" state by upgrading to a provider version that that fixes the issue.)

```
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:permanent::zuu-iac::pulumi:pulumi:Stack::zuu-iac-permanent]
    ~ aws:autoscaling/group:Group: (update)
        [id=Infra-ECS-Cluster-zaffre-37cd4e5b-ECSAutoScalingGroup-982zexeihkOe]
        [urn=urn:pulumi:permanent::zuu-iac::aws:autoscaling/group:Group::platform]
        [provider: urn:pulumi:permanent::zuu-iac::pulumi:providers:aws::default_6_51_0::3a397c39-393f-49e9-8fee-b34c39d39065 => urn:pulumi:permanent::zuu-iac::pulumi:providers:aws::default_6_54_0::output<string>]
      + forceDelete                  : false
      + forceDeleteWarmPool          : false
      + ignoreFailedScalingActivities: false
      + waitForCapacityTimeout       : "10m"
    ~ aws:autoscaling/group:Group: (update)
        [id=Infra-ECS-Cluster-zaffre-mongodb-682cc63e-ECSAutoScalingGroup-tznhtknUgPkL]
        [urn=urn:pulumi:permanent::zuu-iac::aws:autoscaling/group:Group::mongodb]
        [provider: urn:pulumi:permanent::zuu-iac::pulumi:providers:aws::default_6_51_0::3a397c39-393f-49e9-8fee-b34c39d39065 => urn:pulumi:permanent::zuu-iac::pulumi:providers:aws::default_6_54_0::output<string>]
      + forceDelete                  : false
      + forceDeleteWarmPool          : false
      + ignoreFailedScalingActivities: false
      + waitForCapacityTimeout       : "10m"
```

**Comment by t0yv0** [comment] 2024-09-28 10:59
> [provider: urn:pulumi:permanent::zuu-iac::pulumi:providers:aws::default_6_51_0

Pulumi's using a provider version 5.61.0 here that doesn't have the fix yet. Would it be possible to upgrade to 6.54.0 before proceeding?

**Comment by rulatir** [comment] 2024-09-28 11:08
I assumed that's just recorded reference to the version the resource's representation in the state was created with.

I updated the provider with pnpm and `@pulumi/aws` is now at 5.64 in `package.json`. Additionally, when I first ran `pulumi preview` after doing that, it further installed _something_ with 5.64 in it. I honestly thought I'd done due dilligence upgrading the provider at that point. What else does it take? Does Pulumi keep all previous versions of the provider, and a resource's state entry is forever tied to the version that created it, until I delete the resource from the state and re-import it?

**Comment by t0yv0** [comment] 2024-09-28 11:35
IN some cases Pulumi uses the provider version that's written into your state to manage the said resource. Do you have references to 6.51.0 in `pulumi stack export`? You can edit that manually, or is possible just do `pulumi up` on the new version accepting the diff above and that should move that forward.

**Comment by rulatir** [comment] 2024-09-28 11:53
"The diff above" tries to fix properties that are either not even shown in the AWS console for this resource, or set to "Default". "Default" is **semantically distinct** from any concrete value. It must be assumed to mean "Auto", unless it is thoroughly and bindingly documented that the meaning of "Default" for that particular property of that particular resource type is in fact some specific value that does not depend on unknown other properties of this or related resources, or on unknown logic that computes the effective value from those inputs.

**Comment by t0yv0** [comment] 2024-09-28 13:40
For this particular resource, and these particular values, there will be no difference to your cloud in accepting the diff as TF code will populate these values anyway before doing Create/Update calls. I'm starting to think that the evidence points to the bug is indeed fixed in the latest version of the provider, but since stack editing is not working for you I'd recommend accepting the diff with `pulumi up --yes`. 

```
   + forceDelete                  : false
      + forceDeleteWarmPool          : false
      + ignoreFailedScalingActivities: false
      + waitForCapacityTimeout       : "10m"
```

There is also https://github.com/pulumi/pulumi/issues/9878 that can be helpful to up-vote to prioritize making upgrades easier.  I think there isn't much else we can do for this case in pulumi-aws at the moment unfortunately.

**Closed by t0yv0** 2024-09-28 13:40 UTC
Labels: kind/bug, resolution/fixed, awaiting-upstream, p1, impact/regression, area/import
