### ISSUE TITLE
AWS Lightsail public port update incorrect

### ISSUE THREAD

**Issue by nanzeng** [pulumi/pulumi-aws#1918] opened 2022-04-22 10:05 UTC
### What happened?

AWS lightsail public ports is updated incorrectly. Even though there is no change for the opened ports, `pulumi up` tries to modify existing ports, which results in all the IPv4 ports removed. If a new port is added, the result is that only that port is opened, but all the other previous opened ports are removed.

A workaround is to remove the public ports state and run `pulumi up` again to update the ports.

### Steps to reproduce

1. create a set of public ports, such as 22, 53, etc.
2. run `pulumi up` to open these ports
3. run `pulumi up` again without changing anything

### Expected Behavior

ports 22, 53 are opened

### Actual Behavior

ports 22, 53 are removed from the list

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nanzeng** [comment] 2022-04-22 12:29
WIth the native api, update ports fails with the following error:

 error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: xxxxxxx, api error ValidationException: Invalid patch update: readOnlyProperties [/properties/Networking/MonthlyTransfer/GbPerMonthAllocated] cannot be updated

**Comment by lukehoban** [comment] 2022-12-28 07:50
This looks like a duplicate of https://github.com/pulumi/pulumi-aws/issues/1511.

**Closed by lukehoban** 2022-12-28 07:50 UTC
Labels: kind/bug, resolution/duplicate
