### ISSUE TITLE
CI/testing/build hole

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-aws#904] opened 2020-03-20 18:12 UTC
The generator generated reference to a type that doesn't exist:

https://github.com/pulumi/pulumi-aws/blob/e9783ed59f49c6bdaddfd5b7d100fca13fb10d71/sdk/go/aws/autoscaling/group.go#L161

https://github.com/pulumi/pulumi/issues/4135 captures adding that builtin-type. Right now we only exercise this code in CI through the examples. If you run:

```sh
$ go build ./...
```

you get the following output: 

```
# github.com/pulumi/pulumi-aws/sdk/go/aws/autoscaling
sdk/go/aws/autoscaling/group.go:161:17: undefined: pulumi.MapArrayOutput
```

Our release process should at a minimum have some sort of compile/build step to ensure all of the go SDK builds cleanly.

**Comment by lukehoban** [comment] 2020-03-20 18:28
> Our release process should at a minimum have some sort of compile/build step to ensure all of the go SDK builds cleanly.

This appears to be related to (or effectively the same as what is tracked in): https://github.com/pulumi/pulumi/issues/3834

**Comment by stack72** [comment] 2020-04-08 12:31
Closing this as a dupe of https://github.com/pulumi/pulumi/issues/3834

**Closed by stack72** 2020-04-08 12:31 UTC
