### ISSUE TITLE
tags outputs non usable as inputs

### ISSUE THREAD

**Issue by filip-zyzniewski** [pulumi/pulumi-aws#1693] opened 2021-11-08 17:06 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It is not possible to use the `tags` output property of one resource as an input for the `tags` arg for another resource.

### Steps to reproduce

```typescript
pulumi-tags-wtf$ cat index.ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("bucket-1", {tags: {"foo": "bar"}});
const bucket2 = new aws.s3.Bucket("bucket-2", {tags: bucket1.tags});
pulumi-tags-wtf$
```

Expected:

bucket-2 has the same tags as bucket-1

Actual: 

```typescript
pulumi-tags-wtf$ pulumi preview
Previewing update (default):
     Type                 Name                     Plan       Info
 +   pulumi:pulumi:Stack  pulumi-tags-wtf-default  create     1 error

Diagnostics:
  pulumi:pulumi:Stack (pulumi-tags-wtf-default):
    error: Running program '/home/filip/tmp/wtf/pulumi-tags-wtf' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(5,47): error TS2345: Argument of type '{ tags: pulumi.Output<{ [key: string]: string; } | undefined>; }' is not assignable to parameter of type 'BucketArgs'.
      Types of property 'tags' are incompatible.
        Type 'Output<{ [key: string]: string; } | undefined>' is not assignable to type '{ [key: string]: Input<string>; } | Promise<{ [key: string]: Input<string>; }> | OutputInstance<{ [key: string]: Input<string>; }> | undefined'.
          Type 'OutputInstance<{ [key: string]: string; } | undefined>' is not assignable to type '{ [key: string]: Input<string>; } | Promise<{ [key: string]: Input<string>; }> | OutputInstance<{ [key: string]: Input<string>; }> | undefined'.
            Type 'OutputInstance<{ [key: string]: string; } | undefined>' is not assignable to type 'OutputInstance<{ [key: string]: Input<string>; }>'.
              Type '{ [key: string]: string; } | undefined' is not assignable to type '{ [key: string]: Input<string>; }'.
                Type 'undefined' is not assignable to type '{ [key: string]: Input<string>; }'.

        at createTSError (/home/filip/tmp/wtf/pulumi-tags-wtf/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/home/filip/tmp/wtf/pulumi-tags-wtf/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/home/filip/tmp/wtf/pulumi-tags-wtf/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/home/filip/tmp/wtf/pulumi-tags-wtf/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
        at Object.require.extensions.<computed> [as .ts] (/home/filip/tmp/wtf/pulumi-tags-wtf/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:816:12)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (node:internal/modules/cjs/helpers:93:18)


pulumi-tags-wtf$
```

I can copy the tags using the following workaround cast:

```typescript
pulumi-tags-wtf$ cat index.ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("bucket-1", {tags: {"foo": "bar"}});
const bucket2 = new aws.s3.Bucket("bucket-2", {tags: bucket1.tags as pulumi.Output<{ [key: string]: string }>});
pulumi-tags-wtf$
```

```
pulumi-tags-wtf$ pulumi preview --diff
Previewing update (default):
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:default::pulumi-tags-wtf::pulumi:pulumi:Stack::pulumi-tags-wtf-default]
    + aws:s3/bucket:Bucket: (create)
        [urn=urn:pulumi:default::pulumi-tags-wtf::aws:s3/bucket:Bucket::bucket-1]
        [provider=urn:pulumi:default::pulumi-tags-wtf::pulumi:providers:aws::default_4_27_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        acl         : "private"
        bucket      : "bucket-1-9258222"
        forceDestroy: false
        tags        : {
            foo       : "bar"
        }
    + aws:s3/bucket:Bucket: (create)
        [urn=urn:pulumi:default::pulumi-tags-wtf::aws:s3/bucket:Bucket::bucket-2]
        [provider=urn:pulumi:default::pulumi-tags-wtf::pulumi:providers:aws::default_4_27_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        acl         : "private"
        bucket      : "bucket-2-460dbd5"
        forceDestroy: false
        tags        : {
            foo       : "bar"
        }
Resources:
    + 3 to create
pulumi-tags-wtf$
```

**Comment by leezen** [comment] 2021-11-10 17:02
Sorry you ran into this. The issue is that the `undefined` has moved into the `Output` (since it could actually be an undefined `Output`) while the input doesn't accept `Input<undefined>`. I believe this is a dupe of https://github.com/pulumi/pulumi/issues/6175 and am closing as such. Another workaround that might be clearer from a TypeScript perspective is to write this as `bucket.tags.apply(t => t!)`

**Closed** 2021-11-10 17:02 UTC
Labels: kind/bug, resolution/duplicate
