### ISSUE TITLE
Wrong argument type in python example code in AWS Classic/apigateway/RestApi

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi-aws#1789] opened 2022-01-27 11:29 UTC
I'm trying to create an AWS rest api gateway with the python example code [here](https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/). 

And I found that the `types` of `aws.apigateway.RestApiEndpointConfigurationArgs`seems to be wrong.

```
endpoint_configuration=aws.apigateway.RestApiEndpointConfigurationArgs(
    types=["REGIONAL"],
))
```
According to this [document](https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/restapi/#restapiendpointconfiguration), the type of `types` should be `str` instead of `list`.

After chaning that line of code to `types="REGIONAL"`, pulumi correctly displays a preview when running `pulumi up`.

### Steps to reproduce
1. Run `pulumi up` with the following python example code.
```
import pulumi
import hashlib
import json
import pulumi_aws as aws

example_rest_api = aws.apigateway.RestApi("exampleRestApi",
    body=json.dumps({
        "openapi": "3.0.1",
        "info": {
            "title": "example",
            "version": "1.0",
        },
        "paths": {
            "/path1": {
                "get": {
                    "x-amazon-apigateway-integration": {
                        "httpMethod": "GET",
                        "payloadFormatVersion": "1.0",
                        "type": "HTTP_PROXY",
                        "uri": "https://ip-ranges.amazonaws.com/ip-ranges.json",
                    },
                },
            },
        },
    }),
    endpoint_configuration=aws.apigateway.RestApiEndpointConfigurationArgs(
        types=["REGIONAL"],
    ))
example_deployment = aws.apigateway.Deployment("exampleDeployment",
    rest_api=example_rest_api.id,
    triggers={
        "redeployment": example_rest_api.body.apply(lambda body: json.dumps(body)).apply(lambda to_json: hashlib.sha1(to_json.encode()).hexdigest()),
    })
example_stage = aws.apigateway.Stage("exampleStage",
    deployment=example_deployment.id,
    rest_api=example_rest_api.id,
    stage_name="example")
```

Expected: 
A preview of the update should be displayed.

Actual: 
The following error occurs:
```
error: Program failed with an unhandled exception:
error: Traceback (most recent call last):
    File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
    loop.run_until_complete(coro)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
    await wait_for_rpcs()
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
    raise exception
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 447, in do_register
    resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
    serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 149, in serialize_properties
    result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 288, in serialize_property
    is_known = await output._is_known
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/output.py", line 158, in run
    is_known = await self._is_known
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
    result = await rpc
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
    return await is_known and not contains_unknowns(await future)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
    return await is_known and not contains_unknowns(await future)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
    return await is_known and not contains_unknowns(await future)
    [Previous line repeated 15 more times]
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 447, in do_register
    resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
    serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 149, in serialize_properties
    result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 329, in serialize_property
    return {
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 330, in <dictcomp>
    k: await serialize_property(v, deps, input_transformer, types.get(k), keep_output_values)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 193, in serialize_property
    element_type = _get_list_element_type(typ)
    File "/Users/my_name/opt/miniconda3/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 106, in _get_list_element_type
    raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
AssertionError: Unexpected type. Expected 'list' got '<class 'str'>'
error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by viveklak** [comment] 2022-02-02 18:18
Seems an issue in the TF example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api

**Comment by mikhailshilkov** [comment] 2023-11-07 22:13
Duplicate of https://github.com/pulumi/pulumi-aws/issues/2033

**Closed by mikhailshilkov** 2023-11-07 22:13 UTC
Labels: area/docs, kind/bug, resolution/duplicate, awaiting-upstream
