### ISSUE TITLE
SQS Queue docs look wrong

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-aws#3100] opened 2023-12-07 14:44 UTC
### What happened?

https://www.pulumi.com/registry/packages/aws/api-docs/sqs/queue/

Some of the examples for all languages are listed underneath each other, without a language selection menu.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment] 2024-02-01 20:53
This is a duplicate of: https://github.com/pulumi/pulumi-terraform-bridge/issues/926

**Comment by iwahbe** [comment] 2024-03-26 09:47
This has been fixed with https://github.com/pulumi/pulumi-terraform-bridge/issues/926.

**Closed by iwahbe** 2024-03-26 09:47 UTC
Labels: area/docs, kind/bug, resolution/fixed
