### ISSUE TITLE
Automatically tag a magic lambda's log group

### ISSUE THREAD

**Issue by thuringia** [pulumi/pulumi-aws#1601] opened 2021-08-18 17:00 UTC
My teams, including mine, use resource tagging for cost discovery and analysis. Unfortunately Pulumi does not automatically create a CloudWatch LogGroup that was created automatically using "magic lambda".

When passing `aws.lambda.CallbackFunction` with a `tags` property like this: 

```typescript
topic.onEvent(
  "publishEvent",
  new aws.lambda.CallbackFunction("publishEvent", {
    memorySize: 128,
    tags: {
      team: "foo",
      service: "bar"
    },
    callback: handleEvent,
  }),
  { 
    tags: {
      team: "foo",
      service: "bar"
    }
  }
);
```
would create a LogGroup with the tags `team` and `service`.

The "underlying" LogGroup automatically receives the functions tags, even better if `CallbackFunction` could receive tags from its source, I could imaging that this is not always desirable though.

Currently we are using Pulumi only for our AWS account setup which does not involve many lambda functions, however once we start migrating projects from Serverless framework, we're much more in need of an integration like that. Otherwise we'd need to create a helper function of some sort to create the log groups and permissions manually.

## Affected feature

AWS (magic) lambda

**Comment by leezen** [comment] 2021-08-21 00:36
Could you describe more about creating the log group automatically? Generally, my experience has been that the Lambda function will create a corresponding log group. Are you seeing different behavior or expecting something different?

On the tagging side, I think you should be able to do something like the below:

```typescript
const cb = new aws.lambda.CallbackFunction("publishEvent", {
    memorySize: 128,
    tags: {
      team: "foo",
      service: "bar"
    },
    callback: handleEvent,
  }),
  { 
    tags: {
      team: "foo",
      service: "bar"
    }
  }

cb.name.apply(name => {
   // use the AWS SDK to lookup the log group by name
   // use the AWS SDK to tag the log group w/ the tags from above
});
```

But definitely hear the feedback that it'd be ideal if this were built-in behavior.

**Comment by thuringia** [comment] 2021-08-23 10:50
As you said, the Lambda function creating its log group on first execution is the default, and unfortunately also the way AWS constructs the documentation. That way, we'd have to assign tags to the log group at run time, which is undesirable.

Using code like the snippet you shared can be used as a workaround. For our services using Serverless framework, this is exactly what we're doing, using a plugin instead of custom code, but that's not really the point.
Right now, I'm deploying the log groups as separate `aws.cloudwatch.LogGroup` resource including a fully custom IAM role. We need one anyways due to access to cross-account resources. That way we can tag the log group directly and that's also where the question initially came up.

On the Pulumi side, I could imagine this being implemented using a check for custom properties, like tags log retention etc, If these are detected, Pulumi creates a log group directly and sets the required properties but hides the log group similar to how Lambda permissions are handled, otherwise we fall back to the default behavior.

The big question I guess is, how high-level is the magic lambda feature supposed to be?
If you start adding properties and logic for logs, the next question would be "What about IAM?", and so on, increasing the API surface and complexity of the magic lambda feature considerably.

Let's say that from a Pulumi API perspective it's more desirable to keep the AWS provider itself closer to the actual AWS API, or this not being a good candidate for `pulumi-awsx`, maybe this could be added to the docs as a pattern how to wrap something like this using helper function.

**Comment by leezen** [comment] 2021-08-24 00:37
Great feedback and thanks for those additional thoughts and comments. I agree that with more features, it might make more sense to put into `pulumi-awsx` or even its own standalone component library.

**Comment by lukehoban** [comment] 2022-12-28 06:05
I don't expect we would add this support to `CallbackFunction`, since it is specifically designed to handle callbacks as an alternative form of providing source code for a Function.

Users can use the approach as in https://advancedweb.hu/how-to-manage-lambda-log-groups-with-terraform/ to take ownership of managing log groups themselves, whether using `CallbackFunction` or `Function` directly.

We could offer more helpers to do this for users, but I don't expect we would do that in the core AWS package at this point.

I'll close this out as By Design, but if there is still interest in a higher-level component with this built in - either feel free to create and share a simple component that provides this support, or re-open as a new component request in https://github.com/pulumi/pulumi-awsx.

**Closed by lukehoban** 2022-12-28 06:05 UTC
Labels: kind/enhancement, resolution/by-design
