### ISSUE TITLE
Terraform AWS provider SharedConfigErr with AWS SSO

### ISSUE THREAD

**Issue by edalongeville** [pulumi/pulumi-aws#1340] opened 2021-02-02 18:03 UTC
Hello,

Since this morning, I am unable to deploy to AWS, getting the following error message:
`error configuring Terraform AWS Provider: Error creating AWS session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso`

EDIT: Sample repo available: https://github.com/edalongeville/pulumi_sample_credentials

### My environment:
AmazonLinux
Python 3.8.7
Poetry used to install python dependencies
Pulumi 2.19.0 installed using brew
Pulumi-aws 3.26.1

### Steps:
These steps have been tested on both an existing project (stack already deployed) and a new one.

After running `poetry install` and ensuring my .venv is enabled, I navigate to my pulumi python project and run `poetry run pulumi up`. I get the following, as expected:
```
(.venv) [linuxbrew@8b00ad41377e test]$ poetry run pulumi up
[...]
     Type                 Name          Plan       Info
 +   pulumi:pulumi:Stack  test-staging  create     
     └─ aws:s3:Bucket     my-bucket                1 error
 
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
        * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
    
    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.
    
    Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I then login using `aws sso login`. This is the content of my `~/.aws/config`:
```
[default]
sso_start_url = https://<COMPANY>.awsapps.com/start
sso_account_id = <MY_AWS_ACCOUNT_ID>
sso_role_name = AWSAdministratorAccess
sso_region = eu-west-1
region = eu-west-1
output = json
credential_process = aws-sso-credential-process --profile default

```

From here, I attempt a `poetry run pulumi up` again, and get:
```
(.venv) [linuxbrew@8b00ad41377e test]$ poetry run pulumi up
[...]
     Type                 Name          Plan       Info
 +   pulumi:pulumi:Stack  test-staging  create     
     └─ aws:s3:Bucket     my-bucket                1 error
 
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
        * error configuring Terraform AWS Provider: Error creating AWS session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso
```

This is were I'm stuck. I have attempted rolling back pulumi to 2.18.2 and pulumi-aws to 3.25.1 (latest versions for which the deployment worked). I have also ensured that I had no env var configured for AWS.

Could you please help me investigate this further?

**Comment by komalali** [comment] 2021-02-10 16:33
I'm also hitting this error this morning. I have 2 programs, 1 runs successfully, the other one fails with this error. It looks like the error is coming from a call to `default_vpc = ec2.get_vpc(default=True)` (if I add this line to the program that was succeeding, it now fails.

**Comment by komalali** [comment] 2021-02-10 16:47
I had some leftover credentials in my ~/.aws folder since I am also now using SSO. Once I deleted those credentials and only logged in using SSO everything started working again.

**Comment by MatiasNMont** [comment] 2021-02-17 18:57
I tried @komalali 's solutions but unfortunately  it doesn't work for me. 
My scenario is: 
1. I have a custom component resource  where I declared rds component.
2. I linked this with npm link to use this resource in a particular project (within index)
3. In my project, I ran npm run link myComponent.  
When I run pulumi previe a message  `* error configuring Terraform AWS Provider: Error creating AWS session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso` appear. 

NOTE: when I upload my package to custom repository (i.e: Nexus) and then I use this package, this working correctly

**Comment by leezen** [comment] 2021-02-23 18:07
@edalongeville Are you still hitting this issue?
@MatiasNMont I wonder if somehow a different provider configuration is getting picked up in your local scenario vs. when it's published?

**Comment by shousper** [comment] 2021-04-23 09:59
Same issue here, just now, after trying to setup SSO as well.

```
$ AWS_PROFILE=root-sso pulumi -v=9 up
error: failed to load checkpoint: blob (key ".pulumi/stacks/production.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

If I revert back to using access keys, it all magically works again.

```
$ AWS_PROFILE=root pulumi -v=9 up
Previewing update (production):
... snip ...
```

I'm not using `aws-sso-credential-process` (or `aws-sso-util`) though.

**Comment by leezen** [comment] 2021-04-23 17:31
@shousper In the above, it looks like the access issue is for your state in an S3 backend instead of the actual configuration for the provider itself? Any chance you're using a pre-v2.23.0 version of Pulumi? Up until v2.23.0, the version of `go-cloud` used didn't have support for AWS SSO in the underlying AWS SDK.

**Comment by shousper** [comment] 2021-04-27 04:22
Thanks @leezen. I think you hit the nail on the head. Was still using 2.22 :derp:

**Comment by leezen** [comment] 2021-04-27 16:37
At this point, given the lack of updates, I'll close this issue, as we cannot reproduce the original issue.

**Closed by leezen** 2021-04-27 16:37 UTC
Labels: kind/bug, kind/question
