### ISSUE TITLE
Newly disallowed URNs when adopting AWS v6

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#3027] opened 2023-11-20 01:15 UTC
A user reported getting new errors after updating to AWS v6 related to URNS:

>  aws:ssoadmin:ManagedPolicyAttachment sso-permission-set-admin-attachment-arn:aws:iam  error: URN 'urn:pulumi:production::i2::aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment::sso-permission-set-admin-attachment-arn:aws:iam::aws:policy/AdministratorAccess' is not valid

This URN indeed is "invalid", as it has a `::` inside the resource name part of the URN `sso-permission-set-admin-attachment-arn:aws:iam::aws:policy/AdministratorAccess`.  However, it appears this did not cause any issues in AWS v5, and newly errors in V6.  This error appears to be coming from the tf-bridge muxer.  

A few questions:
1. Should we still be supporting this URN for existing working programs?
2. If not, we should include in breaking change list
3. Also, how does a user upgrade if they are in this state?

**Comment by benesch** [comment] 2023-11-20 03:58
> 3\. Also, how does a user upgrade if they are in this state?

I thought we'd be able to work around this by renaming the resource with a `pulumi.Alias` while still using v5 of the provider, and then go in for the upgrade with a properly named resource. Unfortunately `pulumi.Alias` rejects the old name due to its invalid URN:

```
invalid alias URN: invalid URN "sso-permission-set-admin-attachment-arn:aws:iam::aws:policy/AdministratorAccess"
```

So we had to resort to manual stack surgery to in-place rename the existing resources with the invalid `::` resources. A bit scary, but it worked!

**Comment by lukehoban** [comment] 2023-11-20 13:24
The changes in https://github.com/pulumi/pulumi/pull/14107 are likely to fix this by making this style of name legal.

**Comment by t0yv0** [comment] 2023-12-05 18:44
Having a quick look here.  I can reproduce on 6.13.0 with this program:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// // Create an AWS resource (S3 Bucket)
// const bucket = new aws.s3.Bucket("sso-permission-set-admin-attachment-arn:aws:iam");

// // Export the name of the bucket
// export const bucketName = bucket.id;


const user = new aws.iam.User("user", {});
const assumeRole = aws.iam.getPolicyDocument({
    statements: [{
        effect: "Allow",
        principals: [{
            type: "Service",
            identifiers: ["ec2.amazonaws.com"],
        }],
        actions: ["sts:AssumeRole"],
    }],
});
const role = new aws.iam.Role("role", {assumeRolePolicy: assumeRole.then(assumeRole => assumeRole.json)});
const group = new aws.iam.Group("group", {});
const policyPolicyDocument = aws.iam.getPolicyDocument({
    statements: [{
        effect: "Allow",
        actions: ["ec2:Describe*"],
        resources: ["*"],
    }],
});
const policyPolicy = new aws.iam.Policy("policyPolicy", {
    description: "A test policy",
    policy: policyPolicyDocument.then(policyPolicyDocument => policyPolicyDocument.json),
});

const test_attach = new aws.iam.PolicyAttachment("bad::name", {
    users: [user.name],
    roles: [role.name],
    groups: [group.name],
    policyArn: policyPolicy.arn,
});

```


```
  aws:iam:PolicyAttachment (bad::name):
    error: URN 'urn:pulumi:dev::aws-3027::aws:iam/policyAttachment:PolicyAttachment::bad::name' is not valid
```

Testing RC from main branch that incorporates 14107.

**Comment by t0yv0** [comment] 2023-12-05 18:51
This is indeed fixed on master with https://github.com/pulumi/pulumi-aws/commit/c0922002cc410affbfc88ec213f4496c38097488

We'll be releasing an updated provider shortly and I will close then.

**Closed** 2023-12-06 15:15 UTC
Labels: kind/bug, resolution/fixed, impact/regression
