### ISSUE TITLE
Broken S3-to-SQS BucketNotification Example

### ISSUE THREAD

**Issue by isaac-mcfadyen** [pulumi/pulumi-aws#1774] opened 2022-01-14 03:44 UTC
Referenced File: [themes/default/content/registry/packages/aws/api-docs/s3/bucketnotification/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketnotification/)

## Problem
On the 2nd example, the docs show how to create a BucketNotification for sending S3 events to SQS. However, the example provided is completely broken (and hard to debug, given the cryptic error of `Unable to validate the following destination configurations`).

Because an SQS queue has to reference the bucket that it receives notifications from and can't get it's own ARN to reference, it seems to have been hardcoded in here. The Queue will have a randomly generated name (not "s3-event-notification-queue" as provided in the ARN), so everything breaks.

## Possible Solutions
Possible ideas for solutions to this are to:
1. Add a message to the user, indicating that this is a hardcoded ARN and that the Queue name must exactly match part of the ARN (i.e, with a Queue name of "s3-event-notification-queue", the ARN *MUST* be hardcoded as "arn:aws:sqs:*:*:s3-event-notification-queue").
2. Add a `name=` field to the example so that the name is no longer random generated and matches the hardcoded ARN. May need to go along with **1**.
Example of a solution:
```
queue = aws.sqs.Queue("queue", name="s3-event-notification-queue", policy=bucket.arn.apply(lambda arn: f"""{{
  "Version": "2012-10-17",
  "Statement": [
    {{
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:SendMessage",
	  "Resource": "arn:aws:sqs:*:*:s3-event-notification-queue",
      "Condition": {{
        "ArnEquals": {{ "aws:SourceArn": "{arn}" }}
      }}
    }}
  ]
}}
"""))
```

**Comment by lukehoban** [comment] 2022-12-28 05:48
I opened https://github.com/pulumi/pulumi-terraform-bridge/issues/709 which tracks the underlying issue that leads to this.

Closing this as a duplicate of that so that we can track the required fix.

**Closed by lukehoban** 2022-12-28 05:48 UTC
Labels: area/docs, impact/usability, kind/bug, resolution/duplicate
