### ISSUE TITLE
Go sdk does not compile on master

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#1593] opened 2021-08-12 13:53 UTC
## Steps to reproduce

```
$ git rev-parse HEAD
0b73446ce5361fcd9f313d7e5ac36e5668936d31

$ (cd sdk && go build -v all)
github.com/pulumi/pulumi-aws/sdk/v4/go/aws/kinesisanalyticsv2
# github.com/pulumi/pulumi-aws/sdk/v4/go/aws/kinesisanalyticsv2
go/aws/kinesisanalyticsv2/pulumiTypes.go:2438:10: i.ToApplicationApplicationConfigurationSqlApplicationConfigurationOutputWithContext undefined (type ApplicationApplicationConfigurationSqlApplicationConfigurationArgs has no field or method ToApplicationApplicationConfigurationSqlApplicationConfigurationOutputWithContext)
go/aws/kinesisanalyticsv2/pulumiTypes.go:2450:43: impossible type assertion:
	ApplicationApplicationConfigurationSqlApplicationConfigurationOutput does not implement pulumi.Output (missing ApplyT method)
go/aws/kinesisanalyticsv2/pulumiTypes.go:2513:11: cannot use v.Input (type *ApplicationApplicationConfigurationSqlApplicationConfigurationInput) as type *ApplicationApplicationConfigurationSqlApplicationConfigurationInput in return argument:
	*ApplicationApplicationConfigurationSqlApplicationConfigurationInput is pointer to interface, not interface
go/aws/kinesisanalyticsv2/pulumiTypes.go:2520:11: cannot use v.Outputs (type []ApplicationApplicationConfigurationSqlApplicationConfigurationOutput) as type []ApplicationApplicationConfigurationSqlApplicationConfigurationOutput in return argument
go/aws/kinesisanalyticsv2/pulumiTypes.go:2561:11: cannot use v.Input (type *ApplicationApplicationConfigurationSqlApplicationConfigurationInput) as type *ApplicationApplicationConfigurationSqlApplicationConfigurationInput in return argument:
	*ApplicationApplicationConfigurationSqlApplicationConfigurationInput is pointer to interface, not interface
go/aws/kinesisanalyticsv2/pulumiTypes.go:2571:11: cannot use v.Outputs (type []ApplicationApplicationConfigurationSqlApplicationConfigurationOutput) as type []ApplicationApplicationConfigurationSqlApplicationConfigurationOutput in return argument
go/aws/kinesisanalyticsv2/pulumiTypes.go:2585:6: ApplicationApplicationConfigurationSqlApplicationConfigurationInput redeclared in this block
	previous declaration at go/aws/kinesisanalyticsv2/pulumiTypes.go:2417:6
go/aws/kinesisanalyticsv2/pulumiTypes.go:4601:6: ApplicationApplicationConfigurationSqlApplicationConfigurationOutput redeclared in this block
	previous declaration at go/aws/kinesisanalyticsv2/pulumiTypes.go:2486:6
go/aws/kinesisanalyticsv2/pulumiTypes.go:6867:96: cannot use ApplicationApplicationConfigurationSqlApplicationConfigurationOutput{} (type ApplicationApplicationConfigurationSqlApplicationConfigurationOutput) as type pulumi.Output in argument to pulumi.RegisterOutputType:
	
```

1.
2.
3.
4.

Expected: 
Actual:

**Comment by stack72** [comment] 2021-08-12 13:58
Closing this as a duplicate of https://github.com/pulumi/pulumi/issues/7623

Paul

**Closed** 2021-08-12 13:58 UTC
Labels: kind/bug, resolution/duplicate, needs-triage
