### ISSUE TITLE
`tags` on `aws.applicationloadbalancing.getLoadBalancer` isn't actually supported

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#752] opened 2019-09-20 20:50 UTC
Our SDK advertises `tags` on [`GetLoadBalancerArgs`](https://github.com/pulumi/pulumi-aws/blob/adb7f6b166229532299877d607f7da6f256512ef/sdk/nodejs/alb/getLoadBalancer.ts#L57-L67) for `aws.applicationloadbalancing.getLoadBalancer`, but the underlying AWS Terraform provider doesn't actually support this (per [data_source_aws_lb](https://github.com/terraform-providers/terraform-provider-aws/blob/7ad6f363d6f353ffe06c5d6daaf1860872eab553/aws/data_source_aws_lb.go#L126-L150)).

We should remove `tags` as a member of `GetLoadBalancerArgs`.

#### Code
```typescript
import * as aws from "@pulumi/aws";

export const elbs = aws.applicationloadbalancing.getLoadBalancer({
    name: "main-3-bee5864",
    tags: { "index": "1", "otherTag": "otherValue" },  // <-- Does nothing.
});
```

**Comment by lukehoban** [comment] 2019-09-20 22:44
The root of the problem is that the schema for this property marks it as `Optional` + `Computed`, so we expect it can be passed as an input.  But the provider doesn't use it as an input and doesn't document that it uses it as an input.  

Arguably the right fix is in the upstream Terraform provider, but we may also want to have the ability to override this in our mapping, since the impact is greater for Pulumi since we treat the schema "more seriously".

**Comment by stack72** [comment] 2019-09-30 15:53
@lukehoban so for this specific thing, we are going to have to add something to our bridge that tells us to mark this field as computed. In the upstream provider, tags are set as:

```
"tags": tagsSchemaComputed(),
```

This means they are Optional + Computed - but this is used in a LOT of places. I don't believe that the Terraform provider would actually accept a fix upstream there

Thoughts on this?

Paul

**Closed** 2019-10-17 10:00 UTC
Labels: area/providers, kind/bug
