### ISSUE TITLE
Pulumi does not detect failing lambdas during preview

### ISSUE THREAD

**Issue by caboog** [pulumi/pulumi-aws#2260] opened 2022-12-09 22:23 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Scenario: 
 - Pulumi will fail randomly on a random lambda with the following error: `error waiting for Lambda Function (panther-source-api) creation: InsufficientRolePermissions: The function’s execution role doesn’t have permission to perform this operation` 
 - even with that error, Pulumi will add it to the state as the function does return with ListFunction which is a new thing in the AWS world from what I’ve seen 
 - In the AWS console, the function shows in the list of functions. Only when you click into the function, do you notice that the function actually failed deployment. See attached images 
 - The only way forward is to go in as the deployment role and delete the function and re-run the deploy. Is there a way for Pulumi on a `pulumi refresh` to detect that a deployed lambda is in a *failed* state and mark it for replacement so a re-run of `pulumi up` will fix the situation without us having to manually intervene?

### Affected area/feature

Pulumi Service, AWS provider

**Comment by squaremo** [comment] 2022-12-12 15:59
@caboog Is this something you experienced, or are you conveying it from Slack or another such channel? I feel like

> Pulumi will fail randomly on a random lambda

might need a bit of digging into, because it will be difficult to reproduce this problem without replacing some of those "randoms" with particulars :-) Are you able to give more details, or point the original reporter here, perhaps?

The request here is for `pulumi up` to accurately detect when a lambda is not correctly deployed, and the _cause_ of the failure isn't so relevant to fixing that. But it might help with engineering the fix, and it might show up another problem.

By way of triage: I think `kind/enhancement` is right, and the implied priority -- not a P0 or P1 -- is fine.

**Comment by caboog** [comment] 2022-12-16 19:34
@squaremo conveying info from a zendesk ticket https://pulumi.zendesk.com/agent/tickets/2181. Agree that the failure cause isn't so important, just that failing lambdas be detected.

**Comment by grantjoy** [comment] 2023-11-14 19:57
I believe this is a problem with the TF provider itself. I have seen Hashicorp recommend retrying the Lambda creation code, so that if it fails it keeps retrying until the role is created.

Technically,  this is entirely unrelated to AWS Lambdas, it's that the Role is eventually consistent, we just happen to use the Role to create the Lambda.

I am going to see if I can still reproduce using the newest TF provider.

**Comment by guineveresaenger** [comment] 2024-01-31 19:25
@grantjoy - I know it's been a while 😅 but if you happen to have a current reliable repro for this, we'd really appreciate if you shared.

@mikhailshilkov do you have any more context regarding the reliability impact here?

**Comment by guineveresaenger** [comment] 2024-01-31 19:46
A few more notes:

I believe this is the same behavior as described in this upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/29828, which is still open.

It does appear to be caused by a fairly standard race condition between role creation and lambda creation.

Using [pulumi DependsOn](https://www.pulumi.com/docs/concepts/options/dependson/) on the lambda will most likely prevent the original issue.

**Comment by grantjoy** [comment] 2024-01-31 21:34
@guineveresaenger I think something like this _could_ trigger it: https://www.pulumi.com/ai/conversations/5570d83e-2c42-48f3-bd59-9aae2d272ac9

This example may need to be extended to run many more roles/lambdas to simulate a stress test where roles take longer to create.

It would be awesome if the aws.iam.Role function had another parameter that checked if the role actually created before returning and continuing.

**Comment by guineveresaenger** [comment] 2024-01-31 22:08
@grantjoy - yeah, it does appear this just "randomly" happens on very basic role/lambda programs :/ 

I'm exploring ways in which we can possibly make this more robust since this is mainly an upstream bug.

In the meantime, my recommendation for users to avoid hitting this is to use `DependsOn` so that the resource creation is serial, not parallel.

**Comment by grantjoy** [comment] 2024-01-31 22:11
@guineveresaenger that solution does not work because the resource thinks it completed so it moves on to the dependent resource immediately.

you have to use sleep(60) or similar to get around this. you can imagine how that ends up hurting run time (even with parallelism) when we create 150 roles and lambdas associated.

**Comment by guineveresaenger** [comment] 2024-01-31 22:17
@grantjoy can you clarify what you mean by 

> the resource thinks it completed so it moves on to the dependent resource immediately.

It sounds like you're saying that `Role` thinks it is completed before it actually is? Why do you think this is the case?

**Comment by grantjoy** [comment] 2024-01-31 22:26
@guineveresaenger From what I can tell, aws.iam.Role is an asynchronous operation. I believe this to be the case because adding sleep(60) between role creation and lambda creation solves the problem, but if that sleep is not there, I get failures that the role has not been created (even though the lambda is DependsOn the Role). This tells me that the role creation is returning success when it hasn't finished yet.

Stress testing like this might help recreate the issue: https://www.pulumi.com/ai/conversations/1c0ec03b-7882-43dc-aa83-1bb2faceef83

I believe this is a classic case where basic tests seem to work because an async operation feels synchronous until the system is hammered.

**Comment by guineveresaenger** [comment] 2024-02-01 22:21
Hi everyone!

@grantjoy I tried running [your suggestion](https://www.pulumi.com/ai/conversations/1c0ec03b-7882-43dc-aa83-1bb2faceef83) both from scratch, and with a replace-update, and all resources were created successfully multiple times. Ordering of creation dependency looks correct (all necessary Roles and RolePolicyAttachments are created before the Lambda). This is not to say that this would _never_ trigger this problem, but it's not possible to root cause when the problem may never trigger.

**A few more questions:**

- Can you tell us how often this is happening for you? Every deployment; every other deployment? Which AWS region is this?
- It would help to have a sample Statefile that includes the `failed` Lambda.

-----------

**Further thoughts**

The only reference to this particular error ( `creation: InsufficientRolePermissions: The function’s execution role doesn’t have permission to perform this operation` ) that I can find is in the upstream issue. It is not clear to me where this error message comes from. A lot of search results for `execution role doesn’t have permission to perform this operation` seem to point to a missing _permission_, not the Role itself. However those types of errors aren't really provisioning errors; rather they're errors on a properly deployed Lambda that can't do a task. 

The fact that a sleep() solves this issue for you does point to eventual consistency issues. Terraform [has retry functionality aimed at addressing the eventual consistency of Roles](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/lambda/function.go#L1207). I notice that the error messages being processed do not match the one in this issue. We can add this error as a retry condition; but this assumes that the error is coming from the Lambda creation - if the lambda creation attempt does somehow "succeed" into a `Failed` state then this may not be the right answer. And the fact that the `failed` Lambda shows up in state seems to indicate that perhaps this is not the right approach.

I'm going to look at options more along the lines of the original suggestion with checking the state of a Lambda and allowing it to respond better to a `pulumi refresh`.

Thank you for your patience!

**Comment by grantjoy** [comment] 2024-02-02 04:21
@guineveresaenger We call the lambda as part of our Pulumi run (I wish we didn't) - that likely explains why we see this error. I hadn't considered this until now. I can't speak for others in this thread.

We don't see the problem at all because we have a sleep between all our role creations, but as soon as we remove the sleep it errors consistently. I'm on leave right now so I can't provide a state file.

It sounds like the Lambda creation itself is eventually consistent and a solution would allow us to rely on the DependsOn for our lambda invocation that would wait to invoke the lambda until the lambda's role/permissions are consistent.

**Comment by t0yv0** [comment] 2024-02-06 19:22
Does it help to increase create timeout for lambda? 

https://github.com/hashicorp/terraform-provider-aws/blob/master/internal/service/lambda/function.go#L1165 gives up after the default timeout of 10 minutes

https://github.com/hashicorp/terraform-provider-aws/blob/master/internal/service/lambda/function.go#L54

This can be increased for individual resources though: 
https://www.pulumi.com/docs/concepts/options/customtimeouts/#:~:text=Resource%20option%3A%20customTimeouts&text=The%20customTimeouts%20resource%20option%20provides,1d”%20(1%20day).

**Comment by guineveresaenger** [comment] 2024-02-06 23:34
So I ran an additional fault injection scenario causing [`waitFunctionCreated`](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/lambda/function.go#L1165) to return an error.
This does write the lambda to pulumi state, with an initialization error.
When then running `pulumi refresh`, the state is updated to reflect the upstream state, and in my case, without having repro of this exact issue, succeeds because the Lambda is actually in succeeded state on AWS in this case.

It sounds like what is being described here is a failed AWS state. In such a case, it would be _expected_ that `pulumi refresh` fails to address this because the lambda is in the same AWS state as it was written to Pulumi state.

I concur with @t0yv0 - please do try to increase your timeout on the Lambda resource itself instead of `sleep()`ing after role creation and let us know if that helps.

**Comment by t0yv0** [comment] 2024-02-07 14:36
> The only way forward is to go in as the deployment role and delete the function and re-run the deploy. Is there a way for Pulumi on a pulumi refresh to detect that a deployed lambda is in a failed state and mark it for replacement so a re-run of pulumi up will fix the situation without us having to manually intervene?

We had some quick further discussion with the team about this suggestion specifically. This sounds potentially interesting to make pulumi behave in this way (auto-replace failed state) and we do not rule out trying to do this, but Pulumi needs to be certain that:

- the lambda in AWS is in a permanently failed state and is not making progress, that is, it is not something that is in the middle of resolving itself by retrying later
- Pulumi can reliably detect this situation

This kind of behavior change would be need to be held to a high bar because what we do not want to happen is introducing unwanted unexpected replace behavior in some other situations. Unfortunately at the moment we lack a good confirmed understanding of what's happening here and we lack a solid repro. We were able to simulate InitFailed state recorded to the Pulumi statefile, but not yet a partially constructed Lambda in AWS. It would be very helpful to get one - if we had a repro that puts lambdas in this perma-fail state in AWS that could help our team to understand this condition better.

In the meanwhile together with @guineveresaenger really curious if the timeout workaround is viable for your workload or that continues to be problematic. Much appreciated.

**Comment by grantjoy** [comment] 2024-03-04 22:51
I have been testing this situation by removing the `sleep` hack that had been necessary in the past and it's no longer failing! I think something changed, maybe even on the AWS side. I have done this same exercise a number of times of the past years and it always failed, but now it seems to be working just fine. This issue may be resolve.

**Comment by t0yv0** [comment] 2024-03-05 13:29
That's excellent news. I'm going to close this out optimistically but let's reopen if anyone else runs into this. Thank you.

**Closed** 2024-03-05 13:30 UTC
Labels: kind/bug, impact/reliability, resolution/no-repro, awaiting-upstream, needs-repro
