### ISSUE TITLE
CallbackFunction causes (node:300110) ExperimentalWarning with nodejs 18.0.0

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-aws#1947] opened 2022-05-12 13:22 UTC
### What happened?

I use CallbackFunction and upon the `pulumi preview` I receive the warning
`(node:300110) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time`

### Steps to reproduce

Pulumi project index.ts
```typescript
import * as aws from "@pulumi/aws";

const role = new aws.iam.Role("role", {
  assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal(aws.iam.Principals.LambdaPrincipal),
  managedPolicyArns: [aws.iam.ManagedPolicies.AWSLambdaBasicExecutionRole],
});


const lambdaFn = new aws.lambda.CallbackFunction<void, Promise<void>>(
  "lambda-fn",
  {
    role,
    runtime: "nodejs14.x",
    environment: {
      variables: {

        LOG_LEVEL: "debug",
      },
    },

    callbackFactory: () => {return ()=>{}},

  },
);

```

### Expected Behavior

no warnings

### Actual Behavior

`NODE_OPTIONS='--trace-warnings' pulumi preview`

```
 pulumi:pulumi:Stack (zzzz-user-test):
    (node:300110) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
        at emitExperimentalWarning (node:internal/util:224:11)
        at lazyUndici (node:internal/bootstrap/pre_execution:188:5)
        at get (node:internal/bootstrap/pre_execution:204:16)
        at /home/user/work/bluecode/pulumi-utils/pulumi/projects/zzzz/node_modules/@pulumi/runtime/closure/createClosure.ts:316:44
        at Generator.next (<anonymous>)
        at /home/user/work/bluecode/pulumi-utils/pulumi/projects/zzzz/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/user/work/bluecode/pulumi-utils/pulumi/projects/zzzz/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
        at addGlobalInfoAsync (/home/user/work/bluecode/pulumi-utils/pulumi/projects/zzzz/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:129:28)
        at /home/user/work/bluecode/pulumi-utils/pulumi/projects/zzzz/node_modules/@pulumi/runtime/closure/createClosure.ts:289:27

```

### Versions used

CLI          
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.38.1
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs (/home/user/.asdf/shims/node v18.0.0)
from package.json
```
"@pulumi/aws": "^5.4.0",
"@pulumi/pulumi": "^3.32.1",
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment] 2022-12-28 06:51
I tried the steps above but could not reproduce this.  I suspect it was an issue with a patch version of Node?  Will close this as no repro.

**Closed by lukehoban** 2022-12-28 06:51 UTC
Labels: kind/bug, area/core, resolution/no-repro
