### ISSUE TITLE
Unable to invoke lambda functions in dynamic providers. 

### ISSUE THREAD

**Issue by techmouse84** [pulumi/pulumi-aws#1375] opened 2021-03-05 01:45 UTC
```
export class SimpleResourceProvider implements pulumi.dynamic.ResourceProvider
{
    constructor( name: string, options: any = {})
    {
    }

    async create(inputs: SimpleResourceProviderInput) {
        await aws.lambda.getInvocation( { functionName: inputs.lambdaArn , input : "{}" } );
        return { id : "test", outs: [] }
    }
} 
```

The above would result in the following errors. 
```
TypeError: Class extends value undefined is not a constructor or null: TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (G:\code\iac\infra\sandbox\main\node_modules\@pulumi\cloudwatch\eventRuleMixins.ts:70:56)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at Object.<anonymous> (G:\code\iac\infra\sandbox\main\node_modules\@pulumi\cloudwatch\cloudwatchMixins.ts:16:1)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

Probably related to this issue. 
#772

**Comment by leezen** [comment] 2021-03-09 18:47
I'm not sure it's actually possible to nest providers like this. As a workaround, I would suggest trying to use the AWS SDK directly to invoke the function instead of via the data source of the `@pulumi/aws` provider.

**Comment by techmouse84** [comment] 2021-03-10 02:45
I'm currently using the aws sdk directly to work around this issue. 
Is it possible for me to pull the config of the aws provider to be passed to the aws sdk ?
I'm using assume roles, I do not wish to hard code these information inside the dynamic provider. I would hope to at least query these information and pass to the sdk to work around this.

**Comment by lukehoban** [comment] 2021-03-10 02:49
That is effectively what https://github.com/pulumi/pulumi-aws/issues/841 is tracking. Currently you'd need to read the output of `aws.config` and use those to populate your sdk configuration - though it's possible that not 100% of what you need is exposed there yet.

**Comment by lukehoban** [comment] 2022-12-28 05:38
It is by design that you cannot use Pulumi functions/resources from within a Dynamic Provider.

The support in #841  would make it easier to configure an AWS SDK to make this calls directly. 

I'll close this out as By Design with #841 tracking the core approach we'd like to implement to better support this case in the future.

**Closed by lukehoban** 2022-12-28 05:38 UTC
Labels: kind/bug, area/core, language/javascript, resolution/by-design
