### ISSUE TITLE
aws.ecs.TaskDefinition documentation bug

### ISSUE THREAD

**Issue by dd-ssc** [pulumi/pulumi-aws#2165] opened 2022-10-01 11:44 UTC
File: [themes/default/content/registry/packages/aws/api-docs/ecs/taskdefinition/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/)

The documentation in section [TaskDefinitionVolumeEfsVolumeConfiguration](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#taskdefinitionvolumeefsvolumeconfiguration) for attributes [`file_system_id`](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#file_system_id_python), [`authorization_config`](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#authorization_config_python) and [`root_directory`](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#root_directory_python) mentions _Amazon FSx for Windows File Server_ which is not what this section is about; presumably a simple error that occurred when the attribute documentation was copied from the [TaskDefinitionVolumeFsxWindowsFileServerVolumeConfiguration](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#taskdefinitionvolumefsxwindowsfileservervolumeconfiguration) section.

**Comment by lukehoban** [comment] 2022-12-28 00:28
Closing as a duplicate of https://github.com/pulumi/pulumi-aws/issues/1603.

**Closed by lukehoban** 2022-12-28 00:28 UTC
Labels: area/docs, kind/bug, help-wanted, resolution/duplicate, size/S, good-first-issue
