### ISSUE TITLE
[ConflictsWith] Error Message without any context

### ISSUE THREAD

**Issue by nick6969** [pulumi/pulumi-aws#1209] opened 2020-11-10 09:45 UTC
i try to using 
```
	pulumi.Run(func(ctx *pulumi.Context) error {
		vpc, err := ec2.NewVpc(ctx, "test", &ec2.VpcArgs{
			CidrBlock:       pulumi.String("10.0.0.0/24"),
			InstanceTenancy: pulumi.String("default"),
		})

		if err != nil {
			return err
		}

		_, err = ec2.NewSubnet(ctx, "test", &ec2.SubnetArgs{
			VpcId:            vpc.ID(),
			CidrBlock:        pulumi.String("10.0.0.0/24"),
			AvailabilityZone: pulumi.String("us-east-2b"),
			AvailabilityZoneId: pulumi.String("use2-az2"),
		})

		return err
	})
```
setup newSubnet.
but i got error `aws:ec2/subnet:Subnet resource 'test' has a problem: ConflictsWith`
this error description is confuse me. waste me one day to find the solution.

but, i got solution to fix this error.
solution is remove the `AvailabilityZoneId` arg.
if not put the `AvailabilityZoneId`, will got pass.

maybe need in document let user know. don't put `AvailabilityZoneId` this arg.
or just remove `AvailabilityZoneId` this arg.

**Comment by stack72** [comment] 2020-11-10 12:23
Hi @nick6969 

I am sorry that this caused you pain here. Unfortunately, these are both valid options to be passed to a subnet BUT they are not able to be used together. I agree with you that the error message is incorrect here and we should seek to improve that message

Paul

**Comment by lukehoban** [comment] 2020-12-15 00:34
Closing this as a dupe of https://github.com/pulumi/pulumi-terraform-bridge/issues/309 which is the underlying issue to improve the diagnostic message.

**Closed by lukehoban** 2020-12-15 00:34 UTC
