### ISSUE TITLE
registry shows jan 1 date while repo shows correct date

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-aws#2700] opened 2023-08-15 15:30 UTC
### What happened?

The registry:  https://www.pulumi.com/registry/packages/aws/ shows on the very right that v5.42.1 was published on Monday, Jan 1, 0001 by Pulumi, 

if you click on the repo, it shows the correct date for v5.42.0 on Jul 11.
![AWS_Classic___Pulumi_Registry_incorrect_date](https://github.com/pulumi/pulumi-aws/assets/5281839/63aed0c5-1dfa-4e77-bccb-f1d4c2519554)

### Expected Behavior

Expect the date to match the repo which has the correct date of July 11:
https://github.com/pulumi/pulumi-aws

### Steps to reproduce

Check the site above

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ericrudder** [comment] 2023-08-15 15:49
dupe of https://github.com/pulumi/registry/issues/2896

**Closed by ericrudder** 2023-08-15 15:49 UTC
Labels: kind/bug, resolution/duplicate, needs-triage
