### ISSUE TITLE
Wrong version in schema for aws@v6.33.0 and above

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#3915] opened 2024-05-09 22:22 UTC
We are no longer embedding the correct version in the schema returned by the provider.

```bash
$ pulumi package get-schema aws@v6.32.0 | jq '.version'
"6.32.0"

$ pulumi package get-schema aws@v6.33.0 | jq '.version'
"6.0.0-alpha.0+dev"
```

This leads to errors like this when trying to reference types from the AWS package from within other packages (and probably others):

```
cd provider/cmd/pulumi-gen-acmecorp-eks && go run . dotnet ../../../sdk/dotnet /Users/bob/acmecorp/pulumi-acmecorp-eks/schema.json
Failed: importing schema: error binding resource acmecorp-eks:index:Cluster: failed to bind properties for acmecorp-eks:index:Cluster: error binding type for property "clusterResource": resolving package /aws/v6.33.1/schema.json#/resources/aws:eks%2Fcluster:Cluster: req: aws@6.33.1: entries: map[aws:6.33.1:0x14000b540c0 kubernetes:4.11.0:0x1400030ba00] (returned aws@6.0.0-alpha.0+dev)
```

Those errors will presumably start showing up for first-party component like aws and eks when they try to adopt the latest AWS.

**Comment by lukehoban** [comment] 2024-05-09 22:24
Most likely introduced via https://github.com/pulumi/ci-mgmt/pull/900.

**Comment by flostadler** [comment] 2024-05-10 07:45
I just checked and the release builds seem to identify the correct provider version. E.g. https://github.com/pulumi/pulumi-aws/actions/runs/9009768912/job/24755275740 correctly identified the version as `6.34.0` and set the environment variable `PROVIDER_VERSION: 6.34.0`.

Digging deeper why this doesn't end up in the schema.

**Comment by danielrbradley** [comment] 2024-05-10 08:52
The issue will be in the `publish` step as these binaries are produced completely separately to the one which is tested 🤦  (because we use goreleaser). 

In the publish step we aren't setting the PROVIDER_VERSION - only GORELEASER_CURRENT_TAG as that's all goreleaser asks for ... but I think there must be an implicit need for the PROVIDER_VERSION somewhere. The most likely fix it to also export the PROVIDER_VERSION in the publish step too ... but it would be good to understand how these bits are currently threaded through.

**Comment by danielrbradley** [comment] 2024-05-10 10:10
Rollout to providers is underway: https://github.com/pulumi/ci-mgmt/actions/runs/9030462762

**Comment by flostadler** [comment] 2024-05-10 10:10
We tested out the fix for `pulumi-kafka` and where able to confirm the version is set now by downloading the provider binary and running: `pulumi package get-schema ./pulumi-resource-kafka | jq .version`

The changes to `ci-mgmt` are currently being rulled out to all providers: https://github.com/pulumi/ci-mgmt/actions/runs/9030462762.

Once the AWS PR build (https://github.com/pulumi/pulumi-aws/pull/3920) is finished and finally merged I'll kick off another release

**Comment by flostadler** [comment] 2024-05-10 10:14
We'll also have to re-release other providers that have been released since the versioning change (https://github.com/pulumi/ci-mgmt/pull/900) has been released.

From the list of tier 1 providers this should only be GCP (affected releases [v7.21.0](https://github.com/pulumi/pulumi-gcp/releases/tag/v7.21.0) and [v7.21.1](https://github.com/pulumi/pulumi-gcp/releases/tag/v7.21.1))

**Comment by danielrbradley** [comment] 2024-05-10 10:42
A side note during our discussions is that this was missed, in part due to us not testing the binaries that goreleaser builds. We build one binary at the begging of the workflow that we use for running tests then we throw that binary away and build brand new binaries for the release which we don't test. 

We should instead build the binaries to be released at the beginning of the workflow which we then use for testing - where we could add a simple regression test for fetching the schema - then we should release the binaries that we've tested. This requires replacing goreleaser - which is what we're building [pulumi/publish-go-binary-action](https://github.com/pulumi/publish-go-binary-action) for.

**Comment by t0yv0** [comment] 2024-05-10 13:02
Very unfortunate. To add to @danielrbradley suggestion here, the ci-mgmt or similar system needs end-to-end tests of publishing functionality including exercising the binaries and gate its own releases by that validation, then we'd be able to trust it before scaling out to AWS.

**Comment by flostadler** [comment] 2024-05-10 14:42
I also think we should add tests for things like the version being present and correct. This is essentially an API contract; and it's not tested right now

**Comment by t0yv0** [comment] 2024-05-10 17:39
In the meanwhile, please note the AWS version in which this is fixed and close 🙏

**Comment by flostadler** [comment] 2024-05-10 19:31
The release finally finished: https://github.com/pulumi/pulumi-aws/releases/tag/v6.34.1

Validation:
```
~ pulumi package get-schema aws@v6.34.1 | jq .version
"6.34.1"
```

**Closed** 2024-05-10 19:31 UTC
Labels: kind/bug, resolution/fixed, p1, impact/regression
