### ISSUE TITLE
output of UserPoolClient().id is not the same as required for UserPoolClient.get(id=), and different than UserPoolClient.get().id

### ISSUE THREAD

**Issue by sammck** [pulumi/pulumi-aws#2197] opened 2022-10-27 21:07 UTC
File: [themes/default/content/registry/packages/aws/api-docs/cognito/userpoolclient/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpoolclient/)

This is likely a bug in the terraform base, but it should be documented.

When a new UserPoolClient is created with UserPoolClient(), the "id" output is simply the client ID as it would be used by an authenticating client.

However, when attaching to an existing UserPoolClient with UserPoolClient.get(), the input id needs to be set to "\<user-pool-id\>/\<client-id\>". This also becomes the output value for "id", which is inconsistent with the value presented in the creating stack.

**Comment by viveklak** [comment] 2022-10-31 23:08
Thanks for opening the issue. Indeed, this is a reflection of the semantics of the terraform provider. We will use this issue to track updating the docs to make the distinction clear.

**Comment by lukehoban** [comment] 2022-12-28 00:36
This is now documented in the "Import" section of the docs.

https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpoolclient/#import

I've opened https://github.com/pulumi/pulumi/issues/11737 to track generally clarifying the id format for `.get` operations.  I'll close this as a dupe of that.

**Closed by lukehoban** 2022-12-28 00:36 UTC
Labels: area/docs, kind/enhancement, resolution/duplicate, area/api-docs
