### ISSUE TITLE
FSx -> EFS Documentation Typo

### ISSUE THREAD

**Issue by garrett-hopper** [pulumi/pulumi-aws#1603] opened 2021-08-19 17:35 UTC
I noticed in most of the EFS types, there's a reference to FSx for the `fileSystemId` property. (I specifically noticed this in the TypeScript types.)

https://github.com/pulumi/pulumi-aws/blob/86e3d6fc051753ae12890c0c775775a5d5dbe6c6/sdk/dotnet/Ecs/Outputs/TaskDefinitionVolumeEfsVolumeConfiguration.cs#L21

**Comment by lukehoban** [comment] 2022-12-28 00:03
This is another instance of the issue tracked in https://github.com/pulumi/pulumi-terraform-bridge/issues/529.

**Comment by lukehoban** [comment] 2022-12-28 00:15
Going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 to track the required work centrally.

**Closed by lukehoban** 2022-12-28 00:15 UTC
Labels: area/docs, kind/bug, resolution/duplicate
