### ISSUE TITLE
documentation is outdated and inaccurate for cognito userpool and elsewhere

### ISSUE THREAD

**Issue by nyck33** [pulumi/pulumi-aws#1663] opened 2021-10-12 07:23 UTC
https://www.pulumi.com/docs/reference/pkg/aws/cognito/userpool/

I am trying to do:
```
const cognitoUserPool = aws.cognito.UserPool.get(name: id:"arn:aws:cognito-idp:us-west-blahblahblah:userpool/us-west-2_blahblahblah")
```
but name gets crossed out because it is deprecated.
Also, I noticed that overall your documentation is confusing.
```
name This property is required.
    The unique name of the resulting resource.
id This property is required.
    The unique provider ID of the resource to lookup.
```
I may recall one time I used an ARN for an id field but in this case here, there is an id and ARN.
Would it be possible for your to tell me explicitly what each required field is called on AWS and perhaps update your documentation to do so everywhere rather than terms like "provider ID" which sounds generic.  

Thanks in advance,

**Comment by lukehoban** [comment] 2022-12-28 00:27
> They look like named parameters but there is no such thing in JS/TS as I found out here

This is due to https://github.com/pulumi/docs/issues/3351.

The other issues here are I believe all expected - the `.get` function takes a name and id parameter, and the ID must be the same ID format as the resource expects.  Exactly as shown in https://github.com/pulumi/pulumi-aws/issues/1663#issuecomment-941750005.  Closing as duplicate of https://github.com/pulumi/docs/issues/3351 for the original issue causing confusion here.

**Closed by lukehoban** 2022-12-28 00:27 UTC
Labels: area/docs, kind/bug, resolution/duplicate
