### ISSUE TITLE
Refresh with RDS MariaDB after restoring from DB snapshot deletes instance

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi-aws#2910] opened 2023-10-22 14:01 UTC
### What happened?

When you perform a `pulumi refresh` on a database created in RDS (a MariaDB instance) after you've restored it from a snapshot, it triggers a deletion.

### Example

Any Pulumi code that produces a MariaDB database can repro this.

But the following steps are important:
1. Take a snapshot of the created database.
2. Delete the database, so its name can be used for a restore.
3. Restore the snapshot into the database's name again, causing it to have the same name and endpoint as before.
4. Run a `pulumi refresh`. Now it'll detect the database as deleted, although it should pull from the new database instead.

### Output of `pulumi about`

CLI          
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       debian
Version  12.2
Arch     aarch64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.18.2'

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-10-24 21:19
Hi @ffMathy 

I believe the property `identifier` is used as a key lookup for RDS Instances. Do you know if `identifier` matched for two instances in your case?

**Comment by ffMathy** [comment] 2023-10-25 04:37
Identifier was not set, so identifierPrefix was generated automatically by the Pulumi resource name.

Switching to aws-native was a workaround.

**Comment by corymhall** [comment] 2024-04-12 15:09
@ffMathy I've not been able to reproduce this issue, it's possible that the underlying root cause has been fixed since you originally reported this issue. Here is what I have used to try and reproduce:


```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.Vpc("Vpc", {
  natGateways: { strategy: "Single" },
  subnetStrategy: "Auto",
});

const subnetGroup = new aws.rds.SubnetGroup("db-subnet-group", {
  subnetIds: vpc.privateSubnetIds,
})

const db = new aws.rds.Instance("db", {
  allocatedStorage: 20,
  engine: "mariadb",
  engineVersion: "10.11",
  autoMinorVersionUpgrade: true,
  instanceClass: aws.rds.InstanceType.T3_Micro,
  manageMasterUserPassword: true,
  username: "admin",
  dbSubnetGroupName: subnetGroup.name,
})
```

And I followed your steps:

1.     Take a snapshot of the created database.
2.     Delete the database, so its name can be used for a restore.
3.     Restore the snapshot into the database's name again, causing it to have the same name and endpoint as before.
4.     Run a pulumi refresh. Now it'll detect the database as deleted, although it should pull from the new database instead.

When I ran the refresh it pulled the new database and did not show a deletion.

**Comment by mjeffryes** [comment] 2024-05-03 21:43
@ffMathy Have you continued to see this behavior? I'm wondering if we should close this issue since it appears to work in the latest version or if there's something else we're missing in our attempts to reproduce it.

**Comment by mjeffryes** [comment] 2024-05-07 22:48
I'm going to close this out with no-repro for now, but happy to re-open if this you're still encountering this problem.

**Closed by mjeffryes** 2024-05-07 22:48 UTC
Labels: kind/bug, customer/feedback, resolution/no-repro, needs-repro, awaiting-feedback, area/refresh
