### ISSUE TITLE
Provide a way to pass in policies to mixins

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-aws#1486] opened 2021-05-11 21:48 UTC
Mixins such as `EventRuleEventSubscription` don't provide a convenient way to provide the set of policies to attach to the role. As a result, one must write additional boilerplate by creating a `CallbackFunction` as the handler and passing in those policies to that as opposed to being able to directly write the function inline and pass in additional arguments to the mixin for the policies to attach.

Today, one has to write the following:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const fn = new aws.cloudwatch.EventRuleEventSubscription("sub", "rule", 
new aws.lambda.CallbackFunction<aws.cloudwatch.EventRuleEvent, void>("callback", {
    callback: e => {
        ...
    },
    policies: [ ... ],
}));
```

versus the desired:

```typescript
const fn = new aws.cloudwatch.EventRuleEventSubscription("sub", "rule", 
    callback: e => {
        ...
    },
    { policies: [ ... ] },
);
```

**Comment by tenwit** [comment] 2021-05-11 23:31
Additionally, it is not possible to pass an `Output<string>[]` as the policies parameter, which is necessary for passing in custom policies. Even casting the `Output<string> as unknown as string` won't work, as `sha1hash()` is called and it checks the real type, throwing an exception when it detects `Output<string>`.

**Comment by leezen** [comment] 2021-05-12 00:02
Ah, thanks for pointing that out about `policies` -- a workaround for that would be to create the role yourself (and attach the relevant custom policies), then pass the role to the `CallbackFunction`

**Comment by lukehoban** [comment] 2022-12-24 16:30
> Additionally, it is not possible to pass an Output<string>[] as the policies parameter

This is tracked in https://github.com/pulumi/pulumi-aws/issues/995, which has been closed as a duplicate of https://github.com/pulumi/pulumi/issues/4834#issuecomment-644827733 in core Pulumi, since support for something like that would be needed before we could make a change here.

> Mixins such as EventRuleEventSubscription don't provide a convenient way to provide the set of policies to attach to the role. As a result, one must write additional boilerplate by creating a CallbackFunction as the handler and passing in those policies to that as opposed to being able to directly write the function inline and pass in additional arguments to the mixin for the policies to attach.

While this could be slightly nicer interface, it couples concerns that are a bit seperate.  Since you are allowed to pass either a callback or a `Function` to `callback`, and the `policies` argument could only be applied to the callback case.  It's also common in many other cases where you need to pass args (roles, policies, memory, etc.) to have to seperate these - and we don't want to explode all parameters to the callbackfunction back into everyone who accepts one of these.  

Going to close this as by design.

**Closed by lukehoban** 2022-12-24 16:30 UTC
Labels: kind/enhancement, resolution/by-design
