### ISSUE TITLE
Pulumi panic on pulumi up

### ISSUE THREAD

**Issue by aj-garcia05** [pulumi/pulumi-aws#1013] opened 2020-06-22 13:18 UTC
```
    panic: interface conversion: interface {} is []interface {}, not *schema.Set
    goroutine 143 [running]:
    github.com/terraform-providers/terraform-provider-aws/aws.setAutoscalingTags(0xc000010a40, 0xc0010d3500, 0x17, 0x4749900)
        /home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20200616201417-ed844a7bd9d5/aws/autoscaling_tags.go:83 +0xe49
    github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsAutoscalingGroupUpdate(0xc0010d3500, 0x4eacba0, 0xc00047af00, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20200616201417-ed844a7bd9d5/aws/resource_aws_autoscaling_group.go:939 +0x4b8
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000484900, 0xc000931ae0, 0xc000d53da0, 0x4eacba0, 0xc00047af00, 0x1, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:316 +0x263
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00049e180, 0xc000a6d818, 0xc000931ae0, 0xc000d53da0, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/provider.go:294 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc000692b60, 0x64cff00, 0xc000fd85a0, 0xc000ecc2a0, 0xc000692b60, 0x4e29901, 0xc000f95a80)
```

Hello all, I encountered this error above. 

I am not sure what happened but this script worked last week witout any issues

**Comment by stack72** [comment] 2020-06-22 13:25
Hi @aj-garcia05 

My apologies for this being the case - we believe that #1011 will take care of this issue but we are testing this right now. I will alert you to this issue being closed and the version of the provider it has been fixed in. We believe this will be fixed today (June 22, 2020)

If you want to be unblocked for now, you can remove the tags from the autoscaling group and your infrastructure will be deployed as expected :/ I am sorry for this being the case

Thanks

Paul

**Comment by aj-garcia05** [comment] 2020-06-22 13:30
I see. Thanks for responding quickly. I thought there is something wrong with my code. I'll try your fix. by the way, I hope this helps. This is the current npm packages that are being installed on my project.

And also, I'm using the latest version of pulumi. 2.4.0
```
        "@pulumi/aws": "^2.9.1",
        "@pulumi/awsx": "^0.20.0",
        "@pulumi/eks": "^0.19.0",
        "@pulumi/kubernetes": "^2.1.1",
        "@pulumi/pulumi": "^2.4.0",
        "@types/glob": "^7.1.1",
        "aws-sdk": "^2.658.0",
```

**Comment by stack72** [comment] 2020-06-22 13:33
Hi @aj-garcia05 

The issue is actually `pulumi/aws` - and has been broken for 2 of the releases but I didn't grok what the problem was until Friday and we are code reviewing the issue right now

P.

**Comment by aj-garcia05** [comment] 2020-06-22 13:44
I see. Thanks! I just rolled back to my previous version and it worked fine. Thanks for clarifying. :)

**Comment by stack72** [comment] 2020-06-22 13:45
I presume you may have been on pulumi-aws 2.6.x ?

**Comment by aj-garcia05** [comment] 2020-06-23 13:01
@stack72 sorry for the late response.
Yes. I was using 2.6 before the error happened.

**Closed** 2020-06-24 09:19 UTC
Labels: priority/P1
