### ISSUE TITLE
Incorrect description of aws.route53.Record type input

### ISSUE THREAD

**Issue by pierlucg-xs** [pulumi/pulumi-aws#1471] opened 2021-04-28 19:55 UTC
File: [themes/default/content/docs/reference/pkg/aws/route53/record.md](https://www.pulumi.com/docs/reference/pkg/aws/route53/record/)

In the `Inputs` section, `type` is defined as:
> PRIMARY or SECONDARY. A PRIMARY record will be served if its healthcheck is passing, otherwise the SECONDARY will be served. See http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring-options.html#dns-failover-failover-rrsets

however in the first example, we have
```ts
const www = new aws.route53.Record("www", {
    zoneId: aws_route53_zone.primary.zone_id,
    name: "www.example.com",
    type: "A", // <- Neither PRIMARY noor SECONDARY
    ttl: "300",
    records: [aws_eip.lb.public_ip],
});
```

My understanding is that type should be one of A, AAAA, CAA, CNAME, DS, MX, NAPTR, NS, PTR, SOA, SPF, SRV and TXT. 
(from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#type)

**Comment by stack72** [comment] 2022-06-15 11:57
Hi @pierlucg-xs 

I need to apologise for not getting back to this issue sooner! We need to do better here :/

I am going to close this out as a duplicate of #1315 and tell you that the underlying issue for this in https://github.com/pulumi/pulumi-terraform-bridge/issues/529 is currently being worked on

**Closed by stack72** 2022-06-15 11:57 UTC
Labels: kind/bug, resolution/duplicate
