### ISSUE TITLE
EC2 - Unable to import Instance

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws#1605] opened 2021-08-20 03:16 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Steps to reproduce

1. In AWS, create a new EC2 instance (and stop it eventually)
2. Create a new Pulumi project and stack (I used typescript) and set the region to the region used to create your EC2 instance
3. Run the following command to import the instance into your project `pulumi import aws:ec2/instance:Instance TestInstance i-0e122bd18c42c7373`

Expected: The resource is imported into the stack, TypeScript code is generated.
Actual: The command fails to complete. Output below.
```
~$ pulumi import aws:ec2/instance:Instance TestInstance i-0e122bd18c42c7373
Previewing import (dev)

View Live: <removed>

     Type                 Name               Plan       Info
 +   pulumi:pulumi:Stack  pulumi-import-dev  create     1 error
 =   └─ aws:ec2:Instance  TestInstance       import     4 errors
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-import-dev):
    error: preview failed
 
  aws:ec2:Instance (TestInstance):
    error: aws:ec2/instance:Instance resource 'TestInstance' has a problem: AtLeastOne: "instance_type": one of `instance_type,launch_template` must be specified. Examine values at 'Instance.InstanceType'.
    error: aws:ec2/instance:Instance resource 'TestInstance' has a problem: AtLeastOne: "launch_template": one of `ami,instance_type,launch_template` must be specified. Examine values at 'Instance.LaunchTemplate'.
    error: aws:ec2/instance:Instance resource 'TestInstance' has a problem: AtLeastOne: "ami": one of `ami,launch_template` must be specified. Examine values at 'Instance.Ami'.
    error: Preview failed: one or more inputs failed to validate
```

Environment:
* Debian 10 (up to date)
* Pulumi 3.10.2
* NodeJS v16.6.0
* Npm modules
```
pulumi-import@ /<removed>/pulumi-import
├── @pulumi/aws@4.16.0
├── @pulumi/awsx@0.30.0
├── @pulumi/pulumi@3.10.3
└── @types/node@10.17.60
```

**Comment by kxw9298** [comment] 2021-08-20 12:47
same issues here:
os: macos 11.5.2
pulumi:3.10.2
nodejs: 14.17.4
npm modules:
"@pulumi/aws": "^4.16.0",
    "@pulumi/awsx": "^0.30.0",
    "@pulumi/eks": "^0.30.0",
    "@pulumi/kubernetes": "^3.6.0",
    "@pulumi/pulumi": "^3.10.3",

**Comment by alexzaizar09** [comment] 2021-08-21 23:15
Same here, is there any advice?

**Comment by aureq** [comment] 2021-08-22 02:11
@alexzaizar09 Thank you for reporting this. Could you please include details about your environment please ?
- Os type and name
- Pulumi CLI version
- Pulumi app runtime (typescript, python, ...)
- A list of installed modules and their versions please

**Comment by alexzaizar09** [comment] 2021-08-22 16:31
Congratulations on your platform. This calls for a celebration! My team and
I are really looking forward to working with pulumi. We have used Ansible,
Terraform, CloudFormation, Docker, and many other tools. But being able to
use the same programming language is amazing.

We are currently using a Mac OS computer running OSX Big Sur, we have
installed pulumi through brew and we are using version 3.10.3. We are using
Python 3.9.6 as the runtime and the packages we are using are
pulumi>=3.0.0,<4.0.0, and pulumi-aws>=4.0.0,<5.0.0

It will be amazing if we can import all of our infrastructures from AWS
into a single python repo that can provide all the resources for the
different environments we will have. Thank you for your answer and hope to
hear from you soon.

**Comment by joeduffy** [comment] 2021-08-22 17:36
It appears that, although we read back all of the correct existing state:

```
I0822 11:17:34.078330    4452 provider_plugin.go:529] Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www) executing (#olds=36,#news=0
I0822 11:17:34.078372    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078383    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ami={ami-03e8f862f1241c4ed}
I0822 11:17:34.078389    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: associatePublicIpAddress={true}
I0822 11:17:34.078460    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: availabilityZone={us-east-1b}
I0822 11:17:34.078498    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: capacityReservationSpecification={map[__defaults:{[]} capacityReservationPreference:{open} capacityReservationTarget:{<nil>}]}
I0822 11:17:34.078548    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078556    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: capacityReservationPreference={open}
I0822 11:17:34.078562    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: capacityReservationTarget={<nil>}
I0822 11:17:34.078570    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: cpuCoreCount={1}
I0822 11:17:34.078578    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: cpuThreadsPerCore={1}
I0822 11:17:34.078584    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: creditSpecification={map[__defaults:{[]} cpuCredits:{standard}]}
I0822 11:17:34.078592    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078597    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: cpuCredits={standard}
I0822 11:17:34.078605    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: disableApiTermination={false}
I0822 11:17:34.078613    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ebsBlockDevices={[]}
I0822 11:17:34.078619    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ebsOptimized={false}
I0822 11:17:34.078624    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: enclaveOptions={map[__defaults:{[]} enabled:{false}]}
I0822 11:17:34.078632    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078638    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: enabled={false}
I0822 11:17:34.078643    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ephemeralBlockDevices={[]}
I0822 11:17:34.078648    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: getPasswordData={false}
I0822 11:17:34.078654    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: hibernation={false}
I0822 11:17:34.078659    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: iamInstanceProfile={}
I0822 11:17:34.078664    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: instanceInitiatedShutdownBehavior={stop}
I0822 11:17:34.078669    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: instanceType={t2.micro}
I0822 11:17:34.078684    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ipv6AddressCount={0}
I0822 11:17:34.078690    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: ipv6Addresses={[]}
I0822 11:17:34.078695    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: keyName={}
I0822 11:17:34.078700    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: launchTemplate={<nil>}
I0822 11:17:34.078705    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: metadataOptions={map[__defaults:{[]} httpEndpoint:{enabled} httpPutResponseHopLimit:{1} httpTokens:{optional}]}
I0822 11:17:34.078718    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078724    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: httpEndpoint={enabled}
I0822 11:17:34.078730    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: httpPutResponseHopLimit={1}
I0822 11:17:34.078735    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: httpTokens={optional}
I0822 11:17:34.078740    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: monitoring={false}
I0822 11:17:34.078745    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: networkInterfaces={[]}
I0822 11:17:34.078750    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: placementGroup={}
I0822 11:17:34.078755    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: privateIp={172.31.25.119}
I0822 11:17:34.078762    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: rootBlockDevice={map[__defaults:{[]} deleteOnTermination:{true} deviceName:{/dev/xvda} encrypted:{false} iops:{100} kmsKeyId:{} tags:{map[__defaults:{[]}]} throughput:{0} volumeId:{vol-0f47fde344e800966} volumeSize:{8} volumeType:{gp2}]}
I0822 11:17:34.078787    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078794    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: deleteOnTermination={true}
I0822 11:17:34.078799    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: deviceName={/dev/xvda}
I0822 11:17:34.078821    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: encrypted={false}
I0822 11:17:34.078836    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: iops={100}
I0822 11:17:34.078842    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: kmsKeyId={}
I0822 11:17:34.078847    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: tags={map[__defaults:{[]}]}
I0822 11:17:34.078856    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078862    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: throughput={0}
I0822 11:17:34.078868    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: volumeId={vol-0f47fde344e800966}
I0822 11:17:34.078874    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: volumeSize={8}
I0822 11:17:34.078879    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: volumeType={gp2}
I0822 11:17:34.078885    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: secondaryPrivateIps={[]}
I0822 11:17:34.078890    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: securityGroups={[{web-secgrp-5a62154}]}
I0822 11:17:34.078896    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: sourceDestCheck={true}
I0822 11:17:34.078901    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: subnetId={subnet-0fcc7069717899718}
I0822 11:17:34.078906    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: tags={map[__defaults:{[]}]}
I0822 11:17:34.078913    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: __defaults={[]}
I0822 11:17:34.078919    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: tenancy={default}
I0822 11:17:34.078924    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: userData={04e7e1694fd906e83f95cda782abde7d6d1289c6}
I0822 11:17:34.078929    4452 rpc.go:72] Marshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).olds]: vpcSecurityGroupIds={[{sg-076153e37b5d078df}]}
```

The only state that's used as an input during the subsequent `Check` call is the defaults from the provider. Notably, none of the required properties are in there, so it's no wonder this fails:

```
I0822 11:17:34.079802    4452 rpc.go:249] Unmarshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).inputs]: __defaults={[{getPasswordData} {sourceDestCheck}]}
I0822 11:17:34.079831    4452 rpc.go:249] Unmarshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).inputs]: getPasswordData={false}
I0822 11:17:34.079839    4452 rpc.go:249] Unmarshaling property for RPC[Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www).inputs]: sourceDestCheck={true}
I0822 11:17:34.079863    4452 provider_plugin.go:601] Provider[aws, 0xc000faf080].Check(urn:pulumi:dev::imprepo2::aws:ec2/instance:Instance::web-server-www) success: inputs=#3 failures=#3
I0822 11:17:34.079905    4452 eventsink.go:86] eventSink::Error(<{%reset%}>aws:ec2/instance:Instance resource 'web-server-www' has a problem: AtLeastOne: "ami": one of `ami,launch_template` must be specified. Examine values at 'Instance.Ami'.<{%reset%}>)
I0822 11:17:34.079931    4452 eventsink.go:86] eventSink::Error(<{%reset%}>aws:ec2/instance:Instance resource 'web-server-www' has a problem: AtLeastOne: "launch_template": one of `ami,instance_type,launch_template` must be specified. Examine values at 'Instance.LaunchTemplate'.<{%reset%}>)
I0822 11:17:34.079949    4452 eventsink.go:86] eventSink::Error(<{%reset%}>aws:ec2/instance:Instance resource 'web-server-www' has a problem: AtLeastOne: "instance_type": one of `instance_type,launch_template` must be specified. Examine values at 'Instance.InstanceType'.<{%reset%}>)
I0822 11:17:34.079974    4452 eventsink.go:86] eventSink::Error(<{%reset%}>Preview failed: one or more inputs failed to validate<{%reset%}>)
```

This is perplexing because plenty of other resources import just fine (like IAM Roles, which I just tested, and which notably have required properties that I would have thought would have suffered from this same problem).

This smells a bit like https://github.com/pulumi/pulumi/issues/7160 but I'm unsure.

**Comment by joeduffy** [comment] 2021-08-22 18:02
Unless I am mistaken, the root cause is this:

https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/resource/deploy/step.go#L935-L938

This limits the propagation of read properties to inputs based on `IsRequired`. There are plenty of non-required properties that are valid inputs. In this specific case, for example, I assume we can't tell from the schema alone that the AtLeastOne constraints exist which are dynamically validated.

I tried removing that line (since the iteration is already limited to input properties only), but that just yielded more problems:

```
    error: aws:ec2/instance:Instance resource 'web-server-www' has a problem: ConflictsWith: "network_interface": conflicts with associate_public_ip_address. Examine values at 'Instance.NetworkInterfaces'.
    error: aws:ec2/instance:Instance resource 'web-server-www' has a problem: Computed attributes cannot be set: Computed attributes cannot be set, but a value was set for "root_block_device.0.device_name".. Examine values at 'Instance.RootBlockDevice.DeviceName'.
    error: aws:ec2/instance:Instance resource 'web-server-www' has a problem: Computed attributes cannot be set: Computed attributes cannot be set, but a value was set for "root_block_device.0.volume_id".. Examine values at 'Instance.RootBlockDevice.VolumeId'.
    error: Preview failed: one or more inputs failed to validate
```

I think we may need to deeply strip out "empty" values like maps, arrays, etc, but it's even more complicated because they contain `__defaults` properties and I actually don't know why computed-only properties like `root_block_device` are in the input property set from the schema in the first place.

**Comment by alexzaizar09** [comment] 2021-08-22 21:31
I see, thank you for the time you have invested in this issue. Is there
anything we can do from our side?

**Comment by 0x1991babe** [comment] 2021-09-02 21:54
For lambdas I am running into the computed property issue. Since this information is available in the tf provider, it seems like there should be a way to thread this into either the schema or the property itself on read. However, I'm not sure how the codegen works. Right now I'm patching `pkg/resource/step.go` with something that strips out empty inputs and skips a hard coded list of computed properties. This works for me for now.

**Comment by sean-brady** [comment] 2021-11-09 18:33
Having the same issue here, and it's a showstopper for us. Anything we can do to work around this issue? We need to import our ec2 instances to move forward.

Please advise.

**Comment by tychedelia** [comment] 2021-11-10 02:08
> 
> 
> Having the same issue here, and it's a showstopper for us. Anything we can do to work around this issue? We need to import our ec2 instances to move forward.
> 
> Please advise.

This might not make you happy, but I was able to work around it like so: https://github.com/pulumi/pulumi/issues/7160#issuecomment-912093311

**Comment by mikhailshilkov** [comment] 2022-03-18 14:06
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).

**Closed by mikhailshilkov** 2022-03-18 14:06 UTC
Labels: kind/bug, resolution/fixed, area/import
