### ISSUE TITLE
eks-fargate cluster creation failing with coredns patch request

### ISSUE THREAD

**Issue by AishwaryaKhonde** [pulumi/pulumi-aws#2295] opened 2023-01-03 07:20 UTC
### Logs

[Test Report.txt](https://github.com/pulumi/pulumi-aws/files/10336115/Test.Report.txt)

### What happened?

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";
import * as k8s from "@pulumi/kubernetes";

//Create a VPC with private and public subnets in all AZ's of the region
const vpc = new awsx.ec2.Vpc("my-vpc",{
cidrBlock: "10.0.0.0/16",
numberOfAvailabilityZones: "all",
});

//Create an EKS cluster with the fargate configuration
const cluster = new eks.Cluster("my-eks-cluster",{
vpcId: vpc.id,
privateSubnetIds: vpc.privateSubnetIds,
fargate:true,

});

//Export the cluster kubeconfig
export const kubeconfig= cluster.kubeconfig

It is creating all the resource , but "coredns connection refused error while setting up kubernetes cluster"

### Steps to reproduce

[pulumi-eks.zip](https://github.com/pulumi/pulumi-eks/files/10335661/pulumi-eks.zip)
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";
import * as k8s from "@pulumi/kubernetes";

//Create a VPC with private and public subnets in all AZ's of the region
const vpc = new awsx.ec2.Vpc("my-vpc",{
    cidrBlock: "10.0.0.0/16",
    numberOfAvailabilityZones: "all",
});

//Create an EKS cluster with the fargate configuration
const cluster = new eks.Cluster("my-eks-cluster",{
    vpcId: vpc.id,
    privateSubnetIds: vpc.privateSubnetIds,
    fargate:true,
    
});

//Export the cluster kubeconfig
export const kubeconfig= cluster.kubeconfig

### Expected Behavior

To create a EKS-fargate cluster with coredns .

### Actual Behavior

coredns connection refused error while setting up kubernetes cluster
error: Error: Command failed: kubectl patch deployment coredns -n kube-system --type json -p='[{"op":"replace","path":"/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type","value":"fargate"}]'
Unable to connect to the server: net/http: TLS handshake timeout

### Output of `pulumi about`

CLI
Version      3.50.2  
Go Version   go1.19.4
Go Compiler  gc      

Plugins
NAME        VERSION
aws         5.25.0 
aws         5.16.2 
docker      3.6.1  
eks         1.0.1
kubernetes  3.23.1
nodejs      unknown

Host
OS       Microsoft Windows 10 Pro
Arch     x86_64

This project is written in nodejs: executable='C:\nodejs\node.exe' version='v18.12.1'

### Additional context

Hoping to solve this issue as soon as possible.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-01-05 20:03
duplicate of pulumi/pulumi-eks#843

**Closed by thomas11** 2023-01-05 20:03 UTC
Labels: kind/bug, resolution/duplicate
