### ISSUE TITLE
Feature Request: Global Config Values

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-aws#1052] opened 2020-07-29 19:14 UTC
I'd love to put values that are common across all stacks for a project in a central place (instead of copy/paste same value across several stack yaml files).

As an exaple, the CLI could take a -g (--global) flag so that `pulumi config set -g testvalue 12345` would create a config entry in the Pulumi.yaml file, instead of the currently selected stack's yaml file.

**Comment by leezen** [comment] 2020-07-29 19:17
Closing as a dupe of https://github.com/pulumi/pulumi/issues/2307 -- but please re-open if I've misunderstood.

**Closed** 2020-07-29 19:18 UTC
