### ISSUE TITLE
Creating SNS subscription fails 1.6.0

### ISSUE THREAD

**Issue by dbilleci-lightstream** [pulumi/pulumi-aws#779] opened 2019-10-23 19:27 UTC
````
$ pulumi version
v1.3.4
$ pulumi plugin ls
NAME   KIND      VERSION  SIZE    INSTALLED  LAST USED
aws    resource  1.6.0    220 MB  n/a        11 minutes ago

````

Using code:
````
const success_topic_name = `success2`
const success_topic = new aws.sns.Topic(success_topic_name, {
    name: success_topic_name
});

const success_topic_subscription_name = `success-email2`
const success_topic_subscription = new aws.sns.TopicSubscription(success_topic_subscription_name, {
    endpoint: "https://global.sns-api.chatbot.amazonaws.com",
    protocol: "HTTPS",
    topic: success_topic
});
````

Gives an error when ran:  https://pastebin.com/HARi8ZSN

Also, trying to pass in a full ARN as string, or using success_topic.arn as the input, both throw errors on autocomplete and `update` saying you can't use a string there, but the docs show you can:

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/sns/#example-usage-4
example from docs:
````
You can directly supply a topic and ARN by hand in the topicArn property along with the queue ARN:

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const userUpdatesSqsTarget = new aws.sns.TopicSubscription("userUpdatesSqsTarget", {
    endpoint: "arn:aws:sqs:us-west-2:432981146916:queue-too",
    protocol: "sqs",
    topic: "arn:aws:sns:us-west-2:432981146916:user-updates-topic",
});

Alternatively you can use the ARN properties of a managed SNS topic and SQS queue:

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const userUpdates = new aws.sns.Topic("userUpdates", {});
const userUpdatesQueue = new aws.sqs.Queue("userUpdatesQueue", {});
const userUpdatesSqsTarget = new aws.sns.TopicSubscription("userUpdatesSqsTarget", {
    endpoint: userUpdatesQueue.arn,
    protocol: "sqs",
    topic: userUpdates.arn,
});
````

Neither of these is working, both error out with:

````
`    error: Running program '/data/pulumi/infra/aws/company/company-step-functions' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(48,5): error TS2322: Type 'Output<string>' is not assignable to type 'Input<Topic>'.
      Type 'Output<string>' is not assignable to type 'OutputInstance<Topic>'.
        Types of property 'apply' are incompatible.
          Type '{ <U>(func: (t: string) => Promise<U>): Output<U>; <U>(func: (t: string) => OutputInstance<U>): Output<U>; <U>(func: (t: string) => U): Output<U>; }' is not assignable to type '{ <U>(func: (t: Topic) => Promise<U>): Output<U>; <U>(func: (t: Topic) => OutputInstance<U>): Output<U>; <U>(func: (t: Topic) => U): Output<U>; }'.
            Types of parameters 'func' and 'func' are incompatible.
              Types of parameters 't' and 't' are incompatible.
                Type 'string' is not assignable to type 'Topic'.
````

**Comment by pgavlin** [comment] 2020-02-12 00:59
@stack72 can you verify that the content of `resources.go` is correct here?

**Comment by stack72** [comment] 2020-02-12 01:29
I am not sure this is still an issue - I just tried the following (I didn't have a HTTPS endpoint to test this with) and it worked:

```
▶ pulumi up
Previewing update (dev):

     Type                          Name                        Plan
 +   pulumi:pulumi:Stack           sns-topic-subscription-dev  create
 +   ├─ aws:sns:Topic              success_topic_name          create
 +   ├─ aws:sqs:Queue              my-queue                    create
 +   └─ aws:sns:TopicSubscription  success-email2              create

Resources:
    + 4 to create

Do you want to perform this update? yes
Updating (dev):

     Type                          Name                        Status
 +   pulumi:pulumi:Stack           sns-topic-subscription-dev  created
 +   ├─ aws:sns:Topic              success_topic_name          created
 +   ├─ aws:sqs:Queue              my-queue                    created
 +   └─ aws:sns:TopicSubscription  success-email2              created

Resources:
    + 4 created

Duration: 20s
```

The code looks as follows:

```
import * as aws from "@pulumi/aws";

const success_topic = new aws.sns.Topic("success_topic_name", {
    name: "success2"
});

const queue = new aws.sqs.Queue("my-queue");

const success_topic_subscription = new aws.sns.TopicSubscription("success-email2", {
    endpoint: queue.arn,
    protocol: "sqs",
    topic: success_topic
});
```

Notice, I am still passing the topic to the TopicSubscription and it hasn't given the same panic

@dbilleci-lightstream I know we are coming back to you super late on this but is there any way you are still getting the same error as before using the latest version of the codebase?

**Comment by samirageb** [comment] 2020-02-12 04:17
@stack72 He's no longer at our company and his GH emails come to me. Just coming to this thread to close this loop.

**Comment by stack72** [comment] 2020-02-12 07:36
Ok thanks for that @samirageb 

Going to close this out as not able to reproduce

**Closed by stack72** 2020-02-12 07:36 UTC
Labels: kind/bug
