### ISSUE TITLE
Continuous refresh/replace cycle with ec2.Instance+ebs volume

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-aws#605] opened 2019-06-16 08:55 UTC
Hi,

After a refresh to a stack with an ec2 instance, and an ebs volume (without ebsBlockDevices on the instance), pulumi wants to replace the instance, then again after the next refresh, basically stuck in a cycle.

Versions:
```
➜  dliver-sandbox (volume) pulumi version
v0.17.16
➜  dliver-sandbox (volume) pulumi plugin ls
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
aws         resource  0.18.10  204 MB  n/a        2 hours ago
aws         resource  0.17.1   157 MB  n/a        2 months ago
cloudflare  resource  0.17.3   40 MB   n/a        4 days ago
cloudflare  resource  0.17.1   40 MB   n/a        1 month ago
kubernetes  resource  0.24.0   53 MB   n/a        2 hours ago
kubernetes  resource  0.21.1   45 MB   n/a        2 months ago
random      resource  0.5.3    36 MB   n/a        1 day ago
random      resource  0.5.2    36 MB   n/a        1 month ago
random      resource  0.5.1    28 MB   n/a        2 months ago
```

Steps to reproduce:
1. Download the sample repo: https://gitlab.com/proemergotech-public/pulumi-sandbox/tree/volume
2. `yarn install` from the root
3. cd dliver-sandbox, then `pulumi up`
4. `pulumi refresh`, sample details:
```
➜  dliver-sandbox (volume) ✗ pulumi refresh 
Previewing refresh (pul-sbx):

     Type                                 Name                                  Plan           
     pulumi:pulumi:Stack                  dliver-sandbox-pul-sbx                               
     ├─ network:Vpc                       pul-sbx                                              
     │  ├─ aws:ec2:Vpc                    pul-sbx-vpc                                      
     │  ├─ aws:efs:FileSystem             pul-sbx-efs                                      
     │  ├─ aws:ec2:Eip                    pul-sbx-eip-1                                    
     │  ├─ aws:ec2:InternetGateway        pul-sbx-igw                                      
     │  ├─ aws:ec2:Eip                    pul-sbx-eip-0                                    
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-public-1                          
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-public-0                          
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-private-0                         
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-fixedIp-1                         
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-private-1                         
     │  ├─ aws:ec2:Subnet                 pul-sbx-subnet-fixedIp-0                         
     │  ├─ aws:ec2:NatGateway             pul-sbx-nat-1                                    
     │  ├─ aws:ec2:SecurityGroup          pul-sbx-securityGroup-efs                        
     │  ├─ aws:ec2:RouteTable             pul-sbx-routeTable-public                        
     │  ├─ aws:ec2:RouteTable             pul-sbx-routeTable-nat-1                         
     │  ├─ aws:ec2:NatGateway             pul-sbx-nat-0                                    
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-public-1                             
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-fixedIp-1                        
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-public-0                             
     │  ├─ aws:ec2:RouteTable             pul-sbx-routeTable-nat-0                         
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-private-0                        
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-private-1                        
     │  ├─ aws:ec2:VpcEndpoint            pul-sbx-s3-vpcEndpoint                           
     │  ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-fixedIp-0                        
     │  ├─ aws:efs:MountTarget            pul-sbx-mountTarget-efs-0                        
     │  └─ aws:efs:MountTarget            pul-sbx-mountTarget-efs-1                        
     ├─ aws:iam:Role                      pul-sbx-role                                     
     ├─ aws:iam:InstanceProfile           pul-sbx-instanceProfile                          
     ├─ aws:ebs:Volume                    pul-sbx-content                        
     ├─ aws:ec2:VolumeAttachment          pul-sbx-content-attachment             
 ~   └─ aws:ec2:Instance                  pul-sbx-node                          update     [diff: ~ebsBlockDevices,volumeTags]
 
Resources:
    ~ 1 to update
    32 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pul-sbx::dliver-sandbox::pulumi:pulumi:Stack::dliver-sandbox-pul-sbx]
    ~ aws:ec2/instance:Instance: (update)
        [id=i-004e7c58f303932a4]
        [urn=urn:pulumi:pul-sbx::dliver-sandbox::aws:ec2/instance:Instance::pul-sbx-node]
        --outputs:--
        ami                      : "ami-0e82e73403dd69fa3"
        arn                      : "arn:aws:ec2:eu-west-1:615622277724:instance/i-004e7c58f303932a4"
        associatePublicIpAddress : false
        availabilityZone         : "eu-west-1a"
        cpuCoreCount             : 1
        cpuThreadsPerCore        : 2
        creditSpecification      : {
            cpuCredits: "unlimited"
        }
        disableApiTermination    : false
      ~ ebsBlockDevices          : [
          + [0]: {
                  + deleteOnTermination: false
                  + deviceName         : "/dev/xvdb"
                  + encrypted          : false
                  + iops               : 100
                  + volumeId           : "vol-0002cb05612713785"
                  + volumeSize         : 10
                  + volumeType         : "gp2"
                }
        ]
        ebsOptimized             : false
        getPasswordData          : false
        iamInstanceProfile       : "pul-sbx-instanceProfile-49d0768"
        id                       : "i-004e7c58f303932a4"
        instanceState            : "running"
        instanceType             : "t3.small"
        ipv6AddressCount         : 0
        monitoring               : false
        primaryNetworkInterfaceId: "eni-0595a28269dbfbedf"
        privateDns               : "ip-10-151-0-171.eu-west-1.compute.internal"
        privateIp                : "10.151.0.171"
        rootBlockDevice          : {
            deleteOnTermination: true
            iops               : 100
            volumeId           : "vol-0c53253420f6f2076"
            volumeSize         : 10
            volumeType         : "gp2"
        }
        sourceDestCheck          : true
        subnetId                 : "subnet-0b016a7a0b7a09d84"
        tags                     : {
            Name: "test-node"
        }
        tenancy                  : "default"
      ~ volumeTags               : {
          + Name: "content"
        }
        vpcSecurityGroupIds      : [
            [0]: "sg-0702e41bae7fff84b"
        ]
```
5. `pulumi up` again:
```
➜  dliver-sandbox (volume) pulumi up     
Previewing update (pul-sbx):

     Type                         Name                        Plan        Info
     pulumi:pulumi:Stack          dliver-sandbox-pul-sbx                  
 +-  ├─ aws:ec2:Instance          pul-sbx-node                replace     [diff: -associatePublicIpAddress,availabilityZone,cpuCoreCount,cpuThreadsPerCore,ebsBlockDevices,ephemeralBlockDevices,ipv6AddressCou
 +-  ├─ aws:ebs:Volume            pul-sbx-content             replace     [diff: -iops,kmsKeyId,snapshotId~availabilityZone]
 +-  └─ aws:ec2:VolumeAttachment  pul-sbx-content-attachment  replace     [diff: ~instanceId,volumeId]
 
Resources:
    +-3 to replace
    30 unchanged

```
6. Restart the refresh/update cycle, same thing will happen

Plus in the preview shows the Volume as a replace too, but it does not replace it during the update.

**Comment by lukehoban** [comment] 2019-06-16 17:05
If you are able to provide the output of `pulumi up —logtostderr -v=9 2> out.txt`, or at least the lines containing `replaces=` from that output - that would be helpful to diagnose further.

**Comment by ncsibra** [comment] 2019-06-16 17:50
Sure, here's the logs.
[refresh_update.tar.gz](https://github.com/pulumi/pulumi-aws/files/3294394/refresh_update.tar.gz)

**Comment by stack72** [comment] 2019-06-26 12:45
Hi @ncsibra 	

My apologies for this issue. I have been able to replicate it perfectly and remember it well. The issue is that you are using an EBS volume (via rootBlockDevice which is a BlockDevice under the hood according to AWS) as part of the Instance **AND** an additional EBS Volume. This is something that cannot be supported:

```
NOTE on EBS block devices: If you use ebs_block_device on an aws_instance, Terraform will assume management over the full set of non-root EBS block devices for the instance, and treats additional block devices as drift. For this reason, ebs_block_device cannot be mixed with external aws_ebs_volume + aws_ebs_volume_attachment resources for a given instance.
```

Unfortunately, there is no way to counter the continual drift here... I'd love to hear your thoughts on this. The only way to allow this to continue would be to to remove the root_block_device from the AWS Instance and then things will be normal

Paul

**Comment by ncsibra** [comment] 2019-06-26 13:10
I saw this comment, but it says `ebs_block_device`, not `root_block_device` and `Terraform will assume management over the full set of non-root EBS block devices for the instance` suggest that it only a problem with `ebs_block_device`, are you sure that's the case here too?

**Comment by stack72** [comment] 2019-06-26 13:22
mmmhhhhh so it should be the case - but I can dig in further! Thanks for bearing with me on this one!

**Comment by ncsibra** [comment] 2019-07-25 08:37
Now we updated one of our stacks, removed both rootBlockDevices and ebsBlockDevices from the aws.ec2.Instance resource and only attaching 1 ebs volume separately and we still have the same issue with the current latest libraries and cli, after a refresh pulumi wants to recreate the ec2 instance.

**Comment by danielrbradley** [comment] 2023-03-06 12:37
Just revisiting this issue from the backlog. I've got the example repo up and running on the `volume` branch. Having updated aws to `v5.30.0` the problem still exists. It's quite simply fixed by replacing the `ec2.Instance` property `securityGroups` for `vpcSecurityGroup`

```diff
-    securityGroups: [vpc.vpc.defaultSecurityGroupId],
+    vpcSecurityGroupIds: [vpc.vpc.defaultSecurityGroupId],
```

The next step is to establish why both properties exist. The original `securityGroups` only appears as an input, but there's no corresponding output by the same name which is likely why it sees it as a continuous addion - because it was not recorded in the state so it always appears to be an addition.

**Comment by danielrbradley** [comment] 2023-03-06 13:29
Reading through the docs, it appears that `securityGroupIds` is only for use with EC2-Classic and default VPC only and in this instance updating the code to use `vpcSecurityGroupIds` is the correct fix.

Therefore, I'm going to close this issue as resolved. Please do comment back it you think this needs re-opening, or file a new issue. Thanks!

**Closed by danielrbradley** 2023-03-06 13:29 UTC
Labels: kind/bug, area/providers, resolution/fixed
