### ISSUE TITLE
Failed Pulumi update just shows 403 Access Denied and not IAM error

### ISSUE THREAD

**Issue by ctwise** [pulumi/pulumi-aws#907] opened 2020-03-24 15:43 UTC
The code is attempting to create an API Gateway REST interface and it fails w/an Access Denied. When I look in CloudTrail I can see that it was because I didn't have permission on the '/restapis' resource. I would like to see the actual IAM failure and not just a 403.

Ouput seen:

'''
error: update failed
 
proxy (aws:apigateway:x:API$aws:apigateway/restApi:RestApi)
error: Error creating API Gateway: AccessDeniedException: 
	status code: 403, request id: xxxd7e62-cf5e-xxx5-a4f5-a7f00af4exxx
'''

**Comment by maxcan** [comment] 2021-09-17 13:54
did you resolve this?  haven't a similar issue now just running the AWS getting started tutorial

**Comment by bajtos** [comment] 2021-11-08 10:23
I am seeing the same problem when creating a Lambda function too:

```
  aws:lambda:Function (some-fn-name):
    error: 1 error occurred:
    	* error creating Lambda Function (1): AccessDeniedException:
    	status code: 403, request id: 470b4118-6237-43b7-b6de-9a815ab4cf66
```

**Comment by bajtos** [comment] 2021-11-08 10:32
Enabling verbose logs did not help either :(

Here is the relevant part of the log, cleaned up a bit for better readability. (I removed first three columns from each log item.)

```
TF_TRACE=DEBUG pulumi up --yes -v=9 --logtostderr
(...)
eventsink.go:59] Unlocking "aws_lambda_function"
eventsink.go:62] eventSink::Debug(<{%reset%}>Unlocking "aws_lambda_function"<{%reset%}>)
eventsink.go:59] Unlocked "aws_lambda_function"
eventsink.go:62] eventSink::Debug(<{%reset%}>Unlocked "aws_lambda_function"<{%reset%}>)
provider_plugin.go:1531] provider received rpc error `Unknown`: `1 error occurred:
	* error creating Lambda Function (1): AccessDeniedException:
	status code: 403, request id: 470b4118-6237-43b7-b6de-9a815ab4cf66

`
provider_plugin.go:1534] rpc error kind `Unknown` may not be recoverable
provider_plugin.go:760] Provider[aws, 0xc001b627e0].Create(urn:pulumi:dev::myproject::aws:lambda/function:Function::mylambda) failed: 1 error occurred:
	* error creating Lambda Function (1): AccessDeniedException:
	status code: 403, request id: 470b4118-6237-43b7-b6de-9a815ab4cf66

eventsink.go:86] eventSink::Error(<{%reset%}>1 error occurred:
	* error creating Lambda Function (1): AccessDeniedException:
	status code: 403, request id: 470b4118-6237-43b7-b6de-9a815ab4cf66
```

Compare the output above with the error printed when creating e.g. a RolePolicyAttachment:

```
  aws:iam:RolePolicyAttachment (somename-a1de8170):
    error: 1 error occurred:
    	* Error attaching policy arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess to IAM Role somename-f746d02: 
    	  AccessDenied: User: arn:aws:sts::123456789064:assumed-role/SomeRole/1234567890 is not 
          authorized to perform: iam:AttachRolePolicy on resource: role somename-f746d02
    	status code: 403, request id: 7e4ffe5f-001a-4b0a-810c-9116c4e254f4
```

This error message makes it very clear that I need to grant `iam:AttachRolePolicy` to my user/role.

Is there any workaround how to get the same error detail when creating Lambda and API Gateway RestApi resources, using the current Pulumi version?

**Comment by bajtos** [comment] 2021-11-08 10:39
I managed to find error details via AWS CloudTrail ✌🏻

**Comment by bajtos** [comment] 2021-11-09 15:24
Re-posting from https://twitter.com/briggsl/status/1457844512131149825:

> The reason you get a 403 instead of the permission error is an AWS implementation. We simply return the value the AWS API returns to you.
>
> With regards to the base permissions to deploy a lambda, unfortunately, the ways you can implement lambda functions and the assume role permissions is a very wide problem scope. I've seen lots of people have success using iamlive during dev: https://github.com/iann0036/iamlive

**Comment by maxcan** [comment] 2021-11-09 15:38
Cloudtrail was what helped me too.

But, I wish there was a way to just have Pulumi output the AWS API calls its making and the response codes.  It would be **so** much easier to diagnose IAM issues if you could just see the exact API call and argument that failed.

**Comment by lukehoban** [comment] 2022-12-28 05:19
> But, I wish there was a way to just have Pulumi output the AWS API calls its making and the response codes. It would be so much easier to diagnose IAM issues if you could just see the exact API call and argument that failed.

You can do this using the instructions in this guide: https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging.  Unfortunately, even those logs likely don't have complete information - AWS is somewhat limited in how much context it provides on why it didn't allow access in many cases.

As noted above, the AccessDeniedExceptions are not directly related to Pulumi, but to a combination of AWS requirements and user code configuration.  

Given those, I'll close this out as By Design.

**Closed by lukehoban** 2022-12-28 05:19 UTC
Labels: kind/enhancement, impact/usability, resolution/by-design
