### ISSUE TITLE
Perpetual diff in EBS volume attachment since v1.1.0

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-aws#747] opened 2019-09-16 16:41 UTC
From the community slack:

```
Since the v1.1.0 upgrade pulumi up always detects a change in an EBS volume attachment though nothing changed:
$ pulumi up
Previewing update (acmecorp-demo):

     Type                                                 Name                           Plan        Info
     pulumi:pulumi:Stack                                  private-cloud-acmecorp-demo              
 +-  ├─ aws:ec2:Instance                                  services                       replace     [diff: ~ebsBlockDevices]
     ...

Resources:
    +-8 to replace
    156 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:acmecorp-demo::private-cloud::pulumi:pulumi:Stack::private-cloud-acmecorp-demo]
    ++aws:ec2/instance:Instance: (create-replacement)
        [id=i-0eba90d7bd7c11af4]
        [urn=urn:pulumi:acmecorp-demo::private-cloud::aws:ec2/instance:Instance::services]
        [provider=urn:pulumi:acmecorp-demo::private-cloud::pulumi:providers:aws::default_0_18_27::4e650a8e-8d3d-4c3c-a9d1-b31c8638bd95]
      ~ ebsBlockDevices: [
          ~ [0]: {
                  ~ deleteOnTermination: true => true
                  ~ deviceName         : "/dev/sdf" => "/dev/sdf"
                  + encrypted          : true
                  + volumeSize         : 100
                  + volumeType         : "gp2"
                }
        ]
    +-aws:ec2/instance:Instance: (replace)
        [id=i-0eba90d7bd7c11af4]
        [urn=urn:pulumi:acmecorp-demo::private-cloud::aws:ec2/instance:Instance::services]
        [provider=urn:pulumi:acmecorp-demo::private-cloud::pulumi:providers:aws::default_0_18_27::4e650a8e-8d3d-4c3c-a9d1-b31c8638bd95]
      ~ ebsBlockDevices: [
          ~ [0]: {
                  ~ deleteOnTermination: true => true
                  ~ deviceName         : "/dev/sdf" => "/dev/sdf"
                  + encrypted          : true
                  + volumeSize         : 100
                  + volumeType         : "gp2"
                }
        ]
```

Code:

```ts
export const servicesInstance = new aws.ec2.Instance("services", {
    ami: "xxxxxx",
    ebsOptimized: true,
    ebsBlockDevices: [{
        deviceName: "/dev/sdf",
        encrypted: true,
        volumeSize: 100,
        volumeType: "gp2",
    }],
    ...
```

**Comment by stack72** [comment] 2019-09-30 15:48
From the following code:

```
import * as aws from "@pulumi/aws";

const instance = new aws.ec2.Instance("my-instance", {
    ami: "ami-55a7ea65",
    instanceType: aws.ec2.InstanceTypes.M3_Medium,
    ebsBlockDevices: [{
        deviceName: "/dev/sdf",
        volumeSize: 100,
        encrypted: true,
        volumeType: "gp2",
        deleteOnTermination: true,
    }]
});

```

I was able to get this:

```
$ pulumi up
Previewing update (dev):

     Type                 Name            Plan
 +   pulumi:pulumi:Stack  aws-gh-747-dev  create
 +   └─ aws:ec2:Instance  my-instance     create

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev):

     Type                 Name            Status
 +   pulumi:pulumi:Stack  aws-gh-747-dev  created
 +   └─ aws:ec2:Instance  my-instance     created

Resources:
    + 2 created

Duration: 39s
```

Another pulumi up showed no changes required:

```
$ pulumi up
Previewing update (dev):

     Type                 Name            Plan
     pulumi:pulumi:Stack  aws-gh-747-dev

Resources:
    2 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws-gh-747::pulumi:pulumi:Stack::aws-gh-747-dev]
```

This is using Pulumi v1.2.0

I am going to close this out as I can't reproduce it - if there is any other occurrences of it, then we can reopen it

**Closed by stack72** 2019-09-30 15:48 UTC

**Comment by zvikagart** [comment] 2019-10-03 11:45
This still happens to me (with same output [as originally posted](https://github.com/pulumi/pulumi-aws/issues/747#issue-494159609)).

One thing I can think of is that I'm creating an instance with encrypted EBS volume from a source AMI where the `/dev/sdf` EBS volume is not encrypted.

**Comment by stack72** [comment] 2019-10-03 12:00
Hi @zvikagart 

That is indeed the issue - the AMI will not be able to be marked as ebs_optimized and thus will always show it has to change

Paul
