### ISSUE TITLE
aws.networkfirewall.FirewallPolicy page renders weird

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-aws#2259] opened 2022-12-11 18:22 UTC
### What happened?

Looking at https://www.pulumi.com/registry/packages/aws/api-docs/networkfirewall/firewallpolicy/:

There's a Java example at the top of the page with no tabs: 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/410614/206921430-f9609c32-8531-45cb-ac86-e26c29e203d1.png">

It's followed by the same example in YAML.

### Steps to reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment] 2022-12-15 15:23
Definitely something funny going on with the docs generation there. The source material, as fished out of provider/cmd/pulumi-resource-aws/schema.json, doesn't have the same heading nesting as other examples. In particular, it has a `## Policy with a Custom Action for Stateless Inspection` outside an `{{% examples }}` block.

**Comment by lukehoban** [comment] 2023-03-01 15:46
We’re tracking the underlying issue in https://github.com/pulumi/registry/issues/1401.  Will close this out as a duplicate of that.

**Closed by lukehoban** 2023-03-01 15:46 UTC
Labels: area/docs, kind/bug, resolution/duplicate, area/api-docs
