### ISSUE TITLE
Change in field names of the ProviderAssumeRole for Python

### ISSUE THREAD

**Issue by chriskauffman** [pulumi/pulumi-aws#2291] opened 2022-12-28 17:16 UTC
### What happened?

3.35.3 was accepting ProviderAssumeRole field names of `role_arn` and `session_name`. 3.50.2, now requires `roleArn` and `sessionName`. In 3.50.2, if `role_arn` and `session_name` are used an error is received on preview: `error: unable to validate AWS credentials. Details: Assume Role: role ARN not set`.

I am wondering if this commit https://github.com/pulumi/pulumi-aws/commit/60235e34797bc929e71d30c091e5dc4e2c98cdc1 changed the field names of the ProviderAssumeRole for Python.

### Steps to reproduce

In Python, create a provider with assume_role such as:
```
aws.Provider(
            "testProvider",
            region="us-east-2",
            assume_role={
                "role_arn": f"arn:aws:iam::{aws_account_id}:role/OrganizationAccountAccessRole",
                "session_name": "Pulumi",
            },
)
```

Try using provider in 3.35.3: Success!
Try using provider in 3.50.2: Fails with "error: unable to validate AWS credentials. Details: Assume Role: role ARN not set"

In 3.50.2 code must be rewritten as:
```
aws.Provider(
            "testProvider",
            region="us-east-2",
            assume_role={
                "roleArn": f"arn:aws:iam::{aws_account_id}:role/OrganizationAccountAccessRole",
                "sessionName": "Pulumi",
            },
)
```

### Expected Behavior

ProviderAssumeRole field names are backwards compatible.

### Actual Behavior

error: unable to validate AWS credentials. Details: Assume Role: role ARN not set

### Output of `pulumi about`

CLI          
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.25.0
python  unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in python: executable='/Users/ckauffman/Projects/vollgas-pulumi-bootstrap/venv/bin/python3' version='3.10.9
'

Current Stack: chriskauffman/vollgas-pulumi-bootstrap/vollgas

TYPE                                                 URN

Found no pending operations associated with vollgas

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/chriskauffman
User           chriskauffman
Organizations  chriskauffman

Dependencies:
NAME            VERSION
black           22.12.0
flake8          6.0.0
pip             22.3.1
pulumi-aws      5.25.0
pylint          2.15.9
setuptools      65.6.3
vollgas-config  0.2.3
wheel           0.38.4

Pulumi locates its logs in /var/folders/5j/wxysv5ls7tdc1qttnlw0qj800000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by chriskauffman** [comment] 2022-12-28 17:18
I was using pulumi_aws 5.9.2 with Pulumi 3.35.3.

**Comment by Zaid-Ajaj** [comment] 2022-12-28 19:51
Hi there @chriskauffman, looking at the code I think the issue is in using an untyped dictionary to specify the inputs for `assume_role` rather than using the typed `ProviderAssumeRoleArgs` that `assume_role` expects from the type definition which deals with python specific casing internally:
```python
aws.Provider(
            "testProvider",
            region="us-east-2",
            assume_role=aws.ProviderAssumeRoleArgs(
                role_arn=f"arn:aws:iam::{aws_account_id}:role/OrganizationAccountAccessRole",
                session_name="Pulumi",
            ),
)
```
Can you please give this a try and see if it solves your issue?

**Comment by chriskauffman** [comment] 2022-12-28 21:17
Thanks @Zaid-Ajaj. With the changes you suggested my code now works. This makes two working solutions. One using `roleArn` and `sessionName` and one using the typed `ProviderAssumeRoleArgs`. I didn't understand that it needed to be typed. My code must have only been working by accident in previous versions.

**Comment by Zaid-Ajaj** [comment] 2022-12-28 22:44
> With the changes you suggested my code now works

Glad to hear that!

> My code must have only been working by accident in previous versions.

That is very possible: when inputs are not typed, they are sent to the engine _as is_ without preprocessing. The inputs you had were in the format that the provider expected. 

> I didn't understand that it needed to be typed

When in doubt, look at the type annotations of the resources 😄 

That said, I'll consider your issue resolved and close the issue. If you have more questions, don't hesitate to open another issue here or talk to us on the Pulumi community slack.

**Closed by Zaid-Ajaj** 2022-12-28 22:44 UTC
Labels: kind/bug, resolution/fixed
