### ISSUE TITLE
Hash failure is completely hidden

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi-aws#1409] opened 2021-03-17 20:16 UTC
I pointed to a file instead of an archive, and that caused a hash failure, but Pulumi never surfaced the failure to me.

From grepping debug logging:

`I0317 20:03:21.201805     860 eventsink.go:59] RegisterResource RPC finished: resource:my-lambda[aws:lambda/function:Function]; err: Error: 2 UNKNOWN: f
ailed to compute archive hash: '/opt/infrastructure/src/lambda/main.py' is neither a recognized archive type nor a director
y, resp: undefined`

## Expected behavior

Pulumi should surface the failure.

## Current behavior

Pulumi looks like it simply ignores the failure and says everything is fine, but of course the resource is not created. This is very confusing as it looks like Pulumi just isn't running the code.

## Steps to reproduce

```typescript
const lambdaZip = new pulumi.asset.FileArchive(
  `${srcFolder}/lambda/main.py`
);

const myLambda = new aws.lambda.Function(
  "my-lambda,
  {
    code: lambdaZip,
    description: "Lambda",
    role: lambdaRole.arn,
    handler: "main.lambda_handler",
    runtime: "python3.8",
    timeout: 30,
  }
);
```

## Context (Environment)

Trying to create a Lambda from a local Python file, a pattern I am already using in the same codebase without issue on a different Lambda.

**Comment by austinbutler** [comment] 2021-03-17 23:30
Actually this may be a duplicate of https://github.com/pulumi/pulumi/issues/5577.

**Comment by viveklak** [comment] 2021-03-18 17:47
Closing duplicate of https://github.com/pulumi/pulumi/issues/5577

**Closed by viveklak** 2021-03-18 17:47 UTC
Labels: resolution/duplicate
