### ISSUE TITLE
Stack acquiring ownership over foreign resources (f.e. s3 bucket)

### ISSUE THREAD

**Issue by jasminen** [pulumi/pulumi-aws#770] opened 2019-10-16 15:51 UTC
Found what seems to be a critical bug in creating s3 buckets (although not sure yet if it only happens on s3 buckets). When creating a bucket that already exists (was created manually or created by a different pulumi stack) pulumi will show 'created' and the stack will now reference that already existing bucket. Meaning we can have the same s3 bucket managed by different stacks.

Expected behaviour: 
Pulumi should fail creating an already existing bucket (that is not managed by this stack).

Steps to reproduce:
Create 2 stacks with the same s3 bucket: 
`new aws.s3.Bucket('test', { bucket: 'some-unique-name' })`
Run the first. Run the second. See stack resources are pointing to the same bucket.

Pulumi CLI version: 1.3.1, Pulumi SDK (Node) version: 1.2.0, Pulumi AWS version: 1.5.0

**Comment by lukehoban** [comment] 2019-10-16 16:20
This appears to be due to https://github.com/terraform-providers/terraform-provider-aws/issues/3307, which is ultimately due to a [backward compatibility setting in only the `us-east-1` region of AWS](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList).  I confirmed that this does not repro in other regions.

> The bucket you tried to create already exists, and you own it. Amazon S3 returns this error in all AWS Regions except us-east-1 (N. Virginia). For legacy compatibility, if you re-create an existing bucket that you already own in us-east-1, Amazon S3 returns 200 OK and resets the bucket access control lists (ACLs).

It's theoretically possible this could be fixed in the upstream provider via the issue linked above - but may be that this cannot be fixed correctly without a breaking change to the AWS API.

**Closed by lukehoban** 2019-10-16 16:20 UTC
