### ISSUE TITLE
sqsMixins `onEvent` should provide an easy way to change lambda settings

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-aws#2180] opened 2022-10-17 17:36 UTC
It would be nice if there was an easy way to set properties of the lambda like timeout when using the following form:

```
queue.onEvent("reaper-queue-processor", async (e) => {...});
```

Especially because the default SQS timeout of 30 seconds is shorter than the lambda timeout of 180. This throws an error unless you explicitly change the visibility timeout on your queue:

```
const queue = new aws.sqs.Queue("reaper-queue", {
    visibilityTimeoutSeconds: 181, // TODO: tighten this up as well as lambda timeout
});
```

**Comment by guineveresaenger** [comment] 2022-10-19 21:56
Thanks for filing this!

Just for confirmation, we're talking about the [Typescript mixin for SQS](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/sqs/sqsMixins.ts#L128) here, correct?

**Comment by EvanBoyle** [comment] 2022-10-21 21:42
@guineveresaenger Yes!

**Comment by EvanBoyle** [comment] 2022-10-21 22:49
This would be nice for all of the lambda mixins. I hit this again today for cloudwatch scheduled lambdas:

```ts
 aws.cloudwatch.onSchedule("drift-lambda", schedule, async() => {
...
```

**Comment by lukehoban** [comment] 2022-10-21 23:09
Note that you can factor this into:

```ts
const f = new CallbackFunction({ callback: () => … })
 onSchedule(f)
```

The version you used above is just shorthand for this. 

The way that we support specifying all the Function parameters is via this more general form. 

I do not expect we would want to in-line the entire set of Function parameters into every place where we allow callbacks to be passed.

Instead, our design approach is to ensure that any place you can provide a callback in-line, you can also provide a `Function` constructed explicitly.

**Comment by lukehoban** [comment] 2024-07-17 03:31
Closing this as by design based on the previous reply.

**Closed by lukehoban** 2024-07-17 03:31 UTC
Labels: kind/enhancement, resolution/by-design, area/overlays, service/sqs
