### ISSUE TITLE
If no "region" is set anywhere, pulumi up throws error message: unable to validate AWS credentials 

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#2084] opened 2022-08-11 17:36 UTC
### What happened?

I did a `pulumi up` in an environment where no region was set.
I.e. it is not set via any of the mechanisms described here: https://www.pulumi.com/registry/packages/aws/installation-configuration/ 

I received this error message: 
```
Diagnostics:
  aws:ec2:Vpc (wp-example-net-vpc):
    error: unable to validate AWS credentials - see https://pulumi.io/install/aws.html for details on configuration
```

Setting it in my aws profile or as an env variable or in the stack's config file fixes the problem.
However, better error messaging is needed since the root cause is not obvious.

### Steps to reproduce

1. Make sure aws region is not set in your profile, environment variable or stack config
2. run `pulumi up`
3. See error message as described above.
4. set region in any of the allowed ways
5. run `pulumi up` 
6. See things work as expected

### Expected Behavior

An error message indicating that region needs to be set.

### Actual Behavior

Throws confusing error message about not being able to validate AWS credentials.

### Versions used

Dependencies:
NAME           VERSION
pip            22.2.2
pulumi-aws     5.10.0
pulumi-random  4.8.1
setuptools     64.0.0
wheel          0.37.1

### Additional context

Discussed this with @stack72 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2022-08-11 22:16
Hi @MitchellGerdisch - this is a dupe of https://github.com/pulumi/pulumi-aws/issues/1968.

The reason you're not seeing it yet is that we've been blocked on cutting a recent release.

Once we cut the new release, you should see the following output:

```
error: unable to validate AWS credentials. Make sure you have:
    
     	 • Set the AWS_SECRET_ACCESS_KEY
     	 • Set the AWS_ACCESS_KEY_ID
     	 • Set your AWS region using `pulumi config set aws:region <region>`, e.g `us-west-2`
    
    See https://pulumi.io/install/aws.html for details on configuration
```

**Comment by stack72** [comment] 2022-08-11 22:56
> Hi @MitchellGerdisch - this is a dupe of #1968.
> 
> The reason you're not seeing it yet is that we've been blocked on cutting a recent release.
> 
> Once we cut the new release, you should see the following output:
> 
> ```
> error: unable to validate AWS credentials. Make sure you have:
>     
>      	 • Set the AWS_SECRET_ACCESS_KEY
>      	 • Set the AWS_ACCESS_KEY_ID
>      	 • Set your AWS region using `pulumi config set aws:region <region>`, e.g `us-west-2`
>     
>     See https://pulumi.io/install/aws.html[](https://pulumi.io/install/aws.html) for details on configuration
> ```

@guineveresaenger I think we can actually go a little further here and not even try to validate the code if there's no region available... it would save time and give an even more specific message to the user

Thoughts?

**Comment by guineveresaenger** [comment] 2022-08-11 23:51
@stack72 I'm down to tease this out a bit more; it's not too tricky to do, and @MitchellGerdisch is right, region settings feel only tangentially related to credentials validation

**Closed** 2022-08-12 19:32 UTC
Labels: kind/bug, resolution/duplicate, resolution/fixed

**Comment by omidraha** [comment] 2023-06-15 17:52
At first I got this `UnsupportedAvailabilityZoneException` error:
```
Diagnostics:
  pulumi:pulumi:Stack (devops-dev):
    error: update failed
    error: Resource monitor has terminated, shutting down

  aws:eks:Cluster (cluster-eksCluster):
    error: 1 error occurred:
    	* creating EKS Cluster (cluster-eksCluster-9544d32): UnsupportedAvailabilityZoneException: Cannot create cluster 'cluster-eksCluster-9544d32' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "b01087c1-afb6-4a69-963b-ddb0fe411295"
      },
      ClusterName: "cluster-eksCluster-9544d32",
      Message_: "Cannot create cluster 'cluster-eksCluster-9544d32' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f",
      ValidZones: [
        "us-east-1a",
        "us-east-1b",
        "us-east-1c",
        "us-east-1d",
        "us-east-1f"
      ]
    }
```
And then by changing the zone: 

```bash
pulumi config set aws:region us-east-1a
```

I received this same misleading error:

```
Diagnostics:
  aws:iam:Role (cluster-eksRole-role):
    error: unable to validate AWS credentials.
    Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-east-1a.amazonaws.com/": dial tcp: lookup sts.us-east-1a.amazonaws.com on 127.0.0.53:53: no such host
    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.

  pulumi:pulumi:Stack (devops-dev):
    error: Resource monitor has terminated, shutting down

```

Finally fixed with to change to another zone:

```bash
pulumi config set aws:region us-west-2
```
