### ISSUE TITLE
Creating a aws.lambda.Function from FileArchive with an undefined parameter causes a panic

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-aws#2069] opened 2022-08-01 03:29 UTC
### What happened?

Due to a bug in my code, a aws.lambda.Function was being created with an invalid FileArchive. Instead of failing gracefully, it caused a panic. When run with the Pulumi backend, the up doesn't immediately terminate, but instead times out after a long time (maybe an hour?).

### Steps to reproduce

I've created an MCVE:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

function mcve(opts: any) {
  new aws.lambda.Function("mcve", {
    code: new pulumi.asset.FileArchive(opts.theOption),
    role: "not important",
    handler: "not important",
    runtime: "nodejs14.x"
  });
}

mcve({ theOption: new pulumi.Config().get("ValueThatDoesntExist") } );
```
Any code that hides the missing string behind an `any` will produce this problem.

### Expected Behavior

Pulumi would detect that the FileArchive isn't pointing to anything and complain about that.

### Actual Behavior

Pulumi panics and dies.

### Versions used

CLI          
Version      3.34.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.10.0
nodejs  unknown

Host     
OS       debian
Version  11.3
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.15.1'

Current Stack: dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::fileasset::pulumi:pulumi:Stack::fileasset-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/paulhicks_sentify
User           paulhicks_sentify
Organizations  paulhicks_sentify

Dependencies:
NAME            VERSION
@pulumi/aws     5.10.0
@pulumi/pulumi  3.37.2
@types/node     14.18.23

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment] 2022-08-03 22:53
@stack72 

```
stderr: panic: fatal: An assertion has failed: cannot read an archive that has no contents

goroutine 218 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x10, {0x1e4896c, 0x2}, {0x0, 0x40d094, 0x203000})
/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0xf4
github.com/pulumi/pulumi/sdk/v3/go/common/resource.(*Archive).Open(0xc001830780)
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/asset.go:681 +0x54
github.com/pulumi/pulumi/sdk/v3/go/common/resource.(*Archive).archiveTar(0xc001830780, {0x7ff43b18ac00, 0xc001601700})
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/asset.go:1002 +0x5d
github.com/pulumi/pulumi/sdk/v3/go/common/resource.(*Archive).Archive(0xc001830780, 0x1, {0x7ff43b18ac00, 0xc001601700})
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/asset.go:952 +0x155
github.com/pulumi/pulumi/sdk/v3/go/common/resource.(*Archive).EnsureHash(0xc001830780)
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/asset.go:1128 +0x1de
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalPropertyValue({0xc001dd5118, 0x4}, 0x1b9ad20, {{0xc000a7d5c0, 0x5a}, 0x0, 0x1, 0x0, 0x0, 0x1, ...})
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/rpc.go:380 +0x58e
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalProperties(0xc001839380, {{0xc000a7d5c0, 0x5a}, 0x0, 0x1, 0x0, 0x0, 0x1, 0x1, 0x0, ...})
/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/rpc.go:270 +0x134
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*resmon).RegisterResource(0xc000160c00, {0xc0009c38d8, 0x40d3e7}, 0xc000ac8f20)
/home/runner/work/pulumi/pulumi/pkg/resource/deploy/source_eval.go:995 +0xb6e
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceMonitor_RegisterResource_Handler.func1({0x223e198, 0xc001839530}, {0x1da84e0, 0xc000ac8f20})
/home/runner/work/pulumi/pulumi/sdk/proto/go/resource.pb.go:1696 +0x78
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x223e198, 0xc001839350}, {0x1da84e0, 0xc000ac8f20}, 0xc001832f00, 0xc001759f38)
/home/runner/go/pkg/mod/github.com/grpc-ecosystem/[grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645](mailto:grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645)/go/otgrpc/server.go:57 +0x406
github.com/pulumi/pulumi/sdk/v3/go/common/util/rpcutil.OpenTracingServerInterceptor.func1({0x223e198, 0xc001839350}, {0x1da84e0, 0xc000ac8f20}, 0xc0016ddbc8, 0x1b169a0)
/home/runner/work/pulumi/pulumi/sdk/go/common/util/rpcutil/interceptor.go:79 +0x137
github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceMonitor_RegisterResource_Handler({0x1cf1ae0, 0xc000160c00}, {0x223e198, 0xc001839350}, 0xc000b09560, 0xc0006e58c0)
/home/runner/work/pulumi/pulumi/sdk/proto/go/resource.pb.go:1698 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e34000, {0x2266670, 0xc00157b860}, 0xc00183a240, 0xc00087a000, 0x31aff60, 0x0)
/home/runner/go/pkg/mod/google.golang.org/[grpc@v1.47.0](mailto:grpc@v1.47.0)/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc000e34000, {0x2266670, 0xc00157b860}, 0xc00183a240, 0x0)
/home/runner/go/pkg/mod/google.golang.org/[grpc@v1.47.0](mailto:grpc@v1.47.0)/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
/home/runner/go/pkg/mod/google.golang.org/[grpc@v1.47.0](mailto:grpc@v1.47.0)/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
/home/runner/go/pkg/mod/google.golang.org/[grpc@v1.47.0](mailto:grpc@v1.47.0)/server.go:920 +0x294

err?:
```

**Comment by stack72** [comment] 2022-08-05 12:29
So based on this stack trace, I think we should move this to pulumi/pulumi - @mikhailshilkov what do you think? FileArchive should handle this centrally rather than provider by provider

**Comment by stack72** [comment] 2022-08-05 15:54
Hi @tenwit I am going to close this as a dupe of https://github.com/pulumi/pulumi/issues/6254 so that we can centralise the fix there

**Closed** 2022-08-05 15:54 UTC
Labels: kind/bug, resolution/duplicate, p1
