### ISSUE TITLE
pulumi-aws 5.7.0 seems unable to validate AWS credentials for AWS Profile only

### ISSUE THREAD

**Issue by nnewton** [pulumi/pulumi-aws#1995] opened 2022-06-06 23:01 UTC
### What happened?

Updating to pulumi-aws 5.7.0 caused stack to be unable to find the access key/secret key for aws. These keys are working via AWS cli and work on pulumi-aws 5.6.0 (downgrading fixes the issue). 

### Steps to reproduce

$ export AWS_PROFILE=PROFILENAME
$ pulumi preview --diff
Results in: 
error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration

### Expected Behavior

Validating aws credentials based on AWS_PROFILE

### Actual Behavior

It does seem to find the credentials, when run with --debug I see this:
```Diagnostics:
  pulumi:pulumi:Stack (aws-test):
    debug: AWS Auth provider used: "SharedCredentialsProvider"
    debug: Retrieved credentials from "SharedConfigCredentials: /Users/nnewton/.aws/credentials"
    debug: Trying to get account information via iam:GetUser
    debug: [aws-sdk-go-v2] Request
    debug: POST / HTTP/1.1
    debug: Host: iam.amazonaws.com
    debug: User-Agent: APN/1.0 Pulumi/1.0 Pulumi/1.0 Pulumi-Aws/0.11+compatible (+https://www.pulumi.com) aws-sdk-go-v2/1.16.2 os/macos lang/go/1.17.9 md/GOOS/darwin md/GOARCH/arm64 api/iam/1.18.0
    debug: Content-Length: 33
    debug: Amz-Sdk-Invocation-Id: ec89da52-f37b-4985-9dd8-e6d533763942
    debug: Amz-Sdk-Request: attempt=1; max=25
    debug: Content-Type: application/x-www-form-urlencoded
    debug: X-Amz-Date: 20220606T224320Z
    debug: Accept-Encoding: gzip
    debug:
    debug: Action=GetUser&Version=2010-05-08
    debug: [aws-sdk-go-v2] Response
    debug: HTTP/1.1 200
    debug: Content-Length: 527
    debug: Content-Type: text/xml
    debug: Date: Mon, 06 Jun 2022 22:43:20 GMT
    debug: X-Amzn-Requestid: 906e4294-f0bc-40a9-9aa7-e66dc4dc6fdc
    debug:
    debug: <GetUserResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
    debug:   <GetUserResult>
    debug:     <User>
    debug:       <Path>/</Path>
    debug:       <PasswordLastUsed>2022-06-02T17:40:27Z</PasswordLastUsed>
    debug:       <Arn>arn:aws:iam::SNIP:user/nnewton</Arn>
    debug:       <UserName>nnewton</UserName>
    debug:       <UserId>SNIP</UserId>
    debug:       <CreateDate>2015-10-29T20:18:09Z</CreateDate>
    debug:     </User>
    debug:   </GetUserResult>
    debug:   <ResponseMetadata>
    debug:     <RequestId>906e4294-f0bc-40a9-9aa7-e66dc4dc6fdc</RequestId>
    debug:   </ResponseMetadata>
    debug: </GetUserResponse>```

So it does seem to pull credentials and validate a user. However it still fails out with:
```  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:test::aws::pulumi:pulumi:Stack::aws-test]
    ~ pulumi:providers:aws: (update)
        [id=7659c1a4-9b7c-4999-9d3b-64ba59ddcd61]
        [urn=urn:pulumi:test::aws::pulumi:providers:aws::aws-uswest2]
        region                   : "us-west-2"
      ~ skipCredentialsValidation: "true" => "false"
        skipGetEc2Platforms      : "true"
        skipMetadataApiCheck     : "true"
        skipRegionValidation     : "true"
      ~ version                  : "5.4.0" => "5.7.0"
error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
Resources:
    ~ 1 to update
    4 unchanged
```
I tried changing skipCredentialsValidation to false and it had no impact, except that line was no longer in the reported diff.

### Versions used

CLI
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.6.0
awsx        1.0.0-beta.8
docker      3.2.0
eks         0.40.0
kubernetes  3.19.2
python      unknown

Host
OS       darwin
Version  12.4
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-06-06 23:11
Hi @nnewton if you set aws:skipCredentialsValidation: true does the stack work for you?

**Comment by nnewton** [comment] 2022-06-06 23:17
@stack72 No, I tried that thinking the recent change was the issue and that I maybe had something wrong in my environment, but it fails with the same error.

**Comment by stack72** [comment] 2022-06-06 23:18
Ok I'll get on it first thing (it's 0218 here) and I'll see what I can replicate. Sorry for this!

**Comment by nnewton** [comment] 2022-06-06 23:20
No problem at all, downgrading works fine. Let me know if I can get you more information from my stack.

**Comment by stack72** [comment] 2022-06-06 23:22
Just to check that you are only using profile and not any keys with them right?

**Comment by nnewton** [comment] 2022-06-06 23:23
I forgot to add this: with a blank environment if you set AWS_PROFILE to the profile name that holds the credentials it fails. But if you set AWS_ACCESS and SECRET env variables directly to the keys in question, it works. So loading from the environment isn't entirely broken, just loading via the profile name.

**Comment by nnewton** [comment] 2022-06-06 23:24
@stack72 I reset the environment for each test, so just AWS_PROFILE was set and aws:region was set in the stack config.

**Comment by stack72** [comment] 2022-06-06 23:25
Ok that really helps me - thank you!!

**Comment by hognevevle** [comment] 2022-06-08 11:16
@stack72 Unfortunately, it still crashes for me after upgrading to 5.7.1.

```
✗ pulumi about     
CLI          
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.7.1
dotnet  unknown

Host     
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in dotnet (/usr/local/share/dotnet/dotnet v6.0.100)
[...]
NAME        VERSION
Pulumi      3.33.2
Pulumi.Aws  5.7.1

Pulumi locates its logs in /var/folders/n7/dznnt6717nv9vwy28l00ctl80000gn/T/ by default
```

```
✗ pulumi up --debug
[...]
Diagnostics:
  aws:iam:Role (dev-lambdaRole):
    error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
 
  pulumi:pulumi:Stack (Chat.Infrastructure-dev):
    debug: AWS Auth provider used: "SharedCredentialsProvider"
    debug: Retrieved credentials from "SharedConfigCredentials: /Users/hognevevle/.aws/credentials"
    debug: Trying to get account information via iam:GetUser
    debug: [aws-sdk-go-v2] Request
    debug: POST / HTTP/1.1
    debug: Host: iam.amazonaws.com
    debug: User-Agent: APN/1.0 Pulumi/1.0 Pulumi/1.0 Pulumi-Aws/0.11+compatible (+https://www.pulumi.com) aws-sdk-go-v2/1.16.3 os/macos lang/go/1.17.10 md/GOOS/darwin md/GOARCH/amd64 api/iam/1.18.4
    debug: Content-Length: 33
    debug: Amz-Sdk-Invocation-Id: b7e86774-f391-4d99-a469-74823f988277
    debug: Amz-Sdk-Request: attempt=1; max=25
    debug: Authorization: [redacted]
    debug: Content-Type: application/x-www-form-urlencoded
    debug: X-Amz-Date: 20220608T111517Z
    debug: Accept-Encoding: gzip
    debug: 
    debug: Action=GetUser&Version=2010-05-08
    debug: [aws-sdk-go-v2] Response
    debug: HTTP/1.1 200 
    debug: Content-Length: 467
    debug: Content-Type: text/xml
    debug: Date: Wed, 08 Jun 2022 11:15:18 GMT
    debug: X-Amzn-Requestid: b390801f-9dc5-4962-9fad-a61d3f4b8f36
    debug: 
    debug: <GetUserResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
    debug:   <GetUserResult>
    debug:     <User>
    debug:       <Path>/</Path>
    debug:       <Arn>[redacted]</Arn>
    debug:       <UserName>[redacted]</UserName>
    debug:       <UserId>[redacted]</UserId>
    debug:       <CreateDate>2021-05-01T14:21:53Z</CreateDate>
    debug:     </User>
    debug:   </GetUserResult>
    debug:   <ResponseMetadata>
    debug:     <RequestId>b390801f-9dc5-4962-9fad-a61d3f4b8f36</RequestId>
    debug:   </ResponseMetadata>
    debug: </GetUserResponse>
    debug: Fields to assign: [redacted]
    debug: Registering resource start: t=pulumi:pulumi:Stack, name=Chat.Infrastructure-dev, custom=False, remote=False
    debug: Preparing resource: t=pulumi:pulumi:Stack, name=Chat.Infrastructure-dev, custom=False, remote=False

```

**Comment by stack72** [comment] 2022-06-08 11:25
Hey @hognevevle 

Are you in the same setup of trying to using only a Profile to authenticate?

Paul

**Comment by hognevevle** [comment] 2022-06-08 11:27
@stack72 Yup, using the `default` profile.

**Comment by stack72** [comment] 2022-06-08 11:28
Can you do 1 thing for me to try this:

pulumi config set aws:skpMetadataApiCheck false` and tell me if this will then work for you?

**Comment by hognevevle** [comment] 2022-06-08 11:35
`aws:skipMetadataApiCheck` (I assume you were missing the `i` in `skip` there) doesn't seem to have any effect. Tried both 
`true` and `false`.

With `aws:skipCredentialsValidation true` , however, it works actually.

**Comment by nnewton** [comment] 2022-06-08 16:57
I can also confirm that 5.7.1 breaks on AWS_PROFILE usage, but that skipCredentialsValidation works as a mitigation. Thanks!

**Comment by stack72** [comment] 2022-06-08 16:59
Ok, mitigation is good :) I can work on getting this fixed!

**Comment by orcutt989** [comment] 2022-06-08 18:30
Just wanted to chime in that I'm also getting this with `@pulumi/aws` `v5.7.1`

```
Diagnostics:
  aws:iam:Role (xxx):
    error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration

  pulumi:pulumi:Stack (xxx-xxx):
    aws-load-balancer-controller transformation: Will ignore changes to TLS certificate on subsequent "pulumi up".
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:ec2/getVpc:getVpc returned an error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:index/getRegion:getRegion returned an error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:index/getRegion:getRegion returned an error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

with both these set the error changes

```
  aws:skipCredentialsValidation: "true"
  aws:skpMetadataApiCheck: "true"
```


```
 aws:iam:Group (xxx):
    error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key

  pulumi:pulumi:Stack (xxx-xxx):
    aws-load-balancer-controller transformation: Will ignore changes to TLS certificate on subsequent "pulumi up".
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:ec2/getVpc:getVpc returned an error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key


        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:index/getRegion:getRegion returned an error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key


        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
    error: Running program '/Users/xxx/src/xxx' failed with an unhandled exception:
    Error: invocation of aws:index/getRegion:getRegion returned an error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key


        at Object.callback (/Users/xxx/src/xxx/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/xxx/src/xxx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by stack72** [comment] 2022-06-08 18:45
I’m working on this to fix it up!

**Comment by stack72** [comment] 2022-06-08 22:18
Hi all,

we have decided to skipCredentialsValidation by default while we get to grips with the bug here.

The issue is summarised as follows:

* Users who set AWS_ACCESS_KEY as an env var will continue to work as expected
* Users who use credentials file or AWS_PROFILE are being prevented from having their credentials validated

Skipping credentials validation will allow us to fix the problem and then work out the correct fix

Paul

**Comment by stack72** [comment] 2022-06-09 08:35
Folks we have release v5.7.2 of the provider which disables the credentials validation which caused this issue - please let us know if there are further problems here 

I am going to keep this issue open so that we can track fixing the credentials validation bug

Paul

**Comment by nnewton** [comment] 2022-06-09 16:43
I just re-tested with 5.7.2, removing skipCredentialsValidation true from my config and it worked here. Thanks for your work on this.

**Comment by nnewton** [comment] 2022-06-09 17:15
@orcutt989 That is very odd. Are you setting AWS_PROFILE in the environment or you using profiles another way?

**Comment by stack72** [comment] 2022-06-09 17:18
This is VERY odd indeed - we skip credentials validation by default now - we don't need to set the config value to skip it...

If you run a `pulumi refresh` and look at the diff, do you see that `skipCredentialsValidation` changes from false to true?

**Comment by orcutt989** [comment] 2022-06-09 17:30
> This is VERY odd indeed - we skip credentials validation by default now - we don't need to set the config value to skip it...
> 
> If you run a `pulumi refresh` and look at the diff, do you see that `skipCredentialsValidation` changes from false to true?

I cant get it to go to false, if I run a preview I get the unable to validate error, and searching my terminal has no `skipCredentialsValidation` in the output.

This too...
```
pulumi config get aws:skipCredentialsValidation:
error: invalid configuration key: could not parse aws:skipCredentialsValidation: as a configuration key (configuration keys should be of the form `<namespace>:<name>`)
```

**Comment by nnewton** [comment] 2022-06-09 17:44
Got a full reproduction, I just needed to use a default provider instead of a specific one. If you just create a new AWS project with 5.7.2 (```pulumi new aws-python``` in my case) and put the profile in the Pulumi stack it will fail out unable to find the credentials, if you then add skipCredentialsValidation it will work, if you specify AWS_PROFILE in the environment it will work:

```✦ ❯ cat Pulumi.dev.yaml
config:
  aws:region: us-west-2
  aws:profile: da
  aws:skipCredentialsValidation: true

on ⛵ arn:aws:eks:us-west-2:353626856714:cluster/eks-prod-eksCluster-c4369ab () ~/test 🛥 dev via 🐍 v3.9.12
✦ ❯ pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/nnewton/test/dev/previews/ed2d574d-3ee3-496e-9a63-87f8ec4fb705

     Type                 Name       Plan
 +   pulumi:pulumi:Stack  test-dev   create
 +   └─ aws:s3:Bucket     my-bucket  create

Resources:
    + 2 to create
```

```✦ ❯ cat Pulumi.dev.yaml
config:
  aws:region: us-west-2
  aws:profile: da

on ⛵ arn:aws:eks:us-west-2:353626856714:cluster/eks-prod-eksCluster-c4369ab () ~/test 🛥 dev via 🐍 v3.9.12
✦ ❯ pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/nnewton/test/dev/previews/79afce41-54d0-4af5-8b0f-9cda2cf31592

     Type                 Name       Plan       Info
 +   pulumi:pulumi:Stack  test-dev   create
     └─ aws:s3:Bucket     my-bucket             1 error

Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: unable to validate AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
```

**Comment by stack72** [comment] 2022-06-09 19:43
Folks, I just need to take care of an assumeRole configuration and we will be in a much better situation here :)

Currently the creds validation is broken:
[![asciicast](https://asciinema.org/a/AgIZGKgVnFEejf2wKIegTECrm.svg)](https://asciinema.org/a/AgIZGKgVnFEejf2wKIegTECrm)

New code:

With AWS_PROFILE:
[![asciicast](https://asciinema.org/a/qSdDAZCtgnDWiCBH2MBG5cQ8I.svg)](https://asciinema.org/a/qSdDAZCtgnDWiCBH2MBG5cQ8I)

With default creds:
[![asciicast](https://asciinema.org/a/A4v7yF9VHq1Mr0hayfkabLNBm.svg)](https://asciinema.org/a/A4v7yF9VHq1Mr0hayfkabLNBm)

With Environment Vars for AWS_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY
[![asciicast](https://asciinema.org/a/qB50n4onFLYQAwARCGhwVQVK7.svg)](https://asciinema.org/a/qB50n4onFLYQAwARCGhwVQVK7)

**Closed** 2022-06-15 09:57 UTC
Labels: kind/bug
