### ISSUE TITLE
MetricAlarm: Dimension keys gets snake_cased

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi-aws#380] opened 2018-11-21 14:41 UTC
Just encountered a problem when creating a `aws.cloudwatch.MetricAlarm` with dimensions which are defined in `PascalCase`. After applying the resource the dimension name is actually `snake_cased`.

![screenshot 2018-11-21 at 13 41 47](https://user-images.githubusercontent.com/224910/48847846-d4793c00-eda2-11e8-84b7-27ac74d9c288.png)

I defined the dimension as follows:

```typescript
const tunnel = new aws.cloudwatch.MetricAlarm(
  `alarms-vpn-tunnel`,
  {
    metricName: "TunnelState",
    namespace: "AWS/VPN",
    name: "VPN Tunnel",
    alarmDescription: "VPN Tunnel is offline",
    alarmActions: [sap],
    actionsEnabled: true,
    statistic: "Maximum",
    comparisonOperator: "LessThanOrEqualToThreshold",
    dimensions: [
      {
        VpnId: config.alarms.vpn.vpnTunnel.vpnId
      }
    ],
    threshold: 0,
    period: 60,
    evaluationPeriods: 2
  }
);
```

Unfortunately, this makes it impossible to use the `MetricAlarm` at the moment as there are a lot of `PascalCased` dimension identifiers in the AWS universe.

**Comment by lukehoban** [comment] 2018-11-21 16:58
I suspect this is related to https://github.com/pulumi/pulumi-terraform/issues/263.

**Comment by joeduffy** [comment] 2018-11-25 22:53
@akoenig I think I have a fix for you.

Unless I'm mistaken, `"dimensions"` is supposed to be a map of key-value pairs, not an array of maps: https://github.com/pulumi/pulumi-aws/blob/cfcf3ed0c7019484ffc2a62de4498e41d802ee71/sdk/nodejs/cloudwatch/metricAlarm.ts#L226

If you change

```typescript
    dimensions: [
      {
        VpnId: config.alarms.vpn.vpnTunnel.vpnId
      }
    ],
```

to

```typescript
    dimensions: {
        VpnId: config.alarms.vpn.vpnTunnel.vpnId
    },
```

I believe your code will work as intended. At least the preview looks good to me.

Note that I am not sure whether this will work in Python, due to how we mangle names. @swgillespie will need to comment on that (and, if not, we will file a separate issue).

This did reveal a bug, however, in that we should (I think) be rejecting the attempt to pass an array where a map is intended. @jen20 @pgavlin Any idea on this?

**Comment by lukehoban** [comment] 2018-11-25 23:15
> we should (I think) be rejecting the attempt to pass an array where a map is intended.

There are two layers of this - TypeScript and runtime.  Historically we've only done "type checking" at the TypeScript layer.

At the TypeScript layer, I'm honestly not sure why TypeScript allows assigning `any[]` to `{[key: string]: any}`, but it does.  That means that by typing this (and many other) properties as `{[key: string]: any}` we don't get protection against passing arrays.  It appears you could type these things as `{ [key: string]: any; [key: number]: never }` to get protection against this, which would have caused the original code above to report an error.  Feels a little strange to have to do that though.  

Better would be to provide a richer type instead of `any` for the members - in the particular case above - the elements must be `string`.  This is not manifest in the schema, but is clear from the [implementation](https://github.com/terraform-providers/terraform-provider-aws/blob/03a8516d988de201ca3358f09b92a22f2507894d/aws/resource_aws_cloudwatch_metric_alarm.go#L310-L317).  We probably want to audit all `{[key:string]: any}` signatures and manually annotate what the element type is.

Opened https://github.com/pulumi/pulumi-terraform/issues/285 to track one or both of the above.

We could in theory add a layer of runtime type checking as well - which would help especially for pure-JavaScript clients.  We do almost none of this today, and there's probably quite a lot of validation we could do.  This is tracked by https://github.com/pulumi/pulumi-terraform/issues/147.

**Comment by akoenig** [comment] 2018-11-26 11:22
@joeduffy Awesome. This fixed my issue. Thanks a lot! :)

Also a big surprise for me that TS allows assigning `any[]` to `{[key: string]: any}` 😱 I mean, it makes sense from a JS perspective, but still ... hm.

**Comment by lukehoban** [comment] 2018-11-26 13:37
Closing this out for now - we'll track follow-ups to improve things here in https://github.com/pulumi/pulumi-terraform/issues/285, pulumi/pulumi-terraform#263 and https://github.com/pulumi/pulumi-terraform/issues/147.

**Closed by lukehoban** 2018-11-26 13:37 UTC
Labels: customer/feedback, priority/P1
