### ISSUE TITLE
AWS-EC2-Fleet: FleetOnDemandOptions has wrong allocation_strategy values.

### ISSUE THREAD

**Issue by limasilet** [pulumi/pulumi-aws#2163] opened 2022-09-26 22:24 UTC
File: [themes/default/content/registry/packages/aws/api-docs/ec2/fleet/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/fleet/)

[FleetOnDemandOptions ](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/fleet/#fleetondemandoptions) is providing information on Spot Fleet `allocation_strategy` options, not On Demand Fleet `allocation_strategy` options.

I tried using one of the values that are Spot Fleet specific, based on Pulumi docs, and the preview **correctly** failed:
```
'fleet' has a problem: expected on_demand_options.0.allocation_strategy to be one of [prioritized lowestPrice], got capacity-optimized. Examine values at 'Fleet.OnDemandOptions.AllocationStrategy'.
```
AWS doc matches pulumi preview failure https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-on-demand-backup.html

**Comment by viveklak** [comment] 2022-10-03 17:06
This is a result of https://github.com/pulumi/pulumi-terraform-bridge/issues/529

**Comment by lukehoban** [comment] 2022-12-28 00:14
Going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 to track the required work centrally.

**Closed by lukehoban** 2022-12-28 00:14 UTC
Labels: area/docs, kind/bug, resolution/duplicate
