### ISSUE TITLE
Weird S3 Bucket and BucketV2 behavior

### ISSUE THREAD

**Issue by akrantz01** [pulumi/pulumi-aws#1925] opened 2022-04-25 17:50 UTC
### What happened?

I was initially trying to create an S3 bucket with the `BucketV2` resource, but it ended up failing with a cryptic message when I ran either `pulumi up` or `pulumi preview`. However, after doing some digging, I found the same thing happened with the `Bucket` resource. Both failed with the same error.

I continued testing stuff and I found that the error only occurs if I import `Bucket` or `BucketV2` directly (i.e. `import { Bucket, BucketV2 } from "@pulumi/aws/s3"`). If I reference the resources from their parent package, then it works as expected (i.e `import { s3 } from "@pulumi/aws"` or `import * as aws from "@pulumi/aws"`).

### Steps to reproduce

The following should fail:
```ts
import { Bucket } from "@pulumi/aws/s3";
new Bucket("testing", {});
```

The following should succeed:
```ts
import { s3 } from "@pulumi/aws";
new s3.Bucket("testing", {});
```
```ts
import * as aws from "@pulumi/aws";
new aws.s3.Bucket("testing", {});
```

To test, run either `pulumi preview` or `pulumi up`. In all 3 examples, `Bucket` can be replaced with `BucketV2` and the same behaviour should occur.

### Expected Behavior

Pulumi previews/creates the S3 bucket properly in all 3 cases.

### Actual Behavior

An error gets thrown before the preview can be completed when importing the resources directly.

```shell
Previewing update (dev)

View Live: https://app.pulumi.com/<preview url>

     Type                 Name         Plan       Info
 +   pulumi:pulumi:Stack  testing-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (testing-dev):
    error: Running program '/home/alex/Downloads/testing' failed with an unhandled exception:
    TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (/home/alex/Downloads/testing/node_modules/@pulumi/cloudwatch/eventRuleMixins.ts:70:56)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/home/alex/Downloads/testing/node_modules/@pulumi/cloudwatch/cloudwatchMixins.ts:16:1)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

### Versions used

CLI          
Version      3.30.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.2.0
nodejs  unknown

Host     
OS       fedora
Version  35
Arch     x86_64

This project is written in nodejs (/home/alex/.nvm/versions/node/v16.14.2/bin/node v16.14.2)

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/akrantz01
User           akrantz01
Organizations  akrantz01, wafflehacks

NAME            VERSION
@pulumi/aws     5.2.0
@pulumi/pulumi  3.30.0
@types/node     14.18.15

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2022-05-03 18:48
Hi @akrantz01 - thank you for filing this issue. I believe this is a duplicate of https://github.com/pulumi/pulumi-aws/issues/772 and we're not sure if a fix is on the roadmap.

We apologize for any inconvenience here.

**Closed by guineveresaenger** 2022-05-03 18:48 UTC
Labels: kind/bug, resolution/duplicate
