### ISSUE TITLE
Cloudwatch Event Target arn when using ECS Target mode

### ISSUE THREAD

**Issue by asselinpaul** [pulumi/pulumi-aws#2164] opened 2022-09-29 02:19 UTC
File: [themes/default/content/registry/packages/aws/api-docs/cloudwatch/eventtarget/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/cloudwatch/eventtarget/)

In **EventTarget Resource Properties** -> **Inputs**, what should `arn` be set to when using `ecs_target` mode? 
The documentation currently states:
> ARN of the SQS queue specified as the target for the dead-letter queue.

But I struggle to see how that could make sense for ECS target mode? There is no SQS queue involved.

**Comment by viveklak** [comment] 2022-10-03 20:43
Another instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/529

**Comment by lukehoban** [comment] 2022-12-28 00:14
Going to close this out as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/529 to track the required work centrally.

**Closed by lukehoban** 2022-12-28 00:14 UTC
Labels: area/docs, kind/bug, resolution/duplicate, area/api-docs
