### ISSUE TITLE
Changing aws.rds.Instance identifier results in replacement

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-aws#589] opened 2019-06-06 19:19 UTC
If I change the `identifier` of a `aws.rds.Instance`, Pulumi thinks it needs to replace the instance. This property is actually able to be changed in place.

**Comment by kennyjwilli** [comment] 2019-06-06 19:37
@stack72

**Comment by ellismg** [comment] 2019-06-06 20:13
FWIW, this property is listed as `ForceNew` in the upstream provider.  This matches what [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html) says for the `DBInstanceProvider`.

**Comment by kennyjwilli** [comment] 2019-06-06 20:40
Slack discussion: https://pulumi-community.slack.com/archives/C84L4E3N1/p1559848211149300. Changing this property is possible through the AWS console.

**Comment by stack72** [comment] 2019-06-07 11:24
Ok, @kennyjwilli, I have spent the morning looking at how we can do this - it *is* possible but we would need to come up with a way of doing it in the Terraform provider upstream. Basically, we pass the current identifier and `NewDBInstanceIdentifier` to the Modify operation and it will rename it as expected

The trouble we have is, Terraform actually use the DBInstanceIdentifier as the resource ID, therefore, any changes to that ID will force a new operation.

I am going to open an issue upstream to ask the TF team about this to see...

I will cross link it here

**Comment by lukehoban** [comment] 2022-11-19 01:26
This is not supported in Terraform or CloudFormation - and thus also not in AWS Native. I'm going to close this out as by design - but if there is new need for this - please do raise a note here.

**Closed by lukehoban** 2022-11-19 01:26 UTC
Labels: kind/enhancement, resolution/by-design
