### ISSUE TITLE
Error when importing lambda

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi-aws#1271] opened 2020-12-18 02:04 UTC
I'm trying to import an existing aws lambda and it's failing with the error  
`handler and runtime must be set when PackageType is Zip`  
Runtime is set (`.NET Core 3.1 (C#/PowerShell)`), handler is set (`App.Api::App.Api.LambdaEntryPoint::FunctionHandlerAsync`)

Import statement:
`pulumi import aws:lambda/function:Function lambda app-api-dev-6d0784b`

In a verbose import, I don't get any more information
`I1218 10:20:55.752764   12712 eventsink.go:86] eventSink::Error(<{%reset%}>Preview failed: diffing urn:pulumi:App.Api.dev::App.Api::aws:lambda/function:Function::lambda: handler and runtime must be set when PackageType is Zip<{%reset%}>)`

**Comment by jk-fm** [comment] 2021-08-10 14:04
this may be related: #1379

**Comment by lukehoban** [comment] 2021-08-13 17:57
Closing as dupe of #1379 given the additional details now in that issue.

**Closed by lukehoban** 2021-08-13 17:57 UTC
Labels: kind/bug, resolution/duplicate
