### ISSUE TITLE
Can't create AWS IAM VirtualMfaDevice

### ISSUE THREAD

**Issue by AleksandrAksenov** [pulumi/pulumi-aws#2239] opened 2022-11-30 19:49 UTC
### What happened?

When I try to create the VirtualMfaDevice resource I get the error:
```
2022/11/30 20:39:11 ERROR: [core] [Server #3] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

error: grpc: error while marshaling: string field contains invalid UTF-8
error: update failed
```

### Steps to reproduce

* Define the resource:
```
        aws.iam.VirtualMfaDevice(
            f"{username}",
            virtual_mfa_device_name=f"{username}"
        )
```
* Create the resource:
```
pulumi up --diff --refresh
```

### Expected Behavior

The resource should be created.

### Actual Behavior

I get the error
```
2022/11/30 20:39:11 ERROR: [core] [Server #3] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

error: grpc: error while marshaling: string field contains invalid UTF-8
error: update failed
```

### Output of `pulumi about`

```
CLI
Version      3.40.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
hcloud      1.10.1
kubernetes  3.20.5
python      unknown
random      4.8.0

Host
OS       darwin
Version  11.7.1
Arch     arm64

This project is written in python: executable='/Users/user/.pyenv/shims/python3' version='3.10.8
'

Current Stack: users.test

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:users.test::users::pulumi:pulumi:Stack::users-users.test
pulumi:providers:aws                                 urn:pulumi:users.test::users::pulumi:providers:aws::default
pulumi:providers:aws                                 urn:pulumi:users.test::users::pulumi:providers:aws::default_5_10_0


Found no pending operations associated with users.test

Backend
Name           Device-name
URL            file://../
User           user
Organizations

Dependencies:
NAME               VERSION
click              8.1.3
mypy-extensions    0.4.3
pathspec           0.9.0
pip                22.2.2
platformdirs       2.5.2
pulumi-aws         5.10.0
pulumi-hcloud      1.10.1
pulumi-kubernetes  3.20.5
pulumi-random      4.8.0
setuptools         62.3.2
tomli              2.0.1
typing_extensions  4.3.0

Pulumi locates its logs in /var/folders/f8/f_mdzs9x1m34ytjckb7ykb2c0000gn/T/ by default
warning: A new version of Pulumi is available. To upgrade from version '3.40.1' to '3.48.0', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Additional context
In AWS it creates the MFA-device:
```
        {
            "SerialNumber": "arn:aws:iam::number:mfa/username"
        },
```

Looks like the PNG file doesn't properly decode or processed.
The result of this command should contain: [qr_code_png](https://www.pulumi.com/registry/packages/aws/api-docs/iam/virtualmfadevice/#state_qr_code_png_python)
```
A QR code PNG image that encodes otpauth://totp/$virtualMFADeviceName@$AccountName?secret=$Base32String
where $virtualMFADeviceName is one of the create call arguments. AccountName is the user name if set
(otherwise, the account ID otherwise), and Base32String is the seed in base32 format.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment] 2022-12-01 22:35
Hi @AleksandrAksenov, what is the `username` variable in your example? I wanted to make sure that it's not a Pulumi Output, otherwise, you can't use it directly in an f-string.

It would also be helpful to see if running with [verbose logging](https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging) uncovers any additional information about the invalid string field. Thanks!

**Comment by AleksandrAksenov** [comment] 2022-12-02 08:15
> Hi @AleksandrAksenov, what is the `username` variable in your example? I wanted to make sure that it's not a Pulumi Output, otherwise, you can't use it directly in an f-string.
> 
> It would also be helpful to see if running with [verbose logging](https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging) uncovers any additional information about the invalid string field. Thanks!

Hi @lblackstone 
It's just a string variable: user name, like "axenow".

Unfortunately, I can't add the whole output, as there is a lot of secrets and private information, but the main error I'll add here:
```
Membership::aws_iam_user_group_membership_aaksenov
I1202 09:02:12.628122   51124 eventsink.go:62] eventSink::Debug(<{%reset%}>resource registration successful: ty=aws:iam/userGroupMembership:UserGroupMembership, urn=urn:pulumi:users.test::users::aws:iam/userGroupMembership:UserGroupMembership::aws_iam_user_group_membership_aaksenov<{%reset%}>)
I1202 09:02:13.030069   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.029978   51143 schema.go:860] Terraform output qrCodePng = {<89>PNG
<{%reset%}>)
I1202 09:02:13.030210   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>^Z
<{%reset%}>)
I1202 09:02:13.030266   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>^@^@^@^MIHDR^@^@^@<FA>^@^@^@<FA>^H^B^@^@^@^G<8E><CD>j^@^@^F*IDATx<DA><ED><DD>Ar<E3>0^LE<C1><DC><FF>ҙ^S<CC>"%<<82><B2><FB>/]N,
<93>^MUA`f~~E<BE>&?<96>@p^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>^Ew^Q<DC>Ep^W<F9>z<EE>?A<FE><F7><FB><9F><BC><FE><E4><BB><FC><F5>=O֪<B8><9E><A9>k>
<B9><EF><B8><E3><8E>;<EE><B8><E3><8E>;܋<DF><F3>d;<9F>,q<C1><A2><F8><AC><A2><E4><9E>܆<B6><FC><E0><8E>;<EE><B8><E3><8E>;<EE><B8><E3>޶2uK<BA><F5><9E><93><E5>W0<9D>گ<93>e<83>;<EE><B8><E3><8E>;<EE><B8><E3>
..........
w<DC>q<DF>^_3^Ue<F0><96><B6><F8>dyo<B5><8F><F5>-^Fw<DC>q<C7>^]w<DC>q<C7>^]<F7>{<89>?<A1><B3>Ev<EB>h<D4><C9>1S=<9E><C3>^]w<DC>q<C7>^]w<DC>q<C7><FD>\<AB><BA>5<BA><BA>a<CC>t<B2><BC>^K:7^?/<DC>q<C7>^]w<DC>q
<C7>^]w<DC>ϵ<AA>'[<9C><93>#<98><9B>[<C0>b^M<EB>Q^Z<EE><B8><E3><8E>;<EE><B8><E3><8E>;<EE><E7><B8><D7>K_<B4><A7>>Y<87>z<CC>T<8F>ۦZ<DE>^W<B7><AA><B8><E3><8E>;<EE><B8><E3><8E>;<EE>^_ýh^Yk<FA>EI<DC>pd<AD>n<9D>
<EB>G^B<B8><E3><8E>;<EE><B8><E3><8E>;<83>{<FD><B9>S-W=<A2>:9r*n1^_>f<C2>^]w<DC>q<C7>^]w<DC>q<C7>}q<BC>u<C3>{<A6>֭<F8>ܺ<9C>p<C7>^]w<DC>q<C7>^]w<DC>q^?<F7>^Q<B1><AD><F1>P}<FD>^E<9D><93><E3><9E>zmq<C7>^]w<DC>
q<C7>^]w<DC>q?7<9E><A8><B7>綒<A8>Y^W<EB>p[Y<E2><8E>;<EE><B8><E3><8E>;<EE><B8><E3><FE><BE>^?^RU^Dw^Q<DC>Ep^W<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]p^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw
<C1>]<E4>k<F2>^O^L5<DC><FC>^Q6<B9>M^@^@^@^@IEND<AE>B`<82>}
<{%reset%}>)
I1202 09:02:13.030308   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030013   51143 schema.go:860] Terraform output tags = {map[]}
<{%reset%}>)
I1202 09:02:13.030393   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030022   51143 schema.go:860] Terraform output tagsAll = {map[]}
<{%reset%}>)
I1202 09:02:13.030423   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030026   51143 schema.go:860] Terraform output virtualMfaDeviceName = {aaksenov1}
<{%reset%}>)
I1202 09:02:13.030451   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030030   51143 schema.go:860] Terraform output arn = {arn:aws:iam::11111:mfa/aaksenov1}
<{%reset%}>)
I1202 09:02:13.030490   51124 provider_plugin.go:1651] provider received rpc error `Internal`: `grpc: error while marshaling: string field contains invalid UTF-8`
I1202 09:02:13.030525   51124 provider_plugin.go:1654] rpc error kind `Internal` may not be recoverable
I1202 09:02:13.030556   51124 provider_plugin.go:865] Provider[aws, 0x140006cf320].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1) failed: grpc: error while marshaling: string field contains invalid UTF-8
I1202 09:02:13.030612   51124 eventsink.go:86] eventSink::Error(<{%reset%}>grpc: error while marshaling: string field contains invalid UTF-8<{%reset%}>)
I1202 09:02:13.030664   51124 snapshot.go:334] SnapshotManager: createSnapshotMutation.End(..., false)
I1202 09:02:13.030694   51124 snapshot.go:559] SnapshotManager.markOperationComplete(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1)
I1202 09:02:13.030491   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030034   51143 schema.go:860] Terraform output base32StringSeed = {AULV3ZJ7T4Y6J4QLAGNE}
<{%reset%}>)
I1202 09:02:13.030747   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030051   51143 schema.go:860] Terraform output path = {/}
<{%reset%}>)
I1202 09:02:13.030774   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030059   51143 schema.go:860] Terraform output id = {arn:aws:iam::11111:mfa/aaksenov1}
<{%reset%}>)
I1202 09:02:13.030803   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030075   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: arn={arn:aws:iam::11111:mfa/aaksenov1}
<{%reset%}>)
I1202 09:02:13.030829   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030082   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: base32StringSeed={AULV3ZJ7T4SK54WUY6J4QLAGNE}
<{%reset%}>)
I1202 09:02:13.030876   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030087   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: id={arn:aws:iam::11111:mfa/aaksenov1}
<{%reset%}>)
I1202 09:02:13.030910   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030092   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: path={/}
<{%reset%}>)
I1202 09:02:13.030910   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030092   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:
iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: path={/}
<{%reset%}>)
I1202 09:02:13.030934   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030097   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:
iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: qrCodePng={<89>PNG
<{%reset%}>)
I1202 09:02:13.030963   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>^Z
<{%reset%}>)
I1202 09:02:13.030995   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>^@^@^@^MIHDR^@^@^@<FA>^@^@^@<FA>^H^B^@^@^@^G<8E><CD>j^@^@^F*IDATx<DA><ED><DD>Ar<E3>0^LE<C1><DC><FF>ҙ^S<CC>"%<<82><B2><FB>/]N,
<93>^MUA`f~~E<BE>&?<96>@p^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>^Ew^Q<DC>Ep^W<F9>z<EE>?A<FE><F7><FB><9F><BC><FE><E4><BB><FC><F5>=O֪<B8><9E><A9>k>
<B9><EF><B8><E3><8E>;<EE><B8><E3><8E>;܋<DF><F3>d;<9F>,q<C1><A2><F8><AC><A2><E4><9E>܆<B6><FC><E0><8E>;<EE><B8><E3><8E>;<EE><B8><E3>޶2uK<BA><F5><9E><93><E5>W0<9D>گ<93>e<83>;<EE><B8><E3><8E>;<EE><B8><E3>
.......
<91><AD>?<9B>x<B2>V<F5>^Q<B1>ESC<CA>^Ow<DC>q<C7>^]w<DC>q<C7>^]<F7>s<ED>W<B1><9D>[[^_<FF>֑<B5><AD>G^E<B8><E3><8E>;<EE><B8><E3><8E>;c<CC>T<B4><BF><C5>vN<B5>_7<B4><86><F5><B1>3<DC>q<C7>^]w<DC>q<C7>^]w<DC>
<EF><E2>^,<E5><D4>6?Y<EE><A9>^V<BC>.<8F><A9>k<AB>o%+e<80>;<EE><B8><E3><8E>;<EE><B8><E3><8E>{B<BC>^^a<D4>۰Ţ~<P<BF><FE>!Ofp<C7>^]w<DC>q<C7>^]w<DC>_<FD><DC>}<AA>Tnh%^K^<F5><E8><AD>^^^W^V^^p<C7>^]w<DC>q<C7>^]
w<DC>q<DF>^_3^Ue<F0><96><B6><F8>dyo<B5><8F><F5>-^Fw<DC>q<C7>^]w<DC>q<C7>^]<F7>{<89>?<A1><B3>Ev<EB>h<D4><C9>1S=<9E><C3>^]w<DC>q<C7>^]w<DC>q<C7><FD>\<AB><BA>5<BA><BA>a<CC>t<B2><BC>^K:7^?/<DC>q<C7>^]w<DC>q
<C7>^]w<DC>ϵ<AA>'[<9C><93>#<98><9B>[<C0>b^M<EB>Q^Z<EE><B8><E3><8E>;<EE><B8><E3><8E>;<EE><E7><B8><D7>K_<B4><A7>>Y<87>z<CC>T<8F>ۦZ<DE>^W<B7><AA><B8><E3><8E>;<EE><B8><E3><8E>;<EE>^_ýh^Yk<FA>EI<DC>pd<AD>n<9D>
<EB>G^B<B8><E3><8E>;<EE><B8><E3><8E>;<83>{<FD><B9>S-W=<A2>:9r*n1^_>f<C2>^]w<DC>q<C7>^]w<DC>q<C7>}q<BC>u<C3>{<A6>֭<F8>ܺ<9C>p<C7>^]w<DC>q<C7>^]w<DC>q^?<F7>^Q<B1><AD><F1>P}<FD>^E<9D><93><E3><9E>zmq<C7>^]w<DC>
q<C7>^]w<DC>q?7<9E><A8><B7>綒<A8>Y^W<EB>p[Y<E2><8E>;<EE><B8><E3><8E>;<EE><B8><E3><FE><BE>^?^RU^Dw^Q<DC>Ep^W<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]p^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw^Q<DC>Ep^W<C1>]^Dw
<C1>]<E4>k<F2>^O^L5<DC><FC>^Q6<B9>M^@^@^@^@IEND<AE>B`<82>}
<{%reset%}>)
I1202 09:02:13.031021   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030102   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: tags={map[]}
<{%reset%}>)I1202 09:02:13.031064   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030108   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: tagsAll={map[]}
<{%reset%}>)
I1202 09:02:13.031210   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>I1202 09:02:13.030116   51143 rpc.go:74] Marshaling property for RPC[tf.Provider[aws].Create(urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1/aws_iam_virtual_mfa_device).outs]: virtualMfaDeviceName={aaksenov1}
<{%reset%}>)
I1202 09:02:13.031255   51124 eventsink.go:78] eventSink::Infoerr(<{%reset%}>2022/12/02 09:02:13 ERROR: [core] [Server #7] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
<{%reset%}>)
ESC[38;5;1merror: ESC[0mESC[0mgrpc: error while marshaling: string field contains invalid UTF-8ESC[0m
I1202 09:02:13.033249   51124 state.go:304] error copying .pulumi/stacks/users.test.json.gz to .pulumi/stacks/users.test.json.gz.bak: blob (key ".pulumi/stacks/users.test.json.gz -> .pulumi/stacks/users.test.json.gz.bak") (code=NotFound): stat /.pulumi/stacks/users.test.json.gz: no such file or directory
I1202 09:02:13.033366   51124 state.go:310] error deleting source object after rename: .pulumi/stacks/users.test.json.gz (blob (key ".pulumi/stacks/users.test.json.gz") (code=NotFound): remove /.pulumi/stacks/users.test.json.gz: no such file or directory) skipping
I1202 09:02:13.054788   51124 state.go:261] Saved stack users.test checkpoint to: .pulumi/stacks/users.test.json (backup=.pulumi/stacks/users.test.json.bak)
I1202 09:02:13.054927   51124 step_executor.go:389] StepExecutor worker(4): step create on urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1 failed with an error: grpc: error while marshaling: string field contains invalid UTF-8
I1202 09:02:13.054951   51124 step_executor.go:389] StepExecutor worker(4): step create on urn:pulumi:users.test::users::aws:iam/virtualMfaDevice:VirtualMfaDevice::aaksenov1 failed, signalling cancellation
I1202 09:02:13.054984   51124 deployment_executor.go:265] deploymentExecutor.Execute(...): context finished: context canceled
I1202 09:02:13.055004   51124 step_executor.go:389] StepExecutor worker(-1): StepExecutor.waitForCompletion(): waiting for worker threads to exit
I1202 09:02:13.054986   51124 step_executor.go:389] StepExecutor worker(-2): worker exiting due to cancellation
I1202 09:02:13.055038   51124 step_executor.go:389] StepExecutor worker(-1): StepExecutor.waitForCompletion(): worker threads all exited
I1202 09:02:13.055057   51124 deployment_executor.go:275] deploymentExecutor.Execute(...): step executor has completed
I1202 09:02:13.055077   51124 eventsink.go:86] eventSink::Error(<{%reset%}>update failed<{%reset%}>)
ESC[38;5;1merror: ESC[0mESC[0mupdate failedESC[0m
I1202 09:02:13.055123   51124 deployment_executor.go:138] deploymentExecutor.Execute(...): exiting provider canceller
I1202 09:02:13.069158   51124 langruntime_plugin.go:214] langhost[python].Run(pwd=/aws/users,program=.,...,dryrun=false) failed: err=error reading from serve
r: read tcp 127.0.0.1:53452->127.0.0.1:53450: use of closed network connection
I1202 09:02:13.069200   51124 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I1202 09:02:13.071008   51124 source_eval.go:190] EvalSourceIterator ended with an error: error reading from server: read tcp 127.0.0.1:53452->127.0.0.1:53450: use of closed network connection
I1202 09:02:13.071045   51124 deployment_executor.go:212] deploymentExecutor.Execute(...): incoming events goroutine exiting
I1202 09:02:13.071840   51124 update.go:196] *** Update(preview=false) complete ***
(END)```

**Comment by lblackstone** [comment] 2022-12-02 19:11
Thanks for the update. It looks like this is probably an encoding bug in the underlying terraform provider: https://github.com/hashicorp/terraform-provider-aws/issues/23913

**Comment by flostadler** [comment] 2024-09-26 10:10
Hey @AleksandrAksenov , I had a look at this to see if it's still an issue.
This no longer reproduces on the latest pulumi-aws (`v6.52.0`) and pulumi (`v3.134.1`) versions.

I'm gonna close the issue, but please don't hesitate to close a new one if you're running into any other issues around this!

**Closed by flostadler** 2024-09-26 10:10 UTC
Labels: kind/bug, resolution/fixed, awaiting-upstream
