### ISSUE TITLE
aws.GetAvailabilityZones panics

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#1199] opened 2020-10-30 19:54 UTC
I'm using the Go SDK and trying to get the available azs in a region. The code is taken almost example from our generated example:

```go
// retrieve the available availability zones for the region
var t = true
available, err := aws.GetAvailabilityZones(ctx, &aws.GetAvailabilityZonesArgs{
  AllAvailabilityZones: &t,
}, nil)
```

And this is panicing:

```
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16d31f0]
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*Context).Invoke(0xc0001c8200, 0x3b0066d, 0x33, 0x33f60e0, 0xc0001cc5a0, 0x33f6160, 0xc00025e0e0, 0xc00021fb58, 0x1, 0x1, ...)
    	/Users/lbriggs/src/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/context.go:164 +0x1f0
    github.com/pulumi/pulumi-aws/sdk/v2/go/aws.GetAvailabilityZones(0xc0001c8200, 0xc0001cc5a0, 0xc00021fb58, 0x1, 0x1, 0x3adf8f8, 0x9, 0xc0001d7880)
    	/Users/lbriggs/src/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v2@v2.12.0/go/aws/getAvailabilityZones.go:122 +0xaf
    main.main.func1(0xc0001c8200, 0x3ae6d2e, 0x13)
    	/Users/lbriggs/src/git/jaxxstorm/infrastructure/aws/vpc/main.go:21 +0x1a5
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunWithContext(0xc0001c8200, 0x3b1a0d0, 0xc0000442cf, 0x3)
    	/Users/lbriggs/src/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:101 +0x1fb
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunErr(0x3b1a0d0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/lbriggs/src/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:82 +0x239
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.Run(0x3b1a0d0, 0x0, 0x0, 0x0)
    	/Users/lbriggs/src/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:39 +0x59
    main.main()
    	/Users/lbriggs/src/git/jaxxstorm/infrastructure/aws/vpc/main.go:12 +0x3e
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment] 2020-10-30 21:05
This is caused by passing `nil` as a resource option.  

```go
}, nil)
```

We should catch this early and provide a clean error instead.

The panic is from https://github.com/pulumi/pulumi/blob/v2.9.2/sdk/go/pulumi/context.go#L164.

**Comment by lukehoban** [comment] 2020-10-30 21:10
Ahh - we fixed in https://github.com/pulumi/pulumi/issues/5269.  Looks like you are using an older version before that fix.

**Closed by lukehoban** 2020-10-30 21:10 UTC
