### ISSUE TITLE
error on 'pulumi import aws:ebs/volume:Volume id vol-049df61146c4d7901'

### ISSUE THREAD

**Issue by ob-server83** [pulumi/pulumi-aws#1425] opened 2021-04-01 13:01 UTC
pulumi version-2.23.1
Getting error when importing aws:ebs/volume:Volume from https://www.pulumi.com/docs/reference/pkg/aws/ebs/volume/#import

EC2 Instance - Volume overview:
![image](https://user-images.githubusercontent.com/58702131/113296492-d69c1f80-92f9-11eb-8ca6-a1acac33501d.png)
and Volume Details that I want to import:
![image](https://user-images.githubusercontent.com/58702131/113297119-8a051400-92fa-11eb-9153-f40a5602665c.png)

## Expected behavior
The import should work.

## Current behavior
Getting error when importing aws:ebs/volume:Volume from https://www.pulumi.com/docs/reference/pkg/aws/ebs/volume/#import

```
>pulumi import aws:ebs/volume:Volume id vol-00aa3a2fcf5b6c7be
Previewing import (aws_import):
     Type                 Name                   Plan       Info
     pulumi:pulumi:Stack  aws_import-aws_import             1 error
 =   └─ aws:ebs:Volume    id                     import     3 errors

Diagnostics:
  aws:ebs:Volume (id):
    error: aws:ebs/volume:Volume resource 'id' has a problem: AtLeastOne: "snapshot_id": one of `size,snapshot_id` must be specified. Examine values at 'Volume.SnapshotId'.
    error: aws:ebs/volume:Volume resource 'id' has a problem: AtLeastOne: "size": one of `size,snapshot_id` must be specified. Examine values at 'Volume.Size'.
    error: Preview failed: one or more inputs failed to validate

  pulumi:pulumi:Stack (aws_import-aws_import):
    error: preview failed
```

## Steps to reproduce
1. Please note that my instance have multiple ebs_block_devices attached
2. `pulumi import aws:ebs/volume:Volume id vol-00aa3a2fcf5b6c7be`

## Context (Environment)
I want to import Volume and change type or IOPS on that Volume after import.

**Comment by viveklak** [comment] 2021-05-03 17:02
Duplicate of https://github.com/pulumi/pulumi/issues/6547

**Closed by viveklak** 2021-05-03 17:02 UTC
Labels: kind/bug, resolution/duplicate
