### ISSUE TITLE
Python package broken? "No module named 'get_ami'"

### ISSUE THREAD

**Issue by ouroboros8** [pulumi/pulumi-aws#258] opened 2018-07-03 19:07 UTC
Steps to replicate:

1. create & activate virtualenv
```
$ virtualenv pulumi && source pulumi/bin/activate
```
2. install pulumi
```
$ pip install pulumi pulumi-aws
```
3. import pulumi-aws
```
$ python -c 'import pulumi-aws'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dan/tmp/venv/lib/python3.6/site-packages/pulumi_aws/__init__.py", line 9, in <module>
    from get_ami import *
ModuleNotFoundError: No module named 'get_ami'
```

**Comment by ellismg** [comment] 2018-07-03 22:11
Unfortunately, Python 3 support is still a work in progress.  The above issue is due to us generating import directives which are no longer supported in Python 3.X.  We've started to address Python 3 support in our core runtime: (for example https://github.com/pulumi/pulumi/pull/1563) but we haven't yet landed support in packages like `pulumi_aws`.

https://github.com/pulumi/pulumi/issues/1535 tracks the overall effort to move to support Python 3 in addition to Python 2.7.

**Comment by swgillespie** [comment] 2018-07-04 13:36
This is a duplicate of https://github.com/pulumi/pulumi-terraform/issues/184 - we can't generate absolute imports like we are today if we want them to work on Python 3.

**Closed by swgillespie** 2018-07-04 13:36 UTC
