### ISSUE TITLE
Updating versioned lambda fails in `v6.13.2` on type mismatch

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi-aws#3118] opened 2023-12-11 11:34 UTC
### What happened?

After updating the package from 6.13.0 to 6.13.2. I cannot update my lambda code because of an error (see below).
If I downgrade back to 6.13.0 the error is gone.

### Example

```
import * as pulumi from "@pulumi/pulumi";
import * as awsClassic from "@pulumi/aws";

  const role = new awsClassic.iam.Role(`lambda-${name}-role`, {
    assumeRolePolicy: awsClassic.iam.assumeRolePolicyForPrincipal({ Service: `lambda.amazonaws.com` }),
    managedPolicyArns: additionalPolicies.concat([
      awsClassic.iam.ManagedPolicy.AWSLambdaBasicExecutionRole,
      awsClassic.iam.ManagedPolicy.AWSXRayDaemonWriteAccess
    ]),
  });

const mailerLambdaFn = new awsClassic.lambda.Function("lambda-testing", {
  code: new pulumi.asset.AssetArchive({
    ".": new pulumi.asset.FileArchive("./lambdas/testfolder/"), <--- put an empty simple index.mjs inside.
  }),
  runtime: "nodejs20.x",
  handler: "index.handler",
  architectures: ["arm64"],
  role: role.arn,
  name: pulumi.concat("testing"),
  timeout: 10,
  memorySize: 512,
  publish: true,
});
```

Running similar code as above fails on update with v6.13.2.

Error that I get is below. It indicates that an expected type changed.

```

 panic: inconsistent map element types (cty.String then cty.Number)
    goroutine 874 [running]:
    github.com/hashicorp/go-cty/cty.MapVal(0xc00d818560)
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200723130312-85980079f637/cty/value_init.go:207 +0x2fd
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValueOfMapType({{0x10155ef0, 0xc00e746f40}}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:178 +0x337
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValue({{0x10155ef0, 0xc00e746f40}}, {0xcec8040?, 0xc00e60a240?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:107 +0x2be
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValueOfObjectType({{0x10155f60, 0xc00cbb9a90}}, 0x4000?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:191 +0x225
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValue({{0x10155f60, 0xc00cbb9a90}}, {0xcec8040?, 0xc00e60a210?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:109 +0x2dc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValueOfListType({{0x10155e80, 0xc00e746fe0}}, {0xc00e746f30, 0x1, 0xc00d818d18?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:207 +0x187
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValue({{0x10155e80, 0xc00e746fe0}}, {0xc15d280?, 0xc00e236828?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:120 +0x1dc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValueOfObjectType({{0x10155f60, 0xc00cbb9ad8}}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:191 +0x225
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverCtyValue({{0x10155f60, 0xc00cbb9ad8}}, {0xcec8040?, 0xc00e60a150?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:109 +0x2dc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.recoverAndCoerceCtyValue(0xb9f7c1f?, {0xcec8040, 0xc00e60a150})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:82 +0x46
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.makeResourceRawConfig(0xcecac20?, 0xc00e60a270, 0xeac5b3e?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/cty.go:45 +0x3b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc000c05da0?, {0xc0000ff618?, 0x0?, 0x0?}}, {0xeac5b3e, 0x13}, {0x10155f98?, 0xc00e236468}, {0x10019de0, 0xc00e60a270})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfshim/sdk-v2/provider_diff.go:45 +0x14a
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc00149e000, {0x10155a70?, 0xc00e6ff290?}, 0xc00e1f5680)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.1-0.20231207205658-538570c1932f/pkg/tfbridge/provider.go:726 +0x74c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff.func1({0x1018a758?, 0xc00149e000?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:355 +0x30
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0xc009a10dc0?, 0x40, 0xc00d819720?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:320 +0xb5
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Diff(0x0?, {0x10155a70?, 0xc00e6ff290?}, 0x40?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:354 +0x65
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0x10155a70, 0xc00e6ff290}, {0xe4610c0?, 0xc00e1f5680})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.95.0/proto/go/provider_grpc.pb.go:575 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10155a70, 0xc00e6feab0}, {0xe4610c0, 0xc00e1f5680}, 0xc00e6b1440, 0xc00e6c0450)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0xe867ec0?, 0xc009a10dc0}, {0x10155a70, 0xc00e6feab0}, 0xc00e1f5600, 0xc00807ac60)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.95.0/proto/go/provider_grpc.pb.go:577 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000760000, {0x10155a70, 0xc00e6fea20}, {0x1016a9c0, 0xc00be061a0}, 0xc00e6c7680, 0xc005d56f90, 0x18a5abc8, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
    google.golang.org/grpc.(*Server).handleStream(0xc000760000, {0x1016a9c0, 0xc00be061a0}, 0xc00e6c7680)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 100
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145

```

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws         6.13.2
@pulumi/pulumi      3.96.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-12-12 03:11
Thank you for reporting this with a repro! Having a quick Look.

The root cause here very likely involves missing a case in the fix for https://github.com/pulumi/pulumi-aws/issues/3094

**Comment by t0yv0** [comment] 2023-12-12 03:30
Actually I'm running into some difficulties reproducing. Perhaps there is something relevant in additionalPolicies that is not included in the listed code?

I've tried this simplified code:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as awsClassic from "@pulumi/aws";

const role = new awsClassic.iam.Role(`lambda-testpanic-role`, {
    assumeRolePolicy: awsClassic.iam.assumeRolePolicyForPrincipal({ Service: `lambda.amazonaws.com` }),
    managedPolicyArns: [
        awsClassic.iam.ManagedPolicy.AWSLambdaBasicExecutionRole,
        awsClassic.iam.ManagedPolicy.AWSXRayDaemonWriteAccess
    ],
});

const mailerLambdaFn = new awsClassic.lambda.Function("lambda-testing", {
  code: new pulumi.asset.AssetArchive({
    ".": new pulumi.asset.FileArchive("./lambdas/testfolder/"), //<--- put an empty simple index.mjs inside.
  }),
  runtime: "nodejs20.x",
  handler: "index.handler",
  architectures: ["arm64"],
  role: role.arn,
  name: pulumi.concat("testing"),
  timeout: 10,
  memorySize: 512,
  publish: true,
});

```

The script I am using to test looks like this (changing the node version pulls in the matching provider version automatically):

```
npm i "@pulumi/aws@5.42.0"
pulumi up --yes
npm i "@pulumi/aws@6.13.2"
pulumi up --yes
```

Would appreciate help narrowing down the repro or running the failing program with PULUMI_DEBUG_GRPC="$PWD/log.json" and finding the offending method call which could help pin this down as well.

**Comment by Jimmy89** [comment] 2023-12-12 18:21
I ran the script, and it's hard to get an exact cause. I see an issue with a SQS pool, but nothing clear or specific.

The good news is: I just tried to run the script with release 6.13.3 and I did not get any errors, so it seems #3094 fixed it.

**Comment by t0yv0** [comment] 2023-12-12 18:27
Very good to know that you are unblocked, thanks for getting back quickly!

I went ahead and put some randomized tests on the recoverCtyValueOfMapType function and I was able to reproduce the panic at unit test level at least, and got a fix for that just in case:

https://github.com/pulumi/pulumi-terraform-bridge/pull/1568

**Comment by t0yv0** [comment] 2023-12-12 19:03
I'm going to remove P1 here as the users are not known to be blocked at the moment, but if anyone is hitting this panic please comment and we can prioritize it back as P1. As things stand the next week's release should close the possibility of this code to panic via https://github.com/pulumi/pulumi-terraform-bridge/pull/1568. Thank you.

**Comment by t0yv0** [comment] 2024-04-04 14:10
I'm going to close this on the assumption that it got fixed by the bridge commit which has since been included in this provider. Please reopen if you are hitting this again.

**Closed** 2024-04-04 14:10 UTC
Labels: kind/bug, impact/panic, resolution/fixed
