### ISSUE TITLE
After importing ec2 LaunchTemplate pulumi is overriding the field metadataOptions

### ISSUE THREAD

**Issue by infa-nang** [pulumi/pulumi-aws#2410] opened 2023-03-10 15:10 UTC
### What happened?

We have imported aws:ec2/launchTemplate:LaunchTemplate and below is `properties.metadataOptions` field generated by pulumi
```
metadataOptions:
        httpProtocolIpv6:
        httpPutResponseHopLimit: 2
        instanceMetadataTags:
```
and we got the below warning
`warning: aws:ec2/launchTemplate:LaunchTemplate resource 'eks-7ebac768-64e1-c53e-564a-96421a8be6ad' has a problem: expected metadata_options.0.instance_metadata_tags to be one of [disabled enabled], got . Examine values at 'LaunchTemplate.MetadataOptions.InstanceMetadataTags'.`

we manually fixed the metadataOptions as below

```
metadataOptions:
        httpProtocolIpv6: disabled
        httpPutResponseHopLimit: 2
        instanceMetadataTags: disabled
```

then we executed `pulumi preview -r --diff` and below mentioned is the diff

```
    ~ aws:ec2/launchTemplate:LaunchTemplate: (update)
      ~ metadataOptions: {
          + httpProtocolIpv6    : "disabled"
          + instanceMetadataTags: "disabled"
        }
```
then we ran `pulumi up`, we observed that  pulumi updated the `httpPutResponseHopLimit` to `0`, and again we did a `pulumi preview -r --diff` if was showing the below diff

```
 ~ metadataOptions: {
          ~ httpPutResponseHopLimit: 0 => 2
          + instanceMetadataTags   : "disabled"
        }
 ```

### Expected Behavior

* Pulumi should not updated `httpPutResponseHopLimit`
* It should import `httpProtocolIpv6` and `instanceMetadataTags` fields properly

### Steps to reproduce

* pulumi import aws:ec2/launchTemplate:LaunchTemplate aws-some-launch-template-name aws-some-launch-template-id
* pulumi preview -r --diff
* pulumi up -r

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  12.6.2
Arch     x86_64

This project is written in yaml

Current Stack: dev

TYPE                                   URN
pulumi:pulumi:Stack                    urn:pulumi:dev::pulumi-import::pulumi:pulumi:Stack::pulumi-import-dev
pulumi:providers:aws                   urn:pulumi:dev::pulumi-import::pulumi:providers:aws::default
aws:ec2/launchTemplate:LaunchTemplate  urn:pulumi:dev::pulumi-import::aws:ec2/launchTemplate:LaunchTemplate::aws-some-launch-template-name

Found no pending operations associated with dev

Backend        
Name           INM1D5LG7MD6M
URL            file://state
User           nang
Organizations  

No dependencies found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-03-13 07:41
Thanks for reporting this! From the surface, it looks like we may need better handling of default values since the empty fields in the generated Pulumi code is likely due to an empty response from the AWS API server. I will have to take a deeper look into this to see what's the best way to resolve the issues you reported.

**Comment by t0yv0** [comment] 2024-04-22 21:18
Related: https://github.com/pulumi/pulumi-aws/issues/1940 import LaunchTemplate warnings

**Comment by corymhall** [comment] 2024-07-03 15:07
@infa-nang I've just tried to reproduce this issue and I haven't been able to. If you are still seeing this issue can you provide a code example that we can use to reproduce? I've tried a couple different scenarios, but the launch template always imports cleanly.

**Comment by corymhall** [comment] 2024-07-22 19:00
@infa-nang I'm going to go ahead and close this issue since we can't reproduce the issue. If you are still seeing this issue please let us know and I can reopen this.

**Closed by corymhall** 2024-07-22 19:00 UTC
Labels: kind/bug, resolution/no-repro, needs-repro, awaiting-feedback, area/import
