### ISSUE TITLE
Non-deterministic results for `pulumi up`

### ISSUE THREAD

**Issue by chrrlesWork** [pulumi/pulumi-aws#3641] opened 2024-03-15 04:42 UTC
### What happened?

Multiple runs of `pulumi up` result in different outputs for the preview.  Some runs result in no error, while other runs produce errors (with different resources each time).

The resources were recently imported with no issues, and I can find no major differences between my create code and the code generated by `pulumi import`

### Example

![Screenshot 2024-03-15 122351 edit](https://github.com/pulumi/pulumi-aws/assets/162972793/6f272244-0ab6-4fe4-8cd6-d72d9c45d5a8)
![Screenshot 2024-03-15 123351 edit](https://github.com/pulumi/pulumi-aws/assets/162972793/6587e087-511f-4b42-808c-6729ff79e3c0)

### Output of `pulumi about`

![Screenshot 2024-03-15 123737 - pulumi about](https://github.com/pulumi/pulumi-aws/assets/162972793/71c737a8-03ec-4598-96ad-12613fe61e4c)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-03-15 11:33
Hi @chrrlesWork. I'm sorry you're hitting this error. Can you please provide a repro for us: a set of steps (including your code) that we can follow so we see the error on our own computer?

It's very hard for us to fix bugs if we are not able to reproduce the bug on our side.

**Comment by chrrlesWork** [comment] 2024-03-19 00:56
> Hi @chrrlesWork. I'm sorry you're hitting this error. Can you please provide a repro for us: a set of steps (including your code) that we can follow so we see the error on our own computer?
> 
> It's very hard for us to fix bugs if we are not able to reproduce the bug on our side.

Hello @iwahbe,

I was able to find the cause and move past this error.  This behavior occurs when specifying the `pulumi.Parent()` option on resources imported without a declared parent.

For example in `record, err := route53.NewRecord(ctx, recordName, recordArgs, pulumi.Protect(true), pulumi.Parent(zone))` here:
```
func createRecord(ctx *pulumi.Context, r conf.ResourceRecordSet, zone *route53.Zone) (*route53.Record, error) {
  recordName := r.Name + "_" + r.Type
  recordArgs := &route53.RecordArgs{
    ZoneId: zone.ZoneId,
    Name:   pulumi.String(r.Name),
    Type:   pulumi.String(r.Type),
  }
  // Alias types with a target have an additional Alias field and no custom TTLs
  if r.Type == "A" || r.Type == "AAAA" {
    if r.AliasTarget != nil {
      recordAliasArgs := route53.RecordAliasArray{
        &route53.RecordAliasArgs{
          Name:                 pulumi.String(r.AliasTarget.DNSName),
          EvaluateTargetHealth: pulumi.Bool(r.AliasTarget.EvaluateTargetHealth),
          ZoneId:               pulumi.String(r.AliasTarget.HostedZoneId),
        },
      }
      recordArgs.Aliases = recordAliasArgs
    } else {
      recordArgs.Ttl = pulumi.Int(r.TTL)
    }
    if r.Failover != "" {
      recordName = recordName + "_" + r.SetIdentifier
      recordArgs.FailoverRoutingPolicies = route53.RecordFailoverRoutingPolicyArray{
        &route53.RecordFailoverRoutingPolicyArgs{
          Type: pulumi.String(r.Failover),
        },
      }
    }
  } else {
    recordArgs.Ttl = pulumi.Int(r.TTL)
  }
  if r.HealthCheckId != "" {
    recordArgs.HealthCheckId = pulumi.String(r.HealthCheckId)
  }
  if r.SetIdentifier != "" {
    recordArgs.SetIdentifier = pulumi.String(r.SetIdentifier)
  }
  // Populate resource records, if any
  if r.ResourceRecords != nil {
    resourceRecords := pulumi.StringArray{}
    for _, rr := range r.ResourceRecords {
      resourceRecords = append(resourceRecords, pulumi.String(rr.Value))
    }
    recordArgs.Records = resourceRecords
  }
  record, err := route53.NewRecord(ctx, recordName, recordArgs, pulumi.Protect(true), pulumi.Parent(zone))
  if err != nil {
    return nil, err
  }
  return record, nil
}
...
  // Create the domain records
  records := []*route53.Record{}
  for _, r := range cfg.HostedZone.ResourceRecordSets {
    record, err := createRecord(ctx, r, zone)
    if err != nil {
      return nil, err
    }
    records = append(records, record)
  }
```

My initial import script did not specify a parent:
```
    for record in hostedZone["ResourceRecordSets"]:
        tag = "%s_%s" % (record["Name"], record["Type"])
        subprocess.run(["pulumi", "import", "aws:route53/record:Record", tag, zoneId+"_"+tag, "-o", "generated/%s.go" % tag, "--skip-preview", "-y"])
```

This problem has gone away with this change:
```
    # Import Records
    for record in hostedZone["ResourceRecordSets"]:
        recordName = "%s_%s" % (record["Name"], record["Type"])
        subprocess.run(
            [
                "pulumi",
                "import",
                "aws:route53/record:Record",
                recordName,
                zoneId + "_" + recordName,
                "--generate-code=false",
                "--skip-preview",
                "-y",
                "--parent",
                urn,
            ]
        )
```

Please note that code generation in this version is disabled because of this issue: https://github.com/pulumi/pulumi/issues/15410

**Comment by iwahbe** [comment] 2024-03-25 14:12
> > Hi @chrrlesWork. I'm sorry you're hitting this error. Can you please provide a repro for us: a set of steps (including your code) that we can follow so we see the error on our own computer?
> > It's very hard for us to fix bugs if we are not able to reproduce the bug on our side.
> 
> Hello @iwahbe,
> 
> I was able to find the cause and move past this error. This behavior occurs when specifying the `pulumi.Parent()` option on resources imported without a declared parent.
> 
> For example in `record, err := route53.NewRecord(ctx, recordName, recordArgs, pulumi.Protect(true), pulumi.Parent(zone))` here:
> 
> ...
>
> Please note that code generation in this version is disabled because of this issue: [pulumi/pulumi#15410](https://github.com/pulumi/pulumi/issues/15410)

Are you saying that the `delete` behavior or the non-determinism occurs when `pulumi.Parent()` is omitted? I would expect to see deletes if the code you have includes different parent's then what was imported, since resources are named based on their parents.

**Comment by t0yv0** [comment] 2024-09-24 22:06
Going to close this as no/repro. It looks like there still might be some underlying issue but it's too difficult for us to make progress without a smaller self-contained repro, apologies. Please file a new issue with a repro if this still is a problem for you. Appreciated.

**Closed by t0yv0** 2024-09-24 22:06 UTC
Labels: kind/bug, resolution/no-repro, needs-repro
