### ISSUE TITLE
Imagebuilder: ResourceDependencyException: Resource dependency error

### ISSUE THREAD

**Issue by sashaaKr** [pulumi/pulumi-aws#1473] opened 2021-04-29 09:28 UTC
When I'm trying to update image `imagebuilder.Component` data, getting `ResourceDependencyException: Resource dependency error`:
```
     Type                           Name                                                            Status                  Info
     pulumi:pulumi:Stack            dev-workflow-service-dev-workflow-development-us-east-1-shared  **failed**              1 error
 -   └─ aws:imagebuilder:Component  dev_env                                                         **deleting failed**     1 error

Diagnostics:
  aws:imagebuilder:Component (dev_env):
    error: deleting urn:pulumi:dev-workflow-development-us-east-1-shared::dev-workflow-service::aws:imagebuilder/component:Component::dev_env: 1 error occurred:
    	* error deleting Image Builder Component (arn:aws:imagebuilder:us-east-1:824464961347:component/dev-env-e243ad8/1.0.1/1): ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:us-east-1:824464961347:component/dev-env-e243ad8/1.0.1/1' has other resources depended on it.

  pulumi:pulumi:Stack (dev-workflow-service-dev-workflow-development-us-east-1-shared):
    error: update failed
```

## Expected behavior

Update should work.

## Steps to reproduce
Here is code `TS` to reproduce this error:
```ts
const VERSION = `1.0.3`;
const componentSetup = readFileSync('./dev-env/component-setup.yml', 'utf-8');

export const devEnvComponent = new imagebuilder.Component('dev_env', {
  data: componentSetup,
  description: 'This component include all required installs for dev env',
  platform: "Linux",
  version: VERSION,
});

const devEnvImageBuilderRole = new iam.Role("dev-env-image-builder", {
  assumeRolePolicy: {
      Version: "2012-10-17",
      Statement: [{
          Action: "sts:AssumeRole",
          Principal: {
              Service: "ec2.amazonaws.com"
          },
          Effect: "Allow",
          Sid: "",
      }]
  },
});

 new iam.RolePolicyAttachment("dev-env-image-builder-ssn", {
  role: devEnvImageBuilderRole,
  policyArn: 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore',
});

new iam.RolePolicyAttachment("dev-env-image-builder-ec2-ecr", {
  role: devEnvImageBuilderRole,
  policyArn: 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds',
});

new iam.RolePolicyAttachment("dev-env-image-builder-ec2", {
  role: devEnvImageBuilderRole,
  policyArn: 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder',
});

const profile = new iam.InstanceProfile("dev-env-instance-profile", { role: devEnvImageBuilderRole });

export const devEnvInfrastructureConfiguration = new imagebuilder.InfrastructureConfiguration("dev_env", {
  instanceProfileName: profile.name,
});

export const devEnvImgRecipe = new imagebuilder.ImageRecipe("dev_env", {
  blockDeviceMappings: [{
      deviceName: "/dev/xvda",
      ebs: {
          volumeSize: 100,
          volumeType: "gp2",
      },
  }],
  components: [{
      componentArn:  devEnvComponent.arn,
  }],
  parentImage: "arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-2-ecs-optimized-x86/x.x.x",
  version: VERSION,
});

const weeklyCron = 'cron(0 9 ? * mon)';
export const devEnvImagePipeline = new imagebuilder.ImagePipeline("dev-env", {
  imageRecipeArn: devEnvImgRecipe.arn,
  infrastructureConfigurationArn: devEnvInfrastructureConfiguration.arn,
  schedule: {
      scheduleExpression: weeklyCron,
  },
});
```

**Comment by cprice404-aws** [comment] 2021-05-24 02:53
this happens to me every time I attempt to change a component as well.

**Comment by cprice404-aws** [comment] 2021-05-24 02:54
The error goes away if I manually delete both the Image and the Recipe from the previous builds, but it seems like the graph should recognize that those need to be refreshed/deleted.

**Comment by matwerber1** [comment] 2021-08-19 18:23
I am getting the same error, even when explicitly defining `dependsOn: myImageComponent` on my `aws.imagebuilder.ImageRecipe` resource.

**Comment by eugene-riabchuk** [comment] 2021-11-15 18:42
has anyone had a chance to resolve this issue?

**Comment by k-weaver** [comment] 2021-12-21 16:27
I believe this is expected behavior. These same actions performed in the AWS console would yield the same results; You cannot modify a component in use, you can only create a new version of it. This gets tricky with having a state file and IaC. There is no way for Pulumi to auto create a new version when you make a change, because you've only got one item defined.

One work around to this would be to create a second component with your updates and bump the version. If your change happens to be in the yaml file being referenced, you would need to create a second yaml file with the changes. Reference this new file and create the new component. 

The work around I've used is referencing the wildcard of the component in the recipe, details [here](https://docs.aws.amazon.com/imagebuilder/latest/userguide/ibhow-semantic-versioning.html). This breaks the dependency and ensures the recipe is using the latest. 

This isn't super straight forward as doing what I suggest means you cannot just reference the component resource _(in the recipe)_ that is being created. You will have to fabricate the ARN on your own, which brings another set of issues as the component will likely not exist when the recipe is created; Assuming you continue to create everything in one stack.

I ended up splitting out my component creation(s) into their own stack. Recipe/Pipeline/Infra configs all get created in another stack. I fabricate the ARN of the component(s) myself (referencing the wildcard of the component version), then pass that into the recipe.

**Comment by corymhall** [comment] 2024-06-14 19:16
It looks like this issue may have been fixed in a more recent version of pulumi. I've tried to reproduce the issue using the example app provided (thanks for providing that!) and I never receive any error messages when changing the data in the component resource.

Let me know if anyone is still receiving this error message.

**Closed** 2024-07-01 15:35 UTC
Labels: kind/bug, resolution/no-repro, needs-repro, awaiting-feedback
