### ISSUE TITLE
When getting an existing EKS cluster, there isn't a way to pull the kubeconfig

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-aws#478] opened 2019-02-22 21:40 UTC
In the current eks object, we can use the `cluster` props: `certificateAuthority`, `name`, and `endpoint` to fill in the blanks in the kubeconfig file https://gist.github.com/b01eeecacccc3e284771463ed626af5e

we only do this right now in the eks object constructor, when we should actually have a `kubeconfig()` method on the object.

see community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1550871454193500?thread_ts=1550862777.160400&cid=C84L4E3N1

**Comment by stack72** [comment] 2019-07-30 10:29
@metral I think this can be achieved using the import functionality right?

**Comment by stack72** [comment] 2019-08-14 11:45
ping @metral :)

**Comment by metral** [comment] 2019-08-16 00:58
@stack72 Apologies for the delay in response! IIUC how the import works, it takes an existing object not created in Pulumi and imports it to use. If that is correct, then this does not seem like it will work for the `kubeconfig` file as that is not stored in the cluster at all - it is generated by whatever means instantiated the cluster.

The proper fix for this is to expose a `kubeconfig()` method.

What use case are you trying to handle?

**Comment by lukehoban** [comment] 2022-11-19 02:47
We support this in the [`eks` package](https://www.pulumi.com/registry/packages/eks/), but not currently in the raw AWS provider.  It would be nice to expose that function as a general capability, even for clusters not created by that package.  But I expect if we were to do that - we would add it to that package.  This is tracked in https://github.com/pulumi/pulumi-eks/issues/11#issuecomment-430349711, so I'll close this as a dupe of that at this point.

**Closed by lukehoban** 2022-11-19 02:47 UTC
Labels: kind/enhancement, resolution/duplicate
