### ISSUE TITLE
AWS performance tests started breaching 

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3330] opened 2024-01-26 15:52 UTC
### What happened?

#cli-performance-alerts started noting that the standard AWS tests are taking longer than the allowed threshold since Jan 5. 

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment] 2024-01-30 14:11
I ran the AWS tests locally and from the traces it looks like 75% of the time is spent in `CheckConfig` and `Configure`.

These two seem to be equally slow, with each taking about 1.5s during my local run.

**Comment by t0yv0** [comment] 2024-01-30 14:31
Yes these are particularly slow. These methods end up materializing all the SchemaMaps by calling SchemaFunc() inadvertently. This stresses the allocator. We might want to ensure that doesn't happen although to fully solve the problem we'll need to patch upstream. I think it might be worth it.

**Comment by t0yv0** [comment] 2024-01-30 14:33
https://github.com/pulumi/pulumi-aws/pull/3172 has some context here. At first we've improved performance by caching the Schema materialization but that cost us memory usage which was a more significant regression so in 3172 we had to drop the caching. There might be more factors in play than just this one but I think this one is definitely a significant factor. One can always inject a panic inside one of wafv2 SchemaFunc methods and try to run the provider with that to confirm it's being hit or not.

**Comment by VenelinMartinov** [comment] 2024-01-30 15:40
I added a bit more tracing around the code and have confirmed that for both of this virtually all the time is spent on the tf side:

For `CheckConfig`, all the time is in `awsbase.GetAwsConfig`, which gets and validates AWS credentials.

For `Configure`, virtually all the time is spent in the TF `Configure`.

I'll look into https://github.com/pulumi/pulumi-aws/pull/3172 and the `SchemaFunc`s, thanks for the suggestion!

**Comment by t0yv0** [comment] 2024-01-30 15:46
https://github.com/pulumi/pulumi-aws/issues/3044 also FYI we had a regression that was coming from upstream and sensitive to the awsbase and underlying AWS Go SDK version at some point, around parsing profiles. Could be that something upstream changed or could be a change on our end.

**Comment by VenelinMartinov** [comment] 2024-01-30 17:00
I tested the `update-empty` traces of `TestAccAwsPyS3Folder/benchmark` across `6.5`, `6.13`, `6.15`, `6.17` and `6.19` and the performance was pretty much the same, with `CheckConfig` and `Configure` dominating.

If anything, it looks like we've slightly improved - `6.5` took 4.4s, `6.13` 4.2s and the rest roughly 4s when testing locally.

How is the threshold data calculated? If that is correct, could the issue be coming from some performance regression in the AWS API?

**Comment by t0yv0** [comment] 2024-01-30 18:17
If you're not seeing any actual end-user degradation I think it's' fair game to re-calibrate the threshold using recent mean+stddev and reset to a higher threshold so we avoid spurious alerts. I can file suggestions for further improving Configure perf as a separate ticket that doesn't have to be a P1.

**Comment by t0yv0** [comment] 2024-01-30 18:18
Let's meet tomorrow morning and do it together.

**Comment by VenelinMartinov** [comment] 2024-02-01 13:21
Ok, as @t0yv0 suggested I investigated why we are calling the SchemaFuncs during `CheckConfig` and `Configure` as a possible way to optimize AWS startup performance.

Looks like there are two reasons we do that:
1. Applying auto-aliases. https://github.com/pulumi/pulumi-terraform-bridge/pull/1665 hacks it out - could we do this during tfgen and save for later?
2. TF seems to call the resources' `InternalValidate` during the provider `Validate`. This seems quite unnecessary, I suspect we could just do that during tfgen and then rely on the fact that the schema should be the same during runtime, so should be already validated. https://github.com/pulumi/terraform-plugin-sdk/pull/36 hacks it out.

Applying the two changes above I've verified in https://github.com/pulumi/pulumi-aws/pull/3368 that the panics I injected in the WAFv2 `SchemaFunc`s no longer trigger.

I retested `TestAccAwsPyS3Folder` with these changes and in my local tests this shaved off about 150ms from each of `CheckConfig` and `Configure`, so about 300ms total.


LMK what you think about this and if you think this is worth pursuing further.

**Comment by t0yv0** [comment] 2024-02-01 15:28
300ms is nothing to sneeze at, I wager if you looked at allocator stats and peak RAM use you could see a marked improvement as well. I think it's worth finishing out.

**Comment by VenelinMartinov** [comment] 2024-02-01 16:10
Ok, I think I can solve 2. by threading in a parameter for `RunResourceValidation` or something like that from aws tfgen's main.

After looking at 1 again I think that is already solved: https://github.com/pulumi/pulumi-terraform-bridge/blob/2bf0fe56ae8846c9be038e61cf97291a064268d4/pkg/tfbridge/auto_aliasing.go#L63

I believe I was seeing the behaviour because I was running it in a test, so we couldn't guess the `rutimeStage`.

I'll spin up a plugin sdk and aws PR for the changes.

**Comment by t0yv0** [comment] 2024-02-01 16:24
That's right, the tests currently mis-guess the runtime stage I thought I have a ticket on that.

**Comment by t0yv0** [comment] 2024-02-01 18:01
Also possible to solve cleanly with some extra parameters.

**Comment by VenelinMartinov** [comment] 2024-02-01 21:12
I've raised https://github.com/pulumi/terraform-plugin-sdk/pull/37 with the changes to address the `InternalValidate` in plugin-sdk during runtime

**Comment by VenelinMartinov** [comment] 2024-02-03 00:13
https://github.com/pulumi/pulumi-aws/pull/3377 should hopefully bring the test under the threshold again!

**Comment by t0yv0** [comment] 2024-02-03 06:09
Let's wait a bit to confirm.

**Comment by t0yv0** [comment] 2024-02-05 15:16
Yes, we can also document our findings a little bit better, I've heard from you that test benchmark variance increased for some reason we don't fully understand but there was no perceptible difference running the test locally; we took the opportunity to shave off 300ms and some RAM usage by fixing a known bottleneck, and now need to recalibrate if the lower baseline will stop alerting or we still need to consider doing something about the increased variance of the benchmark.

**Comment by t0yv0** [comment] 2024-02-06 16:33
I can confirm this is no longer breaching. The last breach was on the Go S3 folder benchmark. Upon investigation, this benchmark was not receiving the latest versions of the AWS provider https://github.com/pulumi/examples/pull/1576

**Comment by t0yv0** [comment] 2024-02-09 14:19
The problem didn't quite resolve itself and the signal continues to have high variance. Investigating the source of variance a bit, time spent talking to service backend is suspect.

**Comment by lukehoban** [comment] 2024-02-13 05:13
After landing https://github.com/pulumi/examples/pull/1584 and https://github.com/pulumi/examples/pull/1585, we're seeing materially more stable, and lower, baselines.  I'm going to, slightly optimistically, close this out, and we can reactive again (or open a new issue), if we see new regressions or breaches on these tests.

**Closed by lukehoban** 2024-02-13 05:13 UTC
Labels: kind/bug, impact/performance, resolution/fixed, p1, impact/regression
