### ISSUE TITLE
Flake8 errors with Cloudfront argument classes in Python

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi-aws#1581] opened 2021-07-24 09:16 UTC
When creating a `cloudfront.Distribution` in Python, you can either use a `dict` for certain parameters or a properly typed `class`

One such class is `cloudfront.CachePolicyParametersInCacheKeyAndForwardedToOriginCookiesConfigCookiesArgs`.

The problem is that such class names are way too long compared to the PEP8 recommendations (80 characters maximum per line) or even the famous Python formatter `black` (which specifies 88 characters per line instead)

As such, you're pretty much always gonna get a `flake8` error on all the super-long lines of code that use these classes.

## Steps to reproduce

```python
len("cloudfront.CachePolicyParametersInCacheKeyAndForwardedToOriginCookiesConfigCookiesArgs")
```

Expected: much smaller
Actual: 86

## Proposed fix

Instead of `cloudfront.CachePolicyParametersInCacheKeyAndForwardedToOriginCookiesConfigCookiesArgs`

Maybe forego the whole "ParametersInCacheKeyAndForwardedToOrigin" shenanigans and rename the class to:
`cloudfront.CachePolicyCookiesConfigCookiesArgs`

(and still, it's a bit verbose 😓 )

## In the meantime

For those of you like me that are struggling on this, you just need to add `# noqa` at the end of each of those huge lines, and `flake8` will simply ignore them.

It's not great though, because the overall readability of the code (especially on tablet & mobile) is still affected !

**Comment by leezen** [comment] 2021-07-26 19:16
@LouisAmon I agree that these are fairly verbose names and conflict w/ PEP8 recommendations. That said, I'm going to re-label as an `enhancement` given these are currently based on automatically generating the type names from the underlying resource and property names.

**Comment by lukehoban** [comment] 2022-12-28 00:08
I'm going to close this out as By Design, since the current approach is necessarily automated based on the schema, and for complex deeply nested resource types, these names need to be unique based on the entire nesting path.  There is no near-term way to systematically reduce the length of these type names.  We could track an issue in pulumi/pulumi to investigate a structurally sound way to simplify generated type names in general - but this would also be a breaking change across all providers, so would be a somewhat complex undertaking until a major Pulumi version bump.

**Closed by lukehoban** 2022-12-28 00:08 UTC
Labels: kind/enhancement, resolution/by-design
