### ISSUE TITLE
AWS Provider v6 Dogfood Report

### ISSUE THREAD

**Issue by caseyyh** [pulumi/pulumi-aws#2626] opened 2023-07-19 00:40 UTC
## Summary

Release: https://github.com/pulumi/pulumi-aws/releases/tag/v6.0.0-alpha.4
Diff: https://github.com/pulumi/pulumi-service/compare/casey/v6?expand=1
Migration Guide: https://github.com/pulumi/pulumi-aws/pull/2623/files (ie, highlighting only the things not captured here)

## `pulumi preview`

https://app.pulumi.com/pulumi/pulumi-service/casey/previews/153e968b-c640-49f6-88ef-0fabf8dcd32d

Note that the preview gave this warning:

```
info: This update will leave 2 resource(s) untracked in your environment:
    - aws:s3:BucketObject workflow-runner-linux-amd64
    - aws:s3:BucketObject pulumi-deploy-executor-linux-amd64
```

These resources were defined here: 

https://github.com/pulumi/pulumi-service/blob/279c141c616b0da380a25bd840a2b87ac10f2196/infrastructure/workflow/binaries.ts#L17-L29

The following captures what code changes I needed to make to get `pulumi preview` working.

### 1. aws.GetCallerIdentity

Error Message:

```
    workflow/service.ts(168,54): error TS2345: Argument of type '{ parent: this; }' is not assignable to parameter of type 'GetCallerIdentityArgs'.
      Object literal may only specify known properties, and 'parent' does not exist in type 'GetCallerIdentityArgs'.
```

What it took to silence this:

```typescript
   const awsAccountId = aws.getCallerIdentity({ /*parent: this*/ }).then(id => id.accountId);
```

### 2. ServiceServiceConnectConfiguration

Error Message:

```
    services/ratelimit.ts(254,9): error TS2322: Type '{ enabled: true; namespace: pulumi.Output<string>; service: { clientAliases: { port: number; }[]; portName: string; }; }' is not assignable to type 'Input<ServiceServiceConnectConfiguration> | undefined'.
      Object literal may only specify known properties, and 'service' does not exist in type 'Input<ServiceServiceConnectConfiguration>'.
```

<details>

<summary>View relevant resource</summary>

```typescript
ratelimitEcsService = new aws.ecs.Service(
    "ratelimit-", // Add dash before hash suffix.
    {
      cluster: ecsCluster.id,
      taskDefinition: task.taskDefinitionArn,
      desiredCount: config.ratelimitServiceDesiredCount,
      waitForSteadyState: config.waitForECS,
      deploymentMaximumPercent:
        config.clusterNumInstances >= 4 ? 150 : 200,
      orderedPlacementStrategies: [
        {
          field: "attribute:ecs.availability-zone",
          type: "spread"
        },
        {
          field: "instanceId",
          type: "spread"
        }
      ],
      // Migrating to new ASG for #11276
      placementConstraints: [{
          type: "memberOf",
          expression: "registeredAt > 2023-02-07",
      }],
      networkConfiguration: {
          securityGroups: [ecsClusterInstanceSecurityGroup.id],
          subnets: pulumi.all(ecsSubnets.map(s => s.id)),
      },
      serviceConnectConfiguration: {
        enabled: true,
        namespace: namespace.arn,

// ERROR STARTS HERE

        service: {
          clientAliases: [{
            port: 8081
          }],
          portName: "ratelimit"
        }

// ERROR CODE ENDS
      }
    },
    {
      dependsOn: [serviceASG],
    }
  );
```

</details>

### 3. Lambda EventSource

Error Message:

```
    error: unmarshaling urn:pulumi:casey::pulumi-service::pulumi-service:infrastructure:DynamoStreamer$aws:kinesis:StreamEventSubscription$aws:lambda/eventSourceMapping:EventSourceMapping::search-streamer-casey-subscription's instance state: could not read field queues: '' expected type 'string', got unconvertible type '[]interface {}', value: '[]'
```

This got `pulumi preview` to pass but failed on the `pulumi up`

```typescript
        const _ = new aws.kinesis.StreamEventSubscription(
            name + "-subscription",
            stream,
            handler,
            {
                startingPosition: "TRIM_HORIZON",
            },
            // {
            //     parent: this,
            // },
        );
```

## `pulumi up`

https://app.pulumi.com/pulumi/pulumi-service/casey/updates/385

A few resources failed to update after the successful `pulumi preview.`

```
aws:lambda:EventSourceMapping (audit-logs-streamer-subscription):
    error: 1 error occurred:
    	* creating Lambda Event Source Mapping (arn:aws:kinesis:us-west-2:372027080554:stream/audit-logs-streamer-stream-751af88): ResourceConflictException: The event source arn (" arn:aws:kinesis:us-west-2:372027080554:stream/audit-logs-streamer-stream-751af88 ") and function (" audit-logs-streamer-handler-8bd73bd ") provided mapping already exists. Please update or delete the existing mapping with UUID 525d037a-d89f-40e1-a19e-23ba37f12a65
    {
      RespMetadata: {
        StatusCode: 409,
        RequestID: "70ca11df-ea8a-47c0-9249-de5642116f23"
      },
      Message_: "The event source arn (\" arn:aws:kinesis:us-west-2:372027080554:stream/audit-logs-streamer-stream-751af88 \") and function (\" audit-logs-streamer-handler-8bd73bd \") provided mapping already exists. Please update or delete the existing mapping with UUID 525d037a-d89f-40e1-a19e-23ba37f12a65",
      Type: "User"
    }
 
  aws:ec2:Eip (eip-public-subnet1):
    warning: urn:pulumi:casey::pulumi-service::aws:ec2/eip:Eip::eip-public-subnet1 verification warning: use domain attribute instead
 
  pulumi:pulumi:Stack (pulumi-service-casey):
    One or more access tokens for the status webhook registrations is empty. The service will not be able to process incident/component status updates from Bitbucket, GitHub, and GitLab.
    reCAPTCHA Site Key is empty. Email signups will not work.
    reCAPTCHA Secret Key is empty. Email signups will not work.
    GitHub PAT for token scanning service is empty. Calls to the public key endpoint will be rate-limited.
    Creating Service alarms without posting to Slack or PagerDuty.
    Skipping creation of Slack responder for billing-alert-topic due to either a missing Slack access token or channel name.
    Skipping creation of Slack responder for console-notification-topic due to either a missing Slack access token or channel name.
    Skipping creation of Slack responder for dependencies-topic due to either a missing Slack access token or channel name.
    Root domain config value undefined, creating new Route 53 Hosted Zone at: casey.pulumi-dev.io.
    Skipping database migration step for preview
    warning: provider config warning: skip_metadata_api_check: the use of values other than "true" and "false" is deprecated and will be removed in a future version of the provider
    AccountID: 372027080554
    (node:40536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    error: update failed
 
  aws:s3:BucketObject (workflow-runner-linux-amd64):
    warning: urn:pulumi:casey::pulumi-service::aws:s3/bucketObject:BucketObject::workflow-runner-linux-amd64 verification warning: use the aws_s3_object resource instead
    warning: urn:pulumi:casey::pulumi-service::aws:s3/bucketObject:BucketObject::workflow-runner-linux-amd64 verification warning: use the aws_s3_object resource instead
 
  docker:index:Image (consoleImage-arm64):
    error: executor failed running [/bin/sh -c yarn install]: exit code: 1
 
  aws:ec2:Eip (eip-public-subnet0):
    warning: urn:pulumi:casey::pulumi-service::aws:ec2/eip:Eip::eip-public-subnet0 verification warning: use domain attribute instead
 
  docker:index:Image (consoleImage-amd64):
    error: executor failed running [/bin/sh -c yarn install]: exit code: 1
```

**Comment by caseyyh** [comment] 2023-07-19 01:03
Let me know if you need more detail, etc. 🙃

**Comment by iwahbe** [comment] 2023-07-19 15:58
It looks like (1) is caused by upstream allowing the user to input a field: https://github.com/hashicorp/terraform-provider-aws/blob/0a175e3731648077a5457ec792cb53f5eb23dae1/internal/service/sts/caller_identity_data_source.go#L45-L48. Because we now have an argument, the signature of `getCallerIdentity`:
```patch
- function getCallerIdentity(opts?: pulumi.InvokeOptions): Promise<GetCallerIdentityResult>
+ function getCallerIdentity(args?: GetCallerIdentityArgs, opts?: pulumi.InvokeOptions): Promise<GetCallerIdentityResult>
```

You can recover old behavior by transitioning to this:
```go
   const awsAccountId = aws.getCallerIdentity({}, { parent: this }).then(id => id.accountId);
```

**Comment by lukehoban** [comment] 2023-07-20 00:54
(1) seems to be a fundamental forward compatibility issue with codegen. If we drop the args bag when there are no args, then when a new version adds args, it is a breaking change. We probably need to reconsider the codegen approach there - and always emit the variant with args. 

As a more general rule - backward compatible additions to schema should not lead to breaking changes in code generated SDKs.

**Comment by iwahbe** [comment] 2023-07-20 11:08
(2) is caused by `service` changing to `services`. This should fix it:
```patch
-        service: {
+        services: [{

          clientAliases: [{
            port: 8081
          }],
          portName: "ratelimit"
-        }
+        }]
```

This change was not introduced in `pulumi-aws` v6. Its currently services:
https://github.com/pulumi/pulumi-aws/blob/f787a47a2349b5b9024f9ddf1246668539a648a1/sdk/nodejs/types/input.ts#L22923-L22941

This was changed in 0d6441758e3fb50efe48de4441de419e1f5d42ce.

**Comment by iwahbe** [comment] 2023-07-20 14:39
It looks like the `queues` field transitioned from a `Set` to ` `List`, *and* TF has added `MaxItems=1` to the value. My current assumption is that the `MaxItems=1` has caused the shape change (and is causing the problem).

**Comment by iwahbe** [comment] 2023-07-21 16:36
We plan to take the breaking change on (1) for the major version. It will be called out in our migration guide when we launch.

I have opened https://github.com/pulumi/pulumi/issues/13563 to track addressing this (long term) fix in codegen.

**Comment by mikhailshilkov** [comment] 2023-07-25 11:08
@iwahbe Can we close this issue as done or are there still action items?

**Comment by iwahbe** [comment] 2023-07-25 11:58
We have addressed all items mentioned:
1. Addressed in the migration guide and https://github.com/pulumi/pulumi/issues/13563 opened to track upstream.
2. Breaking change unrelated to v5->v6, no addressing needed.
3. Fixed in the bridge and released in v6.0.0-alpha.5. 

Thanks @caseyyh for the helpful feedback!!!

**Closed by iwahbe** 2023-07-25 11:58 UTC
Labels: kind/bug, area/providers, impact/regression

**Comment by t0yv0** [comment] 2023-07-25 19:02
```warning: provider config warning: skip_metadata_api_check: the use of values other than "true" and "false" is deprecated and will be removed in a future version of the provider```

I am still getting this on the latest v6.  Let me know if this warrants another issue.

**Comment by lukehoban** [comment] 2023-07-25 20:51
> ```warning: provider config warning: skip_metadata_api_check: the use of values other than "true" and "false" is deprecated and will be removed in a future version of the provider```
>
> I am still getting this on the latest v6.  Let me know if this warrants another issue.

Yes - lets open an issue on this.  I assume this is an existing problem not specific to v6.
