### ISSUE TITLE
apigateway.BasePathMapping needs a 'name' input for deleteBeforeReplace

### ISSUE THREAD

**Issue by dror-g** [pulumi/pulumi-aws#1035] opened 2020-07-06 16:49 UTC
When making a change to basePathMapping resource, like changing its name or stage_name, a new resource will be created and the old one deleted.

This causes an error: `error: Error creating Gateway base path mapping: ConflictException: Base path already exists for this domain name`

A `name` input is required to prevent Pulumi auto-naming the resource, so that the `deleteBeforeReplace` opt will have effect.

**Comment by dror-g** [comment] 2020-07-06 17:14
Also, if you try to work-around by manually setting a different, unique base_path, deployment still fails as original mapping to api stage must be deleted first -

`error: deleting urn:pulumi:dev::aws-infra::ROAS:curve$APIgateway:<resource-name>$aws:apigateway/restApi:RestApi$aws:apigateway/deployment:Deployment::<resource-name>-deployment-dev: error deleting API Gateway Deployment (o6hmtd): BadRequestException: Active stages pointing to this deployment must be moved or deleted`

**Comment by dror-g** [comment] 2020-07-06 17:48
Also, if you try to work-around by manually setting a different, unique base_path, deployment still fails as original mapping to api stage must be deleted first -

`error: deleting urn:pulumi:dev...: error deleting API Gateway Deployment (o6hmtd): BadRequestException: Active stages pointing to this deployment must be moved or deleted`

**Comment by CanRau** [comment] 2020-08-23 21:53
Is this related to me always getting `Please remove all base path mappings related to the stage in your domains` when I try to destroy a stack? I'd thought Pulumi is there for me to remove resources in the correct order?

Also found this, probably related issue https://github.com/pulumi/pulumi-aws/issues/1026

**Comment by lukehoban** [comment] 2022-11-19 04:42
I believe this is indeed a dupe of #1026, which was itself fixed.

**Closed by lukehoban** 2022-11-19 04:42 UTC
Labels: kind/bug, resolution/fixed
