### ISSUE TITLE
IAM Users cannot be renamed

### ISSUE THREAD

**Issue by robwruck** [pulumi/pulumi-aws#1610] opened 2021-08-26 13:49 UTC
While AWS supports changing a User's name, this causes some problems for pulumi as dependent resources reference the user by name.

Pulumi version: 3.10.3
AWS plugin version: 4.17.0

## Steps to reproduce

1. Create a Pulumi script that creates an IAM user along with a UserPolicy, a UserPolicyAttachment and an AccessKey
2. Deploy via `pulumi up`
3. Change the user's name in the Pulumi script
4. Deploy via `pulumi up`

Expected: The user is renamed and dependent resources remain unchanged.
Actual: The user is renamed, but pulumi then tries to replace dependent resources to reflect the name change - which fails because they are looked up using the original user name:

```
    error: deleting urn:pulumi:dev::rename::aws:iam/accessKey:AccessKey::testuserAccessKey: 1 error occurred:
    	* Error deleting access key AKIAXXXXXXXXXXXXXXXXX: NoSuchEntity: The user with name testuser1 cannot be found.
    	status code: 404, request id: ...
```

After that, the IAM User has the new name but both the old and new versions of the UserPolicy and AccessKey since deleting the previous instance failed.

Doing a `pulumi refresh` then will detect that the user (using its original name) has been deleted. A subsequent `pulumi up` will still fail, because the user actually exists with the new name.

Pulumi script to reproduce (just change the username):

```
import * as aws from "@pulumi/aws";
import * as fs from "fs"

const basename = "testuser"
const username = "testuser2"

const testUserPolicy: aws.iam.PolicyDocument = {
    Version: "2012-10-17",
    Statement: [
        {
            Action: [
                "iam:GetUser"
            ],
            Effect: "Allow",
            Resource: "*",
        }
    ],
}

const testUserPolicies: Record<string, aws.iam.PolicyArgs> = {
    "test-s3-policy": {
      description: "Manage S3 resources",
      policy: {
        Version: "2012-10-17",
        Statement: [
          {
            Action: ["s3:ListBucket"],
            Effect: "Allow",
            Resource: "*"
          }
        ]
      }
    }
}

const user = new aws.iam.User(basename, {name: username})

new aws.iam.UserPolicy(`${basename}Policy`, {
    user: user.name,
    policy: testUserPolicy
})

for (const key in testUserPolicies) {
    const policy = new aws.iam.Policy(key, testUserPolicies[key])
    new aws.iam.UserPolicyAttachment(`${key}-attachment`, {
        user: user.id,
        policyArn: policy.arn
    })
}

const accessKey = new aws.iam.AccessKey(`${basename}AccessKey`, {
    user: user.name,
    pgpKey: fs.readFileSync("gpg.pub").toString()
})
```

**Comment by leezen** [comment] 2021-08-31 18:52
I think this is an unfortunate consequence of how the upstream provider has modeled the attachment by using `name` which is tied in to the identifier (which we'd expect to be stable). One way to work around this is to use `{ replaceOnChanges: ["name"] }` as a resource option for the `iam.User` which will cause cascading replaces for the related resources and you should be able to successfully create/delete the resources.

I don't think restructuring the upstream provider's model of IAM is feasible, so I'll close this issue out as unfortunately "by design" (given the way it's modeled).

**Closed by leezen** 2021-08-31 18:52 UTC
Labels: kind/bug, resolution/by-design
