### ISSUE TITLE
TargetGroup creation error: Health check matcher HTTP code cannot be empty

### ISSUE THREAD

**Issue by jackwtech** [pulumi/pulumi-aws#3746] opened 2024-03-28 04:16 UTC
### What happened?

When trying to create a target group that the protocol version is gRPC with health_check, the HTTP code has passed to the matcher but still raise ValidationError as below. 

However, if the target group is first created without health_check, then update the stack with the health_check, there is no error raised.

```
  aws:lb:TargetGroup (test):
    error: 1 error occurred:
        * creating ELBv2 Target Group (test-20240328040351566400000001): ValidationError: Health check matcher HTTP code cannot be empty
        status code: 400, request id: c0eb6f8b-7050-45fe-8a57-f6596739ac23
```

### Example

```
import pulumi_aws as aws

default_vpc = aws.ec2.DefaultVpc(
    "default",
    tags={
        "Name": "Default VPC",
    },
)

praefect_target_group = aws.lb.TargetGroup(
    "test",
    name_prefix="test-",
    port=1234,
    protocol="TCP",
    protocol_version="GRPC",
    health_check=aws.lb.TargetGroupHealthCheckArgs(
        enabled=True,
        matcher="200",
        path="/",
        port=80,
        protocol="HTTP",
    ),
    target_type="instance",
    vpc_id=default_vpc.id,
)
```

### Output of `pulumi about`

CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.27.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2024-03-28 13:37
Thank you for letting us know @jackwtech

**Comment by mikhailshilkov** [comment] 2024-04-01 10:10
I think this is by design.

This failure started appearing in Pulumi.AWS v. 6.10.0 / terraform-aws 5.27.0, likely due to https://github.com/hashicorp/terraform-provider-aws/pull/34488

Terraform emits a more helpful warning:

```
Attribute "protocol_version" cannot be specified when "protocol" is "TCP".

This will be an error in a future version.
```

@jackwtech Do you need to change the `protocol` to HTTP?

Anyway, this is reproducible with TF too:

```hcl
resource "aws_lb_target_group" "praefect_target_group" {
    vpc_id="myvpc"
    name_prefix="test-"
    port=1234
    protocol="TCP"
    protocol_version="GRPC"
    health_check {
        enabled=true
        matcher="200"
        path="/"
        port=80
        protocol="HTTP"
    }
    target_type="instance"
}
```

**Comment by mikhailshilkov** [comment] 2024-05-08 16:35
Since there was no pushback on my comment above, I'll close the issue as by design

**Closed by mikhailshilkov** 2024-05-08 16:35 UTC
Labels: kind/bug, impact/reliability, resolution/by-design
