### ISSUE TITLE
Using ZoneID instead of zone names across Pulumi (aws, awsx, and etc) 

### ISSUE THREAD

**Issue by seivan** [pulumi/pulumi-aws#1367] opened 2021-02-26 10:43 UTC
Now I am aware that generally CI and tools would use a single role or user for deployment so it wouldn't be affected there but it just seems like a missed opportunity to get a consistent behavior regardless. 

> For example, the Availability Zone us-east-1a for your AWS account might not have the same location as us-east-1a for another AWS account.

The alternative is to use zoneIDs. 

> To identify the location of your resources relative to your accounts, you must use the AZ ID, which is a unique and consistent identifier for an Availability Zone. For example, use1-az1 is an AZ ID for the us-east-1 Region and it is the same location in every AWS account.

Since it's not supposed to be consumed by people, it's fine that `use1-az1` is less readable than `us-east-1a`. 

Now, I not sure if it's currently mixed across the board or it's all zone names, I know I implemented zone names in https://github.com/pulumi/pulumi-awsx/pull/638#pullrequestreview-597031727 because I saw it be used on RDS, but it if it's currently mixed, then it's probably better to make a decision to unify them across the board, but if there is a guarantee that zone name is used everywhere and this isn't a big deal, feel free to close this issue.

**Comment by lukehoban** [comment] 2022-12-28 00:56
We don’t do any interpretation of these identifiers in Pulumi, and just rely on the AWS services to handle them. I’m going to close this out as by design.

**Closed by lukehoban** 2022-12-28 00:56 UTC
Labels: kind/enhancement, impact/usability, resolution/by-design
