### ISSUE TITLE
Update and refresh handle complex tags differently

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-aws#609] opened 2019-06-18 07:35 UTC
Hi,

Adding a tag with special characters to resources, like `"kubernetes.io/cluster/test": "shared"` saved differently in the stack when running update and refresh, which means an update after a refresh will always update these tags. Plus some of the resources may fail when trying to update, e.g. `aws.efs.FileSystem`
Update adds this way:
```
"tags": {
    "__defaults": [],
    "kubernetes.io/cluster/test": "shared"
}
```
Refresh changes to this:
```
"tags": {
    "__defaults": [],
    "kubernetes": {
        "io/cluster/test": "shared"
    }
},
```

Versions:
```
➜  pulumi-sandbox (tags) ✗ pulumi version   
v0.17.16
➜  pulumi-sandbox (tags) ✗ pulumi plugin ls 
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
aws         resource  0.18.10  204 MB  n/a        2 days ago
aws         resource  0.17.1   157 MB  n/a        2 months ago
cloudflare  resource  0.17.3   40 MB   n/a        5 days ago
cloudflare  resource  0.17.1   40 MB   n/a        1 month ago
kubernetes  resource  0.24.0   53 MB   n/a        2 days ago
kubernetes  resource  0.21.1   45 MB   n/a        2 months ago
random      resource  0.5.3    36 MB   n/a        3 days ago
random      resource  0.5.2    36 MB   n/a        1 month ago
random      resource  0.5.1    28 MB   n/a        2 months ago

TOTAL plugin cache size: 637 MB
➜  pulumi-sandbox (tags) ✗ yarn list --pattern "@pulumi"                                  
yarn list v1.15.2
warning package.json: No license field
warning pulumi-sandbox: No license field
├─ @pulumi/aws@0.18.10
├─ @pulumi/pulumi@0.17.17
└─ @pulumi/query@0.3.0
Done in 0.13s.
```

Steps to reproduce: 
1. Download the sample repo: https://gitlab.com/proemergotech-public/pulumi-sandbox/tree/tags
1. `yarn install` from the root
1. cd dliver-sandbox, then `pulumi up`
1. `pulumi refresh`, it does not show, but changes the tags too.:
```
Previewing refresh (pul-sbx):

     Type                                 Name                       Plan           
     pulumi:pulumi:Stack                  dliver-sandbox-pul-sbx                    
     └─ network:Vpc                       pul-sbx                                   
 ~      ├─ aws:ec2:Eip                    pul-sbx-eip-0              refreshing     
 ~      ├─ aws:ec2:Eip                    pul-sbx-eip-1              refreshing     
 ~      ├─ aws:efs:FileSystem             pul-sbx-efs                refreshing     
 ~      ├─ aws:ec2:Vpc                    pul-sbx-vpc                refreshing     
 ~      ├─ aws:ec2:Subnet                 pul-sbx-subnet-public-0    refreshing     
        ├─ aws:ec2:InternetGateway        pul-sbx-igw                           
        ├─ aws:ec2:Subnet                 pul-sbx-subnet-fixedIp-1              
        ├─ aws:ec2:Subnet                 pul-sbx-subnet-private-0              
        ├─ aws:ec2:Subnet                 pul-sbx-subnet-public-1               
        ├─ aws:ec2:Subnet                 pul-sbx-subnet-private-1              
        ├─ aws:ec2:SecurityGroup          pul-sbx-securityGroup-efs             
        ├─ aws:ec2:RouteTable             pul-sbx-routeTable-public             
        ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-public-0                  
        ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-public-1                  
        ├─ aws:ec2:NatGateway             pul-sbx-nat-0                         
        ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-private-0             
        ├─ aws:ec2:Subnet                 pul-sbx-subnet-fixedIp-0              
        ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-fixedIp-0             
        ├─ aws:ec2:NatGateway             pul-sbx-nat-1                         
        ├─ aws:efs:MountTarget            pul-sbx-mountTarget-efs-1             
        ├─ aws:efs:MountTarget            pul-sbx-mountTarget-efs-0             
        ├─ aws:ec2:RouteTable             pul-sbx-routeTable-nat-1              
        ├─ aws:ec2:RouteTable             pul-sbx-routeTable-nat-0              
        ├─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-private-1             
        ├─ aws:ec2:VpcEndpoint            pul-sbx-s3-vpcEndpoint                
        └─ aws:ec2:RouteTableAssociation  pul-sbx-rta-nat-fixedIp-1             
 
Resources:
    ~ 2 to update
    26 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pul-sbx::dliver-sandbox::pulumi:pulumi:Stack::dliver-sandbox-pul-sbx]
        ~ aws:ec2/eip:Eip: (update)
            [id=eipalloc-0b558d01a83c9f143]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/eip:Eip::pul-sbx-eip-0]
            --outputs:--
          + associationId   : "eipassoc-0d6183a3cea876b71"
            domain          : "vpc"
            id              : "eipalloc-0b558d01a83c9f143"
          + networkInterface: "eni-0da05cad8dbb21926"
          + privateDns      : "ip-10-151-100-37.eu-west-1.compute.internal"
          + privateIp       : "10.151.100.37"
            publicDns       : "ec2-34-241-113-229.eu-west-1.compute.amazonaws.com"
            publicIp        : "34.241.113.229"
            publicIpv4Pool  : "amazon"
            tags            : {
                Name      : "pul-sbx-eip-eu-west-1a"
                kubernetes: {
                    io/cluster/test: "shared"
                }
            }
            vpc             : true
        ~ aws:ec2/eip:Eip: (update)
            [id=eipalloc-012e8dabbdf23bbcb]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/eip:Eip::pul-sbx-eip-1]
            --outputs:--
          + associationId   : "eipassoc-0d79523d989e20aff"
            domain          : "vpc"
            id              : "eipalloc-012e8dabbdf23bbcb"
          + networkInterface: "eni-01b3c2c4e5008e8ca"
          + privateDns      : "ip-10-151-101-55.eu-west-1.compute.internal"
          + privateIp       : "10.151.101.55"
            publicDns       : "ec2-54-77-135-30.eu-west-1.compute.amazonaws.com"
            publicIp        : "54.77.135.30"
            publicIpv4Pool  : "amazon"
            tags            : {
                Name      : "pul-sbx-eip-eu-west-1b"
                kubernetes: {
                    io/cluster/test: "shared"
                }
            }
            vpc             : true

```
5.  `pulumi up`:
```
Previewing update (pul-sbx):

     Type                           Name                       Plan       Info
     pulumi:pulumi:Stack            dliver-sandbox-pul-sbx                
     └─ network:Vpc                 pul-sbx                               
 ~      ├─ aws:ec2:Eip              pul-sbx-eip-0              update     [diff: ~tags]
 ~      ├─ aws:efs:FileSystem       pul-sbx-efs                update     [diff: ~tags]
 ~      ├─ aws:ec2:Vpc              pul-sbx-vpc                update     [diff: ~tags]
 ~      ├─ aws:ec2:Eip              pul-sbx-eip-1              update     [diff: ~tags]
 ~      ├─ aws:ec2:InternetGateway  pul-sbx-igw                update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-public-0    update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-fixedIp-0   update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-fixedIp-1   update     [diff: ~tags]
 ~      ├─ aws:ec2:SecurityGroup    pul-sbx-securityGroup-efs  update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-public-1    update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-private-1   update     [diff: ~tags]
 ~      ├─ aws:ec2:Subnet           pul-sbx-subnet-private-0   update     [diff: ~tags]
 ~      ├─ aws:ec2:RouteTable       pul-sbx-routeTable-public  update     [diff: ~tags]
 ~      ├─ aws:ec2:NatGateway       pul-sbx-nat-0              update     [diff: ~tags]
 ~      ├─ aws:ec2:NatGateway       pul-sbx-nat-1              update     [diff: ~tags]
 ~      ├─ aws:ec2:RouteTable       pul-sbx-routeTable-nat-0   update     [diff: ~tags]
 ~      └─ aws:ec2:RouteTable       pul-sbx-routeTable-nat-1   update     [diff: ~tags]
 
Resources:
    ~ 17 to update
    11 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:pul-sbx::dliver-sandbox::pulumi:pulumi:Stack::dliver-sandbox-pul-sbx]
        ~ aws:ec2/eip:Eip: (update)
            [id=eipalloc-0b558d01a83c9f143]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/eip:Eip::pul-sbx-eip-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:efs/fileSystem:FileSystem: (update)
            [id=fs-43f0fd8b]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:efs/fileSystem:FileSystem::pul-sbx-efs]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/vpc:Vpc: (update)
            [id=vpc-0f7783d1af37ac602]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/vpc:Vpc::pul-sbx-vpc]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/eip:Eip: (update)
            [id=eipalloc-012e8dabbdf23bbcb]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/eip:Eip::pul-sbx-eip-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/internetGateway:InternetGateway: (update)
            [id=igw-0d72151d0be172ae0]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/internetGateway:InternetGateway::pul-sbx-igw]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-0a27a4d6c4abfbe2d]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-public-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-081532770becd3bb1]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-fixedIp-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-033acf84c2b1736f9]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-fixedIp-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/securityGroup:SecurityGroup: (update)
            [id=sg-0aadd5bdcb99230e6]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/securityGroup:SecurityGroup::pul-sbx-securityGroup-efs]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-0e4bff4a3a975bd1b]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-public-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-03d8bd3a49d59e905]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-private-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/subnet:Subnet: (update)
            [id=subnet-0cffb49be85c3bf2d]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/subnet:Subnet::pul-sbx-subnet-private-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/routeTable:RouteTable: (update)
            [id=rtb-05c3ca99fb3f60e9b]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/routeTable:RouteTable::pul-sbx-routeTable-public]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/natGateway:NatGateway: (update)
            [id=nat-00c5627f38f0ae6ce]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/natGateway:NatGateway::pul-sbx-nat-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/natGateway:NatGateway: (update)
            [id=nat-0b24632b9158deaa1]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/natGateway:NatGateway::pul-sbx-nat-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/routeTable:RouteTable: (update)
            [id=rtb-0eb6510415fc3c0c5]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/routeTable:RouteTable::pul-sbx-routeTable-nat-0]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }
        ~ aws:ec2/routeTable:RouteTable: (update)
            [id=rtb-0a617336317902a9a]
            [urn=urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:ec2/routeTable:RouteTable::pul-sbx-routeTable-nat-1]
          ~ tags: {
              - kubernetes                : {
                  - io/cluster/test: "shared"
                }
              + kubernetes.io/cluster/test: "shared"
            }

Do you want to perform this update? yes
Updating (pul-sbx):

     Type                      Name                    Status                  Info
     pulumi:pulumi:Stack       dliver-sandbox-pul-sbx  **failed**              1 error
     └─ network:Vpc            pul-sbx                                         
 ~      ├─ aws:efs:FileSystem  pul-sbx-efs             **updating failed**     [diff: ~tags]; 1 error
 ~      ├─ aws:ec2:Eip         pul-sbx-eip-0           updated                 [diff: ~tags]
 ~      ├─ aws:ec2:Vpc         pul-sbx-vpc             updated                 [diff: ~tags]
 ~      └─ aws:ec2:Eip         pul-sbx-eip-1           updated                 [diff: ~tags]
 
Diagnostics:
  pulumi:pulumi:Stack (dliver-sandbox-pul-sbx):
    error: update failed
 
  aws:efs:FileSystem (pul-sbx-efs):
    error: Plan apply failed: 1 error occurred:
        * updating urn:pulumi:pul-sbx::dliver-sandbox::network:Vpc$aws:efs/fileSystem:FileSystem::pul-sbx-efs: Error setting EC2 tags for EFS file system ("fs-43f0fd8b"): BadRequest: 'kubernetes.%' is not a valid value for TagKey - it contains illegal characters
        status code: 400, request id: 8686501f-22db-404f-9911-9e47ed881d93
```

Updating the tags after the refresh is confusing, but does not cause a problem, except for efs FileSystem.
On the aws efs console, I can remove and add the same tag multiple times.
Refresh and update logs:
[tags_update.tar.gz](https://github.com/pulumi/pulumi-aws/files/3300282/tags_update.tar.gz)

**Comment by clstokes** [comment] 2019-06-18 13:09
Seems related to https://github.com/pulumi/pulumi-eks/issues/152.

**Comment by ncsibra** [comment] 2019-06-18 14:03
Yeah, looks the same, except here the FileSystem throw an error the second time.

**Comment by stack72** [comment] 2019-06-26 13:03
Hi @ncsibra 	

We deployed a fix for this in 0.18.14, 2 days ago. Please can you try this and let me know if the issue is still happening for you?

Thanks

Paul

**Comment by ncsibra** [comment] 2019-06-26 13:29
Hi @stack72, looks like it's fixed, thanks!

**Comment by stack72** [comment] 2019-06-26 13:32
Wonderful news! Thanks to @pgavlin for fixing that in `pulumi-terraform`

**Closed by stack72** 2019-06-26 13:32 UTC
Labels: area/providers, kind/bug
