### ISSUE TITLE
`aws.scheduler.Schedule` `ignore_changes` is not honored unless a refresh is done 

### ISSUE THREAD

**Issue by magreenbaum** [pulumi/pulumi-aws#2524] opened 2023-05-12 16:05 UTC
### What happened?

When ignoring changes for `state` attribute for the `aws.scheduler.Schedule` module, if the state is set to `DISABLED`in the pulumi module and then `ENABLED` manually and the `target` attribute has any changes to be applied, the `state` is reverted to `DISABLED`. There is no indication the `state` attribute is to be changed in the preview diff. The same behavior is observed if we start out with `ENABLED`, manually `DISABLE` then apply target changes. The schedule is set back to `ENABLED`. 

If a `pulumi refresh` is done to account for the manual changes outside pulumi, `ignore_changes` is honored. 

### Expected Behavior

The `state` attribute is ignored for any changes made to `aws.scheduler.Schedule` even if a `pulumi refresh` is not done beforehand. 

### Steps to reproduce

Apply the below code snippet (add in required `step_function_arn` and `scheduler_execution_role_arn`). 
Manually go into AWS console and toggle this schedule to `ENABLED`. 
Update `target.input` to `random_string_2`. 
Apply changes. 
```
import pulumi 
import pulumi_aws as aws

example = aws.scheduler.Schedule("example",
    group_name="default",
    flexible_time_window=aws.scheduler.ScheduleFlexibleTimeWindowArgs(
        mode="OFF",
    ),
    schedule_expression="rate(1 hour)",
    state="DISABLED",
    target=aws.scheduler.ScheduleTargetArgs(
        arn="<step_function_arn>",
        role_arn="<scheduler_execution_role_arn>",
        input=json.dumps({
            "test": "random_string_1",
        })
    ),
    opts=pulumi.ResourceOptions(
     ignore_changes=["state"],
    ),
)
```

### Output of `pulumi about`

```
CLI          
Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME     VERSION
aws      5.40.0

Host     
OS       darwin
Version  13.2.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment] 2023-05-16 14:24
Hi @magreenbaum - thank you for opening this issue! I did a bit of digging at various levels, and (unfortunate or not), this is actually _by design_ in Pulumi today. 

From our docs:
> The ignoreChanges resource option specifies a list of properties that Pulumi will ignore when it updates existing resources. Pulumi ignores a property by using the old value from the state instead of the value provided by the Pulumi program when determining whether an update or replace is needed. Ignored properties will still be used from the program when there is no previous value in the state, most importantly when creating the resource.

That is, Pulumi has no way to know that the state in AWS has changed without running refresh, and each update action is undertaken as a wholesale PUT against the given resource, with any `ignoreChanges` properties being reflected by whatever Pulumi state considers them to be at that time.

I think there's plenty of room for valid debate regarding whether this is the ideal approach, and in fact, we've opened this issue against pulumi/pulumi to discuss exactly that: https://github.com/pulumi/pulumi/issues/12346

For now, I would encourage running `refresh` before any other Pulumi actions against stacks like this, and potentially thumbs-upping / chiming in on the linked issue above to get more visibility on the broader issue of statefulness in Pulumi.

Thank you again! I'm going to close this issue now as it's actually a manifestation of the issue linked above, but feel free to continue the conversation there.

**Closed by kpitzen** 2023-05-16 14:24 UTC
Labels: impact/usability, kind/bug, area/core, resolution/by-design
