### ISSUE TITLE
Create RoutingRulesArgs

### ISSUE THREAD

**Issue by axblum** [pulumi/pulumi-aws#1539] opened 2021-06-21 19:26 UTC
Prior to pulumi-aws 4.0.0. Pulumi aws would support a list of dictionaries to pass in S3 Bucket Routing rules. As of 4.0.0, it looks like that we need to explicitly pass a json string. It looks like the Go schema has changed, but there was no RoutingRulesArgs created in the SDK. https://github.com/pulumi/pulumi-aws/pull/616. Can you let me know if it was intentional to require that the routing rules become json strings.

**Comment by leezen** [comment] 2021-06-22 22:54
@axblum You mentioned Go, but the RoutingRule interface is a handwritten TypeScript convenience (https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/s3/routingRules.ts). Are you saying you expect the same strongly typed interface for the Go SDK?

**Comment by axblum** [comment] 2021-06-22 23:28
I should have been more clear about which SDK I am currently using. I am using the python sdk.

**Comment by leezen** [comment] 2021-06-23 02:07
@axblum Thanks for the clarification. At the moment, the type I linked is only available in the NodeJS SDK. There are a number of these types of interfaces that we'll want to reference and expose across all the languages, so keeping this issue open to track that.

**Comment by lukehoban** [comment] 2022-12-27 20:24
This is due to the issue tracked in https://github.com/pulumi/pulumi-terraform-bridge/issues/132, which means that `AltTypes` are not respected for non-TypeScript language codegen.  Going to close this one as a duplicate of that.

**Closed by lukehoban** 2022-12-27 20:24 UTC
Labels: kind/enhancement, resolution/duplicate
