### ISSUE TITLE
TypeSet schema not handled for route53resolver endpoint.go

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-aws#2352] opened 2023-02-03 20:01 UTC
### What happened?

The following [upstream change](https://github.com/hashicorp/terraform-provider-aws/commit/2197a6c2c7a0ff306cec3432acb9f5680866f034) is causing a diff due to hash values changing.  This causes vpc subnets to be replaced  due the hash value changing. This is not handled by the bridge.

The issue is due to the following: https://github.com/hashicorp/terraform-provider-aws/commit/2197a6c2c7a0ff306cec3432acb9f5680866f034

### Expected Behavior

That there would not be a hash value change that causes diffs to happen.

### Steps to reproduce

This happens when upgrading from  pulumi-aws 5.18 to 5.27

### Output of `pulumi about`

Issue found in pulumi-aws 5.27

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-02-03 22:07
https://github.com/pulumi/pulumi-aws/issues/2294 seems related and we've been using the repro from there to successfully reproduce.

**Comment by t0yv0** [comment] 2023-02-06 15:17
New [v5.29.1](https://github.com/pulumi/pulumi-aws/releases/tag/v5.29.1) release fixes the issue by working around it and reverting the [upstream change](https://github.com/hashicorp/terraform-provider-aws/commit/2197a6c2c7a0ff306cec3432acb9f5680866f034). 

Closing the P1 issue for now as this is no longer blocking customers.

Will be using https://github.com/pulumi/pulumi-aws/issues/2294 to track chasing down the root cause and coming up with a longer term fix that lets us get 2197a6c2c7a0ff306cec3432acb9f5680866f034 upstream change back.

**Closed** 2023-02-06 15:17 UTC
Labels: kind/bug, resolution/fixed, p1
